### PR TITLE
Add scroll and linea to rollup_economics

### PR DESCRIPTION
**Pull request by lorenz234**
Added scroll and linea to the rollup economics dune spellbook. 

Only small thing to note here is that Linea sends the verification proofs in the same transaction as the trx data. Therefore at current time it is not possible to distinguish between these two types of costs. I have therefore preliminary added all L1 costs for Linea to the l1_data_fees table.

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by mseidlx** [comment]
@dune-eng is there anything we can do to get this PR processed soon? Would be super helpful for us to get it in

**Comment by jeff-dude** [comment]
please see the failures in the logs. the new unions don't have the same number of columns. be sure the columns match exactly

**Comment by lorenz234** [comment]
ahhh yes, I can quickly fix this, I think a recent update of the spell change the overall structure of the query

**Review by jeff-dude — APPROVED** [review]
thanks for the quick fix!

**Pull request merged**
