### PR TITLE
Cowprotocol/add base

### PR DESCRIPTION
**Pull request by fleupold**
### Description:

This PR adds the trades, batches and solvers abstraction for CoW Protocol on Base

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fleupold** [comment]
@jeff-dude I'm not sure about the remaining error. It says it cannot find `delta_prod.cow_protocol_base.trades` in the hourly run, but I'm creating this file in this PR ([code](https://github.com/duneanalytics/spellbook/pull/7295/files#diff-d122f78dfdf2d16fe038273470a69702730f8a6e13139027e48ab10697295061R75-R77))

Do I have to make two separate PRs. one for the trades table and another one for the batches table to get CI to pass?

**Comment by jeff-dude** [comment]
> @jeff-dude I'm not sure about the remaining error. It says it cannot find `delta_prod.cow_protocol_base.trades` in the hourly run, but I'm creating this file in this PR ([code](https://github.com/duneanalytics/spellbook/pull/7295/files#diff-d122f78dfdf2d16fe038273470a69702730f8a6e13139027e48ab10697295061R75-R77))
> 
> Do I have to make two separate PRs. one for the trades table and another one for the batches table to get CI to pass?

yeah, when we do cross-project sources, we need to build the upstream tables in prod first. can you separate into two PRs, one for dex project, one for hourly? then we can focus on getting the DEX one finalized first

**Comment by fleupold** [comment]
@jeff-dude thanks for the pointer. I removed the second part for now and CI seems to be passing. Ready to merge from my side.

**Review by jeff-dude — APPROVED** [review]
this should be good for first phase 🤝

**Pull request merged**
