### PR TITLE
T-20626 - Make dao.transactions Trino compatible

### PR DESCRIPTION
**Pull request by belen-pruvost**

### CODE REVIEW

**Comment by belen-pruvost** [comment]
I've run all the models locally without errors. Same with the tests, but for some reason the tests fail in the CI 🤷‍♀️ 

Screenshot 2022-12-05 at 19 56 58

**Comment by jeff-dude** [comment]
the test is failing after incremental runs, not initial build. in your local dev, did you do the following?
1. dbt run model
2. dbt test model
3. dbt run model again (for incremental purposes, ensure it runs as expected in a timely manner)
4. dbt test model again post-incremental

step 4 is where it's failing here, as it looks like the incremental didn't merge correctly. seems odd though if you only edited a column datatype

**Comment by jeff-dude** [comment]
confirmed. prod is also failing this test in the same manner. incremental runs aren't breaking though, which means the dupes were likely added in initial full historical run, and we haven't hit the issue since so it runs fine. i will raise this with the original creator.

**Comment by belen-pruvost** [comment]
@jeff-dude considering this pre-existent issue, can this PR still be shipped or is it pending a prior fix?

**Comment by belen-pruvost** [comment]
> did you miss [this model](https://github.com/duneanalytics/spellbook/blob/main/models/dao/transactions/polygon/dao_transactions_polygon_eth.sql)?
> 

No, I did not miss it - it is correctly casted so I did not change it. This is its schema:
Screenshot 2022-12-06 at 19 13 38

**Comment by belen-pruvost** [comment]
Good point 👍 okay, taking this into consideration I'll add explicit casting on that view as well and link with the decode team.

**Comment by henrystats** [comment]
pr to fix what is causing the tests to fail now up here - <https://github.com/duneanalytics/spellbook/pull/2231> 

@belen-pruvost I was thinking I could fork this branch and submit a pr to deploy the fix coz it's just addition of a COALESCE but can't seem to figure it out.

**Comment by jeff-dude** [comment]
okay, so i'll merge #2231 first, then we can rebase here

**Comment by jeff-dude** [comment]
> okay, so i'll merge #2231 first, then we can rebase here

ready for ya

**Comment by belen-pruvost** [comment]
Rebased pushed

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
