### PR TITLE
Use prices.usd_forward_fill in all dexes of dex.trades

### PR DESCRIPTION
**Pull request by 0xRobin**
Applying solution of https://github.com/duneanalytics/spellbook/pull/2142 to dex.trades

### CODE REVIEW

**Comment by soispoke** [comment]
hey @0xRobin so apparently @aalan3 seems to think prices.usd should be up to date for (+10 minutes), let's wait for this one until there is a fix/solution on the prices.usd table itself?

**Comment by 0xRobin** [comment]
@soispoke ok no problem discarding this fix if the base table is fixed!
As of now it still has +1h of delay on all tokens

**Comment by aalan3** [comment]
Yes please wait, this shouldn't be needed. Problem was a bit more messy than I thought so might take a couple more days to fix.

**Comment by 0xRobin** [comment]
closing this now, can always re-open should the problems with prices persist.

**Pull request closed without merging**
