### PR TITLE
Labels/addresses/bridge migration

### PR DESCRIPTION
**Pull request by Hosuke**
This part is relatively independent.

### CODE REVIEW

**Comment by jeff-dude** [comment]
> based on the failure, my best guess is you have `ref()` usage downstream that calls these spells and needs updated to `ref(model_name_legacy)`

yep, can confirm:
image

**Comment by jeff-dude** [comment]
this will always need checked each migration PR

**Comment by Hosuke** [comment]
> this will always need checked each migration PR

So I need to change ref('labels_bridges') to ref('labels_bridges_legacy') in existing spells globally?

**Comment by jeff-dude** [comment]
> > this will always need checked each migration PR
> 
> So I need to change ref('labels_bridges') to ref('labels_bridges_legacy') in existing spells globally?

yes, until those downstream ones are also migrated, then you can remove again. we had a script to help this:
https://github.com/duneanalytics/spellbook/blob/main/scripts/generate_legacy_models.py#L53-L57

there is usage notes at the top. i wonder if locally, you can comment out the other pieces not needed, then run?
i'd try this on a fresh commit on your branch locally, so it's easy to revert if weird outcomes occur

**Review by jeff-dude — APPROVED** [review]
looking good 🔥

**Comment by jeff-dude** [comment]
> > > this will always need checked each migration PR
> > 
> > 
> > So I need to change ref('labels_bridges') to ref('labels_bridges_legacy') in existing spells globally?
> 
> yes, until those downstream ones are also migrated, then you can remove again. we had a script to help this: https://github.com/duneanalytics/spellbook/blob/main/scripts/generate_legacy_models.py#L53-L57
> 
> there is usage notes at the top. i wonder if locally, you can comment out the other pieces not needed, then run? i'd try this on a fresh commit on your branch locally, so it's easy to revert if weird outcomes occur

you can use this for future PRs

**Pull request merged**
