### PR TITLE
T-26026 - Change hashflow trades model to be Trino compatible

### PR DESCRIPTION
**Pull request by belen-pruvost**

### CODE REVIEW

**Comment by belen-pruvost** [comment]
Unrelated issue `Missing model (ref) dex_model` pops in the CI, everything else is green ✅

**Review by soispoke — APPROVED** [review]

**Comment by belen-pruvost** [comment]
Thanks for the approval! I'll let you merge the PR when you think it's a good time.

**Comment by jackromo888** [comment]
Thanks
Approved

**Comment by jackromo888** [comment]
Meerge

**Comment by jackromo888** [comment]
- [ ]

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
