### PR TITLE
Add Element Base NFT Trades - Ready for Review

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!

Thank you for taking the time to submit code in Spellbook. A few things to consider:

- If you are a first-time contributor, please sign the CLA by copy & pasting **_exactly_** what the bot mentions in PR comment
- Refer to [docs](#spellbook-contribution-docs) section below to answer questions
- Dune team will review submitted PRs as soon as possible

## Spellbook sub-projects

To prepare for Spellbook to scale in size, Dune team has started to pilot sub-projects:

- For a quick overview, see [the GH discussion on the topic](https://github.com/duneanalytics/spellbook/discussions/5238)
  - Please ask questions and continue the conversation there
- The first spell lineage to move: `tokens.erc20` and all upstream spells which help build it
  - **_Note_**: Please navigate to [tokens](/tokens) root directory to find tokens objects

## Spellbook contribution docs

The [docs](docs) directory has been implemented to answer as many questions as possible. Please take the time to reference each `.md` file within this directory to understand how to efficiently contribute & why the repo is designed as it is 🪄

Example questions to be answered:

- What does each property in the [model config block](/docs/models/model_config_block.md) mean?
- What is the [CI test](/docs/ci_test/ci_test_overview.md) attached to PRs and how can I best utilize it?
- What are the Spellbook [best practices](/docs/general/best_practices.md)?

Please navigate through the [docs](/docs) directory to find as much info as you can.

**Note**: happy to take PRs to improve the docs, let us know 🤝

### CODE REVIEW

**Comment by henrystats** [comment]
Not sure why the seed is failing, I duplicated the ethereum seed just to get the gh action to run, soo I don't understand why it would fail.

It seems like the ABI is inaccurate for some element contracts on other chains though (including base & optimism) as there's also an ERC1155 buy and sell events not showing up which is causing this spell to not work when I test the compiled version on dune.

I'll try and resolve the decoding and come back and update these models.

**Comment by 0xRobin** [comment]
@henrystats let me know if this is still blocked and you need a second pair of eyes on it.

**Comment by henrystats** [comment]
@0xRobin yeah this is no longer blocked and is ready for review.

**Review by 0xRobin — APPROVED** [review]
:heavy_check_mark:  looks good, great work

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
