### PR TITLE
polygon contract mappings: added manual template for community to contribute

### PR DESCRIPTION
**Pull request by peterrliem**
A Polygon contract mapping template for the community to contribute

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by jeff-dude** [comment]
hi @peterrliem -- can you provide more context the intention of this new spell?

i notice you're adding in the existing contract mapping directory, but not following the build pattern. the spells in this directory are dynamic and query-driven, while the PR here is adding static metadata.

plz also see [here](https://github.com/duneanalytics/spellbook/pull/4986/files#diff-f4a4fc471d05670adfeb4584c745e027b4ae0af8ee8e2bfcbae1a82e45b76e73), where @MSilb7 is building out the polygon contract mapping with the same model name as you have, which we can't have overlapping

**Comment by peterrliem** [comment]
@jeff-dude I had submitted this PR about a week ago and @MSilb7 just submitted his today so that's why there is an overlap.

I am building a static database of contract mapping (similar to [BNB's](https://github.com/duneanalytics/spellbook/blob/main/models/_sector/contracts/bnb/contracts_bnb_contract_mapping.sql)) for the community to manually map contracts for Polygon. Happy to put that as a subfolder under @MSilb7's new PR.

Let me know what you think.

**Comment by MSilb7** [comment]
> @jeff-dude I had submitted this PR about a week ago and @MSilb7 just submitted his today so that's why there is an overlap.
> 
> I am building a static database of contract mapping (similar to [BNB's](https://github.com/duneanalytics/spellbook/blob/main/models/_sector/contracts/bnb/contracts_bnb_contract_mapping.sql)) for the community to manually map contracts for Polygon. Happy to put that as a subfolder under @MSilb7's new PR.
> 
> Let me know what you think.

Yeah, I can walk you through the contract mapping spell we have going @peterrliem, I think/hope it would lead to more contracts being mapped with less work. What you're working on could function well for either 1) Mapping new deployer addresses, or 2) Adding to the list of 'contract overrides' where we hardcode mappings.

See https://github.com/duneanalytics/spellbook/tree/main/models/_sector/contracts

**Comment by jeff-dude** [comment]
would be great if you guys could coordinate on that structure together.

we will need to see the manually static ones renamed, so the dynamic new approach can use that naming standard

**Comment by peterrliem** [comment]
@MSilb7  I am looking for a static database that can complement that spell with information on the owners (known name), verticals (e.g. DeFi, Gaming, Brands etc.) and sub-categories that the contracts would belong to.

I'm still definitely up for your contract mapping spell too.

**Pull request closed without merging**
