### PR TITLE
CryptoPunks - fixes + new tables

### PR DESCRIPTION
**Pull request by catherine-2**
Brief comments on the purpose of your changes:

WIP - opening PR to start tracking progress / any error checks. Will tag and add more context once ready for review!

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by catherine-2** [comment]
Hi @jeff-dude ! This is ready for review.

This PR contains a few different tables all related to the CryptoPunks collection. Because they have their own marketplace and are an ERC20 they require some specific queries to pull data. There are also some nuances due to the June 2017 migration to the current contract that aren't supported in current tables. These new tables will make it easy for any wizard to pull stats on the collection.

Here's a summary of each file added or changed in the PR:

**Tables Edited**

1/ events
- the original query did not accurately show the buyer for bid sales (was sometimes NULL)
- this query addresses that so that this table + nft.trades are now accurate

**New Tables Added**

1/ current_listings
- select * from this new table will let a wizard pull all currently available public listings in the punks marketplace
- query looks at all listing and de-listing events per punk id, and where the most recent event was a listing it shows it as active in the final table

2/ current_owners_per_token
- select * will show a wizard the current owner of each token
- ERC20 balances tables don't work for CryptoPunks because of the 2017 contract migration. I pulled that into this query via the call table data in V1 which I confirmed is accurate

3/ listings_over_time
- show the number of active listings per day over time
- similar logic to current listings table

4/ owners_over_time
- show the number of unique wallets that owned a CryptoPunk per day over time
- similar logic to current owners table

5/ metadata
- punk type, number of attributes, and attributes array for each punk ID 

Please let me know of any suggestions or questions! Thank you!

**Comment by jeff-dude** [comment]
thanks for the add & details @catherine-2 !
i pushed a final commit with few minor fixes, we'll see how the gh action runs go & then we can merge if successful and you agree with changes 🤝

**Comment by catherine-2** [comment]
Thank you @jeff-dude ! These changes all look great to me

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
fyi, moving forward, to help us meet a future-state requirement for ansi-sql compliance -- can you ensure to use cast() for type conversions, rather than ```::``` usage? i know many times code is copied from v1, where it works, but we need to continue to enhance for future architecture. existing models should get updated soon.

**Comment by catherine-2** [comment]
> fyi, moving forward, to help us meet a future-state requirement for ansi-sql compliance -- can you ensure to use cast() for type conversions, rather than `::` usage? i know many times code is copied from v1, where it works, but we need to continue to enhance for future architecture. existing models should get updated soon.

Yes will do!

**Pull request merged**
