### PR TITLE
zeroex - explorer cleanup

### PR DESCRIPTION
**Pull request by RantumBits**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by RantumBits** [comment]
ready

**Review by jeff-dude — APPROVED** [review]
sounds good.

can you follow up here and/or tg if post-merge / run in prod (about a few hours from now) if they still appear in data explorer? the way the post-hook works, i'm wondering if it ever removes table properties if this is removed.

you're doing the correct thing in the current setup, but similar to removing a spell altogether, we may have a gap where it never actually *deletes* objects and/or properties in the db, just ignores writing them again in the future

**Comment by RantumBits** [comment]
> sounds good.
> 
> can you follow up here and/or tg if post-merge / run in prod (about a few hours from now) if they still appear in data explorer? the way the post-hook works, i'm wondering if it ever removes table properties if this is removed.
> 
> you're doing the correct thing in the current setup, but similar to removing a spell altogether, we may have a gap where it never actually _deletes_ objects and/or properties in the db, just ignores writing them again in the future

_some_ tables still appear in data explorer, including `api_fills `and `api_fills_deduped `on BNB. Also the latter is still showing on Polygon but was removed in an earlier PR. Fantom tables no longer show individually fwiw

**Comment by jeff-dude** [comment]
> > sounds good.
> > can you follow up here and/or tg if post-merge / run in prod (about a few hours from now) if they still appear in data explorer? the way the post-hook works, i'm wondering if it ever removes table properties if this is removed.
> > you're doing the correct thing in the current setup, but similar to removing a spell altogether, we may have a gap where it never actually _deletes_ objects and/or properties in the db, just ignores writing them again in the future
> 
> _some_ tables still appear in data explorer, including `api_fills `and `api_fills_deduped `on BNB. Also the latter is still showing on Polygon but was removed in an earlier PR. Fantom tables no longer show individually fwiw

okay. good to know. please note the below too:
in order to debug prod orchestration issues that started friday afternoon, i will revert this PR and start clean. once things look good, we can look to "revert the revert" and add back one at a time (there were a batch of PRs added at same time).

once we get this merged back in, we can revisit the question again of what persisted and manually clean it up. i still have a backlog item to automate this, but it's de-prioritized a bit until we get migrated to trino for spellbook.

**Pull request merged**
