### PR TITLE
update sql

### PR DESCRIPTION
**Pull request by sharkxff**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by sharkxff** [comment]
recheck

**Comment by sharkxff** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sharkxff** [comment]
recheck

**Comment by sharkxff** [comment]
recheck

**Comment by sharkxff** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sharkxff** [comment]
@Hosuke @jeff-dude This round of code submissions dbt-slim have all gone through, only CLA issues for historical accounts remain. The account used for this round of commits has already been certified with CLA, the other two accounts zhengxiaofei and 郑晓飞 are past names, and I can't use them at the moment, so please help me with the CLA issues for these two accounts.

**Comment by 0xRobin** [comment]
hey @sharkxff, you should make sure your PR only contains the commits that you added.
can you try rebasing your branch onto `upstream/main`?
Note that your main branch of your fork is out of sync with the spellbook main branch.

**Pull request closed without merging**
