### PR TITLE
Remove METIS token from prices_bnb_tokens for bad price feed 

### PR DESCRIPTION
**Pull request by chef-seaweed**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by chef-seaweed** [comment]
The price of METIS on BNB chain (pancakeswap) is way lower than other sources but coinpaprika api does not reflect it.
This issue has caused wrongly high volume in `pancakeswap_v2_bnb.amm_trades` and `pancakeswap_v3_bnb.amm_trades`, making charts and dashboards using these tables presenting wrong numbers.

Kindly ping @jeff-dude for merge approve asap if possible, many thanks 🙏
Screenshot 2023-07-10 at 6 26 29 PM

**Review by jeff-dude — APPROVED** [review]
sounds good!

**Comment by jeff-dude** [comment]
please note my PR [here](https://github.com/duneanalytics/spellbook/pull/3700) for prices migration to dunesql. maybe i can just add this change to my PR and i'll look to finalize it today/tomorrow?

**Comment by jeff-dude** [comment]
nvm, we can push through for now

**Comment by jeff-dude** [comment]
please note, a full refresh is required for the pancake swap data to reflect these changes. we will try to push one asap. also note that pancake swap is in process of being migrated with an open PR now

**Comment by chef-seaweed** [comment]
> please note, a full refresh is required for the pancake swap data to reflect these changes. we will try to push one asap. also note that pancake swap is in process of being migrated with an open PR now

Got it, thank you very much @jeff-dude 🙏 !

**Pull request merged**
