### PR TITLE
adding token2022 support for orca swaps

### PR DESCRIPTION
**Pull request by andrewhong5297**
adding token2022, this is more difficult because the offset of transfer indices is not strictly known like with spl_token

### CODE REVIEW

**Comment by andrewhong5297** [comment]
I've checked it works for token extensions like PyUSD. Note that this spell could potentially break in the future if some new kind of token extension comes out and changes the instruction invocation pattern.

https://solscan.io/tx/2P2hcK79CV82MqjXa6S4xxKoTHkgqmYkszWkxY1KmASvCek8YfSekSrB8rtdRJSTUYYyuCVxMXFrQd11bXDZqn6K

**Comment by jeff-dude** [comment]
> Note that this spell could potentially break in the future if some new kind of token extension comes out and changes the instruction invocation pattern.

this scares me a bit. is there any way we can set up the spell to avoid failing in this scenario, but rather ignore swaps for new token extensions that change the pattern? then it'd be a new spell and/or fix here if it happens?

**Comment by andrewhong5297** [comment]
> > Note that this spell could potentially break in the future if some new kind of token extension comes out and changes the instruction invocation pattern.
> 
> this scares me a bit. is there any way we can set up the spell to avoid failing in this scenario, but rather ignore swaps for new token extensions that change the pattern? then it'd be a new spell and/or fix here if it happens?

it will fail silently. it won't stop the spell from running

**Comment by andrewhong5297** [comment]
lmk if you have other questions! orca team and blockworks team have been requesting this for a while now haha

**Review by jeff-dude — APPROVED** [review]
sorry for the delay. this looks good, follows the design from v1 as expected. thank you!

**Pull request merged**
