### PR TITLE
Update prices_avalanche_c_tokens.sql

### PR DESCRIPTION
**Pull request by chefcronje**
Add EGS token

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by jeff-dude** [comment]
@chefcronje the id value provided doesn't match to the price provider:
https://api.coinpaprika.com/v1/coins/egmingunsirer

to find the appropriate id value, find the token on coinpaprika front-end and grab id from the url once there. update the row modified here to reflect new id. then it should run fine.

**Comment by jeff-dude** [comment]
please also copy/paste:
`I have read the CLA Document and I hereby sign the CLA`

and post as comment on it's own, to sign the license agreement to contribute

**Comment by chefcronje** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by jeff-dude — APPROVED** [review]
looks good -- thank you!

**Pull request merged**
