### PR TITLE
add nft trade to nft.trades

### PR DESCRIPTION
**Pull request by henrystats**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by henrystats** [comment]
Not sure why the seed tests are failing as the test schema returns the correct results.

**Comment by 0xRobin** [comment]
> Not sure why the seed tests are failing as the test schema returns the correct results.

The `block_times` aren't matching, I assume because they don't contain seconds in the seed file. 
It's more convenient to use `block_number` in the seed tests, less worries about formatting.

**Comment by henrystats** [comment]
ouuu, thank you ser, will update now!

**Comment by henrystats** [comment]
me again not understanding how these tests are failing :(

**Comment by 0xRobin** [comment]
Ok so if you do a local compile and get the tests sql
`target/compiled/spellbook/models/nftrade/bnb/nftrade_bnb_schema.yml/check_seed_nftrade_bnb_events_....sql`

then you replace the model and the seed with the ones generated by the CI and you can inspect the tests results.
I'll rerun the CI to inspect it.

**Comment by henrystats** [comment]
thank you soo much ser!

**Review by 0xRobin — APPROVED** [review]
made some final changes and checked results, all looks good! :heavy_check_mark:

**Comment by henrystats** [comment]
thank you soo soo much ser!

**Comment by soispoke** [comment]
lgtm, thanks @henrystats and @0xRobin

**Review by soispoke — APPROVED** [review]

**Pull request merged**
