### PR TITLE
[EASY] Add missing tokens

### PR DESCRIPTION
**Pull request by harisang**
This PR adds some erc20 missing tokens.

### CODE REVIEW

**Comment by harisang** [comment]
Would be great if this could actually get merged today as it would help a lot with some internal accounting we do. Sorry for this last-minute request.

cc @jeff-dude

**Review by jeff-dude — APPROVED** [review]
sounds good -- will try to merge in a bit 🙏

**Comment by harisang** [comment]
> sounds good -- will try to merge in a bit 🙏

Thanks a lot! Really appreciate it!

**Comment by jeff-dude** [comment]
fyi, we're actively working on integrating automated erc20 token metadata into spellbook as a source. more info on this to come shortly, but i'll be sure to tag you for updates. ideally this makes your life easier!

**Pull request merged**
