### PR TITLE
Freeze dbt-databricks to 1.4.1

### PR DESCRIPTION
**Pull request by 0xRobin**
This freezes the dbt-databricks adapter to a specific version as breaking changes are introduced in `1.4.2`
cmds used:
```
pipenv install dbt-databricks===1.4.1
pipenv lock
pipenv sync
```

--

[These changes](https://github.com/databricks/dbt-databricks/pull/270) are breaking our ability to compile locally withouth a db connection and were included in `dbt-databricks 1.4.2`

### CODE REVIEW

**Comment by dot2dotseurat** [comment]
@couralex6 @0xRobin before this is merged, we'll need to make the same change on the docker images for the gh runner. otherwise, we will hit issues with mismatched manifest versions when checking for modified models.

**Comment by Hosuke** [comment]
There might be a slight difference in dbt `1.2` and `1.4`.

The 1.2 dbt-spark may compile targeted source
```
{{ source('erc20_ethereum', 'evt_transfer') }}
```
as 
```
erc20_ethereum.evt_transfer
```
,
while 1.4 dbt-spark may compile to
```
`erc20_ethereum`.`evt_transfer`
```
(and 1.4's output format may be even more incompatible to dune sql syntax)

**Review by jeff-dude — APPROVED** [review]
i'll coordinate with the team prior to pushing this through, based on comments

**Review by couralex6 — APPROVED** [review]

**Comment by couralex6** [comment]
Amazing. I'll open a PR to update the runner right now

**Comment by jeff-dude** [comment]
@couralex6 when can we merge these coupled PRs?

**Comment by couralex6** [comment]
Just merge the infra PR @jeff-dude

**Pull request merged**
