### PR TITLE
[EASY] Add missing tokens

### PR DESCRIPTION
**Pull request by harisang**
This PR adds some missing erc20 tokens on mainnet.

### CODE REVIEW

**Comment by harisang** [comment]
cc @jeff-dude

**Review by jeff-dude — APPROVED** [review]

**Comment by harisang** [comment]
Thanks for the quick review! Much appreciated!

**Comment by jeff-dude** [comment]
> Thanks for the quick review! Much appreciated!

plz help fix merge conflicts, as another PR added a few to `main`

**Comment by harisang** [comment]
> > Thanks for the quick review! Much appreciated!
> 
> plz help fix merge conflicts, as another PR added a few to `main`

Oh missed it. Just pushed a fix

**Comment by harisang** [comment]
> > Oh missed it. Just pushed a fix
> 
> now some dupes to clean up :)

Sorry for the back and forth, missed that there were some duplicates. Should be fixed now.

**Review by jeff-dude — APPROVED** [review]
all good, should be set now

**Pull request merged**
