### PR TITLE
Add optimism CEX deposit address spell

### PR DESCRIPTION
**Pull request by kaiblade**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @kaiblade 

[Sample cex_optimism_deposit_addresses](https://dune.com/queries/3140723)

**Comment by hildobby** [comment]
Oh interesting, I'm currently working on a crosschain version of this, still iterating on the heuristics: https://github.com/duneanalytics/spellbook/pull/4665

I was also speaking with @MSilb7 about how `cex.addresses` should maybe be crosschain instead of per chain since those wallets are sometimes used across chains and it would make it easier to have `cex_evms.addresses` that feeds into `cex.addresses `(so you can have non-evm chains in there too). What do you guys think @jeff-dude @0xRobin @Hosuke ?

That would make maintenance a lot easier imo, I'm happy to make the PR that changes all evms' cex_{chain}.addresses into `cex_evms.addresses` and look back into this PR and mine right after (I think we can merge the heuristics from both into a more robust model, something I can also tackle)

**Comment by jeff-dude** [comment]
> Oh interesting, I'm currently working on a crosschain version of this, still iterating on the heuristics: #4665
> 
> I was also speaking with @MSilb7 about how `cex.addresses` should maybe be crosschain instead of per chain since those wallets are sometimes used across chains and it would make it easier to have `cex_evms.addresses` that feeds into `cex.addresses `(so you can have non-evm chains in there too). What do you guys think @jeff-dude @0xRobin @Hosuke ?
> 
> That would make maintenance a lot easier imo, I'm happy to make the PR that changes all evms' cex_{chain}.addresses into `cex_evms.addresses` and look back into this PR and mine right after (I think we can merge the heuristics from both into a more robust model, something I can also tackle)

i think we need to continue down the path that you have in #4665 for now. i'm still hesitant to go down the rabbit hole of using `evms` spells in other spells that build a complex dependency lineage. we need to figure out the final approach of these `evms` tables, as we mentioned previously, where the heavy usage indicates potentially building at the raw data level with other base tables.

with that in mind, i think we can close this PR and let hildobby finalize it in #4665 where we leverage the single macro + model per chain for now.

**Comment by hildobby** [comment]
> > Oh interesting, I'm currently working on a crosschain version of this, still iterating on the heuristics: #4665
> > I was also speaking with @MSilb7 about how `cex.addresses` should maybe be crosschain instead of per chain since those wallets are sometimes used across chains and it would make it easier to have `cex_evms.addresses` that feeds into `cex.addresses `(so you can have non-evm chains in there too). What do you guys think @jeff-dude @0xRobin @Hosuke ?
> > That would make maintenance a lot easier imo, I'm happy to make the PR that changes all evms' cex_{chain}.addresses into `cex_evms.addresses` and look back into this PR and mine right after (I think we can merge the heuristics from both into a more robust model, something I can also tackle)
> 
> i think we need to continue down the path that you have in #4665 for now. i'm still hesitant to go down the rabbit hole of using `evms` spells in other spells that build a complex dependency lineage. we need to figure out the final approach of these `evms` tables, as we mentioned previously, where the heavy usage indicates potentially building at the raw data level with other base tables.
> 
> with that in mind, i think we can close this PR and let hildobby finalize it in #4665 where we leverage the single macro + model per chain for now.

Oh you misunderstood, I don't want to use evms spells at all here, but it imo makes more sense to have one spell for cex.addresses across evms instead of [cex_ethereum.addresses, cex_bnb.addresses, cex_optimism.addresses, ...]. Since a lot of those adresses are used crosschains and it would be a lot easier to maintain!

**Comment by jeff-dude** [comment]
> Oh you misunderstood, I don't want to use evms spells at all here, but it imo makes more sense to have one spell for cex.addresses across evms instead of [cex_ethereum.addresses, cex_bnb.addresses, cex_optimism.addresses, ...]. Since a lot of those adresses are used crosschains and it would be a lot easier to maintain!

gotcha -- this is fine with me!

still think we close this PR and use your linked one for the other spell(s)

**Comment by hildobby** [comment]
> > Oh you misunderstood, I don't want to use evms spells at all here, but it imo makes more sense to have one spell for cex.addresses across evms instead of [cex_ethereum.addresses, cex_bnb.addresses, cex_optimism.addresses, ...]. Since a lot of those adresses are used crosschains and it would be a lot easier to maintain!
> 
> gotcha -- this is fine with me!
> 
> still think we close this PR and use your linked one for the other spell(s)

yeah sg, got a lot on my plate but I'll try to have it ready by DuneCon

**Pull request closed without merging**
