### PR TITLE
introduce dex aggregator trades to spellbook using Arbitrum 1inch contract data

### PR DESCRIPTION
**Pull request by jacubcub**
Brief comments on the purpose of your changes:
build out the infrastructure for dex aggregator trades (heavily based off of PR #1353) using Arbitrum 1inch aggregation router contract data (only versions 3 and 4 are deployed on arbitrum)

Adds the following models:

1. oneinch_aggregator_v3_arbitrum_trades
2. oneinch_aggregator_v4_arbitrum_trades
3. oneinch_aggregator_arbitrum_trades
4. oneinch_aggregator_trades (to allow for cross-chain integration)
5. dex_aggregator_trades
6. tokens_arbitrum_erc20

*For Dune Engine V2*
I've checked that:

* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by jacubcub** [comment]
Will adapt this to make oneinch_aggregator_v3_arbitrum_trades.sql and oneinch_aggregator_v4_arbitrum_trades.sql https://dune.com/queries/1174997

**Comment by jacubcub** [comment]
unsure why `{{ ref('tokens_arbitrum_erc20') }}` is compiling to `tokens.erc20` but `{{ ref('tokens_ethereum_erc20') }}` compiles to `tokens_ethereum.erc20`
expect it to compile to `tokens_arbitrum.erc20`

**Comment by jeff-dude** [comment]
> unsure why `{{ ref('tokens_arbitrum_erc20') }}` is compiling to `tokens.erc20` but `{{ ref('tokens_ethereum_erc20') }}` compiles to `tokens_ethereum.erc20` expect it to compile to `tokens_arbitrum.erc20`

i believe you need to add this new directory within tokens to the dbt_project yaml file under models block, which allows you to assign default schema name for that directory. you should see examples existing for other blockchains in that file.

**Comment by jeff-dude** [comment]
@jacubcub i wanted to give you an FYI that we've reorganized our public repo, therefore there will be minor tweaks in this PR and future.
1. changed repo name from 'abstractions' to 'spellbook'
2. renamed default branch from 'master' to 'main'
3. moved all v1 engine abstractions into 'deprecated-dune-v1-abstractions'
4. removed 'spellbook' directory at root and moved all objects within (i.e. models directory you use here) to the root level

it might be easiest to start fresh with a fork of the repo, config local env, refresh and/or recreate branch for new spell building here, close this PR and open new. that's the safe route, but you can also try to solve merge conflicts locally and have this PR refresh.

let me know what you want to do, apologies for the changes mid-PR but there was never the "right" time to do it 🙂

**Comment by jacubcub** [comment]
@jeff-dude thanks for the heads up. I think it will be easiest to start with a fresh one

**Pull request closed without merging**
