### PR TITLE
Fix null opensea & seaport null currency_address

### PR DESCRIPTION
**Pull request by jensenity**
Brief comments on the purpose of your changes:

Fixes https://github.com/duneanalytics/spellbook/issues/2802 's seaport null currency address if the nft is given for free with weth address

Test Query: https://dune.com/queries/2634765

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [X] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by jensenity** [comment]
ask; hi @hildobby @sohwak @jeff-dude , I checked on some of the transactions and found out that the currency symbols on seaport v3, v4 are all `ETH` right now. Is there a reason for the symbol to be ETH and not WETH? since the address is changed to WETH's address anyways, wouldn't it more accurate to use WETH?

**Comment by hildobby** [comment]
> ask; hi @hildobby @sohwak @jeff-dude , I checked on some of the transactions and found out that the currency symbols on opensea v3 & v4 + seaport v1, v2 are all `ETH` right now. Is there a reason for the symbol to be ETH and not WETH? since the address is changed to WETH's address anyways, wouldn't it more accurate to use WETH?

Unfortunately the OpenSea models have had a lot of bugs for months and are by far the most inaccurate NFT marketplace models on Dune. I proposed a full rewrite a few months ago (albeit with some fixes needed still) to the OS data team but haven't heard back from them about it since 🤷‍♂️

@0xRobin & I wrote + maintain most other marketplaces but the OS ones are seeing regular PRs from the OS team and current spells' code have me confused more than anything so I'm not sure how to fix them. A full rewrite would imo be the best way forward as I and others have suggested many times. I'm happy to work on the rewrite once the OS team agree it's the best way forward.

Plz do tell me if there are any bugs we haven't caught with other marketplace spells, I'm happy to look into those @jensenity!

**Comment by sohwak** [comment]
@jensenity 
We're changing the structure of opensea_ethereum.events(https://github.com/duneanalytics/spellbook/pull/3567), so I'd like to apply this part later. 
The `token_address = 0x0000....` was caused by a native token, so using `WETH` to get price, but I thought it was correct to represent it as `ETH`.
However, I agree that the problem is the trade being created without a currency should be fixed.

**Comment by sohwak** [comment]
@hildobby 
I understand what you're saying. Opensea data on Dune had considerable discrepancies in February-March 2023, particularly for platform fees and creator earnings, which were caused by some hardcoding in the seaport source I created. You're one of the biggest contributors here, and you've also been working hard to make sure the data is accurate, so I'd like to say that I'm sorry you feel that way.

The reason it didn't get fixed was partly because I didn't find the right way to do it, and partly because we didn't use it that much. I also didn't get to give you feedback on the source review that you recently requested. What I did was, I tried to run the code, and the results were different for the cases that I thought they were, and to give you feedback as to why, I would have to review the code, and reviewing the code takes time, even for me. At the time, I was in the middle of testing a new method for the same error case with Polygon, and I thought it would be better to apply it quickly to solve the problem. But I really apologize for not getting back any response to you.

I'm not trying to monopolize the works on Seaport. I've been writing tables for them much, but I'm not the one who wrote the contract codes, I'm the one who breaks down and interprets the cases for the transactions that happen to that contract. When a new case comes up, the interpretation breaks down, and I have to come up with a cause and solution again, which is also a burden, so it's been out of date for a long time. 

I would like to do this with many other contributors, and I think the biggest problem with not being able to do this is that I haven't been able to share what I've learned and worked with others, but I haven't been able to do. So I'll try to share them like interpretation and the different cases, so that more people can use the data well, and more people can modify it.

**Comment by 0xRobin** [comment]
@jensenity thank you for bringing forward a possible solution! 
I'm going to close this PR (for now) since we are starting the freeze and migration to DuneSQL (see the discussions). 
While the main code changes look good, the seed file was also changed drastically which makes me not comfortable enough to get this in before the freeze (later today).

Let's revisit this in ~10 days time.

**Comment by jensenity** [comment]
sure! I was late in checking all your comments! @sohwak I would love to work on the opensea models with you :)

**Pull request closed without merging**
