### PR TITLE
Add seaport v1.5 to `opensea.trades`

### PR DESCRIPTION
**Pull request by sohwak**
Brief comments on the purpose of your changes:

Since Seaport v1.5 is newly deployed, add this contract address to `opensea.trades`

- Newly added contract address : `0x00000000000000adc04c56bf30ac9d3c0aaf14dc`  ([etherescan](https://etherscan.io/address/0x00000000000000adc04c56bf30ac9d3c0aaf14dc))
- Applied for decode, and was approved for the same project
- has the same data type as the existing v1.4 (`0x00000000000001ad428e4906ae43d8f9852d0dd6`)
- The version of the contract has been raised, but will be stay in spell as the same version (opensea - v4)

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by sohwak** [comment]
Okay, Dune Team, can you take a quick look at this? Because this version v1.5 doesn't have any changes in data, so I think it's going to be a quick transition.

**Review by 0xRobin — COMMENTED** [review]
@sohwak can you add a couple sample trades from v1.5 to the seed file?

**Comment by sohwak** [comment]
Yep, @0xRobin
The contract changed, but the data was the same, so I kept this version at v4. I put the data from 27 Apr as the seed.

**Review by 0xRobin — APPROVED** [review]
:heavy_check_mark: thanks @sohwak, this looks good

**Review by jeff-dude — APPROVED** [review]
thanks both

**Comment by sohwak** [comment]
@jeff-dude 
Thanks for the merge.
I think most of them have been updated, but strangely I don't see them in nft.trades. I can see them in opensea.trades right before that.
https://dune.com/queries/2424488

**Comment by sohwak** [comment]
just realized that `nft.trades` is materialized table, right? I think it should probably be something like rebuild.

**Comment by jeff-dude** [comment]
> just realized that `nft.trades` is materialized table, right? I think it should probably be something like rebuild.

it was just rebuilt ~15 minutes ago -- can you try again?

**Comment by sohwak** [comment]
Yes, confirmed. The data is well-stacked. Thank you for the prompt check.

**Pull request merged**
