### PR TITLE
Proof of reserve labels

### PR DESCRIPTION
**Pull request by soispoke**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by jackromo888 — APPROVED** [review]

**Review by augustog — APPROVED** [review]
Looks good:
- Tests passed ✅ 
- Spot checked addresses ✅ 

good to go

**Comment by MSeidl-Analytics** [comment]
@soispoke @augustog this PR lead to a breaking change in the column naming. 
Column "address" is now named "lower(address)".
image

**Comment by soispoke** [comment]
@MSeidl-Analytics thanks for flagging, will push a fix today !

**Comment by MSeidl-Analytics** [comment]
@soispoke I created a quick fix in pr 1953: https://github.com/duneanalytics/spellbook/pull/1953
not sure though if I have to keep any other Dune specific spellbook rules in mind - first contribution to spellbook

**Comment by soispoke** [comment]
yes, I opened the same  #1952 but it was the exact same fix, thanks again

**Pull request merged**
