### PR TITLE
small fixes to solana nft and dex

### PR DESCRIPTION
**Pull request by andrewhong5297**
fixing a bunch of small mistakes I made in last weeks nft/dex PRs

- fixing the hardcoded project_program_id for tensorswap v2 and magiceden v1
- fixing the name/symbol swap for hardcoded wrapped sol
- fixing hardcoded phoenix project id for trade_source
- adding minter ids for easier balance tracking on nfts

### CODE REVIEW

**Comment by andrewhong5297** [comment]
@0xRobin have you seen this seed error before? metadata not found? I have not changed any core logic or the seed files

**Comment by andrewhong5297** [comment]
maybe needs @jeff-dude, seems to be a hive metastore issue https://kb.databricks.com/delta/file-transaction-log-not-found

**Comment by 0xRobin** [comment]
@andrewhong5297 this is a known problem with the current setup where the seeds are not materialized in prod. 
The workaround is to spoof a modification in the seeds used by for example swapping 2 rows. This will trigger the seed in the CI step so it's available for the tests.

**Comment by andrewhong5297** [comment]
okay this is good to go. Again, it's mainly just some hardcode fixes - nothing that affects the core logic.

**Review by jeff-dude — APPROVED** [review]

**Comment by andrewhong5297** [comment]
can we merge this today? need it for some work I am trying to wrap up before vacation

**Comment by andrewhong5297** [comment]
@jeff-dude can we merge this?

**Comment by jeff-dude** [comment]
> @jeff-dude can we merge this?

yes, sorry, we had prod stability issues last week & i was offline for a few days. should be good to push today.

**Comment by andrewhong5297** [comment]
Thanks!

**Pull request merged**
