### PR TITLE
Quote "from" in nft.transfers

### PR DESCRIPTION
**Pull request by MSilb7**
Brief comments on the purpose of your changes:

In Dune SQL, `nft.transfers` errored out due to the engine reading `from` as if it's a `select * from table`. We put `from` in wuotes `"from"` to fix this issue.

Q for dune team: Is `"from"` the best syntax, or would that potentially introduce other downstream issues? (i.e. being read as a string)

image

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by belen-pruvost — APPROVED** [review]
Thanks a lot for this fix! 🚀

**Comment by jeff-dude** [comment]
i manually canceled the ci job, with the hope that prod succeeding now clears up the queue. please try to merge main back into your branch, ideally the action runs smoother now

**Comment by jeff-dude** [comment]
@dot2dotseurat note on a dunesql change, belen is aware too :) something to consider for ci tests

**Comment by jeff-dude** [comment]
image
hmm this doesn't seem right 🤔

**Comment by 0xRobin** [comment]
So this is a syntax difference between the 2 engines.
Spark SQL
```sql
select `from` from nft.transfers
```
Dune SQL
```sql
select "from" from nft.transfers
```
I'm not sure how we can solve this with the current setup @belen-pruvost.. ?
For other syntax differences (like the array indexing) we are currently materializing the views to make them available in DuneSQL?

**Comment by belen-pruvost** [comment]
Hey folks, sorry for the delay here. I tested a few variations locally against Spark and Dune SQL. We should use backsticks for reserved words to work across engines. @MSilb7 could you please change your commit to have this instead? :
```
`from`
```

**Comment by 0xRobin** [comment]
> Hey folks, sorry for the delay here. I tested a few variations locally against Spark and Dune SQL. We should use backsticks for reserved words to work across engines. @MSilb7 could you please change your commit to have this instead? :
> 
> ```
> `from`
> ```

does this mean backticks are supported in DuneSQL for spellbook views but not in dune.com queries?

**Comment by belen-pruvost** [comment]
> > Hey folks, sorry for the delay here. I tested a few variations locally against Spark and Dune SQL. We should use backsticks for reserved words to work across engines. @MSilb7 could you please change your commit to have this instead? :
> > ```
> > `from`
> > ```
> 
> does this mean backticks are supported in DuneSQL for spellbook views but not in dune.com queries?

Backticks are not supported out of the box on DuneSQL, but we have added a patch to convert them to quotes only on views.

**Comment by MSilb7** [comment]
> Hey folks, sorry for the delay here. I tested a few variations locally against Spark and Dune SQL. We should use backsticks for reserved words to work across engines. @MSilb7 could you please change your commit to have this instead? :
> 
> ```
> `from`
> ```

Done 👍

**Review by belen-pruvost — APPROVED** [review]

**Pull request merged**
