### PR TITLE
[Erc20] Add 410 Missing Mainnet Tokens

### PR DESCRIPTION
**Pull request by bh2smith**
Generated via

```sh
docker run \
    -e INFURA_KEY=$INFURA_KEY \
    -e DUNE_API_KEY=$DUNE_API_KEY \
    ghcr.io/cowprotocol/data-misc-missing-tokens:main
```

using this [Missing Tokens Query](https://dune.com/queries/2444707)

suppressed output logs:

```
2023-06-04 09:07:39,930 INFO dune_client.base_client waiting for query execution 01H22TK1KP66GM01APHDQQMZWY to complete: ExecutionState.EXECUTING
2023-06-04 09:07:50,192 INFO dune_client.base_client waiting for query execution 01H22TK1KP66GM01APHDQQMZWY to complete: ExecutionState.EXECUTING
Execute on Network.MAINNET
Fetching missing tokens for Network.MAINNET from https://dune.com/queries/2444707?Blockchain=ethereum&DateFrom=2023-01-01+00%3A00%3A00&Popularity=250
Found 410 missing tokens. Fetching details...
...
```

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]

**Comment by bh2smith** [comment]
poke poke -- please merge today! @jeff-dude 🙏🏽

**Comment by jeff-dude** [comment]
i just merged a similar PR from @gentrexha -- can you fix conflicts now?

**Comment by bh2smith** [comment]
Sure thing, just waiting on the script to finish.

**Comment by bh2smith** [comment]
Updated. @jeff-dude

**Pull request merged**
