### PR TITLE
fix: misc contract cleanup

### PR DESCRIPTION
**Pull request by ccerv1**
* elk: 0xf220ea963d27ebe782f09403017b29692a4fc4ae (contract) deployed by 0x111617795C52555D45cF100D0cBF01c82E157E81
* holograph: 0x0c8af56f7650a6e3685188d212044338c21d3f73 (contract) deployed by 0xdeADFED00b7848545d8FE5cb4E7c51eD37e5A2fA
* o3 swap: 0xee9801669c6138e84bd50deb500827b776777d28 (contract) deployed by 0x4283b3469a9edCE1Fda34Ec6e8A453cF82b9cAB7
* synapse: 0xa67b7147dce20d6f25fd9abfbcb1c3ca74e11f0b (contract) deployed by 0x0AF91FA049A7e1894F480bFE5bBa20142C6c29a9
* synapse: 0xa9e90579eb086bcda910dd94041ffe041fb4ac89 (contract) deployed by 0x0AF91FA049A7e1894F480bFE5bBa20142C6c29a9
* synapse: 0x22cdc93f53ee3f6b8ad66fad6f98915a5349950e (contract) deployed by 0x0AF91FA049A7e1894F480bFE5bBa20142C6c29a9
* tarot: 0x952e9c6391d9c0f6c6174d395aa9b4ec1030335a (contract) deployed by 0x5b0390bccCa1F040d8993eB6e4ce8DeD93721765
* thales: 0x2d356b114cbca8deff2d8783eac2a5a5324fe1df (contract) deployed by 0x8314125C8B68aF2AfD0D151eb4A551E88128A2aE
* zeroex: 0xf8ebddd333b3ab285906fd5eb603b17ecd18266f (contract) deployed by 0x60908C4037cbb8F3AA040D9FB668aB36280eb871

### CODE REVIEW

**Comment by ccerv1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ccerv1** [comment]
@MSilb7 @chuxinh 

This PR cleans up some project naming issues and cases where the contract was listed as the deployer.

There were a few other addresses that may be worth looking into, but I didn't address in my PR:

- [0x98b2920d53612483f91f12ed7754e51b4a77919e](https://optimistic.etherscan.io/address/0x98b2920d53612483f91f12ed7754e51b4a77919e)
- [0x914d7fec6aac8cd542e72bca78b30650d45643d7](https://optimistic.etherscan.io/address/0x914d7fec6aac8cd542e72bca78b30650d45643d7)
- [0x00000000f9490004c11cef243f5400493c00ad63](https://optimistic.etherscan.io/address/0x00000000f9490004c11cef243f5400493c00ad63)
- [0x1f98431c8ad98523631ae4a59f267346ea31f984](https://optimistic.etherscan.io/address/0x1f98431c8ad98523631ae4a59f267346ea31f984)
- [0x4a27c059fd7e383854ea7de6be9c390a795f6ee3](https://optimistic.etherscan.io/address/0x4a27c059fd7e383854ea7de6be9c390a795f6ee3)

**Comment by MSilb7** [comment]
Nice, yeah some of these had contracts marked as deployers, likely from a time before we were able to iterate up through the "this contract created this contract which created this contract" flow.

Could you also duplicate the changes in https://github.com/duneanalytics/spellbook/blob/main/models/contracts/contracts_contract_creator_address_list.sql ? This will make it flow through once we move everything from the chain-specific version to the cross-chain version (been slow with model building issues). @ccerv1

**Comment by ccerv1** [comment]
@MSilb7 should be good to go now ✌️

**Review by jeff-dude — APPROVED** [review]
works for me!

thank you & welcome to spellbook 🤝

**Pull request merged**
