### PR TITLE
Feature/oracle addresses

### PR DESCRIPTION
**Pull request by AnonJon**
Add new networks
- arbitrum
- avalanche_c
- ethereum
- fantom
- gnosis

Add all the current feeds on each network for oracle addresses.

### CODE REVIEW

**Comment by Hosuke** [comment]
Hi @AnonJon, you may need to update/merge this PR with the latest main branch.

**Review by Hosuke — CHANGES_REQUESTED** [review]
Hi @AnonJon,

you can add the dummy models for those newly added dune sql spells.

Dummy models looks like this:
https://github.com/duneanalytics/spellbook/blob/5f58228423549b8ea0b05d90219e708c30eabfcb/models/maverick/bnb/maverick_v1_bnb_trades_legacy.sql

**Comment by AnonJon** [comment]
Hi @Hosuke, by dummy models are you referring to adding legacy models for feeds and feeds_hourly for all new networks?

**Comment by AnonJon** [comment]
recheck

**Comment by Hosuke** [comment]
> Hi @Hosuke, by dummy models are you referring to adding legacy models for feeds and feeds_hourly for all new networks?

Yes, if the spell do not have a corresponding legacy model, then you can add a dummy model for the spell.

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @AnonJon 

- Partition by block_month ✅
- Dummy legacy models added for new spells ✅

**Comment by AnonJon** [comment]
@Hosuke just rebased. Feel free to merge when you are able.

**Review by jeff-dude — APPROVED** [review]
nice work!

**Pull request merged**
