### PR TITLE
Add type assurance test

### PR DESCRIPTION
**Pull request by Hosuke**
Try to add `assert_type_*` macro to help ensure type consistency in schema.yml

### CODE REVIEW

**Comment by Hosuke** [comment]
Seems working on the expected values. https://github.com/duneanalytics/spellbook/actions/runs/5224083078/jobs/9431831597?pr=3503#step:10:22

I will try to test a failed one.

**Comment by Hosuke** [comment]
Seems working...
image
https://github.com/duneanalytics/spellbook/actions/runs/5224567976/jobs/9432918282?pr=3503#step:10:22
on top of that, there may be some data with wrong types hidden in `uniswap_v1_ethereum_trades`.

I will finalize my test.

**Comment by Hosuke** [comment]
Now looks as expected.
image
https://github.com/duneanalytics/spellbook/actions/runs/5224699533/jobs/9433229197?pr=3503#step:10:22

**Comment by jeff-dude** [comment]
closing PRs marked as `wip` state, prior to the freeze announced and tracked [here](https://github.com/duneanalytics/spellbook/discussions/3558), we can reopen and reformat post-freeze

**Pull request closed without merging**
