### PR TITLE
SPE-6 Flashloans Migration - #10 - Main Table - Relies on prev models 

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by jeff-dude** [comment]
gm gm @henrystats 
looks like you may be able to close all the flashloan PRs, as they snuck into this PR:
https://github.com/duneanalytics/spellbook/pull/4239/files

let me know what ya think! i plan to merge that one today or tomorrow

**Comment by henrystats** [comment]
ahh @jeff-dude sorry I don't really understand.. In the pr only the uni swap model was migrated, are you suggesting that I close just the uniswap one?

**Comment by jeff-dude** [comment]
> ahh @jeff-dude sorry I don't really understand.. In the pr only the uni swap model was migrated, are you suggesting that I close just the uniswap one?

oops, yes, that's right

**Comment by henrystats** [comment]
ah oke sure no worries ser will close that one @jeff-dude

**Comment by henrystats** [comment]
@jeff-dude I made some small fixes as some of the underlying models had their version in `INT`, and some in VARCHAR.

Also added block month to uniswap celo model.

**Comment by jeff-dude** [comment]
> @jeff-dude I made some small fixes as some of the underlying models had their version in `INT`, and some in VARCHAR.
> 
> Also added block month to uniswap celo model.

thank you v much! much appreciated as always

**Pull request merged**
