### PR TITLE
T-26472 materialize nft/perpetual sector

### PR DESCRIPTION
**Pull request by jeff-dude**

### CODE REVIEW

**Review by couralex6 — APPROVED** [review]

**Comment by jeff-dude** [comment]
timing out on copying data over in dunesql check. @jmsgu will look to filter in the CTAS statement to make this timeout occur less frequently

**Comment by dot2dotseurat** [comment]
@jeff-dude looks like this is ready barring the dune sql check?
should we coordinate with query (@belen-pruvost) to see if they need to add any types overrides for this table or just remove the timeout constraint for this pr to get the grimoire test running.

**Comment by jeff-dude** [comment]
> @jeff-dude looks like this is ready barring the dune sql check? should we coordinate with query (@belen-pruvost) to see if they need to add any types overrides for this table or just remove the timeout constraint for this pr to get the grimoire test running.

we should be set on the overrides, as there's been a lot of iteration on these as views already. i can double check quickly.

as for the dunesql check, i'm comfortable moving on with the timeout, but we can let it run without one just to be sure since i won't merge until a bit later anyway

**Comment by dot2dotseurat** [comment]
@jeff-dude mind it I merge?

**Review by dot2dotseurat — APPROVED** [review]

**Comment by jeff-dude** [comment]
> @jeff-dude mind it I merge?

let's go for it. i just merged a batch of belen's fixes for dunesql, so might as well put this one in too

**Comment by jeff-dude** [comment]
forgot to remove the timeout change :) i can follow up

**Pull request merged**
