### PR TITLE
Bnb Bep20 & BNB balances - Ready for review 

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
This table is also ready for review @antonio-mendes, @jeff-dude.

I wanted to ask if it's possible to remove the unique test in the transfers tables (the base table that contains just the transactions details)...

The unique test is taking about 10min to run for both initial and incremental... Query looks okay soo I assume that we don't need the test after the first run as it'd take a lot of resources. 

The erc20 bnb table alone has over 6bn entries.

**Comment by henrystats** [comment]
Also I must say dune-sql is soo freaking powerful... I think I remember someone tried building a balances spell on bnb (on spark) and they faced issues setting it up because of how big the transfers table was on bnb...

But now it runs pretty fast! long live dune-sql haha!

**Comment by henrystats** [comment]
@antonio-mendes just dropping  a bump here as I believe this is ready for merging as well (similar to the polygon one)...

I'm going to be digging into what is causing the gas fees tiny decimals error, not sure where the error is from as the calculations seem correct!

**Comment by antonio-mendes** [comment]
Good timing @henrystats haha I am just validating the results of this model and was about to change the column names where needed 👍

**Comment by henrystats** [comment]
hehe nice!

**Review by antonio-mendes — APPROVED** [review]
The PR looks good to me, and I managed to build the models locally and validated balances against several addresses confirming the values are accurate at different levels of aggregation.

Will go ahead and merge it as soon it passes the CI tests.

**Comment by antonio-mendes** [comment]
Regarding removing the uniqueness test we'd prefer to keep it there for now as it's a really good safety measure if something goes wrong.

Something that might help you when building a spell is commenting the test out so CI runs quicker, and when everything is working and passing the tests you reintroduce the uniqueness constraint for a final check. It will make the development cycle quicker for you without having to actually remove it in prod 👍

**Comment by henrystats** [comment]
okeee ser, thank you very much!

**Comment by henrystats** [comment]
Alrighty ser, thank you very much. Tests have now passed ser @antonio-mendes!

**Pull request merged**
