### PR TITLE
[CoW] cast amount_sold as string

### PR DESCRIPTION
**Pull request by bh2smith**
In order to match the types emitted by the event and avoid precision loss we cast back to string after deducting feeAmount

Screenshot 2023-02-12 at 00 42 28

cc @fleupold for internal review.

### CODE REVIEW

**Comment by fleupold** [comment]
Can you please get input from the Dune team, as what datatype they suggest to encode solidity uint256? I don't know enough about hive to tell if this is the right way.

**Comment by bh2smith** [comment]
> Can you please get input from the Dune team, as what datatype they suggest to encode solidity uint256? I don't know enough about hive to tell if this is the right way.

I would infer from the fact that they encode event data fields of `u256` type as strings that this is the way to go... but we can surely ask as well.

**Comment by jeff-dude** [comment]
> > Can you please get input from the Dune team, as what datatype they suggest to encode solidity uint256? I don't know enough about hive to tell if this is the right way.
> 
> I would infer from the fact that they encode event data fields of `u256` type as strings that this is the way to go... but we can surely ask as well.

i believe this is changing (in a good way) with the move towards duneSQL -- @belen-pruvost can you confirm approach for datatype uint256?

**Comment by belen-pruvost** [comment]
> i believe this is changing (in a good way) with the move towards duneSQL -- @belen-pruvost can you confirm approach for datatype uint256?

Hey @jeff-dude, indeed - DuneSQL has a uint256 data type. 
In a world where spells are built with Spark, I'd also leave this as a string. And then, as we move to building them on DuneSQL, uint256 is the way to go.

**Comment by fleupold** [comment]
@belen-pruvost since DuneSQL is still in beta and we needed to move away from Dune v1, what is a way to do lossless addition and subtraction of these u256 datatypes in Dune v2 for our production use case?

Cf. https://dune.com/queries/1992539?d=1 that summing up strings by defaults is interpreted as summing up double which suffer from non-deterministic precision loss (executing this query multiple times randomly yields 0 or 1 as a result).

**Comment by belen-pruvost** [comment]
> @belen-pruvost since DuneSQL is still in beta and we needed to move away from Dune v1, what is a way to do lossless addition and subtraction of these u256 datatypes in Dune v2 for our production use case?
> 
> Cf. https://dune.com/queries/1992539?d=1 that summing up strings by defaults is interpreted as summing up double which suffer from non-deterministic precision loss (executing this query multiple times randomly yields 0 or 1 as a result).

Hey @fleupold - the numbers on the query you shared (`115792089237316195423570985008687907853269984665640564039457584007913129639934` and `115792089237316195423570985008687907853269984665640564039457584007913129639935`) don't fit in 256 bits, they need 257. 

The max number you would be able to represent as a uint256 is `2^256` (`115792089237316195423570985008687907853269984665640564039457584007913129639935`). We can guarantee deterministic results with the usage of this type.

**Comment by bh2smith** [comment]
Thanks for your reply @belen-pruvost - It seems that casting back to string here is the way to go for now (in Spark). Could we perhaps get this merged sometime?

**Comment by jeff-dude** [comment]
i was waiting to see resolution on your questions -- i can certainly take a look to finalize soon 🤝

**Comment by fleupold** [comment]
> It seems that casting back to string here is the way to go for now (in Spark)

From my limited tests it looks like the string you will end up with in the database is in scientific notion e.g. 1527638e14 and already suffered from precision loss, so we would still end up with inconsistencies to our other numbers (which are long decimal strings). In that case, maybe it's better to signal "this number may have already los precision" by leaving it a Double type.

**Comment by jeff-dude** [comment]
> > It seems that casting back to string here is the way to go for now (in Spark)
> 
> From my limited tests it looks like the string you will end up with in the database is in scientific notion e.g. 1527638e14 and already suffered from precision loss, so we would still end up with inconsistencies to our other numbers (which are long decimal strings). In that case, maybe it's better to signal "this number may have already los precision" by leaving it a Double type.

if i'm reading correctly, that means we don't want to merge this, as it casts to string. i'll wait one more time for @bh2smith to confirm your wording here

**Pull request closed without merging**
