### PR TITLE
Dao migration - update#2 - colony tables - Ready for review

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
@jeff-dude, I'm separating the tables as you suggested in https://github.com/duneanalytics/spellbook/pull/3793.

The tests failing is normal as in this pr I didn't migrate the dune-sql models of the other creator tools. so this should be ready to go.

Submitting separate pr's for each project model.

**Comment by jeff-dude** [comment]
> @jeff-dude, I'm separating the tables as you suggested in #3793.
> 
> The tests failing is normal as in this pr I didn't migrate the dune-sql models of the other creator tools. so this should be ready to go.
> 
> Submitting separate pr's for each project model.

sorry for the delays (across all your PRs), we've been hitting a few bugs within the migration.

at first glance here, my recommendation is to open a PR which is solely the seed / test migration. for instance, the PR would have:
- duplicate seed file, rename one with `_legacy` suffix
- add seed schema file with dunesql types and tag (as you've done here)
- duplicate the generic test which references the seed, rename one with `_legacy` suffix, change seed ref within to `_legacy`
- ensure dunesql generic test remains, with the ref to the proper seed within

examples:
https://github.com/duneanalytics/spellbook/pull/3702/files
https://github.com/duneanalytics/spellbook/pull/3875/files

**Comment by jeff-dude** [comment]
> > @jeff-dude, I'm separating the tables as you suggested in #3793.
> > The tests failing is normal as in this pr I didn't migrate the dune-sql models of the other creator tools. so this should be ready to go.
> > Submitting separate pr's for each project model.
> 
> sorry for the delays (across all your PRs), we've been hitting a few bugs within the migration.
> 
> at first glance here, my recommendation is to open a PR which is solely the seed / test migration. for instance, the PR would have:
> 
> * duplicate seed file, rename one with `_legacy` suffix
> * add seed schema file with dunesql types and tag (as you've done here)
> * duplicate the generic test which references the seed, rename one with `_legacy` suffix, change seed ref within to `_legacy`
> * ensure dunesql generic test remains, with the ref to the proper seed within
> 
> examples: https://github.com/duneanalytics/spellbook/pull/3702/files https://github.com/duneanalytics/spellbook/pull/3875/files

once that is merged, when you revisit here, ideally only your modified model that calls the seed test will actually run in the test section of CI gh action. right now, all projects are running, so they all fail.

**Comment by henrystats** [comment]
thank you ser, I set up a pr here - <https://github.com/duneanalytics/spellbook/pull/3885/files>

although it's triggering all the other generic tests and failing..

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
