### PR TITLE
dex.offers 🦕

### PR DESCRIPTION
**Pull request by denverbaumgartner**
Brief comments on the purpose of your changes:

this is the same set of changes addressed in PR #3042 but moved to a personal account to allow for edits by maintainers. this is forced because of the following [issue](https://github.com/orgs/community/discussions/5634). @Hosuke pinging you here for reference 🤝 

short purpose:
we currently have dex.trades but no dex.offers, this changes that! the initial motivation was to enable easy cross chain data / aggregation for Rubicon, a fully on-chain order book (and currently the only DEX in dex.offers).

longer purpose:
this spell sets a foundation for other order book DEXs (as they emerge) to contribute to. as well, i believe this could be a way to track historical execution prices across all DEXs. the approach would not be as simple when it comes to an AMM (the goal here being "what rate could i have swapped USDC -> ETH on xyz AMM at block 1,000,000), but i think its definitely feasible given some constraints (most likely setting some type of bin size to model an order book off of an AMM's constant function (ex: solve for the scenario previously mentioned (USDC -> ETH at block 1,000,000) by calculating the cost of purchasing ETH in .1 increments (0.1, 0.2, ..., 5.1, etc.)). i hope to take a stab at this sometime in the near future, but for now im off to fight other 🔥s

some general thoughts:

- i wanted to be as chain agnostic as possible, so transaction costs are just represented as USD values (transaction costs being the primary limiter of on chain order books (s/o L2 scaling solutions 🙏 ))

- going through the dex tests, it looks like they mainly depend on the lower level tables being well tested, rather than having extensive testing at the aggregate level. so, rubicon_optimism_offers has full test coverage, and ideally that sound state trickles up to dex.offers 💯 *any feedback here is appreciated 🤹

- within the dbt_project.yml file i added in dex.offers in a similar fashion to the other aggregate tables, but it looks like i was more verbose with types defined for every column, wasn't sure why others hadn't done this, but expect i will find out as a result of this pr ;)

would love any thoughts / feedback on how to improve the work done here so far. i await everyone's feedback and am excited to do my small part to support the ecosystem 🖖

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @denverbaumgartner 

[Sample dex.offer](https://dune.com/queries/2330759?d=1)

**Comment by jeff-dude** [comment]
thank you @denverbaumgartner for the initiative to create a new spell in the dex sector 🙌 

if this isn't in a rush, i'd love to use this as an example for how we'd like to restructure `dex.trades`, then objects in the `dex` schema will have consistency (in the future), with this being the first step. does that work for you?

**Comment by denverbaumgartner** [comment]
> thank you @denverbaumgartner for the initiative to create a new spell in the dex sector 🙌
> 
> if this isn't in a rush, i'd love to use this as an example for how we'd like to restructure `dex.trades`, then objects in the `dex` schema will have consistency (in the future), with this being the first step. does that work for you?

hey @jeff-dude thanks for the kind words! this is currently a blocker for a dashboard i am working on and was the main motivator for making `dex.offers`, so if it could be accepted sooner rather than later that would be a big help for me. 

happy to help contribute on this restructure you are speaking of 🙏

**Comment by jeff-dude** [comment]
> > thank you @denverbaumgartner for the initiative to create a new spell in the dex sector 🙌
> > if this isn't in a rush, i'd love to use this as an example for how we'd like to restructure `dex.trades`, then objects in the `dex` schema will have consistency (in the future), with this being the first step. does that work for you?
> 
> hey @jeff-dude thanks for the kind words! this is currently a blocker for a dashboard i am working on and was the main motivator for making `dex.offers`, so if it could be accepted sooner rather than later that would be a big help for me.
> 
> happy to help contribute on this restructure you are speaking of 🙏

okay, no problem. we can merge as-is & then i can propose a follow-up PR to redesign and tag you for review

**Comment by denverbaumgartner** [comment]
> > > thank you @denverbaumgartner for the initiative to create a new spell in the dex sector 🙌
> > > if this isn't in a rush, i'd love to use this as an example for how we'd like to restructure `dex.trades`, then objects in the `dex` schema will have consistency (in the future), with this being the first step. does that work for you?
> > 
> > 
> > hey @jeff-dude thanks for the kind words! this is currently a blocker for a dashboard i am working on and was the main motivator for making `dex.offers`, so if it could be accepted sooner rather than later that would be a big help for me.
> > happy to help contribute on this restructure you are speaking of 🙏
> 
> okay, no problem. we can merge as-is & then i can propose a follow-up PR to redesign and tag you for review

sounds great, thanks for understanding! will be on the lookout for this follow-up PR 🖖

**Review by jeff-dude — APPROVED** [review]
i pushed a commit to prep the standardization prior to merge
- make `dex.offers` materialized as a table
- remove CAST statements in downstream objects, only use in base model
- add blockchain filter on some tokens metadata joins
- move seed file to generic dex offers seed, prep for future models
- update join conditions to seed to match unique keys on model
- clean up columns which are checked from seed
- fix test with new seed name / join conditions

**Pull request merged**
