### PR TITLE
SPE-93 Migrate cow_protocol models downstream of dex_trades

### PR DESCRIPTION
**Pull request by couralex6**
```
models/cow_protocol/tx_hash_labels/cow_protocol_tx_hash_labels_all.sql
models/cow_protocol/tx_hash_labels/bluechip_investment/cow_protocol_tx_hash_labels_bluechip_investment.sql
models/cow_protocol/tx_hash_labels/bluechip_investment/ethereum/cow_protocol_tx_hash_labels_bluechip_investment_ethereum.sql
models/cow_protocol/tx_hash_labels/early_investment/cow_protocol_tx_hash_labels_early_investment.sql
models/cow_protocol/tx_hash_labels/early_investment/ethereum/cow_protocol_tx_hash_labels_early_investment_ethereum.sql
models/cow_protocol/tx_hash_labels/harvest_yield/cow_protocol_tx_hash_labels_harvest_yield.sql
models/cow_protocol/tx_hash_labels/harvest_yield/ethereum/cow_protocol_tx_hash_labels_harvest_yield_ethereum.sql
models/cow_protocol/tx_hash_labels/offramp/cow_protocol_tx_hash_labels_offramp.sql
models/cow_protocol/tx_hash_labels/offramp/ethereum/cow_protocol_tx_hash_labels_offramp_ethereum.sql
models/cow_protocol/tx_hash_labels/onramp/cow_protocol_tx_hash_labels_onramp.sql
models/cow_protocol/tx_hash_labels/onramp/ethereum/cow_protocol_tx_hash_labels_onramp_ethereum.sql
models/cow_protocol/tx_hash_labels/stable_to_stable/cow_protocol_tx_hash_labels_stable_to_stable.sql
models/cow_protocol/tx_hash_labels/stable_to_stable/ethereum/cow_protocol_tx_hash_labels_stable_to_stable_ethereum.sql
models/cow_protocol/tx_hash_labels/staking_token_investment/cow_protocol_tx_hash_labels_staking_token_investment.sql
models/cow_protocol/tx_hash_labels/staking_token_investment/ethereum/cow_protocol_tx_hash_labels_staking_token_investment_ethereum.sql
models/cow_protocol/tx_hash_labels/treasury_management/cow_protocol_tx_hash_labels_treasury_management.sql
models/cow_protocol/tx_hash_labels/treasury_management/ethereum/cow_protocol_tx_hash_labels_treasury_management_ethereum.sql
```

### CODE REVIEW

**Comment by jeff-dude** [comment]
this was just migrated:
https://github.com/duneanalytics/spellbook/pull/3809

after a successful prod run, should be able to refresh this PR and try again

**Comment by jeff-dude** [comment]
> @jeff-dude canceling the ci run because i have some local changes and this is gonna be a massive ci run

okay, no problem, feel free to take it from here

**Comment by couralex6** [comment]
Added these two models since they're upstream dependencies:
```
models/tokens/ethereum/tokens_ethereum_erc20_stablecoins.sql
models/tokens/fantom/tokens_fantom_erc20_stablecoins.sql
```

**Comment by jeff-dude** [comment]
> Good to go! @jeff-dude

i won't be around the next few hours, so if you want to merge/monitor/be ready for possible reverts, feel free to go ahead 🤝

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
