### PR TITLE
Add more docs slugs

### PR DESCRIPTION
**Pull request by 0xBoxer**
Add more docs slug to spells elevated in data explorer

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
all good here?
hate that schema files kick off CI. feel free to manually cancel those with each commit, to avoid running so much for no reason

**Comment by 0xBoxer** [comment]
yep this is finished, any label I can use to not trigger the CI runs?

I feel like I saw that pattern somewhere

**Comment by jeff-dude** [comment]
> yep this is finished, any label I can use to not trigger the CI runs?
> 
> I feel like I saw that pattern somewhere

nah, not really, only option is `prod_exclude` dbt tag in model configs. wouldn't help this scenario.

**Comment by 0xBoxer** [comment]
ok, will cancel manually going forward 🫡

**Pull request merged**
