### PR TITLE
Contracts - Test Incremental Initial Build & Add Polygon PoS

### PR DESCRIPTION
**Pull request by MSilb7**
Add Polygon PoS to contracts mapping

Edit:
- Testing incremental initial builds, where we just run forward 1 year at a time on the initial build.
- This means it should take 1 hour * # of years to catch up (i.e. ~8 for Ethereum), but this should only matter when we edit the base and incremental tables, which ~should be rare.

Also incorporates https://github.com/duneanalytics/spellbook/pull/5026

---

Merging https://github.com/duneanalytics/spellbook/pull/5128 should be a fast follow after merging this

### CODE REVIEW

**Comment by jeff-dude** [comment]
polygon is going to be tough to fit into CI test window :(

**Comment by MSilb7** [comment]
> polygon is going to be tough to fit into CI test window :(

Maybe we can try the similar "look forward up to this many blocks" at the base level to try to chunk it.

**Comment by MSilb7** [comment]
The yearly incremental predicate here now matches what's in https://github.com/duneanalytics/spellbook/pull/4917

(It should look unchanged to whatever is merged second).

Should be ready for review @jeff-dude

**Comment by MSilb7** [comment]
Modifying the forward facing window for runtime

**Review by jeff-dude — APPROVED** [review]
excited to see how this goes in prod

assuming it runs as expected, we should check back tomorrow to ensure run times in prod decrease after the number of hourly runs needed to catchup to present time

**Pull request merged**
