### PR TITLE
Add 0x zeroex Fantom

### PR DESCRIPTION
**Pull request by RantumBits**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by jeff-dude** [comment]
> @jeff-dude this model now matches other chains as well

thanks. i pushed a commit for schema/table name cleanup. please do apply in a similar fashion moving forward. let's see how this runs via test automation

**Comment by RantumBits** [comment]
thanks for updating the name 

i just spoke with @bakabhai993 about changing directory structure to remove subdirectories on all chains

**Comment by RantumBits** [comment]
> > @jeff-dude this model now matches other chains as well
> 
> thanks. i pushed a commit for schema/table name cleanup. please do apply in a similar fashion moving forward. let's see how this runs via test automation

thanks for updating the name 

i just spoke with @bakabhai993 about changing directory structure to remove subdirectories on all chains

**Comment by jeff-dude** [comment]
this one doesn't have the updated logic for simplifying the original CTE & adding `block_number` to joins downstream. it is running longer than expected based on other chains. it could also just be that the gh action server is overloaded at the moment too. we can try another run here as-is, then attempt to change logic if it's slow still.

**Review by jeff-dude — APPROVED** [review]
we're likely fine here. i can monitor first run in prod.

**Pull request merged**
