### PR TITLE
Update Bebop - ready for review

### PR DESCRIPTION
**Pull request by B1boid**
Ready for review

Add new smart contract for bebop-trades

### CODE REVIEW

**Comment by B1boid** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @B1boid

**Comment by B1boid** [comment]
> LGTM.✅ Thank you @B1boid
> 
> By the way do you want to add new seed for testing the trades from new contracts?

Done✅

**Review by jeff-dude — APPROVED** [review]
works for me, thank you!

for reference, @B1boid in the future, you could break out spells per version, then have more that union them back together. that could be useful if you ever wanted tables that granular and assign different version values and such. we won't require breaking up by version, but it's something other projects have done (maybe more so when logic is v different)

**Pull request merged**
