### PR TITLE
Spellbook Workshop Submission

### PR DESCRIPTION
**Pull request by 1chioku**
Major Changes:
1. Changed the ordering of the CTEs within the query to simplest to most complex to enhance general code readability;
2. Updated CTE naming for clearer readability when it comes to subquery operations;
3. Optimised select portions of the code (see comments in balancer_ethereum_balances.sql);
4. Added a commented placeholder for a ERC20 inflow filtering (right now the inflows into the Balancer do not filter out non-supported ERC20 that are being sent to the Balancer V1 pools or the Balancer V2 vaults)
5. Added clear commenting for better general readability.

Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by 1chioku** [comment]
@jeff-dude, if you can have a look:

The automated test keeps failing at: " Create Macro to Determine dependencies."

Discord thread here: https://github.com/duneanalytics/spellbook/commit/38c42beaab06ca9b7137ff968d4063d4e21e486f

The timing and error messages seems to coincide with the new commits that were made yesterday: https://github.com/duneanalytics/spellbook/commit/38c42beaab06ca9b7137ff968d4063d4e21e486f

Thanks.

**Comment by dot2dotseurat** [comment]
> @jeff-dude, if you can have a look:
> 
> The automated test keeps failing at: " Create Macro to Determine dependencies."
> 
> Discord thread here: https://discord.com/channels/757637422384283659/999683200563564655/1022722670082658354
> 
> The timing and error messages seems to coincide with the new commits that were made yesterday: [38c42be](https://github.com/duneanalytics/spellbook/commit/38c42beaab06ca9b7137ff968d4063d4e21e486f)
> 
> Thanks.

@1chioku I think it's working now. Can you sync with main and retry?

**Comment by 1chioku** [comment]
Works wonders, thanks!!!

**Comment by dot2dotseurat** [comment]
Thank you for participating in our Spellbook workshop competition! It was a close race and although your submission didn't win, there will be future opportunities to participate in Spellbook hackathons and bounties (launching soon). we hope you learned something new and had some fun.

**Pull request closed without merging**
