### PR TITLE
Perpetuals Migration - #5 - Migrate Synthetix - Ready for review 

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
this is now ready for review pending when Perpetuals Migration #1 gets merged..


@MSilb7, @RplusT I'm tagging since you built the original spell... I'm migrating to dunesql and the way I've written it returns the correct details (checked the test schemas on dunesql)

The issue is there was some filtering you did whilst decoding some of the data soo I wanted to double check that I'm not missing something because all the assets & market names show up correctly to me without needing to do those filtering...

I commented the previous code for the decoded columns underneath the ones I wrote so it's easier to review, so if you could please help check that what I have is correct, so this could be reviewed, I'd really appreciate...


I'm trying to migrate the perpetuals spell (so need to migrate all the models), and also for my selfish goal of becoming an  optimism NumbaNERD...

**Comment by MSilb7** [comment]
> this is now ready for review pending when Perpetuals Migration #1 gets merged..
> 
> @MSilb7, @RplusT I'm tagging since you built the original spell... I'm migrating to dunesql and the way I've written it returns the correct details (checked the test schemas on dunesql)
> 
> The issue is there was some filtering you did whilst decoding some of the data soo I wanted to double check that I'm not missing something because all the assets & market names show up correctly to me without needing to do those filtering...
> 
> I commented the previous code for the decoded columns underneath the ones I wrote so it's easier to review, so if you could please help check that what I have is correct, so this could be reviewed, I'd really appreciate...
> 
> I'm trying to migrate the perpetuals spell (so need to migrate all the models), and also for my selfish goal of becoming an optimism NumbaNERD...

@RplusT said he wasn't able to reply here, but I got a response form him:

"All good. If the market names are all coming out properly as you said then it should be fine. I think dunesql has a simple equivalent function to the long convoluted series of functions in sparksql that was in there originally. That was only done because of sparksql’s limitations. dunesql looks more flexible in this regard :)”

**Comment by henrystats** [comment]
oke.. thank you ser @MSilb7

**Comment by jeff-dude** [comment]
> oke.. thank you ser @MSilb7

thank you both for confirming -- can @henrystats go ahead and remove all the sql comments of old code then to keep clean? git history will always be there if needed :)

**Comment by henrystats** [comment]
oke ser will do now @jeff-dude

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
