### PR TITLE
Zksync native bridge flows

### PR DESCRIPTION
**Pull request by lgingerich**
All data looks good, other than the fact that I messed up the token/price joins to only include `zksync` and not `ethereum`. I'll do another check in the CI output table before wanting to move forward.

Did not catch it in time before this got merged

### CODE REVIEW

**Comment by jeff-dude** [comment]
sounds good, looks like you need to merge our main into your branch

**Comment by lgingerich** [comment]
Yep, I keep missing stuff, thanks

**Review by jeff-dude — APPROVED** [review]
works for me, let me know if you're good on the CI table output

**Comment by lgingerich** [comment]
CI table output (finally) looks good to me. Good with merging

**Pull request merged**
