### PR TITLE
Drop airdrop claims

### PR DESCRIPTION
**Pull request by aalan3**
Dropped airdrops claims, the blockchain files and one more level down for the project files.

### CODE REVIEW

**Comment by aalan3** [comment]
The CI check here for schemas is not happy here. Not sure I should add dummy models or if there's another way

**Review by jeff-dude — APPROVED** [review]

**Comment by aalan3** [comment]
@jeff-dude don't merge this just yet, if we do it will fail CI for all subsequent PRs. We need to update the check or script first.

**Comment by jeff-dude** [comment]
> @jeff-dude don't merge this just yet, if we do it will fail CI for all subsequent PRs. We need to update the check or script first.

yeah, holding off, just marking for my awareness to find later

**Comment by jeff-dude** [comment]
closing due to latest approach discussed in our grooming session, where we don't need lineage drops

**Pull request closed without merging**
