### PR TITLE
T-31588 - Set join_distribution_type='PARTITION' as session property

### PR DESCRIPTION
**Pull request by belen-pruvost**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by belen-pruvost** [comment]
Let's wait until Monday at least to confirm this approach

**Comment by belen-pruvost** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by belen-pruvost** [comment]
recheck

**Comment by belen-pruvost** [comment]
Tables that are not materialized and partitioned don't get any session properties set:
Screenshot 2023-07-31 at 18 15 55
Screenshot 2023-07-31 at 18 16 02


Tables that not materialized and partitioned get any session properties set:
Screenshot 2023-07-31 at 18 19 03
Screenshot 2023-07-31 at 18 19 11

**Comment by jeff-dude** [comment]
i think we need a bit further testing on this. the last CI run had the 300+ models triggered, but also contained views (i.e. `uniswap_trades`).

since it's a pre-hook, i think only `dbt run` commands would output what we'd want to see in the logs.

the first thing i'd try locally:
- `dbt run --select <model which fits criteria>`, i.e. an incremental with partition set
- then check logs in repo, search for the trino session property sql statement, see the query output and ensure it's good
- try `dbt run --select <model which doesn't fit criteria>`, i.e. a view and no partition
- and ensure the logs don't have the command

**Comment by jeff-dude** [comment]
> i think we need a bit further testing on this. the last CI run had the 300+ models triggered, but also contained views (i.e. `uniswap_trades`).
> 
> since it's a pre-hook, i think only `dbt run` commands would output what we'd want to see in the logs.
> 
> the first thing i'd try locally:
> 
> * `dbt run --select <model which fits criteria>`, i.e. an incremental with partition set
> * then check logs in repo, search for the trino session property sql statement, see the query output and ensure it's good
> * try `dbt run --select <model which doesn't fit criteria>`, i.e. a view and no partition
> * and ensure the logs don't have the command

@couralex6 is in your timezone currently, so tomorrow morning he should be able to help you setup/run locally

**Comment by couralex6** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
