### PR TITLE
migrate erc4337 to dunesql

### PR DESCRIPTION
**Pull request by 0xbitfly**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by jeff-dude** [comment]
hi @0xbitfly -- thank you for jumping in on the migration efforts 🤝 

can i request that you start simple, with one blockchain in a PR? it'll be quicker to debug / review, then we can get some momentum and knock out more blockchain versions after

**Comment by 0xbitfly** [comment]
@jeff-dude hi, i can't figure out how is the error caused.  i have replace the `timestamp` with `date`, it still trigger the `unsupported type: timestamp(3) with time zone` error. any hint?

``` bash
Run dbt -x run $PROFILE --select state:modified$TAG --exclude tag:prod_exclude --defer --state .
  dbt -x run $PROFILE --select state:modified$TAG --exclude tag:prod_exclude --defer --state .
  shell: /usr/bin/bash -e {0}
  env:
    PROFILE: --profiles-dir /home/github/.dbt --profile dunesql
    TAG: ,tag:dunesql
    COMPILE_TAG: --select tag:dunesql
    S3_LOCATION: manifest-spellbook-dunesql
    GIT_SHA: 1bbae7df
  
13:56:57  Running with dbt=1.4.6
13:57:04  Found [2](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:2)66[3](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:3) models, 2089 tests, 0 snapshots, 0 analyses, 585 macros, 0 operations, 122 seed files, 1653 sources, 0 exposures, 0 metrics
13:57:05  
13:57:13  Concurrency: 8 threads (target='dev')
13:57:13  
13:57:13  1 of [4](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:4) START sql incremental model test_schema.git_dunesql_1bbae7df_account_abstraction_erc4337_ethereum_v0_[5](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:5)_userops_basics  [RUN]
13:57:13  2 of 4 START sql incremental model test_schema.git_dunesql_1bbae7df_account_abstraction_erc4337_ethereum_v0_[6](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:6)_userops_basics  [RUN]
13:5[7](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:7):16  1 of 4 ERROR creating sql incremental model test_schema.git_dunesql_1bbae7df_account_abstraction_erc4337_ethereum_v0_5_userops_basics  [ERROR in 2.[9](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:9)0s]
13:57:16  2 of 4 ERROR creating sql incremental model test_schema.git_dunesql_1bbae7df_account_abstraction_erc4337_ethereum_v0_6_userops_basics  [ERROR in 2.99s]
13:57:16  CANCEL query model.spellbook.account_abstraction_erc4337_ethereum_v0_5_userops_basics  [CANCEL]
13:57:16  CANCEL query model.spellbook.account_abstraction_erc4337_ethereum_v0_6_userops_basics  [CANCEL]
13:57:16  
13:57:16  Database Error in model account_abstraction_erc4337_ethereum_v0_6_userops_basics (models/account_abstraction/erc4337/ethereum/account_abstraction_erc4337_ethereum_v0_6_userops_basics.sql)
13:57:16    TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="unsupported type: timestamp(3) with time zone", query_id=20230717_135714_16179_x6ccr)
13:57:16    compiled Code at target/run/spellbook/models/account_abstraction/erc4337/ethereum/account_abstraction_erc4337_ethereum_v0_6_userops_basics.sql
13:57:16  
13:57:16  Finished running 2 incremental models in 0 hours 0 minutes and [11](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:12).44 seconds (11.44s).
[13](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:14):57:[17](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:18)  Encountered an error:
FailFast Error in model account_abstraction_erc4337_ethereum_v0_6_userops_basics (models/account_abstraction/erc4337/ethereum/account_abstraction_erc4337_ethereum_v0_6_userops_basics.sql)
  Failing early due to test failure or runtime error
Error: Process completed with exit code 2.
```

**Comment by jeff-dude** [comment]
> @jeff-dude hi, i can't figure out how is the error caused. i have replace the `timestamp` with `date`, it still trigger the `unsupported type: timestamp(3) with time zone` error. any hint?
> 
> ```shell
> Run dbt -x run $PROFILE --select state:modified$TAG --exclude tag:prod_exclude --defer --state .
>   dbt -x run $PROFILE --select state:modified$TAG --exclude tag:prod_exclude --defer --state .
>   shell: /usr/bin/bash -e {0}
>   env:
>     PROFILE: --profiles-dir /home/github/.dbt --profile dunesql
>     TAG: ,tag:dunesql
>     COMPILE_TAG: --select tag:dunesql
>     S3_LOCATION: manifest-spellbook-dunesql
>     GIT_SHA: 1bbae7df
>   
> 13:56:57  Running with dbt=1.4.6
> 13:57:04  Found [2](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:2)66[3](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:3) models, 2089 tests, 0 snapshots, 0 analyses, 585 macros, 0 operations, 122 seed files, 1653 sources, 0 exposures, 0 metrics
> 13:57:05  
> 13:57:13  Concurrency: 8 threads (target='dev')
> 13:57:13  
> 13:57:13  1 of [4](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:4) START sql incremental model test_schema.git_dunesql_1bbae7df_account_abstraction_erc4337_ethereum_v0_[5](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:5)_userops_basics  [RUN]
> 13:57:13  2 of 4 START sql incremental model test_schema.git_dunesql_1bbae7df_account_abstraction_erc4337_ethereum_v0_[6](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:6)_userops_basics  [RUN]
> 13:5[7](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:7):16  1 of 4 ERROR creating sql incremental model test_schema.git_dunesql_1bbae7df_account_abstraction_erc4337_ethereum_v0_5_userops_basics  [ERROR in 2.[9](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:9)0s]
> 13:57:16  2 of 4 ERROR creating sql incremental model test_schema.git_dunesql_1bbae7df_account_abstraction_erc4337_ethereum_v0_6_userops_basics  [ERROR in 2.99s]
> 13:57:16  CANCEL query model.spellbook.account_abstraction_erc4337_ethereum_v0_5_userops_basics  [CANCEL]
> 13:57:16  CANCEL query model.spellbook.account_abstraction_erc4337_ethereum_v0_6_userops_basics  [CANCEL]
> 13:57:16  
> 13:57:16  Database Error in model account_abstraction_erc4337_ethereum_v0_6_userops_basics (models/account_abstraction/erc4337/ethereum/account_abstraction_erc4337_ethereum_v0_6_userops_basics.sql)
> 13:57:16    TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="unsupported type: timestamp(3) with time zone", query_id=20230717_135714_16179_x6ccr)
> 13:57:16    compiled Code at target/run/spellbook/models/account_abstraction/erc4337/ethereum/account_abstraction_erc4337_ethereum_v0_6_userops_basics.sql
> 13:57:16  
> 13:57:16  Finished running 2 incremental models in 0 hours 0 minutes and [11](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:12).44 seconds (11.44s).
> [13](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:14):57:[17](https://github.com/duneanalytics/spellbook/actions/runs/5576520132/jobs/10187923966?pr=3772#step:10:18)  Encountered an error:
> FailFast Error in model account_abstraction_erc4337_ethereum_v0_6_userops_basics (models/account_abstraction/erc4337/ethereum/account_abstraction_erc4337_ethereum_v0_6_userops_basics.sql)
>   Failing early due to test failure or runtime error
> Error: Process completed with exit code 2.
> ```

looks like it's the partition column [here](https://github.com/duneanalytics/spellbook/pull/3772/files#diff-11be3fa8a093380da38d584c2e7cbaaf01463a850ae2cc91f9c621cc566090aaR13). we have seen issues with the partition column being timestamp as well. with that in mind, we should be partitioning at a much higher level of granularity anyway (must've been an oversight in original creation). can you add a column with something like:
`cast(date_trunc(evt_block_time, 'month') as date) as block_month`
then use that as partition column?

**Comment by 0xbitfly** [comment]
@jeff-dude the unit-test seems can not find the the `seed` table.  is there any modify for dunesql ?

``` bash
02:48:49  Completed with 18 errors and 0 warnings:
02:48:49  
02:48:49  Database Error in test check_seed_account_abstraction_erc4337_arbitrum_userops_tx_hash__bundler__arbitrum__v0_5__userop_hash__ref_account_abstraction_erc4337_userops_seed_ (models/account_abstraction/erc4337/arbitrum/account_abstraction_erc4337_arbitrum_schema.yml)
02:48:49    TrinoUserError(type=USER_ERROR, name=SCHEMA_NOT_FOUND, message="line 18:18: Schema 'test_data' does not exist", query_id=20230718_024845_04871_x6ccr)
02:48:49  
02:48:49  Database Error in test check_seed_account_abstraction_erc4337_arbitrum_userops_tx_hash__bundler__arbitrum__v0_6__userop_hash__ref_account_abstraction_erc4337_userops_seed_ (models/account_abstraction/erc4337/arbitrum/account_abstraction_erc4337_arbitrum_schema.yml)
02:48:49    TrinoUserError(type=USER_ERROR, name=SCHEMA_NOT_FOUND, message="line 18:18: Schema 'test_data' does not exist", query_id=20230718_024845_04872_x6ccr)
```

**Comment by 0xbitfly** [comment]
> > @jeff-dude the unit-test seems can not find the the `seed` table. is there any modify for dunesql ?
> > ```shell
> > 02:48:49  Completed with 18 errors and 0 warnings:
> > 02:48:49  
> > 02:48:49  Database Error in test check_seed_account_abstraction_erc4337_arbitrum_userops_tx_hash__bundler__arbitrum__v0_5__userop_hash__ref_account_abstraction_erc4337_userops_seed_ (models/account_abstraction/erc4337/arbitrum/account_abstraction_erc4337_arbitrum_schema.yml)
> > 02:48:49    TrinoUserError(type=USER_ERROR, name=SCHEMA_NOT_FOUND, message="line 18:18: Schema 'test_data' does not exist", query_id=20230718_024845_04871_x6ccr)
> > 02:48:49  
> > 02:48:49  Database Error in test check_seed_account_abstraction_erc4337_arbitrum_userops_tx_hash__bundler__arbitrum__v0_6__userop_hash__ref_account_abstraction_erc4337_userops_seed_ (models/account_abstraction/erc4337/arbitrum/account_abstraction_erc4337_arbitrum_schema.yml)
> > 02:48:49    TrinoUserError(type=USER_ERROR, name=SCHEMA_NOT_FOUND, message="line 18:18: Schema 'test_data' does not exist", query_id=20230718_024845_04872_x6ccr)
> > ```
> 
> we don't run seeds in prod & our CI process will look for objects in prod when they aren't modified in the PR. you will need to push a dummy edit to the seed files to the PR so they build here. it can just be a new line at the end or something

i just edit the seed file. but it not work. any other hint?

**Comment by jeff-dude** [comment]
this PR still has a large scope of items with so many models included, so it's hard to pinpoint all exactly, but you will need to ensure all models included in PR that contain seeds are included here. all schema yaml files which contain metadata about the models should tell you which have seed files and which don't. plz double check all are included, or close this PR and start with a smaller set of models to easily identify.

the other thing to check is that the legacy models use the legacy seed check macro, and the dunesql models use the non-legacy check seed macro

**Pull request closed without merging**
