### PR TITLE
OP Token Distributions v1

### PR DESCRIPTION
**Pull request by MSilb7**
Brief comments on the purpose of your changes:

!Keeping this up as a draft to test as I go, and make sure changes to labels and things are implemented.~

Should be good to go now! The contains various address mappings tables and token transfer tagging. The stated project wallets are already in labels, but many other distribution wallets are speculative/guesses for now (we will have a formal reporting process getting started which will help).

Also, once https://github.com/duneanalytics/spellbook/pull/2731 gets merged, we can add transfers to these wallets to known incentive distributions.

Goal: Migrate the data that powers this in to a spell so that queries run faster & it's less of a mess & others can contribute.

Open Q:
- How can we ensure that the "Distributions" model updates whenever address lists are changed?

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by MSilb7** [comment]
I keep getting this error, can't figure out why...

`Couldn't find to_name#1629316 in [evt_block_time#1629305,evt_block_number#1629306L,evt_index#1629307,tx_to_address#1629308,tx_from_address#1629309,evt_tx_hash#1629310,from_label#1629311,from_type#1629312,from_name#1629313,to_type#1629314,to_label#1629315,op_amount_decimal#1629317,tx_method#1629318,from_address#1629321,to_address#1629322,block_date#1629304]`

**Comment by jeff-dude** [comment]
> I keep getting this error, can't figure out why...
> 
> `Couldn't find to_name#1629316 in [evt_block_time#1629305,evt_block_number#1629306L,evt_index#1629307,tx_to_address#1629308,tx_from_address#1629309,evt_tx_hash#1629310,from_label#1629311,from_type#1629312,from_name#1629313,to_type#1629314,to_label#1629315,op_amount_decimal#1629317,tx_method#1629318,from_address#1629321,to_address#1629322,block_date#1629304]`

that means the `to_name` column wasn't in select of CTE, so downstream can't find it

**Comment by jeff-dude** [comment]
please compile the query, run on dune and find where the missing column is

**Comment by MSilb7** [comment]
Specifying column names in the last CTE, rather than * to see if that solves the issue.

**Comment by MSilb7** [comment]
I'm not getting issues when I run it in Dune https://dune.com/queries/2167745?d=1

Weird...

**Comment by MSilb7** [comment]
omg we did it. cc @jeff-dude, the issue seemed to be that `to_name` had some error in joins/selects way upstream because some values were null. Idk if a test could've caught that, but I added a bunch of not null tests now to error-proof in the future.

**Review by jeff-dude — APPROVED** [review]
good usage of the PR testing process 🤝

**Pull request merged**
