### PR TITLE
Update dex info

### PR DESCRIPTION
**Pull request by Hosuke**
- Add missing dexes
- Fix thena typo

### CODE REVIEW

**Comment by jeff-dude** [comment]
is there something i can help look at, or you know what the failure here is?

**Comment by Hosuke** [comment]
> is there something i can help look at, or you know what the failure here is?

It shows not existed dex `then` in the dex.trades table:
https://dune.com/queries/3355041

**Comment by Hosuke** [comment]
Ok, after refreshing all roll-up middle spells, the CI is passing now.

**Review by jeff-dude — APPROVED** [review]
thank you for seeing this all the way through. sometimes we have to take those painful steps to prove it out prior to prod 😅 

looking better now!

**Pull request merged**
