### PR TITLE
[quick fix] revert last PR on labels table

### PR DESCRIPTION
**Pull request by catherine-2**
Sorry! I realized I think we should remove the table I just uploaded from the main labels table / function in Dune. 

Some additional context below. Let me know of any questions!

- The usernames I uploaded are for SuperRare users - most of these will be active SuperRare users but I can't guarantee 100% (e.g. may have just made an account but never purchased anything). Because it is static it is also not comprehensive, though I plan to maintain every few weeks. So don't think it makes sense to tag them as an active SR user on the labels function / table
- I can build a code based table later on if we want (e.g. look on chain at addresses that are active on SR) though think it makes sense to do that in tandem with other NFT marketplaces as well 
- However I think it's still valuable to have the separate table of SR usernames under this general category so I didn't remove the new sr table itself. This table I put together is an update to a deprecated v1 table that was used on a number of dashboards
https://github.com/duneanalytics/spellbook/blob/8bc08889ce260676888fe0449156c87739a92f32/deprecated-dune-v1-abstractions/ethereum/superrare/usernames.sql

Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by catherine-2** [comment]
Going to make a few other changes - will tag once ready for review!

**Comment by catherine-2** [comment]
@jeff-dude sorry quick change to the PR we just merged - I added context in the first comment, let me know any questions! thank you!

**Comment by jeff-dude** [comment]
hi @catherine-2 -- this makes sense. if we back out of the final labels table, maybe we should just move this static user list to the superrare/ethereum/ models directory and get out of labels altogether?
then later on when ready to write a query against the list, we can add that to labels?

if you agree, feel free to move the files around and i can get it merged

**Comment by catherine-2** [comment]
@jeff-dude Checks passed! Think it should be ready to merge but let me know if you see any issues - thank you!

**Review by jeff-dude — APPROVED** [review]
pushed a minor commit to rename similar to v1 engine, we can save the labels tag for next phase :) also added to schema file for docs

**Comment by catherine-2** [comment]
@jeff-dude  thank you!

Do you know what the table name is on Dune? I just tried a few but couldn't find - below are the ones I tried. I had already written some queries using labels table we merged yesterday so want to fix them to use the new name

select * 
from superrare.usernames
-- from superrare_ethereum.usernames
-- from superrare.ethereum_usernames
-- from superrare_ethereum.ethereum_usernames

**Comment by jeff-dude** [comment]
it will be ```superrare.usernames``` -- our prod job just ran with updated main branch, can you confirm now?

**Comment by jeff-dude** [comment]
> @jeff-dude Ah yes it works now! Got it - will be more patient in the future 😅 thank you again!

fyi, the job runs on the hour every hour, with first step being to create new models & full refresh edit of existing models (if applicable). then the normal incremental models load after that. on average, ~30-45 minute full run time as of now, with new views usually on the front-end of that timeframe

**Comment by catherine-2** [comment]
@jeff-dude super helpful context - thank you!

**Pull request merged**
