### PR TITLE
Adding Ethereum Genesis balances

### PR DESCRIPTION
**Pull request by bernatfp**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by bernatfp** [comment]
I am not sure if the namespace naming / model structure I have chosen is optimal, let me know if I should change it.

**Review by augustog — CHANGES_REQUESTED** [review]
Looks good! I think only the config block is missing.

As for structure, I think it makes more sense to put this under the `balances` model, since it will be a dependency of `balances_eth`.

This would mean:
- Changing the dbt_project.yml file (since we already have balances there, we don't need to add anything new)
- Changing directory structure

**Review by bernatfp — COMMENTED** [review]
Done

**Review by augustog — APPROVED** [review]

**Comment by augustog** [comment]
Looks good! Added a few minor adjustments to match conventions of other spells.
Quick EDA
- [First 100 records ](https://dune.com/queries/1736303?d=1)look as expected ✅ 
- [Aggregates](https://dune.com/queries/1736306) show no duplicates and now nulls ✅ 

This looks good to me cc @jeff-dude

**Pull request merged**
