### PR TITLE
Dex Aggregator Migration - #5 - Paraswap - WIP

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
hola ser @jeff-dude, I'm getting this constant error with paraswap

```Database Error in model paraswap_v4_ethereum_trades (models/paraswap/ethereum/paraswap_v4_ethereum_trades.sql)
13:15:07    TrinoQueryError(type=INSUFFICIENT_RESOURCES, name=CLUSTER_OUT_OF_MEMORY, message="Query killed because the cluster is out of memory. Please try again in a few minutes.", query_id=20230815_131001_66254_9uda9)
13:15:07    compiled Code at target/run/spellbook/models/paraswap/ethereum/paraswap_v4_ethereum_trades.sql```

The ethereum models are quite complex, I'm wondering if there was any similar issues when the spell was originally set up?

I didn't make any changes to the code... just migrated to dunesql.. I'll try and optimize by creating one (ethereum transactions table) as there are multiple join with the etheruem transactions & erc20 transfer tables so I wonder if that would optimize the spell..

**Comment by henrystats** [comment]
compiled version on dune 👀 < Error: Query exceeds cluster capacity (memory/pages), please optimize your query [Execution ID: 01H7WQQBP69FVVRSFMSYE3XXKV].>

guess I have to separate out the tables

**Comment by jeff-dude** [comment]
gm ser, few things to try that i've learned recently on dunesql engine performance:
- move the largest table to the `FROM` statement, and then join in smaller ones (so if previously used left join, would switch to right if the table order switched, etc.)
- consider adding this `pre-hook` to tell the engine the type of join distribution to do

**Comment by henrystats** [comment]
Hola ser @jeff-dude I didn't get a notification that you replied here :(... I'll take a look at fixing this..

I don't understand what you mean by "pre-hook" thoigh//

**Pull request closed without merging**
