### PR TITLE
Make nft.wash_trades easier to use + final small tweaks

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by hildobby** [comment]
⚠️ MANUAL TIMEOUT CHANGE TO BE REMOVED BEFORE MERGING ⚠️

**Comment by jeff-dude** [comment]
it's a bit worrisome to see the query still timing out. i think it will need to be refined further

**Comment by hildobby** [comment]
> it's a bit worrisome to see the query still timing out. i think it will need to be refined further

It runs for every single NFT trade on Ethereum so it has quite a bit to run on so runtime does make a bit of sense to me. I can also run it on dune.com for the past day and it takes less runtime than running OpenSea's abstraction for the past day on dune.com 🤷 

I did add one more Join for increased accuracy but otherwise it's just variable name changes (so they're easier for others to find in the table)

You don't think it's good to go?

**Comment by dot2dotseurat** [comment]
@hildobby we can't merge this because our incremental job would completely break down if we added a model that was this compute-intensive. But I think there are things we can do to refactor. 

refactoring is imho completely hellish/impossible if your model can't finish in five hours. So what I am suggesting if you use some sampled data and a "refactor test" which is just the current state rather than a test where we know all the values are 100% correct. Then you can make changes to your query without worrying about inadvertently breaking your past sql logic. 

I think this will be helpful to make the development cycle much shorter and make refactoring less time-consuming. When you are done just replace the sampled tables with the real ones and see if runtime has improved. 

I made two new sources. 
table_sample_nft.trades_2022_11_20
(nft trades from 2022-11-20)
table_sample_nft.addresses_events_ethereum_first_funded_by_GT_2022_11_10
(addresses_events_ethereum_first_funded_by greater than 2022-11-10)

I added a seed which is your existing logic but with the sampled tables above
nft_wash_trades_refactor_seed.csv

And finally, a test nft_wash_trades_refactor_test
which compares the wash trades columns from your model to the seed. 

As for refactoring, this is my suggestion. But don't hate me if it doesn't work. 
Convert all the joins to inner joins and create CTEs for each filter, merge them together, do a single left join to nft.trades at the end. 

so CTE_1 -> only trades with same buyer seller
...
CTE_MERGE 
UNIQUE_KEY, FILTER_1, FILTER_2... FILTER_N
...
nft.trades left join CTE_MERGE

**Pull request closed without merging**
