### PR TITLE
SPE-19  Aggregator Migration - #6 - OpenOcean

### PR DESCRIPTION
**Pull request by antonio-mendes**
Migrates OpenOcean on AVAX and Fantom - it's a dependency for dex_aggregator

### CODE REVIEW

**Comment by henrystats** [comment]
hola ser @antonio-mendes are you planning to migrate the other models in the dex_aggregator sector?


I built a couple of them and I was planning to migrate the dex_aggregator models later today as I just completed the perpetuals tables migration...


Please lmk if I can still be of any help!

**Comment by antonio-mendes** [comment]
Hey Henry!

Feel free to go ahead and migrate other models, I just picked this one
randomly for now.

Thanks btw!

**Comment by henrystats** [comment]
okie dokie ser.. thanks very much! I'll set up pr's later today for the remaining models.

**Comment by henrystats** [comment]
@antonio-mendes in cow_protocol trades, maker is still casted as varchar...and it should now be varbinary.. I can submit a pr to update cow_protocol trades but wanted to drop a tag here so open ocean's maker column could be casted as varbinary..

**Comment by henrystats** [comment]
Hola ser @antonio-mendes, the trace address column is necessary in the dex_aggregator_seed test as some models require it for their unique keys.

I faced some issues because of the ,, being used for null trace address... I noticed that in another model 

`array[-1] as trace_address` was used as a default value for the trace address instead of null so I used that and then edit the `,,` in the seeds for the model I was editing and entered `-1` the tests passed afterwards.

**Comment by antonio-mendes** [comment]
Thanks for flagging the `trace_address` point @henrystats !! Almost missed that

**Pull request merged**
