### PR TITLE
Create `zora.mints` incl. Ethereum, Zora Network, Optimism, Base & Goerli

### PR DESCRIPTION
**Pull request by hildobby**

### CODE REVIEW

**Comment by hildobby** [comment]
That's a new error and I'm not sure what it means 🤔 Would love some help here @jeff-dude @0xRobin 

`TrinoUserError(type=USER_ERROR, name=MERGE_TARGET_ROW_MULTIPLE_MATCHES, message="One MERGE target table row matched more than one source row", query_id=20230826_082919_65679_ksage)
08:29:22    compiled Code at target/run/spellbook/models/zora/zora_mints.sql`

**Comment by jeff-dude** [comment]
> That's a new error and I'm not sure what it means 🤔 Would love some help here @jeff-dude @0xRobin
> 
> `TrinoUserError(type=USER_ERROR, name=MERGE_TARGET_ROW_MULTIPLE_MATCHES, message="One MERGE target table row matched more than one source row", query_id=20230826_082919_65679_ksage) 08:29:22 compiled Code at target/run/spellbook/models/zora/zora_mints.sql`

this means your initial historical run loaded duplicates, then incremental run couldn't determine which row to update. you can now see there are dupes after adding the tests in latest commit

**Comment by hildobby** [comment]
> > That's a new error and I'm not sure what it means 🤔 Would love some help here @jeff-dude @0xRobin
> > `TrinoUserError(type=USER_ERROR, name=MERGE_TARGET_ROW_MULTIPLE_MATCHES, message="One MERGE target table row matched more than one source row", query_id=20230826_082919_65679_ksage) 08:29:22 compiled Code at target/run/spellbook/models/zora/zora_mints.sql`
> 
> this means your initial historical run loaded duplicates, then incremental run couldn't determine which row to update. you can now see there are dupes after adding the tests in latest commit

Ah thanks, that makes sense, the new error had me confused at first!

**Comment by 0xRobin** [comment]
@hildobby please note the directory changes made in https://github.com/duneanalytics/spellbook/pull/4486
To follow the same design patterns as nft.trades we should add the zora mint models in a directory:
`/models/_sector/nft/mints/platforms/` 
You can dump all the legacy models in the `legacy` folder that's already there, makes for ez cleanup afterwards.

**Comment by jeff-dude** [comment]
closing due to inactivity, feel free to reopen as needed 🤝

**Review by jeff-dude — APPROVED** [review]
okay, pushed changes to merge. hope this works for you both @hildobby @0xRobin 
- remove dependency on `evms.info`, for better orchestration in prod, use variables instead to get address
- add incremental filters throughout
- add goerli, even though it looks like no rows come through when querying CI table

**Pull request merged**
