### PR TITLE
Maverick on ethereum dex trades

### PR DESCRIPTION
**Pull request by jeff-dude**
replace #2934 due to access issues, commit history remains intact

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]

**Comment by jeff-dude** [comment]
i'm not following why the asset volume test is failing. i've copied the test into dune, ran on the dex trades table created via the CI test, but it shows no rows returned (as expected)

**Comment by Hosuke** [comment]
> i'm not following why the asset volume test is failing. i've copied the test into dune, ran on the dex trades table created via the CI test, but it shows no rows returned (as expected)

I will try to fix the test wombat_bnb_assert_samples in this PR.

**Comment by Hosuke** [comment]
Fixed `wombat_bnb_assert_samples` as its original column names contain characters outside ASCII.

**Comment by jeff-dude** [comment]
> i'm not following why the asset volume test is failing. i've copied the test into dune, ran on the dex trades table created via the CI test, but it shows no rows returned (as expected)

nevermind. it was the freshness test, not volume. i've removed airswap for now, unrelated to this PR.

**Pull request merged**
