### PR TITLE
Velodrome tokenlist.

### PR DESCRIPTION
**Pull request by stas**
Sorry for the large set to review. I extracted the tokens based on our tokenlist we'd need the prices for in Dune.

Appreciate if you guys could review this :pray: 

/cc @antonio-mendes

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by stas** [comment]
Might need to remove the tokens provided via #1742 

Should we merge first #1730 

/cc @MSilb7 please let me know if I can help get these merged :pray:

**Comment by MSilb7** [comment]
> 

Yeah #1730 has a lot of mappings, then we can find the diff here.

Are the coinpaprika ids accurate for a lot of them? Looks like the token symbol duplicated twice. But since coinpaprika doesn't list a lot of L2 tokens, I think we'll have to build our own price approximation table (similar to v1) once #1730 and #1731 get merged. Waiting on Dune team review.

**Comment by augustog** [comment]
hey all!

indeed most coinpaprika ids are wrong (see below), in any case it seems we should get the two others looked into first. 

Labeling this one as WIP in the meantime and jumping to #1730 & #1731. Below is the list of ids that didn't match, for reference:

token_id | error
-- | --
0xbtc-0xbtc | id not found
aave-aave | id not found
acrv-acrv | id not found
aelin-aelin | id not found
aleth-aleth | id not found
alusd-alusd | id not found
bal-bal | id not found
baxa-baxa | id not found
bond-bond | id not found
crv-crv | id not found
ctsi-ctsi | id not found
dcn-dcn | id not found
df-df | id not found
dht-dht | id not found
dola-dola | id not found
ens-ens | id not found
eqz-eqz | id not found
fxs-fxs | id not found
gtc-gtc | id not found
gysr-gysr | id not found
han-han | id not found
hnd-hnd | id not found
jeur-jeur | id not found
knc-knc | id not found
krom-krom | id not found
l2dao-l2dao | id not found
ldo-ldo | id not found
link-link | id not found
liz-liz | id not found
lpf-lpf | id not found
lrc-lrc | id not found
lusd-lusd | id not found
lyra-lyra | id not found
mai-mai | id not found
mask-mask | id not found
mkr-mkr | id not found
o3-o3 | id not found
op-op | id not found
openx-openx | id not found
opl-opl | id not found
opp-opp | id not found
perp-perp | id not found
petho-petho | id not found
pool-pool | id not found
qi-qi | id not found
rai-rai | id not found
rfwsteth-rfwsteth | id not found
rgt-rgt | id not found
sarco-sarco | id not found
sdl-sdl | id not found
setho-setho | id not found
slink-slink | id not found
snx-snx | id not found

**Comment by stas** [comment]
Thank you @augustog and sorry about this (didn't know these have to match). Will take care of it by tomorrow :bow:

**Comment by augustog** [comment]
@stas please wait on https://github.com/duneanalytics/spellbook/pull/1730 & https://github.com/duneanalytics/spellbook/pull/1731. I'd suggest:
- check which tokens are already covered by both sources (coinpaprika & chainlink)
- add any that are missing here or in a new PR to another source (e.g. chainlink)
- if adding token feeds to coinpaprika, make sure that they exist on cp and have active price feeds (e.g. rETH is inactive)

happy to assist further if you need!

**Comment by stas** [comment]
Closing in favor of https://github.com/MSilb7/spellbook/pull/4

**Pull request closed without merging**
