### PR TITLE
MagicEden solana: fix unique trade id

### PR DESCRIPTION
**Pull request by 0xRobin**
fixes null unique trade id

### CODE REVIEW

**Comment by jeff-dude** [comment]
about to push a batch of merges, are we thinking this should be good after it's CI run? i can wait for this, as a large refresh in prod will already be happening

**Comment by 0xRobin** [comment]
@jeff-dude tests have failed, so no need to further wait on this.

**Review by jeff-dude — APPROVED** [review]
thanks for the fix 🤝 

was thinking about changing `unique_key` to just `id` rather than `unique_trade_id`, but we can save that for the larger overhaul

also going to save this merge for the morning EST tomorrow, so we're all available

**Comment by jeff-dude** [comment]
context for dunesql label:
- our gh action as a whole times out at 60 minutes. this model takes almost all that time to run/test (solana volume is large). i wonder if this makes us rethink including in existing CI gh action or if we should extend the time 🤔

**Pull request merged**
