### PR TITLE
Dex_trades: remove partition by project

### PR DESCRIPTION
**Pull request by couralex6**

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
pushed a commit to remove from base trades too

**Comment by 0xRobin** [comment]
note that this will decrease the performance of any project-specific queries (like `uniswap.trades`)

**Comment by jeff-dude** [comment]
> note that this will decrease the performance of any project-specific queries (like `uniswap.trades`)

yeah, testing performance now.

background for this PR:
- partitions with spaces (`0x API`, `1inch LOP`) are causing issues in pricing pipeline downstream

try two things:
- remove `project` altogether, assuming no major performance impact
- rename those projects, not fully sure the downstream impact on queries

**Comment by jeff-dude** [comment]
okay, yes, performance on the downstream project views is degraded enough to not make this change right now. i will close this PR, then ask those above teams if we can change project name.

**Pull request closed without merging**
