### PR TITLE
T-21220 - Make nft.mints Trino compatible

### PR DESCRIPTION
**Pull request by belen-pruvost**

### CODE REVIEW

**Comment by jeff-dude** [comment]
@belen-pruvost i think magiceden will likely continue to timeout -- did this get tested locally? can we feel confident to merge?

**Comment by jeff-dude** [comment]
keep in mind that magiceden events model will feed into essentially everything nft downstream

**Comment by belen-pruvost** [comment]
No, I'm still building this model (it's taking forever, even using the incremental date filters). That's why I haven't pushed this one out for review yet 😅

**Comment by belen-pruvost** [comment]
The changes of this PR are essentially a subset of the changes in https://github.com/duneanalytics/spellbook/pull/2272. So I will close this one.

**Pull request closed without merging**
