### PR TITLE
add morpho blue to lending sector

### PR DESCRIPTION
**Pull request by hildobby**
### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by hildobby** [comment]
Screenshot 2024-07-12 at 01 42 06
@jeff-dude  any chance we could get column name in the log when we get this kind of error? that would be a huge help

**Comment by jeff-dude** [comment]
> Screenshot 2024-07-12 at 01 42 06 @jeff-dude any chance we could get column name in the log when we get this kind of error? that would be a huge help

i believe this is just a trino default error message. not sure it can be overwritten.

@belen-pruvost any additional insight on this error and ability to surface column name? or do we need to continue to compile the query and count out the column position?

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
adding blocked until the other morpho PRs are marked ready

**Comment by belen-pruvost** [comment]
> @belen-pruvost any additional insight on this error and ability to surface column name? or do we need to continue to compile the query and count out the column position?

hey @jeff-dude! This error is populated by Trino.

We discussed this with @kasiafi and the input causing mismatch can be a source table or a subquery, and the field name may not always be present (or there could be ambiguity on its name). We don't think we could propose an upstreamable solution, but we can try to make errors more clear on some scenarios on our fork. We added this to our backlog, I'll tag you for reference.

**Comment by hildobby** [comment]
> adding blocked until the other morpho PRs are marked ready

they're all ready to be merged now, but fyi, there may be some merge conflicts across PRs with the sources file

**Comment by jeff-dude** [comment]
> > adding blocked until the other morpho PRs are marked ready
> 
> they're all ready to be merged now (#6359 & #6360), but fyi, there may be some merge conflicts across PRs with the sources file
> 
> this is probably also worth merging alongside since it will refresh the same table: #6331

sounds good, will get it all queued up

**Pull request merged**
