### PR TITLE
Add zkSync to Contracts Mapping

### PR DESCRIPTION
**Pull request by MSilb7**
Adds logic to pull extra zkSync contracts (where creation data is in events).

ref: https://github.com/duneanalytics/spellbook/pull/4788
cc @lgingerich for sanity checking

edit: my local dbt is throwing beethovenx schema errors, so testing compiling here.

### CODE REVIEW

**Comment by lgingerich** [comment]
@MSilb7 looks good to me, thanks for handling this

**Comment by MSilb7** [comment]
> @MSilb7 looks good to me, thanks for handling this

Awesome, also want to validate that pulling `deployerAddress` from the event `ContractDeployer_evt_ContractDeployed` is "correct" for determining what address is responsible for deploying the contract? (i.e. this is likely an address of a developer deploying a contract, not a factory, or person who happened to create a DEX pool).

**Comment by lgingerich** [comment]
Good callout. I thought that would work, but turns out it doesn't. The `deployerAddress` field can/will be a factory contract. You should use the `evt_tx_from` field to get the "developer" address.

**Comment by MSilb7** [comment]
> Good callout. I thought that would work, but turns out it doesn't. The `deployerAddress` field can/will be a factory contract. You should use the `evt_tx_from` field to get the "developer" address.

Actually, it should be fine if it's factories, because we iterate up to the top-level deployer (like for creation_trace created contracts).

**Comment by MSilb7** [comment]
Moreso like, is `deployerAddress` ~equivalent to "from" in traces? Which seems like yes.

**Comment by lgingerich** [comment]
Yes I believe they are equivalent

**Review by jeff-dude — APPROVED** [review]
thanks both -- this looks good to me

**Pull request merged**
