### PR TITLE
`lending.supply` - add repay with atokens evt

### PR DESCRIPTION
**Pull request by tomfutago**
### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [x] Bug fix

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** current total supply for certain tokens is higher comparing to onchain source 
- **Implementation details:** per @defispartan suggestion in reffed issue, adding Repay events flagged as repayWithATokens
- **Related issue(s):** #6417 

---

### CODE REVIEW

**Comment by defispartan** [comment]
Hey @tomfutago, any estimate on when you think think this will be ready?

**Comment by tomfutago** [comment]
> Hey @tomfutago, any estimate on when you think think this will be ready?

hey @defispartan hopefully by end of the week 🤞 

atm dbt-test seems to be stuck for some reason. @jeff-dude @Hosuke is this because I'm only changing macro? thought this will trigger all spells relying on it to re-run?

**Comment by jeff-dude** [comment]
> is this because I'm only changing macro? thought this will trigger all spells relying on it to re-run?

i've noticed this pattern on a few PRs lately. odd for sure. for now, if you don't mind, maybe push a model (or a few) into PR to get to run?

**Comment by foodaka** [comment]
hey @tomfutago any update on this one?

**Comment by tomfutago** [comment]
hey @foodaka - this PR is ready for review and it's in dune team hands now + comments on #6417 issue.

just one note tho:
@jeff-dude there's a conflict on supply macro, but gh doesn't allow me to resolve it - I was able to resolve merge conflict before 🤔

**Comment by jeff-dude** [comment]
> hey @foodaka - this PR is ready for review and it's in dune team hands now + comments on #6417 issue.
> 
> just one note tho: @jeff-dude there's a conflict on supply macro, but gh doesn't allow me to resolve it - I was able to resolve merge conflict before 🤔

i'll look at it all today, thanks for getting it ready 🙏

**Pull request merged**
