### PR TITLE
Add fraxswap, chronos, zyberswap and solidlizard dex to dex.trades

### PR DESCRIPTION
**Pull request by ARDev097**
Added trades data for fraxswap, chronos, zyberswap and solidlizard dex (arbitrum)

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @ARDev097 

We'll rerun CI after #5166 getting merged.

**Comment by ARDev097** [comment]
Hello @Hosuke,

After adding the DEX information in the dex_info SQL file, I am encountering the following error during checks. Could you please help me resolve this error by specifying the required changes that are needed on my end?

image

**Comment by Hosuke** [comment]
> Hello @Hosuke,
> 
> After adding the DEX information in the dex_info SQL file, I am encountering the following error during checks. Could you please help me resolve this error by specifying the required changes that are needed on my end?
> 
> image

Replied above.
We'll rerun CI after https://github.com/duneanalytics/spellbook/pull/5166 getting merged.

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @ARDev097

**Review by jeff-dude — APPROVED** [review]
thanks both!

**Pull request merged**
