### PR TITLE
add cex addresses

### PR DESCRIPTION
**Pull request by hildobby**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
am i waiting to merge, based on `wip` label?

**Comment by hildobby** [comment]
@jeff-dude Yeah I use the wip label as a don't merge yet label, is that inaccurate? Got so many projects at once I'll constantly go back to PRs and finish them days later, sorry if this is confusing!

**Comment by jeff-dude** [comment]
> @jeff-dude Yeah I use the wip label as a don't merge yet label, is that inaccurate? Got so many projects at once I'll constantly go back to PRs and finish them days later, sorry if this is confusing!

nope, that's all good!

not all wizards have the access to assign labels themselves, so i'm usually labeling. i'll leave yours as-is and wait 🙏

**Comment by hildobby** [comment]
> > @jeff-dude Yeah I use the wip label as a don't merge yet label, is that inaccurate? Got so many projects at once I'll constantly go back to PRs and finish them days later, sorry if this is confusing!
> 
> nope, that's all good!
> 
> not all wizards have the access to assign labels themselves, so i'm usually labeling. i'll leave yours as-is and wait 🙏

Ohhhh, I thought we all had access to labels editing. I tend to be very careful with those, so I always only use wip, ready_to_merge, question and easy when they make sense

**Comment by jeff-dude** [comment]
closing for now, feel free to reopen in future as needed

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
