### PR TITLE
Update Incremental Structure in Tigris Models

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!

Thank you for taking the time to submit code in Spellbook. A few things to consider:
- If you are a first-time contributor, please sign the CLA by copy & pasting **_exactly_** what the bot mentions in PR comment
- Refer to [docs](#spellbook-contribution-docs) section below to answer questions
- Dune team will review submitted PRs as soon as possible

## Spellbook sub-projects

To prepare for Spellbook to scale in size, Dune team has started to pilot sub-projects:
- For a quick overview, see [the GH discussion on the topic](https://github.com/duneanalytics/spellbook/discussions/5238)
    - Please ask questions and continue the conversation there
- The first spell lineage to move: `tokens.erc20` and all upstream spells which help build it
    - **_Note_**: Please navigate to [tokens](https://github.com/duneanalytics/spellbook/tree/main/tokens) root directory to find tokens objects

## Spellbook contribution docs

The [docs](https://github.com/duneanalytics/spellbook/tree/main/docs) directory has been implemented to answer as many questions as possible. Please take the time to reference each `.md` file within this directory to understand how to efficiently contribute & why the repo is designed as it is 🪄

Example questions to be answered:
- What does each property in the [model config block](https://github.com/duneanalytics/spellbook/blob/main/docs/models/model_config_block.md) mean?
- What is the [CI test](https://github.com/duneanalytics/spellbook/blob/main/docs/ci_test/ci_test_overview.md) attached to PRs and how can I best utilize it?
- What are the Spellbook [best practices](https://github.com/duneanalytics/spellbook/blob/main/docs/general/best_practices.md)?

Please navigate through the [docs](https://github.com/duneanalytics/spellbook/tree/main/docs) directory to find as much info as you can.

**Note**: happy to take PRs to improve the docs, let us know 🤝

### CODE REVIEW

**Comment by henrystats** [comment]
hola ser @jeff-dude, I was trying to fix the incremental predicates for the tigris spells as I noticed that was being added to the new pr's

I'm getting an error in the config that's stopping the incremental models from running 

` incremental_predicates = [incremental_predicate('DBT_INTERNAL_DEST.block_time')]`

The error I'm getting is that the column `block_time` wasn't found, what could cause this? could it be because in the final tables `block_time` isn't a column?

Most of the tables have evt_block_time & day as the time column so I'm wondering If that's what caused the error, I originally though Interal_dest.blok_time was referring to an internal source

**Comment by henrystats** [comment]
bump @jeff-dude

**Comment by jeff-dude** [comment]
> hola ser @jeff-dude, I was trying to fix the incremental predicates for the tigris spells as I noticed that was being added to the new pr's
> 
> I'm getting an error in the config that's stopping the incremental models from running
> 
> ` incremental_predicates = [incremental_predicate('DBT_INTERNAL_DEST.block_time')]`
> 
> The error I'm getting is that the column `block_time` wasn't found, what could cause this? could it be because in the final tables `block_time` isn't a column?
> 
> Most of the tables have evt_block_time & day as the time column so I'm wondering If that's what caused the error, I originally though Interal_dest.blok_time was referring to an internal source

yes, you are correct, that property in the config block for filtering incrementally is on the _target_ data, so the column must exist in the final spell. if you don't use `block_time` in the spell(s), then use whatever you do store. from a quick glance, i see `evt_block_time`, which means you could use `incremental_predicates = [incremental_predicate('DBT_INTERNAL_DEST.evt_block_time')]`

**Comment by jeff-dude** [comment]
closing for now, feel free to reopen in future as needed

**Pull request closed without merging**
