### PR TITLE
[Prices.USD] Add 311 missing, but available token prices

### PR DESCRIPTION
**Pull request by bh2smith**
Running the [missing_prices script](https://github.com/cowprotocol/data-misc/blob/main/src/missing_prices.py) displayed the following logs (similar to our missing_tokens script)

```
Getting Coin Paprika token list
Excluded address for 4937 entries out of 53440
Loaded 2927 coins from Coin Paprika
2023-04-12 10:55:37,283 INFO dune_client.client waiting for query execution 01GXTATWX2BNBJ9DA6ADT5JZ5X to complete: ExecutionState.EXECUTING
...
2023-04-12 10:56:08,307 INFO dune_client.client waiting for query execution 01GXTATWX2BNBJ9DA6ADT5JZ5X to complete: ExecutionState.EXECUTING
Fetched 2170 traded tokens from Dune without prices
Found 311 matches
Results written to missing-prices.txt
```

and created this file (which has been pasted here).

[missing-prices.txt](https://github.com/duneanalytics/spellbook/files/11209282/missing-prices.txt)

### CODE REVIEW

**Comment by jeff-dude** [comment]
it's been a minute since we've pushed a large batch of prices -- @aalan3 do you have any concerns? you can see the script in the PR description which runs against the coinpaprika API

**Comment by bh2smith** [comment]
To add some context, I have used this script in the past to add batches of several hundred tokens at a time... [Here](https://github.com/duneanalytics/spellbook/pull/1807) is one such example. In my experience, we have run into only a few issues and wound up later having to remove ~2 or 3 of them at a later point.

**Comment by jeff-dude** [comment]
> To add some context, I have used this script in the past to add batches of several hundred tokens at a time... [Here](https://github.com/duneanalytics/spellbook/pull/1807) is one such example. In my experience, we have run into only a few issues and wound up later having to remove ~2 or 3 of them at a later point.

yeah, it's been done before and the outcome was pretty good. i'm leaning towards let's push it and ask for forgiveness later :)

**Review by jeff-dude — APPROVED** [review]

**Comment by aalan3** [comment]
LGTM! I'll keep an eye on it, thanks for notifying.

**Pull request merged**
