### PR TITLE
adding bnbchain contracts

### PR DESCRIPTION
**Pull request by davidcheongyl**
Brief comments on the purpose of your changes: adding clean bnbchain contracts

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by jeff-dude** [comment]
there are merge conflicts with main branch. please merge main into your branch and resolve the conflicts in your local editor.

**Comment by davidcheongyl** [comment]
i've already pulled latest changes, but my main shows the date as Dec 5. do you know what is causing this? thanks
image

**Comment by jeff-dude** [comment]
> hey jeff-dude! thanks. i've git fetch and git pull, and merged main into my branch but still facing this issue. is there some issue with the main branch?

no, main is working fine on other PRs. when you pull main to your local editor, it should fail to commit due to merge conflicts, where you can resolve there. i'm not sure what your setup is, but that's the general flow. worst case scenario, if you need to, you can create a new project locally with a fresh fork of this repo, then copy over your changes from the current project setup.

**Comment by jeff-dude** [comment]
> > > hey jeff-dude! thanks. i've git fetch and git pull, and merged main into my branch but still facing this issue. is there some issue with the main branch?
> > 
> > 
> > no, main is working fine on other PRs. when you pull main to your local editor, it should fail to commit due to merge conflicts, where you can resolve there. i'm not sure what your setup is, but that's the general flow. worst case scenario, if you need to, you can create a new project locally with a fresh fork of this repo, then copy over your changes from the current project setup.
> 
> image
> 
> i get 'already up to date' after merging main into my branch

my best guess is you are looking at main on your forked repo. merge main from dune into main in your fork.

**Comment by davidcheongyl** [comment]
> > > > hey jeff-dude! thanks. i've git fetch and git pull, and merged main into my branch but still facing this issue. is there some issue with the main branch?
> > > 
> > > 
> > > no, main is working fine on other PRs. when you pull main to your local editor, it should fail to commit due to merge conflicts, where you can resolve there. i'm not sure what your setup is, but that's the general flow. worst case scenario, if you need to, you can create a new project locally with a fresh fork of this repo, then copy over your changes from the current project setup.
> > 
> > 
> > image
> > i get 'already up to date' after merging main into my branch
> 
> my best guess is you are looking at main on your forked repo. merge main from dune into main in your fork.

ok, i figured i did not click 'sync fork' before doing all my changes. have 'synced fork' and am pushing now

**Comment by davidcheongyl** [comment]
hey jeff_dude, managed to push changes , and now have 2 errors. do you know what the 1st error is about?

for 2nd error im guessing it failed the uniqueness test (duplicates)

image

**Comment by jeff-dude** [comment]
> hey jeff_dude, managed to push changes , and now have 2 errors. do you know what the 1st error is about?
> 
> for 2nd error im guessing it failed the uniqueness test (duplicates)
> 
> image

you can safely ignore first error. it was picked up from another merged PR. it shouldn't show up next run. as for the second, yes, you have duplicates on your unique identifier.

**Comment by davidcheongyl** [comment]
hey Jeff-dude , i've removed the duplicates, but am now facing this latest error - do you know how we can solve this? thanks 
image

**Comment by davidcheongyl** [comment]
hey jeff_dude,i've checked the file and there are no duplicates - but the dbt test is saying there is 1 duplicate - how should i trouble shoot this?

**Comment by jeff-dude** [comment]
> hey jeff_dude,i've checked the file and there are no duplicates - but the dbt test is saying there is 1 duplicate - how should i trouble shoot this?

run `dbt compile` on your up-to-date branch, grab query from target directory, copy/paste into dune app, place in CTE and select from it, group by unique key having count > 1, find the outlier

**Review by jeff-dude — APPROVED** [review]
thank you for the patience. hopefully you learned a few ways to leverage the tools available 👍

**Comment by davidcheongyl** [comment]
hey Jeff! there is no error now, but the dbt-test seemed to be cancelled - how do i clear this issue?

**Comment by jeff-dude** [comment]
> hey Jeff! there is no error now, but the dbt-test seemed to be cancelled - how do i clear this issue?

this was likely canceled by the backend cluster as it was rescaling to a larger size. i just manually retriggered the test.

**Pull request merged**
