### PR TITLE
WIP: seed for test data and other set ups like schema and sources yaml defined.

### PR DESCRIPTION
**Pull request by PaulApivat**
Following Spellbook Workshop at MetricsDAO.

### CODE REVIEW

**Comment by jeff-dude** [comment]
@agaperste please let us know the needs with this PR (if any) -- i've applied do not merge label for now

**Comment by agaperste** [comment]
Thanks for flagging this! I think do not merge label sounds right -- unless @PaulApivat disagrees here!

**Comment by PaulApivat** [comment]
> Thanks for flagging this! I think do not merge label sounds right -- unless @PaulApivat disagrees here!

Probably best to leave this un-merged. Will take another stab for a future use-case, thanks!

**Comment by jeff-dude** [comment]
closing this for now, it'll be here for reference in future if needed

**Pull request closed without merging**
