### PR TITLE
Add Balancer Arbitrum to dex.trades

### PR DESCRIPTION
**Pull request by mtitus6**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ X] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [X ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [X] if adding a new model, I added a test
* [X] the filename is unique and ends with .sql
* [X] each sql file is a select statement and has only one view, table or function defined  
* [X] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [X] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [X] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [X] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [X] where block_time >= date_trunc("day", now() - interval '1 week')
* [X] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [X] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by markusbkoch** [comment]
Thank you @mtitus6 - at Balancer Labs we've been working on that too for a while now, see #1642 and #1974. 
We're conducting a big effort to migrate our abstractions/queries/dashboards from Dune V1 to V2 - we'd love to coordinate with you to avoid duplicating our efforts. If that's something you might be interested in, hit me up on discord (markusbkoch#6770). Cheers!

**Comment by mtitus6** [comment]
> Thank you @mtitus6 - at Balancer Labs we've been working on that too for a while now, see #1642 and #1974. 
> We're conducting a big effort to migrate our abstractions/queries/dashboards from Dune V1 to V2 - we'd love to coordinate with you to avoid duplicating our efforts. If that's something you might be interested in, hit me up on discord (markusbkoch#6770). Cheers!

Yes, for sure.  Will hit you up tomorrow.  I'm mtitus6#4318 on Discord

**Comment by Hosuke** [comment]
Hi @mtitus6 , I patched some minor fixes in last few commits:
- Added missed columns [`blockchain`, `block_date`, `token_pair`]
- Use '' instead of NULL for `maker`

Also you can hit me up/tag me when you think this PR is ready for the final review to merge.

**Comment by mtitus6** [comment]
Thanks @Hosuke .  I'll reach out to the Balancer team today when they are active on Discord and let you know.

**Pull request closed without merging**
