### PR TITLE
Add ens old pre images

### PR DESCRIPTION
**Pull request by soispoke**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by soispoke** [comment]
@0xRobin and @bh2smith, would love to know what you guys think

**Review by bh2smith — COMMENTED** [review]
Looks good to me - although I noticed the data file is a zip file so I can't actually look at it. was that intended? I don't see any place in the code that is responsible for unzipping it...

**Comment by 0xRobin** [comment]
@soispoke I don't think this will work.
Unless you reprocessed it somehow, the old file contains labels and labelhashes.

What we need to do is have a table of names and nodes and union them to ens_node_names.
And then expand the ens_resolver_records to catch the resolver settings of old addresses.
Refresher:
vitalik -> label
namehaseh(vitalik) -> labelhash
vitalik.eth -> name
namehash(vitalik.eth) -> node

When a new address is set on an ENS name we get event:
newAddr(node, addr)

This is the reason we have to build a name <> node database to make the nodes readable names.

**Comment by 0xRobin** [comment]
I tried to look at some old example transaction to see if we can extract node information but this get's really tricky and might break in a lot of edge cases.
I believe we should focus the further efforts in making the `namehash()` function available as a UDF.
This will allow us to remove the sketchy event matching currently in place and to process a list of plain labels.

**Comment by soispoke** [comment]
got it, closing this for now then thanks for the feedback !

**Comment by soispoke** [comment]
wait, would it work to use a hardcoded to reformat `labels` (e.g., vitalik) to names (e.g., `vitalik.eth`) for now ?
Capture d’écran 2022-10-11 à 12 19 10

**Comment by 0xRobin** [comment]
That still leaves us with labelhashes instead of nodes. 
What would work is generating the sql file with a python script.
something like
```python
from namehash import namehash
for label in labels:
    name = label+".eth"
    yield (name , namehash(name), label, namehash(label))
```
It's a bandaid solution but gives us something to work with.
When we've got namehash available as a UDF we can do this logic in a model and just need a seed file with the labels we want to process.

**Comment by 0xRobin** [comment]
nothing is so permanent as a temporary fix though.. :sweat_smile:

**Pull request closed without merging**
