### PR TITLE
Add Aptos Prices

### PR DESCRIPTION
**Pull request by andrewhong5297**
@seventyaptos to help fill in other tokens before we merge

### CODE REVIEW

**Comment by andrewhong5297** [comment]
@alan any idea why aptos isn't getting recognized in price CI?

**Comment by andrewhong5297** [comment]
@seventyaptos to fix decimals and add other token prices

**Comment by jeff-dude** [comment]
> @alan any idea why aptos isn't getting recognized in price CI?

@aalan3 tag correction :)

**Comment by andrewhong5297** [comment]
@aalan3 following up on this one

**Comment by aalan3** [comment]
I think this metadata hasn't been added on coinpaprikas end, but should be fine to merge.

**Review by aalan3 — APPROVED** [review]

**Comment by andrewhong5297** [comment]
Got it - wait dont merge yet, waiting for @seventyaptos to give me the other tokens

**Comment by jeff-dude** [comment]
> Got it - wait dont merge yet, waiting for @seventyaptos to give me the other tokens

we also have a bug in normal CI -- can you look to fix query?

**Comment by jeff-dude** [comment]
closing until we revisit and finalize

**Pull request closed without merging**
