### PR TITLE
Add back missing swaps for orca_whirlpool.trades

### PR DESCRIPTION
**Pull request by chef-seaweed**
## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

Context: 
1. Volume and # of swaps of Orca Whirlpool v2 are being underestimated in `orca_whirlpool.trades`. For example, orca_whirlpool.trades undercounts both volume and the number of txs (47 vs 10k) of GOAT-SOL (4kKFykZkVqE5wbBgj6o8ddnj5TmA6UQgXJLYzAasgKdD) compared to dexscreener.

image
 
image

2. The gap seems to be caused by missing swap data of v2 pools in `orca_whirlpool_base_trades`. Turns out that pools found in `whirlpool_call_initializePoolV2` also show up in 1whirlpool_solana.whirlpool_call_swap` but we failed to include them in `orca_whirlpool_base_trades` (version = 1) where we only count pools from `whirlpool_call_initializePool`
3. In addition, swap data of pools in `whirlpool_call_initializePool` can also be found in `whirlpool_call_swapV2`. However, this should be a minor issue as the # of entries seem lower.

Solution:
1. Include`whirlpool_solana.whirlpool_call_initializePoolV2` in `orca_whirlpool_base_trades.sql`
2. Include`whirlpool_solana.whirlpool_call_initializePool` in `orca_whirlpool_v2_base_trades.sql` 

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by chef-seaweed** [comment]
Hi @jeff-dude I got  Database Error "No free or healthy space available for spill". Any suggestions for solving this? Thanks!

**Comment by jeff-dude** [comment]
> Hi @jeff-dude I got Database Error "No free or healthy space available for spill" when running checks. Any suggestions for solving this? Thanks!

this is a memory error due to data volume. plz hardcode a date filter for non-incremental runs to see CI complete end-to-end on smaller data volume. anywhere you see `if is incremental` check, that is good spot to hardcode recent date filter outside of that block

**Comment by chef-seaweed** [comment]
> > Hi @jeff-dude I got Database Error "No free or healthy space available for spill" when running checks. Any suggestions for solving this? Thanks!
> 
> this is a memory error due to data volume. plz hardcode a date filter for non-incremental runs to see CI complete end-to-end on smaller data volume. anywhere you see `if is incremental` check, that is good spot to hardcode recent date filter outside of that block

Thanks sir. Added and seems like it passed the checks. I suppose the hardcoded date filters will be removed once the code goes live in production?

**Comment by jeff-dude** [comment]
> Thanks sir. Added and seems like it passed the checks. I suppose the hardcoded date filters will be removed once the code goes live in production?

you need to revert the commit on your side prior to merge. feel free to do any time, i can always refer back to previous CI run to check 🤝

**Comment by chef-seaweed** [comment]
> > Thanks sir. Added and seems like it passed the checks. I suppose the hardcoded date filters will be removed once the code goes live in production?
> 
> you need to revert the commit on your side prior to merge. feel free to do any time, i can always refer back to previous CI run to check 🤝

Thanks @jeff-dude. Wanna double check if I understand correctly:
1. Does it mean I must revert my commit before merge? If so, should I do it before your review / approval (just not so sure if the code is good to go for you)
2. Also if I revert my commit, I assume the database error will happen again, but sounds like it won't affect the merge?

**Comment by jeff-dude** [comment]
> 1. Does it mean I must revert my commit before merge? If so, should I do it before your review / approval (just not so sure if the code is good to go for you)

yes, you need to revert on your side. now is fine, no need to wait for final review/approval. history of the successful CI run will be there to check back on.

> 2\. Also if I revert my commit, I assume the database error will happen again, but sounds like it won't affect the merge?

correct, no impact on merge. we just need the code back in final state prior to merge. it's okay for it to fail, or you can manually cancel the gh action to avoid it running at all (assuming you have access to, can't recall tbh)

**Comment by jeff-dude** [comment]
also want to be sure you are aware you can query CI tables built [here](https://github.com/duneanalytics/spellbook/actions/runs/11726297438/job/32664611515?pr=7106#step:12:20)

**Comment by chef-seaweed** [comment]
> also want to be sure you are aware you can query CI tables built [here](https://github.com/duneanalytics/spellbook/actions/runs/11726297438/job/32664611515?pr=7106#step:12:20), helps with data validation prior to merge

Thanks for the heads up 🙏



> > 1. Does it mean I must revert my commit before merge? If so, should I do it before your review / approval (just not so sure if the code is good to go for you)
> 
> yes, you need to revert on your side. now is fine, no need to wait for final review/approval. history of the successful CI run will be there to check back on.
> 
> > 2. Also if I revert my commit, I assume the database error will happen again, but sounds like it won't affect the merge?
> 
> correct, no impact on merge. we just need the code back in final state prior to merge. it's okay for it to fail, or you can manually cancel the gh action to avoid it running at all (assuming you have access to, can't recall tbh)

Okay got it and reverted. Can't figure how to cancel the gh action so gues I have no access. Thanks!

**Review by jeff-dude — APPROVED** [review]
thank you for the patience here, looks good to me!

**Pull request merged**
