### PR TITLE
Add Base to all `evms` tables

### PR DESCRIPTION
**Pull request by hildobby**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by hildobby** [comment]
Screenshot 2023-08-02 at 14 11 03

@jeff-dude Looks like `base.contracts`'s `address`, `code` & `from` values are still varchar, could those be converted to varbinary? CI tests first fail here, but that might also be the case for other base tables

**Comment by jeff-dude** [comment]
> Screenshot 2023-08-02 at 14 11 03
> @jeff-dude Looks like `base.contracts`'s `address`, `code` & `from` values are still varchar, could those be converted to varbinary? CI tests first fail here, but that might also be the case for base's other raw tables

@aalan3 any idea of the datatypes posted here on source object(s) for base?

**Comment by jeff-dude** [comment]
@hildobby can you resolve merge conflicts? @MSilb7 has recently built out the base base sources in another PR that was merged.

in the meantime, i can raise the question again internally on the types.

once merge conflicts resolved, we should be quick to get the evms updated

**Comment by thetroyharris** [comment]
@hildobby the Base Contracts schema has been updated.
image

@jeff-dude any idea about the following? https://github.com/duneanalytics/spellbook/discussions/3940#discussion-5471612
Having those contracts in this spell would be great, but when I went to add them I couldn't. Any idea why?

**Comment by jeff-dude** [comment]
> @hildobby the Base Contracts schema has been updated. image
> 
> @jeff-dude any idea about the following? [#3940 (comment)](https://github.com/duneanalytics/spellbook/discussions/3940#discussion-5471612) Having those contracts in this spell would be great, but when I went to add them I couldn't. Any idea why?

thanks for confirming base sources are fixed!

i followed up in the gh discussion on your other question.

**Comment by hildobby** [comment]
Looks like it's all good now @jeff-dude, lmk if there's anything else I need to do

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
