### PR TITLE
Adding polygon wallets & transactions to daos sector

### PR DESCRIPTION
**Pull request by henrystats**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by henrystats** [comment]
@soispoke updated this and I included the name change as well. I'd wait for this to get reviewed/merged then I'll make an update to the other pr that adds the labels.

**Comment by henrystats** [comment]
hola ser @soispoke, this took a while before I could get the tests to run (it kept timing out). I'm not sure what the problem is here as it says fails to find table or view. 

I didn't make any changes from earlier today when it worked so not sure what went wrong.

**Comment by henrystats** [comment]
finally got it to work, I didn't change anything though. Wondering why it failed earlier. 

This is now ready for review/merging ser 😁

**Comment by henrystats** [comment]
@soispoke this is now ready for review/merging ser, will update the dao addresses labels pr once this is merged.

I'm seeing conflicts here but no way for me to resolve them, is this not conflict to be resolved from my end?

**Comment by soispoke** [comment]
great thanks, reviewing/editing now @henrystats

**Comment by soispoke** [comment]
alright ran it locally, everything lgtm

**Review by soispoke — APPROVED** [review]

**Pull request merged**
