### PR TITLE
standardize trace address for dex aggregators

### PR DESCRIPTION
**Pull request by jeff-dude**
during 1inch development, trace address is used heavily. we need to standarize this field to prepare for 1inch data.

### CODE REVIEW

**Comment by jeff-dude** [comment]
note: i won't be surprised if seed tests fail. the fix for seed file/macro/test will be in 1inch spell here: #2744

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Hope the tests can be passed

**Comment by jeff-dude** [comment]
fyi @henrystats for future dex aggregator models.

**Comment by jeff-dude** [comment]
also fyi @bh2smith though i don't think this will impact you too much. just raising awareness.

**Comment by jeff-dude** [comment]
this is now failing on a known issue, which is excluded model in production and a WIP PR from @henrystats to fix odos avalanche trades on duplicates. even if that passes, as mentioned, i'd expect the seed tests to fail (until 1inch is merged), meaning incremental won't run in this PR.

early next week, i'll likely take the risk to merge this without full CI test passing and monitor closely in prod.

**Review by bh2smith — APPROVED** [review]
cool wit me!

**Pull request merged**
