### PR TITLE
Add PolyDoge on tokens list

### PR DESCRIPTION
**Pull request by RomualdH**
- Add PolyDoge on Polygon

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @RomualdH 

API: https://api.coinpaprika.com/v1/coins/polydoge-polydoge
SCAN: https://polygonscan.com/token/0x8a953cfe442c5e8855cc6c61b1293fa648bae472

**Comment by Hosuke** [comment]
Hi @RomualdH, as there is a prices.tokens standard update ongoing, please run `git merge main`, and put `polydoge` in models/prices/polygon/prices_polygon_tokens.sql. 
Thank you.

**Comment by RomualdH** [comment]
> Hi @RomualdH, as there is a prices.tokens standard update ongoing, please run `git merge main`, and put `polydoge` in models/prices/polygon/prices_polygon_tokens.sql. Thank you.

Done. Thank you in advance!

**Comment by Hosuke** [comment]
Updated to new format based on https://github.com/duneanalytics/spellbook/pull/2824

**Comment by jeff-dude** [comment]
@RomualdH i'm unable to resolve merge conflicts due to access restraints on your forked repo. please resolve, as other rows have been added to this file in main branch. please be careful on commas usage to ensure it's correct

**Review by jeff-dude — APPROVED** [review]
thank you

**Pull request merged**
