### PR TITLE
Create get_chain_explorer macros

### PR DESCRIPTION
**Pull request by hildobby**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by hildobby** [comment]
I really want to use some macros including those new ones, but I'm waiting for them to be DuneSQL compatible which doesn't appear to be the case atm

**Comment by jeff-dude** [comment]
> I really want to use some macros including those new ones, but I'm waiting for them to be DuneSQL compatible which doesn't appear to be the case atm

hmm, good question. @jkylling what's our plan for macros in spellbook which need to run on trino to build UDFs?

**Comment by hildobby** [comment]
@jkylling is it planned for macros to work in DuneSQL like they did in SparkSQL?

**Comment by jeff-dude** [comment]
> @jkylling is it planned for macros to work in DuneSQL like they did in SparkSQL?

i've forwarded this to our engine team. it is in their backlog to look to create these functions so that you can use on the dune app.

would it be worthwhile to merge this now? then you could use macros in spell code, but will need to wait for usage on the app itself until the above is done

**Comment by hildobby** [comment]
Yeah sg, you can merge those now @jeff-dude, ty!

**Review by jeff-dude — APPROVED** [review]

**Comment by jkylling** [comment]
> @jkylling is it planned for macros to work in DuneSQL like they did in SparkSQL?

This will likely be addressed by allowing to use queries with parameters as views. Do you have any preferences on the syntax for this?

**Comment by hildobby** [comment]
> > @jkylling is it planned for macros to work in DuneSQL like they did in SparkSQL?
> 
> This will likely be addressed by allowing to use queries with parameters as views. Do you have any preferences on the syntax for this?

Not sure what you mean with using queries with parameters here, I would love to be able to go on dune.com and have queries like this working (same way macros worked on SparkSQL):

```
SELECT get_chain_explorer(blockchain)
, tx_hash
FROM evms.transactions
LIMIT 1000
```

**Pull request merged**
