### PR TITLE
Perpetuals Migration #8 - Migrate main table

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
@jeff-dude I've set up pr's to migrate the perpetuals trades spell.. I followed a similar process to how we did the dao model migration..

submitted a first pr to migrate the seed...


then a pr for each model which I'll edit once the seed pr is merged to trigger the new seed file...

This final pr would also be edited to trigger the new seed file once all the other pr's have been merged.

**Review by jeff-dude — APPROVED** [review]
lets give this a minute to merge all the others, then we will rebase with main and ensure we're all good

**Comment by henrystats** [comment]
okee! thank you ser!

**Comment by jeff-dude** [comment]
looks like a model (or some) need to ensure casting to correct dunesql type. you can use this PR to add models as needed

**Comment by henrystats** [comment]
oke.. thank you ser, will fix now!

**Comment by henrystats** [comment]
hola ser @jeff-dude, so I fixed the data type and tested on dune.com so I know it works... The issue now is that some of the models have multiple versions soo the edits I made load downstream to a main project_perpetual_trades model which is what perpetual_trades is querying from. 

I tried to put just a line in the codes so it triggers a run of the main models as well but for some reason they're not being trigged in the ci run...

In files changed I can see the edits I made so I'm not sure why they're not being trigged, this is causing perpetual_trades to not run since it's reading those tables from prod.

**Comment by henrystats** [comment]
it finally worked 😅😅

**Comment by henrystats** [comment]
ready to go now ser! @jeff-dude

**Review by jeff-dude — APPROVED** [review]
thank you for taking on this entire sector spell, much appreciated! great work.

**Pull request merged**
