### PR TITLE
update zeroex avalanche_c naming, directory structure

### PR DESCRIPTION
**Pull request by RantumBits**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
Similar to https://github.com/duneanalytics/spellbook/pull/2598

Updates in this PR:

1. add and define `zeroex_avalanche_c_api_fills_sample` seed in `dbt_project.yml`
2. move `zeroex/avalanche_c` related sql files
3. rename zeroex_avalanche_c models

LGTM.✅

**Comment by RantumBits** [comment]
@augustog - i'm not familiar with the error here. do you need me to do anything before merging? 

`12:28:26  Completed with 1 error and 0 warnings:
12:28:26  
12:28:26  Failure in test dex_trades_assert_freshness (tests/dex/dex_trades_assert_freshness.sql)`

**Comment by dot2dotseurat** [comment]
@RantumBits no, don't worry about it. that's not related to your changes. 

Let me see what's going on and I'll let you know if there are needed changes or if I can go ahead and merge.

**Comment by dot2dotseurat** [comment]
@RantumBits sorry for the inconvenience. we are overhauling the CI flow at the moment and you got caught in the crossfire. Merged now!

**Comment by RantumBits** [comment]
no worries - thanks for your help!

**Pull request merged**
