### PR TITLE
Update contracts_contract_creator_address_list.sql

### PR DESCRIPTION
**Pull request by MarcoVugts**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by MarcoVugts** [comment]
I have read the CLA Document and I hereby sign the CLA

recheck

**Comment by jeff-dude** [comment]
> I have read the CLA Document and I hereby sign the CLA
> 
> recheck

you'll need to comment with just the one line, no `recheck` in same comment. the bot is pretty picky on that :)

**Review by jeff-dude — APPROVED** [review]
the change itelf here is good! thank you. once the license is properly signed, we can proceed

**Comment by MarcoVugts** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MarcoVugts** [comment]
recheck

**Pull request merged**
