### PR TITLE
Add Zora NFT Marketplace to nft.trades

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:

Adding Zora v1, v2 & v3, see results here: https://dune.com/queries/1301674

*For Dune Engine V2*
I've checked that:
General checks:
* [X] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [X] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [X] if adding a new model, I added a test
* [X] the filename is unique and ends with .sql
* [X] each sql file is a select statement and has only one view, table or function defined  
* [X] column names are `lowercase_snake_cased`
* [X] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [X] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)
* [X] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [X] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [X] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [X] where block_time >= date_trunc("day", now() - interval '1 week')
* [X] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [X] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by soispoke** [comment]
@hildobby Duplicates were found in the dbt_thomas_zora_ethereum_events.sql model (which makes it impossible to incrementally update the model) https://dune.com/queries/1316780?d=1

**Comment by hildobby** [comment]
> @hildobby Duplicates were found in the dbt_thomas_zora_ethereum_events.sql model (which makes it impossible to incrementally update the model) https://dune.com/queries/1316780?d=1

I couldn't figure out why there were duplicates so I added a distinct tag which should solve the issue

**Comment by soispoke** [comment]
@hildobby unfortunately adding distinct doesn't fix the duplicates issue (see query here: https://dune.com/queries/1316780?d=1&category=abstraction&namespace=bnb)

**Comment by hildobby** [comment]
> @hildobby unfortunately adding distinct doesn't fix the duplicates issue (see query here: https://dune.com/queries/1316780?d=1&category=abstraction&namespace=bnb)

Those are all normal behaviour I believe, those trades have multiple NFTs traded within one transactions. If you group by `unique_trade_id`, you get 0 duplicates: https://dune.com/queries/1317505

If we search for the first tx hash from your query here we can see the 9 separate lines all for a different nft all traded within the same tx, see screenshot here:
Screenshot 2022-09-26 at 16 39 50

**Comment by hildobby** [comment]
Not sure why some tests now fail though, those are from tables unaffected by this PR so I don't understand, do you know what's going on here? 🤔

**Comment by soispoke** [comment]
@hildobby That makes sense, should've grouped by unique_trade_id 👍

And @dot2dotseurat can you take a look at those failing tests ? 🙏

**Comment by dot2dotseurat** [comment]
> Not sure why some tests now fail though, those are from tables unaffected by this PR so I don't understand, do you know what's going on here? 🤔

@hildobby can you merge main in and try again?

**Comment by dot2dotseurat** [comment]
@soispoke @hildobby missing dependencies fixed now, we just needed the most recent pr_utils file. if we see this again, ask the user to merge main.

**Comment by dot2dotseurat** [comment]
> @soispoke @hildobby missing dependencies fixed now, we just needed the most recent pr_utils file. if we see this again, ask the user to merge main.

nvm it's still failing on seeds I think.

**Comment by hildobby** [comment]
> ok, now we got it. @soispoke @hildobby
> 
> sorry the dependency management has been so rough.

sorry I just saw this, i try to always merge main into branches I work on but sorry if I forgot here, ill try to always do it going forward!

**Comment by pandajackson42** [comment]
> > @hildobby Duplicates were found in the dbt_thomas_zora_ethereum_events.sql model (which makes it impossible to incrementally update the model) https://dune.com/queries/1316780?d=1
> 
> I couldn't figure out why there were duplicates so I added a distinct tag which should solve the issue

I think I figured out the problem.

The problem occurs on Zora v2(Auction House), typically when the winner is PartyBid Proxy. Example tx: https://etherscan.io/tx/0x4e47e99155dda53d21ffc147b2b283fe95df9144acefe31561184112cbb5a347

According to PartyBid Proxy's Implementation(https://etherscan.io/address/0x744c2be04d079eddb21c1a9bb13bb5259a368614#code), after `finalize()` call, the NFT token will transfer to the first address, and then to another new address. So one Zora v2 AuctionEnded event corresponds to two ERC721 transfer events for the auctioned token.

Since you used `zora_trades` table to left join `erc721_ethereum.evt_Transfer` table, just with coinditions `evt_block_time`, `evt_tx_hash`, `contract_address`, and `tokenId`. This results in duplicate rows after join.

There are 243 transactions matching the condition mentioned above, therefore resulting in 243 duplicates.

I think another solution other than adding distinct is to add a condition `` erc721.`to`=zt.buyer`` on the join(https://dune.com/queries/1318729), which generates the same result as adding distinct (https://dune.com/queries/1318705).

**Comment by hildobby** [comment]
Thank you very much for the suggestion @pandajackson42 !  You are right so I added that extra filter you suggested :) I also kept the distinct which should help sieve out any duplicate errors that could arise in the future because of unforeseen behaviour

**Comment by soispoke** [comment]
Hey guys @hildobby @pandajackson42 thanks a lot for trying to fix this. However it seems like some rows are still duplicated (see https://dune.com/queries/1319652?d=1&blockchains=ethereum&namespace=ethereum&category=canonical&table=blocks)

After looking at this a bit more, I think it we have to include two fixes:
1. `tx_hash` should be included in `unique_trade_id` 
2. Royalty fees that should be summed (instead of split between the different recipients), see https://dune.com/queries/1319986?d=1

**Comment by soispoke** [comment]
🎉lgtm, thanks @hildobby !

**Review by soispoke — APPROVED** [review]

**Comment by dot2dotseurat** [comment]
No worries. It was my fault not yours. I was missing recreating the seeds
under the right schema for the gh action.

**Pull request merged**
