### PR TITLE
NFTX Events/Trades Added

### PR DESCRIPTION
**Pull request by yogesh-bansal**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:

* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

When you are ready for a review, tag duneanalytics/data-experience. We will re-open your forked pull request as an internal pull request. Then your spells will run in dbt and the logs will be avaiable in Github Actions DBT Slim CI. This job will only run the models and tests changed by your PR compared to the production project.

### CODE REVIEW

**Comment by jeff-dude** [comment]
as we discussed in discord, we'll look into this asap 👍

**Comment by jeff-dude** [comment]
@yogesh-bansal first open question: are you reliant on dex trades and sushiswap data within? is there anyway to read from sushiswap decoded tables directly instead?

at this time, dex trades is in development for v2 engine and sushiswap data will come at a later time (still tbd when).

**Comment by jeff-dude** [comment]
i have some feedback i can provide in a few comments on more process-oriented changes to fit the new ETL pipeline, but the question around dex trades will be a blocker regardless

**Comment by yogesh-bansal** [comment]
On every update of the data we would want to pull the latest price of our tokens from their sushi pool and if no new trades have been made it goes to check the last trade, so if we apply the incremental run filter to it we would miss the price data for tokens which haven't been traded in the current incremental time frame.

**Comment by jeff-dude** [comment]
> On every update of the data we would want to pull the latest price of our tokens from their sushi pool and if no new trades have been made it goes to check the last trade, so if we apply the incremental run filter to it we would miss the price data for tokens which haven't been traded in the current incremental time frame.

i'm not sure i'm fully following, but i think the question can be asked in another way:
dex trades doesn't exist on the new v2 engine yet. would you rather wait until it's available and sushiswap data is loaded or rewrite your query here to read from the sushiswap source tables which populate dex trades?

here is script to load dex trades for sushi: https://github.com/duneanalytics/abstractions/blob/master/ethereum/dex/trades/insert_sushi.sql

you could possibly take the inner subquery which reads from 'sushi' schema decoded tables and use that instead of dex trades.

**Comment by yogesh-bansal** [comment]
Yeah, we can change the part to read from the sushi decoded contracts, I will have the commit pushed for same soon.

**Comment by jeff-dude** [comment]
on another separate note, have you seen the docs for contributing a new spell?
https://docs.dune.com/dune-engine-v2-beta/abstractions-in-dunev2/how-to-contribute-a-spell

these steps will help you identify a few gaps in the PR here which are needed for the ETL pipeline to run. items such as adding sources to a source file, writing a quick unit test, using JINJA syntax to reference sources/other dbt models to avoid hardcoding tables in the models, etc.

as you look through those, i'm happy to help where i can.

here's an example PR which loaded nft trades in engine v2:
https://github.com/duneanalytics/abstractions/pull/1241

this gives a visual idea to the files needed to edit and/or add new, directory paths to mimic, etc.

**Comment by yogesh-bansal** [comment]
> on another separate note, have you seen the docs for contributing a new spell? https://docs.dune.com/dune-engine-v2-beta/abstractions-in-dunev2/how-to-contribute-a-spell
> 
> these steps will help you identify a few gaps in the PR here which are needed for the ETL pipeline to run. items such as adding sources to a source file, writing a quick unit test, using JINJA syntax to reference sources/other dbt models to avoid hardcoding tables in the models, etc.
> 
> as you look through those, i'm happy to help where i can.
> 
> here's an example PR which loaded nft trades in engine v2: #1241
> 
> this gives a visual idea to the files needed to edit and/or add new, directory paths to mimic, etc.

Thanks, Working through the steps to have a more suitable pull request.

**Comment by yogesh-bansal** [comment]
So I am facing a issue where my decoded contracts are not appearing in V2 as they appear in V1.
In V1 this contract `nftx_v2.NFTXVaultFactoryUpgradeable` is decoded using 2 ABIs so I get two function versions. which are `nftx_v2."NFTXVaultFactoryUpgradeable_v1_evt_NewVault` and `nftx_v2."NFTXVaultFactoryUpgradeable_v1_evt_NewVault0`

But in V2 there is only 1 which is `nftx_v2_ethereum.NFTXVaultFactoryUpgradeable_v1_evt_NewVault` so the decoding isn't matching, So can I keep them as v1 here?

**Comment by jeff-dude** [comment]
> So I am facing a issue where my decoded contracts are not appearing in V2 as they appear in V1. In V1 this contract `nftx_v2.NFTXVaultFactoryUpgradeable` is decoded using 2 ABIs so I get two function versions. which are `nftx_v2."NFTXVaultFactoryUpgradeable_v1_evt_NewVault` and `nftx_v2."NFTXVaultFactoryUpgradeable_v1_evt_NewVault0`
> 
> But in V2 there is only 1 which is `nftx_v2_ethereum.NFTXVaultFactoryUpgradeable_v1_evt_NewVault` so the decoding isn't matching, So can I keep them as v1 here?

unfortunately, you can't reference v1 engine decoded tables from the new database. this seems like we need to explore more decoding to be done on NFTX specifically. i'm going to tag our good friend @antonio-mendes to see if he can help with the discrepancy between the two databases and why the new database doesn't have both decoded tables. two separate ABI's make sense as to why there would be two output.

**Comment by antonio-mendes** [comment]
I think I know what the problem is and will try to fix it on V2. Basically, some contracts that had multiple ABIs on V1 were migrated to V2 with only 1 of the ABIs. I'm working on this 👍

**Comment by jeff-dude** [comment]
> I think I know what the problem is and will try to fix it on V2. Basically, some contracts that had multiple ABIs on V1 were migrated to V2 with only 1 of the ABIs. I'm working on this 👍

thank you!

**Comment by jeff-dude** [comment]
do we have a resolution on the decoded tables @antonio-mendes?

is this what you're waiting for on next steps @yogesh-bansal?

**Comment by yogesh-bansal** [comment]
> do we have a resolution on the decoded tables @antonio-mendes?
> 
> is this what you're waiting for on next steps @yogesh-bansal?

The issue with the decoded tables is fixed, Thanks to @antonio-mendes 
I am working on rewriting the queries to match the whole spellbook structure, Will push the PR again soon with updated code.

**Comment by jeff-dude** [comment]
@yogesh-bansal i wanted to give you an FYI that we've reorganized our public repo, therefore there will be minor tweaks in this PR and future. 
1. changed repo name from 'abstractions' to 'spellbook'
2. moved all v1 engine abstractions into 'deprecated-dune-v1-abstractions'
3. removed 'spellbook' directory at root and moved all objects within (i.e. models directory you use here) to the root level

it might be easiest to start fresh with a fork of the repo, refresh and/or recreate branch for new spell building here, close this PR and open new. that's the safe route, but you can also try to solve merge conflicts locally and have this PR refresh.

let me know what you want to do, apologies for the changes mid-PR but there was never the "right" time to do it 🙂

**Comment by yogesh-bansal** [comment]
Will open a new PR adhering to the new repo structure.

**Comment by soispoke** [comment]
Hi @yogesh-bansal, do you need help submitting the PR on the new repo ?

**Pull request closed without merging**
