### PR TITLE
Use different trino cluster

### PR DESCRIPTION
**Pull request by belen-pruvost**
Towards NGN-1225

### CODE REVIEW

**Comment by belen-pruvost** [comment]
I changed the `scripts/missing_legacy_model.sh` script so that the triggering model (`trigger_scale`) won't need a legacy equivalent. This change is causing the pytest-automation check to run. The check is failing but from looking at the errors it does not seem related to the changed I've done, @aalan3 / @couralex6 could you help me understand if this is indeed unrelated?

**Comment by aalan3** [comment]
try excluding it from the [dbt ls](https://docs.getdbt.com/reference/commands/list) command instead. otherwise if you just want a quick fix add a legacy model as well. I am having a similar issue and we might actually drop this soon if possible.

**Comment by belen-pruvost** [comment]
We've tested these retries and the routing to the new spellbook-ci cluster and it is working nicely.

@aalan3 / @couralex6 / @jeff-dude - can this be merged so that new PR runs happen on an isolated environment?

**Review by jeff-dude — APPROVED** [review]
v nice! this should be a game changer, thank you 🙏

**Review by aalan3 — APPROVED** [review]
nice thank you!

**Pull request merged**
