### PR TITLE
Add carbon to dex.trades

### PR DESCRIPTION
**Pull request by tiagofilipenunes**
Brief comments on the purpose of your changes:

- Add Carbon, an Ethereum DEX to dex.trades.
Carbon is an on-chain trading protocol allowing users to perform automated trading strategies using custom limit orders and range orders with no dependence on oracles or external tooling. Users can submit individual orders or combine their orders together to create “recurring strategies” that buy a token low and sell it high in specific price ranges.

Documentation on Carbon can be found at https://docs.carbondefi.xyz.

_For Dune Engine V2_
I've checked that:
General checks:

- [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
- [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables
- [x] if adding a new model, I added a test
- [x] the filename is unique and ends with .sql
- [x] each sql file is a select statement and has only one view, table or function defined
- [x] column names are `lowercase_snake_cased`
- [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
- [x] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
- [x] if adding a new materialized table, I edited the optimize table macro

Join logic:

- [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:

- [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  - [x] where block_time >= date_trunc("day", now() - interval '1 week')
- [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
- [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by tiagofilipenunes** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tiagofilipenunes** [comment]
@jeff-dude This is ready for review please, whenever you can. I have not added carbon to dex.trades yet as I was getting this error:

```
check tags
  Run test=$(dbt --quiet --no-print ls $PROFILE --resource-type model --select state:modified --exclude tag:legacy tag:dunesql --output path --state .)

Found models with no dunesql or legacy tag:
models/dex/dex_trades.sql
Error: Process completed with exit code 1.
```

**Comment by jeff-dude** [comment]
> @jeff-dude This is ready for review please, whenever you can. I have not added carbon to dex.trades yet as I was getting this error:
> 
> ```
> check tags
>   Run test=$(dbt --quiet --no-print ls $PROFILE --resource-type model --select state:modified --exclude tag:legacy tag:dunesql --output path --state .)
> 
> Found models with no dunesql or legacy tag:
> models/dex/dex_trades.sql
> Error: Process completed with exit code 1.
> ```

yes, `dex.trades` isn't ready on dunesql yet unfortunately. we can add when ready. this hsould be fine as a standalone until then

**Review by jeff-dude — APPROVED** [review]
great work here!

**Pull request merged**
