### PR TITLE
Update safe_bnb_safes.sql

### PR DESCRIPTION
**Pull request by safeintern**
Added filter, tx_success

# Thank you for contributing to Spellbook!

Thank you for taking the time to submit code in Spellbook. A few things to consider:

- If you are a first-time contributor, please sign the CLA by copy & pasting **_exactly_** what the bot mentions in PR comment
- Refer to [docs](#spellbook-contribution-docs) section below to answer questions
- Dune team will review submitted PRs as soon as possible

## Spellbook sub-projects

To prepare for Spellbook to scale in size, Dune team has started to pilot sub-projects:

- For a quick overview, see [the GH discussion on the topic](https://github.com/duneanalytics/spellbook/discussions/5238)
  - Please ask questions and continue the conversation there
- The first spell lineage to move: `tokens.erc20` and all upstream spells which help build it
  - **_Note_**: Please navigate to [tokens](/tokens) root directory to find tokens objects

## Spellbook contribution docs

The [docs](docs) directory has been implemented to answer as many questions as possible. Please take the time to reference each `.md` file within this directory to understand how to efficiently contribute & why the repo is designed as it is 🪄

Example questions to be answered:

- What does each property in the [model config block](/docs/models/model_config_block.md) mean?
- What is the [CI test](/docs/ci_test/ci_test_overview.md) attached to PRs and how can I best utilize it?
- What are the Spellbook [best practices](/docs/general/best_practices.md)?

Please navigate through the [docs](/docs) directory to find as much info as you can.

**Note**: happy to take PRs to improve the docs, let us know 🤝

### CODE REVIEW

**Comment by safeintern** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by safeintern** [comment]
hi @jeff-dude, I have edited the BNB Safe model to remove duplicates. Can you please review and merge them for changes? 

There is another [PR](https://github.com/duneanalytics/spellbook/pull/5384) that is dependent on this spell so if we can get this merged by Monday, that would be awesome!

Thank you!

**Review by Hosuke — APPROVED** [review]
LGTM.✅

**Comment by jeff-dude** [comment]
@safeintern you will need to remove the `prod_exclude` tag in order for this spell to run in CI or prod
https://github.com/duneanalytics/spellbook/pull/5409/files#diff-cb8020ab7b6b284896409b2d25ece4bd8274f7516db8bf1d342ab6183623174dR5

you'll notice at this time, CI didn't actually run anything:
https://github.com/duneanalytics/spellbook/actions/runs/8016992085/job/21900002913?pr=5409#step:11:15

**Comment by safeintern** [comment]
@jeff-dude done! 

Can we get this merged and afterwards, the [PR](https://github.com/duneanalytics/spellbook/pull/5384) dependent on this spell too?

Thank you and have a good weekend!

**Pull request merged**
