### PR TITLE
Fix volume_usd for synthetix on optimism

### PR DESCRIPTION
**Pull request by RplusT**
Brief comments on the purpose of your changes:
Fixes the USD volume of Synthetix/Kwenta perpetual swaps on Optimism.

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
* [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by soispoke — APPROVED** [review]
lgtm

**Comment by RplusT** [comment]
@soispoke thanks for approving! Would this recompute all historical values since the table was already built or would that require a different fix?

**Comment by soispoke** [comment]
@RplusT yes, this is already done it should be the right data now lmk if everything seems good for you

**Comment by RplusT** [comment]
@soispoke ah yeah this worked as intended. I think there's just a bigger bug that I need to address. Thanks!

**Pull request merged**
