### PR TITLE
update tigris new contracts - ready for review - easy 

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
I've been on a very long break for a while now :(, was dealing with some personal issues. Finally back now and feels great to open a pr once again..

Going to attend to all my previous pr's now....

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @henrystats

**Comment by henrystats** [comment]
hola @Hosuke, @jeff-dude this pr is now ready for review... I only added the new options and perpetual contracts tables and didn't make any changes to the underlying code. Tagging in the hope that this can get reviewed/merged soon as the tigris dashboard on dune and also defillama rely on this spell.

**Review by jeff-dude — APPROVED** [review]
nice to have ya back! this looks good to me.

**Pull request merged**
