### PR TITLE
Safes in Celo: transactions, transfers, singletons and Safes

### PR DESCRIPTION
**Pull request by danielpartida**
# SPELLBOOK FREEZE

From June 22 to June 29, we will be freezing some Spellbook contributions for the migration to DuneSQL. We will not accept contributions to the lineage of the following models:

* dex.trades
* nft.trades
* labels
* token.erc20
* tokens.nft

Run the following command to see the list of affected files:

```
dbt ls --resource-type model --output path --select +dex_trades +labels +nft_trades +tokens_nft +tokens_erc20
```

Don't hesitate to reach out on Discord if you have any questions.

Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by jeff-dude** [comment]
[this jinja source](https://github.com/duneanalytics/spellbook/pull/3589/files#diff-d85b42f596c3a03f7c94d454dc5d12fa0fb74db2804520605ea66e32729861ccR41) will need added to a dbt source file for base sources. [here](https://github.com/duneanalytics/spellbook/tree/main/models/base_sources) is that directory. it'll need a new file for celo, but can copy existing ones.

general project-wise design:
- base tables / views go into these base source files to keep clean
- decoded tables go into their respective project source files, which i see you've already done

**Comment by danielpartida** [comment]
Just created celo_base_sources.yml

**Comment by danielpartida** [comment]
@jeff-dude I think that it is currently failing because the contract GnosisSafeProxyFactory_v1_3_0 has not been approved yet. Correct?

**Comment by jeff-dude** [comment]
> @jeff-dude I think that it is currently failing because the contract GnosisSafeProxyFactory_v1_3_0 has not been approved yet. Correct?

yes, if this contract is still waiting to be approved in the decoding pipeline, it'll fail to find and read. you'll need to wait for confirmation that it's approved and built

**Comment by jeff-dude** [comment]
@danielpartida since you're waiting on decoded tables & also we're in a freeze period for spellbook, would you want to wait until post-freeze to build these on the dunesql engine? it'll require some syntax changes most likely, but could help you avoid rework to migrate these spells?

ideally you'll be able to start that end of next week and have the PR tests run on dunesql for you

**Comment by danielpartida** [comment]
Hi @jeff-dude. Ideally not since we want to have some insights about Safes deployed on Celo by the beginning of next week. Happy to join the effort once the migration is done though

**Comment by danielpartida** [comment]
gm @jeff-dude let me know if additional input is required from my end to merge this PR

**Review by jeff-dude — CHANGES_REQUESTED** [review]

**Review by jeff-dude — APPROVED** [review]
thank you!

**Comment by danielpartida** [comment]
Thank you for the input @jeff-dude, do you need other input from my end for merging the PR?

**Comment by jeff-dude** [comment]
> Thank you for the input @jeff-dude, do you need other input from my end for merging the PR?

nope -- all good!

**Pull request merged**
