### PR TITLE
Add Iziswap to dex.trades

### PR DESCRIPTION
**Pull request by UmerHA**
Brief comments on the purpose of your changes: Added iziswap to dex.trades (dework: https://app.dework.xyz/bnb-chain/dextrades/view/board-lal5q2o4?taskId=559c48df-1973-4fbc-9793-37c5459949d7)

(Also added wombat exchange to dbt_project.yaml, which I forgot in PR https://github.com/duneanalytics/spellbook/pull/2013)

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by UmerHA** [comment]
@Hosuke this is ready-to-review from my pov :)

**Comment by Hosuke** [comment]
This PR contains 2 models for `dex.trades`:

1. wombat_bnb_trades
2. izumi_bnb_trades

**Comment by Hosuke** [comment]
For `wombat_bnb_trades`, I have reviewed this PR and here is the summary:

- Metadata & naming conventions look good ✅
- Config blocks match uniqueness tests in schema files ✅
- Tests and seeds added for the new models ✅ (with customized test + dex_trades_token_bought_address test)
- Incremental filters added when joining large tables(prices.usd) ✅
- Contract addresses are lowercased ✅ 
- The model is implemented using the minimum data source(`wombat_bnb.Pool_evt_Swap`), without joining transaction table and logs table ✅

[Sample query results here](https://dune.com/queries/1654228).

**Review by Hosuke — APPROVED** [review]
For `izumi_bnb_iziswap_trades`, I have reviewed this PR and here is the summary:

- Metadata & naming conventions look good ✅ 
 (one question: which is better, `izumi_bnb_iziswap_trades` or `izumi_bnb_trades`)
- Config blocks match uniqueness tests in schema files ✅
- Tests and seeds added for the new models ✅ (with customized test + dex_trades_token_bought_address test)
- Incremental filters added when joining large tables ✅
- Contract addresses are lowercased ✅
- Inner join to large tables(bnb.transactions) as possible ✅

[Sample query results here](https://dune.com/queries/1654319?d=1).

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
pushed a change for universal ```iziswap``` naming standard -- i think it's easier to track.

also added inner join to bnb transactions on wombat, for consistency across models

**Pull request merged**
