### PR TITLE
Adds balance facilities for bnb bep20 tokens

### PR DESCRIPTION
**Pull request by crypto586**
Brief comments on the purpose of your changes:

The idea is to have balances (in/out flows of tokens to/from contract/addresses) for the BNB chain just as we have balances for ethereum. The implementation is based on the already present transfers models.

I've looked at the code for the ethereum part and mostly duplicated for BSC.
LGTM but this is my first time on contributing on v2 spellbook, so minor things might have slipped away.

If it's ok, the idea, the implementation and the general goal, I'll add also erc721 and erc1155 models as well as tests to the PR, in order to have both BSC and Ethereum chains, aligned.

Thanks for your time.

**For Dune Engine V2**

I've checked that:

### General checks:
* [X] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [X] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [X] the filename is unique and ends with .sql
* [X] each sql file is a select statement and has only one view, table or function defined  
* [X] column names are `lowercase_snake_cased`
* [X] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [X] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [X] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by Hosuke** [comment]
Hi @crypto586, thank you for your contribution(and finish my semi-finished code in `transfers_bnb_bep20_rolling_hour` and `transfers_bnb_bep20_rolling_day`). In my last commits I modify the models into incremental views.

**Review by Hosuke — APPROVED** [review]
Everything in this PR is similar to `balances_ethereum_erc20`.
However it takes over 60 minutes for `dbt-test` to finish.

**Comment by Hosuke** [comment]
Hi @crypto586, there might be too many rows produced for the hourly balances table. Can we try only have daily balances for bep20 tokens in this PR first? And see if the daily model can be built and test in 60 minutes?

**Comment by crypto586** [comment]
> Hi @crypto586, there might be too many rows produced for the hourly balances table. Can we try only have daily balances for bep20 tokens in this PR first? And see if the daily model can be built and test in 60 minutes?
> 
> Also we may need to filter out those token pairs only had one transaction. Or we may use inner join to prices_bnb/token_bnb tables for now to cut down the tokens list for the balances.

Hi. You mean dropping all the hourly stuff altoghether? I can do that.

**Comment by Hosuke** [comment]
> > Hi @crypto586, there might be too many rows produced for the hourly balances table. Can we try only have daily balances for bep20 tokens in this PR first? And see if the daily model can be built and test in 60 minutes?
> > Also we may need to filter out those token pairs only had one transaction. Or we may use inner join to prices_bnb/token_bnb tables for now to cut down the tokens list for the balances.
> 
> Hi. You mean dropping all the hourly stuff altoghether? I can do that.

Yes, exactly.

**Comment by crypto586** [comment]
> > > Hi @crypto586, there might be too many rows produced for the hourly balances table. Can we try only have daily balances for bep20 tokens in this PR first? And see if the daily model can be built and test in 60 minutes?
> > > Also we may need to filter out those token pairs only had one transaction. Or we may use inner join to prices_bnb/token_bnb tables for now to cut down the tokens list for the balances.
> > 
> > 
> > Hi. You mean dropping all the hourly stuff altoghether? I can do that.
> 
> Yes, exactly.

Done..

**Comment by crypto586** [comment]
> Hi @crypto586 I have modified the model using INNER JOIN to `prices.usd`, to limit the number of tokens for bep20 balances, for the first version.

I see. But I also see the model still takes over 60 minutes to build.
Is there something obvious we are missing?
Are there so much rows comparing to eth?

**Comment by Hosuke** [comment]
> > Hi @crypto586 I have modified the model using INNER JOIN to `prices.usd`, to limit the number of tokens for bep20 balances, for the first version.
> 
> I see. But I also see the model still takes over 60 minutes to build. Is there something obvious we are missing? Are there so much rows comparing to eth?

There may be 2B rows, I will retry to build the model in 180 minutes. If this fails, we may need to further optimize the model.

**Comment by Hosuke** [comment]
Sorry @crypto586, I am currently unable to come up with a solution to calculate the bep20 balance efficiently. This model may be too heavy. I was wondering if we could break the `logs`/`traces` to smaller parts(like for 1 year or 1 month) and first calculate the aggregate amount changes in the interval, and then sum.

**Comment by crypto586** [comment]
> Sorry @crypto586, I am currently unable to come up with a solution to calculate the bep20 balance efficiently. This model may be too heavy. I was wondering if we could break the `logs`/`traces` to smaller parts(like for 1 year or 1 month) and first calculate the aggregate amount changes in the interval, and then sum.

No prob. I will personally live with the transfers spells for the time being. I actually don't know if the logs/traces can be useful.

**Comment by henrystats** [comment]
@Hosuke could it be that the reason it's timing out is because of the way the bep20-transfers table is written? 

it's different from how the ethereum erc20 transfers table is written. 

The rolling hour/day tables aren't written incrementally, only the agg day/hour. 

In bnb, the transfers table are written incrementally. I'm working on a balances spell for FTM (erc20, NFTs & FTM) and the gh action runs in ~30mins. 

https://github.com/duneanalytics/spellbook/pull/2389

And I added the transfers model as well.

**Comment by Hosuke** [comment]
> @Hosuke could it be that the reason it's timing out is because of the way the bep20-transfers table is written?
> 
> it's different from how the ethereum erc20 transfers table is written.
> 
> The rolling hour/day tables aren't written incrementally, only the agg day/hour.
> 
> In bnb, the transfers table are written incrementally. I'm working on a balances spell for FTM (erc20, NFTs & FTM) and the gh action runs in ~30mins.
> 
> #2389
> 
> And I added the transfers model as well.

There are too many transfers in bep20 transfers table, the rolling_day is calculated(which is heavy) when it is used as a ref/source maybe. I will try your approach.

**Comment by jeff-dude** [comment]
closing due to inactivity

**Pull request closed without merging**
