### PR TITLE
EVM blockchain metrics

### PR DESCRIPTION
**Pull request by 0xRobin**
EVM blockchain metrics

### CODE REVIEW

**Comment by 0xRobin** [comment]
On issue I see here is that you can't properly aggregate the address and contract metrics (if you want to show daily or weekly stats in the dashboard, there's no way to correctly calculate these from the hourly stats as they are dependent on the time window)

**Comment by hannahblue** [comment]
> On issue I see here is that you can't properly aggregate the address and contract metrics (if you want to show daily or weekly stats in the dashboard, there's no way to correctly calculate these from the hourly stats as they are dependent on the time window) Hourly might not be the best timeframe for this dataset.

@0xRobin  That's a good point. And even if the timeframe was daily, it would push the problem to broader timeframes like weekly or monthly. The new_addresses and new_contracts are ok at least, because they only ever get counted once. But we should remove active_addresses, returning addresses, and active_contracts.

**Comment by jeff-dude** [comment]
expected schema, per requirements doc:
- `blockchain`: name of blockchain
- `chain_id`: unique id associated to blockchain
- `block_hour`: truncate block time to hour
- `tx_count`: count distinct tx_hash values
- `tx_success_count`: count of successful txs
- `tx_success_rate`: count of successful txs / total txs
- `avg_block_time_seconds`: current block time - previous block time, recorded in seconds granularity
- `tx_per_second`: count distinct tx's / block_time
- `new_addresses`: distinct "from" where not in previous block(s)
- `new_contracts`: distinct "to" where not in previous block(s), in contracts list

columns removed, per feedback:
- `active_addresses`: removed per hannah comment above
- `returning_addresses`: removed per hannah comment above
- `active_contracts`: removed per hannah comment above

**Comment by hannahblue** [comment]
This looks good. Thank you @jeff-dude and @0xRobin

**Pull request merged**
