### PR TITLE
[CoW Protocol] Add OpenOcean Aggregator solver and rename PropellerHeads to PropellerSwap

### PR DESCRIPTION
**Pull request by harisang**
This PR adds the OpenOcean Aggregator solver that just joined the competition and renames the PropellerHeads solver to PropellerSwap, as requested by the corresponding solver team.

### CODE REVIEW

**Comment by harisang** [comment]
cc @bh2smith

**Review by bh2smith — CHANGES_REQUESTED** [review]
I only see a rename of propeller head to swap here. Didn't you say there was another solver being added?

**Comment by harisang** [comment]
> I only see a rename of propeller head to swap here. Didn't you say there was another solver being added?

There is also a solver being added. Lines 101-102 and 98-99 in the two modified files.

**Comment by bh2smith** [comment]
Srry -- not sure how I missed it.. Must be going colour blind.

**Review by bh2smith — APPROVED** [review]

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
