### PR TITLE
[branch repeat] [swell] adding daily balances table of core swell assets

### PR DESCRIPTION
**Pull request by darvinrio**
## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:

[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by darvinrio** [comment]
opened this cause https://github.com/duneanalytics/spellbook/pull/7194 closed

**Comment by darvinrio** [comment]
tried distinct token_address on the resultant table above. 
query: 
```sql
select --count(*)
    distinct token_address
from test_schema.git_dunesql_18c9336_swell_balances_ethereum_core_assets
limit 100
```
image

it is missing balances of 
- (0x358d94b5b2F147D741088803d932Acb566acB7B6,  'rSWELL', 'Swell LRT')
- (0x9Ed15383940CC380fAEF0a75edacE507cC775f22, 'earnETH', 'Swell LRT')
- (0x66E47E6957B85Cf62564610B76dD206BB04d831a, 'earnBTC', 'Swell LRT')

I checked that these balances do exist in the source table `tokens_ethereum.balances_daily_agg_base` 
query: 
```sql
select * from tokens_ethereum.balances_daily_agg_base
where token_address = 0x9Ed15383940CC380fAEF0a75edacE507cC775f22
and address = 0xbdD5d655ad781FB9929BFe515EB4A50090444C21
```
image

tagging @0xRobin since we worked on the `balances_incremental_subset_daily` macro.

**Comment by darvinrio** [comment]
found the issue. 
the query left joins with `tokens.erc20` 
and earnETH, earnBTC and rSWELL don't have entries in there, possibly because they are ERC4626. 
this means, the balance calculation always results in null values, which are filtered out. 
balance calc:
```sql
        CASE
            WHEN b.token_standard = 'erc20' THEN b.balance_raw / power(10, erc20_tokens.decimals)
            WHEN b.token_standard = 'native' THEN b.balance_raw / power(10, 18)
            ELSE b.balance_raw
        END as balance,
```

query: 
```sql
with
tokens as (
  select * from (values
    (0xf951E335afb289353dc249e82926178EaC7DEd78,   'swETH', 'Swell LRT'),
    (0xFAe103DC9cf190eD75350761e95403b7b8aFa6c0,  'rswETH', 'Swell LRT'),
    (0x0a6E7Ba5042B38349e437ec6Db6214AEC7B35676,   'SWELL', 'Swell LRT'),
    (0x358d94b5b2F147D741088803d932Acb566acB7B6,  'rSWELL', 'Swell LRT'),
    (0x9Ed15383940CC380fAEF0a75edacE507cC775f22, 'earnETH', 'Swell LRT'),
    (0x66E47E6957B85Cf62564610B76dD206BB04d831a, 'earnBTC', 'Swell LRT'),
    (0x8DB2350D78aBc13f5673A411D4700BCF87864dDE,   'swBTC', 'Swell LRT')
  ) as t(
    token_address,
    symbol,
    name
  )
)

select * from tokens.erc20
where contract_address in (select token_address from tokens)
limit 10
``` 

image

I'm not entirely sure how to add the assets to `tokens.erc20`

**Comment by darvinrio** [comment]
okay. 
i have added the missing assets to `tokens_ethereum_erc20`
but I think i wouldn't be able to test it until this is merged. 
i guess we can revisit this if the assets are missing post merge.

**Comment by 0xRobin** [comment]
@darvinrio Thank you for describing the issue so clearly. 
While adding the tokens to erc20 will solve this, it would be good to also resolve the bug (I can do so in a different PR).

What do you think of doing something like this?
```
        CASE
            WHEN b.token_standard = 'erc20' THEN b.balance_raw / power(10, coalesce(erc20_tokens.decimals,18))
            WHEN b.token_standard = 'native' THEN b.balance_raw / power(10, 18)
            ELSE b.balance_raw
        END as balance,
 ```
 Which falls back to 18 decimals if the tokens aren't available.

**Comment by darvinrio** [comment]
@0xRobin 
i was thinking of doing the same. its a generalized solution. 
but i was thinking, this isn't an appropriate solution in my case since, for earnBTC, the decimal adjustment was 1e8. 

i do feel, adding to `erc20.tokens` is the ideal solution. 
having a warning in the macro about this dependancy is good. and proper seed tests catch these. 
i ll add the warning once im in front of my pc.

i was also thinking of adding a `balances_raw` column. then we can replace the `balance > 0` check with `balances_raw > 0`.
but i saw multiple models depending on the same macro, so i didn't feel it would be safe to make that change.

**Comment by 0xRobin** [comment]
@darvinrio can you also please rebase this branch onto main? (make sure to pull in latest from duneanalytics/spellbook)
That should remove all the unnecessary commits in your branch.

**Comment by darvinrio** [comment]
@0xRobin this good ?

**Review by 0xRobin — APPROVED** [review]
@darvinrio looks good. 
1 request before we're able to merge:
Can you open a new PR with just the token additions to erc20?
We need to merge this separately and propagate this change before we can merge the balance model.

**Comment by darvinrio** [comment]
@0xRobin 
https://github.com/duneanalytics/spellbook/pull/7288 - PR to add erc20s.

**Comment by darvinrio** [comment]
lfg 🚀 
 @0xRobin 
 
 
image

query: 
```sql
select distinct token_symbol from test_schema.git_dunesql_8d9135d_swell_balances_ethereum_core_assets
```

**Comment by jeff-dude** [comment]
will be interesting to see if this merge will kickoff all spells which call the macro, since comment updated here?
@0xRobin i'll let you merge early next week, as i'm merging a few other daily project ones and want to avoid that scenario.

**Comment by darvinrio** [comment]
@jeff-dude if its going to kickoff all dependant spells, 
@0xRobin  it might be better to add a `balances_raw` column and update all downstream tables schemas. 

that would remove the dependency in the comment.

**Pull request merged**
