### PR TITLE
Always attempt to parse contributors as JSON

### PR DESCRIPTION
**Pull request by jkylling**
~~I have not tested this.~~

### CODE REVIEW

**Comment by belen-pruvost** [comment]
Test: https://github.com/duneanalytics/spellbook/pull/4443

**Comment by belen-pruvost** [comment]
I don't see this check erroring out on the CI on my test (side note: it might not be the best test, I was trying to escape models)

**Comment by jeff-dude** [comment]
> I don't see this check erroring out on the CI on my test (side note: it might not be the best test, I was trying to escape models)

we don't run the `expose_spell` macro in CI, which is why we never see these errors pop up until prod. you can see through line 2:
`if target == prod`

**Comment by jkylling** [comment]
@jeff-dude @aalan3 the expose macro is updated to throw an exception whenever it is unable to parse the contributors string as JSON. This should serve as a basic safeguard against malformed contributors lists.

**Review by jeff-dude — APPROVED** [review]
got it -- thanks for the assistance here!

i will look to merge this at a time where it's the only merge, as it'll require some special handling in prod & i'd like to monitor to ensure post-hook queries don't fail with the changes (since CI doesn't run this)

**Pull request merged**
