### PR TITLE
Apply trusted tokens to dex_aggregator.trades

### PR DESCRIPTION
**Pull request by Hosuke**
### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [x] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by Hosuke** [comment]
Bebop is using `token_bought_amount`(instead of `token_bought_amount_raw`) with `decimal to calculate the amount_usd originally:
https://github.com/duneanalytics/spellbook/blob/main/models/bebop/optimism/bebop_jam_optimism_trades.sql#L154

**Comment by Hosuke** [comment]
Since aggregators may have different ways of calculating the `amount_usd`, the batch processing may not be suitable in this case.

**Comment by jeff-dude** [comment]
do you think we should wait to apply this until we refactor dex aggregator lineage? then maybe it'll be cleaner to match dex?

**Comment by Hosuke** [comment]
> do you think we should wait to apply this until we refactor dex aggregator lineage? then maybe it'll be cleaner to match dex?

Based on current aggregators' implementation, we may apply trusted tokens at project-level.

Maybe we could wait first.

**Comment by jeff-dude** [comment]
> > do you think we should wait to apply this until we refactor dex aggregator lineage? then maybe it'll be cleaner to match dex?
> 
> Based on current aggregators' implementation, we may apply trusted tokens at project-level.
> 
> Maybe we could wait first.

i think it's better to wait in that case. let's discuss tomorrow, if needed

**Comment by jeff-dude** [comment]
lets close this for now, as discussed to wait until refactor

**Pull request closed without merging**
