### PR TITLE
Sudoswap: attribute gem domainhash

### PR DESCRIPTION
**Pull request by 0xRobin**
implement attribution for gem through calldata domainhash
https://twitter.com/vasa_develop/status/1579830106067202049?s=20&t=GgkgSf__TCLuq2rjDjAajg

### CODE REVIEW

**Comment by 0xRobin** [comment]
@jeff-dude ready for review :heavy_check_mark:

**Review by soispoke — APPROVED** [review]
everything lgtm thanks @0xRobin !

**Comment by jeff-dude** [comment]
we've been having issues with the sudoswap seed file edited here. originally, @soispoke changed the ```block_number``` to ```blocknumber``` to try to fix, but apparently the issue is more than that. this only fails for us in dbt cloud, but using dbt core locally works. it's a bit confusing. as of now, this seed & test are disable in prod until we can find the solution

**Comment by 0xRobin** [comment]
@jeff-dude hmm, strange.
Can you share more details on what is failing?
Is the seed file itself the issue, or is the test failing?

**Comment by jeff-dude** [comment]
```
20:59:17  1 of 4 START seed file test_data.cryptopunks_trades_buys_bids_seed ............. [RUN]
20:59:17  2 of 4 START seed file test_data.dex_trades_seed ............................... [RUN]
20:59:17  3 of 4 START seed file test_data.perpetual_trades_seed ......................... [RUN]
20:59:17  4 of 4 START seed file test_data.sudoswap_ethereum_example_trades .............. [RUN]
20:59:22  4 of 4 ERROR loading seed file test_data.sudoswap_ethereum_example_trades ...... [ERROR in 5.54s]
20:59:25  3 of 4 OK loaded seed file test_data.perpetual_trades_seed ..................... [INSERT 13 in 8.17s]
20:59:25  1 of 4 OK loaded seed file test_data.cryptopunks_trades_buys_bids_seed ......... [INSERT 2 in 8.19s]
20:59:25  2 of 4 OK loaded seed file test_data.dex_trades_seed ........................... [INSERT 24 in 8.20s]
20:59:26  
20:59:26  Finished running 4 seeds in 0 hours 4 minutes and 24.74 seconds (264.74s).
20:59:26  
20:59:26  Completed with 1 error and 0 warnings:
20:59:26  
20:59:26  Runtime Error in seed sudoswap_ethereum_example_trades (seeds/sudoswap/sudoswap_ethereum_example_trades.csv)
20:59:26    ('The SQL contains 0 parameter markers, but 184 parameters were supplied', 'HY000')
```

**Pull request merged**
