### PR TITLE
Create balance macros for balancer 

### PR DESCRIPTION
**Pull request by viniabussafi**
The macros and subsequent spells on this PR were inspired by the balances and balances_daily models (https://github.com/duneanalytics/spellbook/blob/main/macros/models/_sector/tokens/balances_daily_agg.sql
https://github.com/duneanalytics/spellbook/blob/main/macros/models/_sector/tokens/balances_daily.sql).
It basically creates intermediate views for what impacts on balancer.liquidity and balancer.bpt_supply, which will end up being a second best solution, considering that I believe https://github.com/duneanalytics/spellbook/pull/5925 will fail, based on https://github.com/duneanalytics/spellbook/pull/5925#issuecomment-2115269730

### CODE REVIEW

**Comment by viniabussafi** [comment]
Also, I'm thinking of a better way to organize our spells, considering the folders are getting quite crowded and will double in # of files with v3 coming. Would something like this work? If so, I'll create a new PR after this one is merged

I'm using this as reference: https://github.com/duneanalytics/spellbook/tree/main/models/_sector

My initial division would be something like:
balances
bpt
flashloans
liquidity
pools
protocol_fee
support
trades
vebal

You can find it here: https://github.com/balancer/dune-spellbook/tree/organize-folders/models/balancer

**Comment by jeff-dude** [comment]
marking this blocked until we resolve the reorg in linked PR

**Comment by viniabussafi** [comment]
Guess we can go ahead and close this one and we start running these macros on the reorg PR. Would that be ok?

**Comment by jeff-dude** [comment]
> Guess we can go ahead and close this one and we start running these macros on the reorg PR. Would that be ok?

sure, if it's easy for ya to combine, go ahead and close this

**Comment by viniabussafi** [comment]
thanks, @jeff-dude! Moving to https://github.com/duneanalytics/spellbook/pull/6005

**Pull request closed without merging**
