### PR TITLE
Airdrop Claims Migration - #7 - Main Model - Relies on previous pr's 

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Review by antonio-mendes — APPROVED** [review]
lfg 🚀

**Comment by antonio-mendes** [comment]
Waiting for ethereum to go live and will rerun tests and merge

**Comment by henrystats** [comment]
hmm weird, will try and check to see where the dupes here is coming from!

**Comment by antonio-mendes** [comment]
@henrystats I think maybe somethings are flowing into the Ethereum model at least that are not airdrop data? I picked 2 random examples from the test that failed - https://dune.com/queries/3008741 - one is for Gala and one is SHIBA. Neither of these is in the Ethereum airdrop models

**Comment by antonio-mendes** [comment]
Problem is on Ethereum only https://dune.com/queries/3008765

**Comment by antonio-mendes** [comment]
Pushed a fix here - [fix_eth_airdrops](https://github.com/duneanalytics/spellbook/pull/4288)

**Pull request merged**
