### PR TITLE
Add block_time and block_slot to solana_utils balances

### PR DESCRIPTION
**Pull request by enriquerodbe**
### Contribution type

- [ ] New spell(s)
- [x] Adding to existing spell lineage
- [ ] Bug fix

### Description
Add block_time and block_slot to `solana_utils.latest_balances` and `solana_utils.daily_balances`

---

### Additional information

- Solves #6527

### CODE REVIEW

**Comment by enriquerodbe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by enriquerodbe** [comment]
recheck

**Comment by jeff-dude** [comment]
you're all set on signing the CLA. CI builds are just failing due to cluster crashes on large solana volumes of data. i will have to help get this to run early next week.

**Comment by jeff-dude** [comment]
since this change is a simple column add, my goal here is to push a test commit to shrink the timeframe of historical data to make this much less compute intensive on the cluster. i would be comfortable with this change on portions of history.

**Review by jeff-dude — APPROVED** [review]
good with me here after the tests ran 🙏

**Pull request merged**
