### PR TITLE
SPE-117 Migrate Hop Protocol

### PR DESCRIPTION
**Pull request by couralex6**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @couralex6 

[Sample hop_protocol_optimism_flows](https://dune.com/queries/3053318)

**Comment by couralex6** [comment]
The tests run successfully when testing after a full refresh. They're failing after an incremental run. I'm not sure what's causing them to fail. I won't spend anymore time on this since there's no downstream deps, but will revisit in the future

**Comment by Hosuke** [comment]
> The tests run successfully when testing after a full refresh. They're failing after an incremental run. I'm not sure what's causing them to fail. I won't spend anymore time on this since there's no downstream deps, but will revisit in the future

Then this might be caused by the null values in unique_key.

**Comment by Hosuke** [comment]
Fixed. The current dbt does not support null values in unique_key comparison (which is a serious bug).

**Pull request merged**
