### PR TITLE
Update zksync era for v24 protocol upgrade

### PR DESCRIPTION
**Pull request by lgingerich**
The ZKsync Era v24 upgrade marked the transition to shared bridge contracts on L1. This changed where data gets posted on L1.

### CODE REVIEW

**Comment by lgingerich** [comment]
Getting this error:

```
TrinoQueryError(type=INSUFFICIENT_RESOURCES, name=CLUSTER_OUT_OF_MEMORY, message="Query killed because the cluster is out of memory. Please try again in a few minutes."
```

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @lgingerich

**Comment by jeff-dude** [comment]
the changes look good, this spell may just need a refactor to be more efficient. it unions a lot of reads from a large raw table. a similar thing is happening on a spell similar to this one in the `rollup_economics` directory. we may need to explore building with the standard design of one spell per union'd query. let those build in parallel, then union the materialized tables together after.

**Comment by jeff-dude** [comment]
CI is running again now, we'll see how this goes.

**Comment by jeff-dude** [comment]
please see conversation in #6169 for optimization. i'm not sure if anyone is actively working on it, the PR has been stale for a bit now.

**Comment by lgingerich** [comment]
Thanks @jeff-dude, I just started looking into this but did not know about that other PR. I'll try to get something together

**Comment by jeff-dude** [comment]
fyi @0xRobin

**Pull request closed without merging**
