### PR TITLE
Adding reth to price model

### PR DESCRIPTION
**Pull request by xmc2**
Brief comments on the purpose of your changes:

Added rETH price API info for Ethereum and Arbitrum 

**For Dune Engine V2**

I've checked that:

### General checks:
* [NA] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [NA]  I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [NA]  if adding a new model, I added a test
* [NA]  the filename is unique and ends with .sql
* [NA]  each sql file is a select statement and has only one view, table or function defined  
* [NA]  column names are `lowercase_snake_cased`
* [NA]  if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [NA]  if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ YES ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ YES ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
manually checked these, looks good to go.
todo: add abitrum [here](https://github.com/duneanalytics/spellbook/blob/main/scripts/token_checker.py#L14)
fyi @0xRobin @dot2dotseurat

**Comment by 0xRobin** [comment]
> todo: add abitrum [here](https://github.com/duneanalytics/spellbook/blob/main/scripts/token_checker.py#L14)

coinpaprika doesn't have info on arbitrum tokens (for now?) 
https://api.coinpaprika.com/v1/contracts

**Comment by jeff-dude** [comment]
hmm, good point. not 100% how it works, but i also don't see optimism in that link, but the script outputs that it finds 11 contacts for optimism? or maybe i'm looking at it wrong?
https://github.com/duneanalytics/spellbook/actions/runs/3976714604/jobs/6817374497#step:6:19

**Comment by 0xRobin** [comment]
good point, arbitrum might actually be hiding somehwere then.. The API is a bit a mess. :(

**Pull request merged**
