### PR TITLE
Add seaport v1.5 to opensea_events

### PR DESCRIPTION
**Pull request by sohwak**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

Modifications:
- opensea.v4
  - Include Seaport v1.5 (`0x00000000000000adc04c56bf30ac9d3c0aaf14dc`) 
  - Along with existing v1.4 (`0x00000000000001ad428e4906ae43d8f9852d0dd6`)
- opensea.v3 
  - filter only Seaport v1.0 (`0x00000000006c3852cbef3e08e8df289169ede581`)

Need pre/post check :
- Requested change to polygon contract decoding (cc. Antonio Mendes) 
  - 0x00000000000001ad428e4906ae43d8f9852d0dd6 was already going into the project name `seaportv1_4polygon`, and I want to change it to project `seaport`. Therefore, this should be done after the table (e.g. `seaport_polygon.Seaport_evt_OrderFulfilled`) contains data with `contract_address = 0x00000000000001ad428e4906ae43d8f9852d0dd6`.
- Although it is a SparkSQL result, the resulting `opensea_v4_polygon.events` column is varchar instead of varbinary, causing an error in the UNION previous, so please check this part again.

I'll test it a few, and when it's ready, I'll request a merge in the comments.

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by sohwak** [comment]
Hi @0xRobin, this seems to be coming well now, so please check to merge.

**Review by 0xRobin — APPROVED** [review]
:heavy_check_mark: LGTM

**Comment by sohwak** [comment]
Hi, Dune team. This has been held up for the last week might be due to polygon decoding delay, is there any chance this could be done sooner? 🙂

**Comment by ytoast** [comment]
Hey, just wondering: what's the difference between `opensea_v1_ethereum_events.sql`, `opensea_v3_ethereum_events.sql`, and `opensea_v4_ethereum_events.sql`? 

Seems to me that:
v1 - wyvern contract
v3 - seaport 1.0
v4 - seaport 1.4, 1.5

Some other questions I have:
* Is there a reason why `opensea_v2_ethereum_events.sql` is skipped? 
* I'd have assumed seaport 1.5 `opensea_v5_ethereum_events.sql`. When do we decide to create a new version?

**Review by jeff-dude — APPROVED** [review]
will look to include in a batch of merges today.

this is a random gut feel, but it seems the `opensea` directory could use a comprehensive readme with the intention behind each spell. especially as it overlaps with spells in `seaport` directory as well. i'm thinking we'd include a list of the spells with an overview, any important notes to call out (contracts with links to explorers, any complex logic unique to opensea relative to nft trades, etc.) -- do you think this is something you're comfortable helping build? or maybe @0xRobin can do in the redesign process?

**Comment by sohwak** [comment]
@ytoast 
For the most part, you're right. Originally, in the past 
v1 - wyvern v2.2
v2- wyvern v2.3
v3- seaport v1.0
v4- seaport v1.4, v1.5
but now that I look at it, all wyvern is v1.

There is no version ordering convention here. I contributed after Seaport came, so I used v3, and v4 for seaport v1.4 because some difference happened. But, seaport v1.5 is the same as v1.4, so I kept it as v4.

**Comment by jeff-dude** [comment]
> @jeff-dude I see this reply now, yes I'll check it out. I've been wanting to write a document on Seaport decoding but never got around to it. It might be a bit of a low priority, but I'll try to write it. Also, it looks like you're doing an NFT redesign recently, so if there's any work that needs to be done on that, I'd be happy to help. CC @0xRobin

hop into the gh discussions section in spellbook, there's a pinned discussion on the nft redesign -- would love your input!

**Comment by jeff-dude** [comment]
> @ytoast For the most part, you're right. Originally, in the past v1 - wyvern v2.2 v2- wyvern v2.3 v3- seaport v1.0 v4- seaport v1.4, v1.5 but now that I look at it, all wyvern is v1.
> 
> There is no version ordering convention here. I contributed after Seaport came, so I used v3, and v4 for seaport v1.4 because some difference happened. But, seaport v1.5 is the same as v1.4, so I kept it as v4.

lets ensure we standardize this in the redesign effort

**Comment by ytoast** [comment]
understood, thank you @sohwak!

**Pull request merged**
