### PR TITLE
Create `unique_or_null` generic test

### PR DESCRIPTION
**Pull request by hildobby**
Will be useful to use on the staking_ethereum_entities spell's `depositor_address`, `tx_from` & `pubkey` columns once this PR is merged: https://github.com/duneanalytics/spellbook/pull/4556

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
We may have one more demo usage in this PR.

**Comment by jeff-dude** [comment]
> We may have one more demo usage in this PR.

let's revisit this PR after the linked PR is merged, so examples are a bit easier to do. i agree that it'd be nice to see how it's applied to a spell, the output test query from `dbt compile`, expected results vs. actual results, etc etc

adding new generic tests is relatively new concept within spellbook, so would be good to be calculated about the approach

**Comment by 0xRobin** [comment]
@hildobby dbt has support for filtering on existing generic tests.

So this can also be achieved with:
```
tests:
  - unique:
      config:
        where: "project is not null"
   ```
   https://docs.getdbt.com/reference/resource-properties/tests#unique

**Comment by hildobby** [comment]
> @hildobby dbt has support for filtering on existing generic tests.
> 
> So this can also be achieved with:
> 
> ```
> tests:
>   - unique:
>       config:
>         where: "project is not null"
> ```
> 
> https://docs.getdbt.com/reference/resource-properties/tests#unique

Oooh I'll test that instead in https://github.com/duneanalytics/spellbook/pull/4621 and close this PR if it works as intended, didn't know you could add a where clause like that, thanks for the heads up!

**Comment by hildobby** [comment]
Update, it works flawlessly, you're a wizard @0xRobin ty 🙌

closing this PR

**Pull request closed without merging**
