### PR TITLE
[Easy] make trader age spell crosschain - Ready for review 

### PR DESCRIPTION
**Pull request by henrystats**
@gentrexha I'd like to make a small change to the trader age spell you built. 

I removed the **blockchain/ethereum** filter so there are more blockchains included for this spell as the dex.trades table is a lot more robust now with multiple dexes from multiple chains and the aggregator trades table will also soon have more models from other chains (I've a couple of pr's up).

Please let me know what you think!

### CODE REVIEW

**Comment by gentrexha** [comment]
> @gentrexha I'd like to make a small change to the trader age spell you built.
> 
> I removed the **blockchain/ethereum** filter so there are more blockchains included for this spell as the dex.trades table is a lot more robust now with multiple dexes from multiple chains and the aggregator trades table will also soon have more models from other chains (I've a couple of pr's up).
> 
> Please let me know what you think!

Sounds great to me. Good idea. I'd still want the option for these to be filtered out to a single blockchain.

Worth tagging @soispoke for these, as he's the label's expert.

**Comment by henrystats** [comment]
Hmm so the way I've written it, the trader age is basically the max date - min date across all blockchains.

I just need to remove the collect_list(blockchain) so it'd group the min & max date by blockchain as well, that way one can easily filter for the chain you'd want. 

Should I proceed with that's ser? @gentrexha

**Comment by henrystats** [comment]
Edited the spells now so each address on a different blockchain are treated separately.

**Comment by soispoke** [comment]
The version I'm seeing now makes sense to me thanks @henrystats, wdyt @gentrexha ?

**Comment by gentrexha** [comment]
> The version I'm seeing now makes sense to me thanks @henrystats, wdyt @gentrexha ?

Looks good to me. @henrystats feel free to add yourself as a contributor to spells.

@soispoke I've always wondered why `array(blockchain) as blockchain,` is used for the `blockchain` column?

**Comment by soispoke** [comment]
@gentrexha Initially it was a design choice so it could allow crosschain labels for single addresses (i.e., mostly across EVM compatible blockchains). But tbh looking back it prob wasn't the best choice :)

**Comment by soispoke** [comment]
@henrystats I'll wait until you get a chance to add yourself as a contributor and then merge

**Comment by henrystats** [comment]
Thank you very much sers! @soispoke will update and add myself as a contributor now.

**Comment by henrystats** [comment]
Updated the contributors list ser @soispoke , tyvm!

**Comment by henrystats** [comment]
@soispoke I made a change to the labels.all table and added fantom to the post hook hence why the unique combinations test for it was triggered. 

I'll rerun now though as this passed before, checking.

**Comment by henrystats** [comment]
Here's why the tests are failing, looks to be some cex addresses?

https://dune.com/queries/1934284?d=1

will check and see if I can fix it

**Comment by henrystats** [comment]
Hmm can't find where the duplicates are, running Command + F in the cex labels file for the addresses doesn't return duplicates.

**Comment by soispoke** [comment]
I got it, let me push the fix

**Comment by soispoke** [comment]
I think the test should've full-refreshed the table, and didn't. I'll test locally and if it succeeds I'll just merge it

**Comment by henrystats** [comment]
okaie ser! thank you!

**Comment by henrystats** [comment]
yes sure ser will update now!

**Comment by henrystats** [comment]
Updated ser @soispoke tyvm

**Comment by soispoke** [comment]
thanks, will merge and see if everything is alright

**Review by soispoke — APPROVED** [review]

**Pull request merged**
