### PR TITLE
1inch: perf test

### PR DESCRIPTION
**Pull request by grkhr**
will be removed soon

### CODE REVIEW

**Comment by jeff-dude** [comment]
i think i'm following your performance test here. let's see if i can summarize:
- first step: create a metadata spell, which will be used in other spells downstream
  - **_note:_** both approaches below provide the same hardcoded metadata
  - approach 1: `models/oneinch/test/oneinch_test_dict_table.sql` materialize as table
  - approach 2: `models/oneinch/test/oneinch_test_dict_view.sql` materialize as view
- second step: create the downstream spell, which calls a dbt macro that contains the sql query to build the spell
  - **_note:_** both approaches below call the same macro, i.e. same SQL query
  - approach 1: `models/oneinch/test/oneinch_test_single_table.sql` passes in the table for metadata
  - approach 2: `models/oneinch/test/oneinch_test_single_view.sql` passes in the view for metadata

the two approaches are nearly identical, with only difference being metadata materialized as a table vs. a view. the performance output is staggering:
- passing in table, spell completes in ~147s
- passing in view, spell completes in ~1,608s
reference: https://github.com/duneanalytics/spellbook/actions/runs/7248105296/job/19743387711?pr=5017#step:11:24

**Comment by grkhr** [comment]
yes, everything is correct!

**Comment by jeff-dude** [comment]
> yes, everything is correct!

i've raised a ticket internally and we'll report back what we can find 🙏

**Comment by jeff-dude** [comment]
with the help from our engine team, here are the findings:
- trino behind-the-scenes picks a build side of a join in it's plan. for some reason, when a view and not a table, trino picks the poor performing side
- the root cause is the `and block_time >= (select first_deploy_at from meta)` filter in the macro. if it's switched to the `and block_time >= timestamp '2019-06-03 20:11'` format, then trino plan is more efficient regardless of materialization
- relevant stats when a table
```
Fragment 2 [SOURCE]
    Output layout: [block_number_645, trace_address, expr_658, expr_657, expr_656, tx_hash_bytearray, expr_655]
    Output partitioning: HASH [block_number_645, tx_hash_bytearray]
    FilterProject[filterPredicate = ("block_time_644" >= "first_deploy_at")]
    │   Layout: [block_number_645:bigint, trace_address:array(bigint), expr_658:varbinary, expr_657:varbinary, expr_656:uint256, tx_hash_bytearray:varbinary, expr_655:varbinary]
    │   Estimates: {rows: 340693804 (94.87GB), cpu: 202.36G, memory: 0B, network: 0B}/{rows: 340693804 (94.87GB), cpu: 94.87G, memory: 0B, network: 0B}
    │   expr_658 := (CASE WHEN (substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('qQWcuw=='))) THEN substr("input_bytearray", BIGINT '17', BIGINT '20') WHEN (substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('I7hy3Q=='))) THEN substr("input_bytearray", BIGINT '49', BIGINT '20') WHEN ("_unsafe_uint256" > "$literal$"(from_base64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='))) THEN "to_bytearray" END)
    │   expr_657 := (CASE WHEN ((substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('qQWcuw=='))) OR ("_unsafe_uint256" > "$literal$"(from_base64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')))) THEN "from_bytearray" WHEN (substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('I7hy3Q=='))) THEN substr("input_bytearray", BIGINT '17', BIGINT '20') END)
    │   expr_656 := (CASE substr("input_bytearray", BIGINT '1', BIGINT '4') WHEN "$literal$"(from_base64('qQWcuw==')) THEN varbinary_to_uint256(substr("input_bytearray", BIGINT '37', BIGINT '32')) WHEN "$literal$"(from_base64('I7hy3Q==')) THEN varbinary_to_uint256(substr("input_bytearray", BIGINT '69', BIGINT '32')) ELSE "_unsafe_uint256" END)
    │   expr_655 := (CASE WHEN ("_unsafe_uint256" > "$literal$"(from_base64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='))) THEN "$literal$"(from_base64('rg==')) ELSE "to_bytearray" END)
    └─ CrossJoin[]
       │   Layout: [block_number_645:bigint, from_bytearray:varbinary, input_bytearray:varbinary, _unsafe_uint256:uint256, block_time_644:timestamp(3) with time zone, trace_address:array(bigint), tx_hash_bytearray:varbinary, to_bytearray:varbinary, first_deploy_at:timestamp(3) with time zone]
       │   Estimates: {rows: 627233237 (202.36GB), cpu: 399.46G, memory: 270B, network: 0B}
       │   Distribution: REPLICATED
       │   dynamicFilterAssignments = {first_deploy_at -> #df_3415}
       ├─ ScanFilterProject[table = delta_prod:ethereum.traces_0010, filterPredicate = (("call_type" = VARCHAR 'call') AND ("tx_success_646" = true) AND ("success" = true) AND (((substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('qQWcuw=='))) AND (length("input_bytearray") = BIGINT '68')) OR ((substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('I7hy3Q=='))) AND (length("input_bytearray") = BIGINT '100')) OR (_unsafe_uint256("value_uint256") > "$literal$"(from_base64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='))))), dynamicFilters = {"block_number_645" = #df_3413, "tx_hash_bytearray" = #df_3414, "block_time_644" >= #df_3415}]
       │      Layout: [block_number_645:bigint, from_bytearray:varbinary, input_bytearray:varbinary, _unsafe_uint256:uint256, block_time_644:timestamp(3) with time zone, trace_address:array(bigint), tx_hash_bytearray:varbinary, to_bytearray:varbinary]
       │      Estimates: {rows: 8089986549 (2.42TB), cpu: 2.53T, memory: 0B, network: 0B}/{rows: 627233237 (197.10GB), cpu: 2.53T, memory: 0B, network: 0B}/{rows: 627233237 (197.10GB), cpu: 197.10G, memory: 0B, network: 0B}
       │      _unsafe_uint256 := _unsafe_uint256("value_uint256")
       │      value_uint256 := value_uint256:varbinary:REGULAR
       │      block_number_645 := block_number:bigint:REGULAR
       │      tx_success_646 := tx_success:boolean:REGULAR
       │      from_bytearray := from_bytearray:varbinary:REGULAR
       │      success := success:boolean:REGULAR
       │      input_bytearray := input_bytearray:varbinary:REGULAR
       │      block_time_644 := block_time:timestamp(3) with time zone:REGULAR
       │      trace_address := trace_address:array(bigint):REGULAR
       │      call_type := call_type:varchar:REGULAR
       │      tx_hash_bytearray := tx_hash_bytearray:varbinary:REGULAR
       │      to_bytearray := to_bytearray:varbinary:REGULAR
       └─ LocalExchange[partitioning = SINGLE]
          │   Layout: [first_deploy_at:timestamp(3) with time zone]
          │   Estimates: {rows: 1 (9B), cpu: 0, memory: 0B, network: 0B}
          └─ RemoteSource[sourceFragmentIds = [3]]
                 Layout: [first_deploy_at:timestamp(3) with time zone]
```
- relevant stats when a view
```
Fragment 2 [SOURCE]
    Output layout: [block_number_645, expr_659, expr_660, trace_address, expr_658, expr_657, tx_hash_bytearray]
    Output partitioning: BROADCAST []
    Project[]
    │   Layout: [block_number_645:bigint, expr_659:varbinary, expr_660:varbinary, trace_address:array(bigint), expr_658:uint256, expr_657:varbinary, tx_hash_bytearray:varbinary]
    │   Estimates: {rows: 0 (0B), cpu: 0, memory: 0B, network: 0B}
    │   expr_659 := (CASE WHEN ((substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('qQWcuw=='))) OR ("_unsafe_uint256" > "$literal$"(from_base64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')))) THEN "from_bytearray" WHEN (substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('I7hy3Q=='))) THEN substr("input_bytearray", BIGINT '17', BIGINT '20') END)
    │   expr_660 := (CASE WHEN (substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('qQWcuw=='))) THEN substr("input_bytearray", BIGINT '17', BIGINT '20') WHEN (substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('I7hy3Q=='))) THEN substr("input_bytearray", BIGINT '49', BIGINT '20') WHEN ("_unsafe_uint256" > "$literal$"(from_base64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='))) THEN "to_bytearray" END)
    │   expr_658 := (CASE substr("input_bytearray", BIGINT '1', BIGINT '4') WHEN "$literal$"(from_base64('qQWcuw==')) THEN varbinary_to_uint256(substr("input_bytearray", BIGINT '37', BIGINT '32')) WHEN "$literal$"(from_base64('I7hy3Q==')) THEN varbinary_to_uint256(substr("input_bytearray", BIGINT '69', BIGINT '32')) ELSE "_unsafe_uint256" END)
    │   expr_657 := (CASE WHEN ("_unsafe_uint256" > "$literal$"(from_base64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='))) THEN "$literal$"(from_base64('rg==')) ELSE "to_bytearray" END)
    └─ FilterProject[filterPredicate = ("block_time_644" >= "expr_670")]
       │   Layout: [block_number_645:bigint, from_bytearray:varbinary, input_bytearray:varbinary, _unsafe_uint256:uint256, trace_address:array(bigint), tx_hash_bytearray:varbinary, to_bytearray:varbinary]
       │   Estimates: {rows: 0 (0B), cpu: 202.36G, memory: 0B, network: 0B}/{rows: 0 (0B), cpu: 0, memory: 0B, network: 0B}
       └─ CrossJoin[]
          │   Layout: [block_number_645:bigint, from_bytearray:varbinary, input_bytearray:varbinary, _unsafe_uint256:uint256, block_time_644:timestamp(3) with time zone, trace_address:array(bigint), tx_hash_bytearray:varbinary, to_bytearray:varbinary, expr_670:timestamp(3) with time zone]
          │   Estimates: {rows: 627233734 (202.36GB), cpu: 399.46G, memory: 270B, network: 0B}
          │   Distribution: REPLICATED
          │   dynamicFilterAssignments = {expr_670 -> #df_3259}
          ├─ ScanFilterProject[table = delta_prod:ethereum.traces_0010, filterPredicate = (("call_type" = VARCHAR 'call') AND ("tx_success_646" = true) AND ("success" = true) AND (((substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('qQWcuw=='))) AND (length("input_bytearray") = BIGINT '68')) OR ((substr("input_bytearray", BIGINT '1', BIGINT '4') = "$literal$"(from_base64('I7hy3Q=='))) AND (length("input_bytearray") = BIGINT '100')) OR (_unsafe_uint256("value_uint256") > "$literal$"(from_base64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='))))), dynamicFilters = {"block_time_644" >= #df_3259}]
          │      Layout: [block_number_645:bigint, from_bytearray:varbinary, input_bytearray:varbinary, _unsafe_uint256:uint256, block_time_644:timestamp(3) with time zone, trace_address:array(bigint), tx_hash_bytearray:varbinary, to_bytearray:varbinary]
          │      Estimates: {rows: 8089992852 (2.42TB), cpu: 2.53T, memory: 0B, network: 0B}/{rows: 627233734 (197.10GB), cpu: 2.53T, memory: 0B, network: 0B}/{rows: 627233734 (197.10GB), cpu: 197.10G, memory: 0B, network: 0B}
          │      _unsafe_uint256 := _unsafe_uint256("value_uint256")
          │      value_uint256 := value_uint256:varbinary:REGULAR
          │      block_number_645 := block_number:bigint:REGULAR
          │      tx_success_646 := tx_success:boolean:REGULAR
          │      from_bytearray := from_bytearray:varbinary:REGULAR
          │      success := success:boolean:REGULAR
          │      input_bytearray := input_bytearray:varbinary:REGULAR
          │      block_time_644 := block_time:timestamp(3) with time zone:REGULAR
          │      trace_address := trace_address:array(bigint):REGULAR
          │      call_type := call_type:varchar:REGULAR
          │      tx_hash_bytearray := tx_hash_bytearray:varbinary:REGULAR
          │      to_bytearray := to_bytearray:varbinary:REGULAR
          └─ LocalExchange[partitioning = SINGLE]
             │   Layout: [expr_670:timestamp(3) with time zone]
             │   Estimates: {rows: 1 (9B), cpu: 0, memory: 0B, network: 0B}
             └─ Project[]
                │   Layout: [expr_670:timestamp(3) with time zone]
                │   Estimates: {rows: 1 (9B), cpu: 9, memory: 0B, network: 0B}
                │   expr_670 := CAST("expr_655" AS timestamp(3) with time zone)
                └─ RemoteSource[sourceFragmentIds = [3]]
                       Layout: [expr_655:timestamp(0)]
```
- estimates of final project are different:
  - table: `│   Estimates: {rows: 340693804 (94.87GB), cpu: 202.36G, memory: 0B, network: 0B}/{rows: 340693804 (94.87GB), cpu: 94.87G, memory: 0B, network: 0B}`
  - view: `│   Estimates: {rows: 0 (0B), cpu: 0, memory: 0B, network: 0B}`
- for some reason the `FilterProject[filterPredicate = ("block_time_644" >= "expr_670")` produces wildly incorrect estimates
- engine team recommendation would be to extract `first_deploy_at` as a parameter to the macro. Then one avoids the above cross join altogether and get the most accurate statistics. Then it does not matter if one uses a table or a view
- to figure out why stats are incorrect, it would require engine team to dig into trino code (not going to happen atm, but they will eventually look)

**Comment by grkhr** [comment]
Thanks for this explanation!
 
Btw not necessary to pass the date explicitly to the macro, CTE is fine too (look at how it's already been implemented here https://github.com/duneanalytics/spellbook/pull/5028)

I believe this finding is useful, perhaps you should review the entire spellbook repo to see if such cases exist in other spells. Maybe migrating all dict-views to tables could significantly increase the prod performance.

**Pull request closed without merging**
