### PR TITLE
Modify `opensea.trades` refer to `seaport.trades`

### PR DESCRIPTION
**Pull request by sohwak**
Brief comments on the purpose of your changes:

Modify `opensea.trades` refer to `seaport.trades`

This should be dealt after PR https://github.com/duneanalytics/spellbook/pull/1942 to use `block_number`

- `opensea.trades` : 
  - opensea.trades has the same columns as seaport.trades
  - only some specified zone_address are recognized as opensea's
  - project/version : opensea/v3
  - materialize : view

- `opensea.events` :
  - opensea.events is compose of mint, burn, and trades. 
  - but now there are only trades.
  - materialize : view

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
lgtm, this should run in proper dependency order based on other PR change first. give it about an hour or two in prod

**Comment by jeff-dude** [comment]
> lgtm, this should run in proper dependency order based on other PR change first. give it about an hour or two in prod

ah, nevermind, there is an error for ambiguous column in select. can you fix?

**Comment by sohwak** [comment]
ok, looks well-finished. I'll check the result data once. just minute.

**Comment by sohwak** [comment]
@jeff-dude, I checked. I think the data column and volume match well. continue to merge, please. :)

**Pull request merged**
