### PR TITLE
Add Uniswap Blast (V2 & V3) - Ready for review

### PR DESCRIPTION
**Pull request by henrystats**

### CODE REVIEW

**Comment by henrystats** [comment]
will update seed file once tables are backfilled on dune

**Comment by henrystats** [comment]
@Hosuke hola ser 👋 -- this is ready for review and the tests are failing (incremental test) because it gets timed out since I made changes to dex base trades & dex trades (so I could update hooks to show blast chain  on the ui as well)

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @henrystats 

[Sample uniswap_v2_blast_base_trades](https://dune.com/queries/3836807)
[Sample uniswap_v3_blast_base_trades](https://dune.com/queries/3836830)

**Comment by Hosuke** [comment]
Please run `git merge main` and resolve conflicts.
Thank you @henrystats.

**Comment by henrystats** [comment]
done ser @Hosuke

**Review by jeff-dude — APPROVED** [review]
thanks for being on top of it!

**Pull request merged**
