### PR TITLE
Lifinity migrate

### PR DESCRIPTION
**Pull request by andrewhong5297**
migrating solana lifinity

### CODE REVIEW

**Comment by aalan3** [comment]
can you drop `tags = ['prod_exclude'],` at the top of the models? they are currently excluded and not running in CI either because of that.

**Comment by andrewhong5297** [comment]
guessing this ref error is just because the solana models have not been rebuilt yet

**Comment by aalan3** [comment]
@andrewhong5297 table is back again. I reran this and we got the same error as the prod run

**Comment by andrewhong5297** [comment]
> @andrewhong5297 table is back again. I reran this and we got the same error as the prod run

odd it worked fine in the raydium PR. I'm merging main again

**Comment by andrewhong5297** [comment]
oh its giving a different error now, it was giving a missing ref error before. I'll look.

**Comment by andrewhong5297** [comment]
for some reason the inner joins make the cardinality filter not work. fixed

**Comment by andrewhong5297** [comment]
Never seen this error

**Review by 0xRobin — APPROVED** [review]

**Pull request merged**
