### PR TITLE
Migrate balances_ethereum_erc20_day

### PR DESCRIPTION
**Pull request by lajarre**
# Summary of changes

- Migrating `balances_ethereum_erc20_day` and `balances_ethereum_erc20_hour` and related files to DuneSQL and update their related schema
- `tests/balances/ethereum/balances_ethereum_erc20_day_assert_nonnegative.sql`: relax test by rounding to 0 digits. This might be improved if necessary.
- Non-compliant tokens check: relaxed to `< 1100`, from `< 550`. This seems reasonable as the test itself was reporting a number of reported non-compliant tokens slightly above 1000.

### CODE REVIEW

**Comment by lajarre** [comment]
recheck

**Comment by lajarre** [comment]
@Hosuke Thanks for your help on this one. Any idea what's causing the Error in seed:

```
15:46:51  Database Error in seed balances_ethereum_erc20_latest_entries (seeds/balances/ethereum/balances_ethereum_erc20_latest_entries.csv)
15:46:51    TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 2:73469: mismatched input '\'. Expecting: <expression>", query_id=20230818_154649_18874_ksage)
```

I haven't figured for now what this is related to.

It seems to be the last technical issue before getting this into a mergeable state.

**Comment by Hosuke** [comment]
I am not sure why is the `test balances_ethereum_erc20_hour_assert_samples` triggered, but you can continue to migrate other balances spell like ..._erc20_hour to solve the problem.

**Comment by lajarre** [comment]
> I am not sure why is the `test balances_ethereum_erc20_hour_assert_samples` triggered, but you can continue to migrate other balances spell like ..._erc20_hour to solve the problem.

I've migrated `..._hour` but that doesn't solve the issue.

**Comment by Hosuke** [comment]
Currently I am not sure with the error message.
https://github.com/duneanalytics/spellbook/actions/runs/5966167467/job/16185232072?pr=4074#step:14:39

**Comment by lajarre** [comment]
Produced a merge commit to keep the branch up to date, but I would happily clean up the branch history once problems have been fixed.

**Comment by lajarre** [comment]
This PR faces tough technical complexities because the 10000 `sequence` max. I've replaced it by https://github.com/duneanalytics/spellbook/pull/4257 which is a tentative at removing the erc20 hourly spell to circumvent this entirely.

**Review by Hosuke — APPROVED** [review]
[Sample balances_ethereum_erc20_day](https://dune.com/queries/3023338)

**Review by antonio-mendes — CHANGES_REQUESTED** [review]
Hey @lajarre !

Thanks for this submission, I'd like to request some changes so we align this with other chains:
- Use https://github.com/duneanalytics/spellbook/pull/4259 + https://github.com/duneanalytics/spellbook/pull/4327 as referrence
- The `unique_transfer_id` created in transfers is no longer needed if you use the `evt_index` field
- Feel free to materialise transfer tables but not balances tables, use the `block_month` field as the partition key
- For time variables name them `block_day`, `block_hour`, `block_month` etc

**Comment by lajarre** [comment]
Thanks @antonio-mendes for the review.  
I tried applying the recommendations you gave.

> The `unique_transfer_id` created in transfers is no longer needed if you use the `evt_index` field

I could remove `unique_transfer_id` and add back `evt_index` and `evt_tx_hash` to `transfers_ethereum_erc20`. But that would modify this table which is already available and in use on dune.com, so it seems such a change would break a lot of things for users.  
Please tell me if I'm getting something wrong.

**Comment by antonio-mendes** [comment]
@lajarre given that we ended up being able to merge (this)[https://github.com/duneanalytics/spellbook/pull/4366] PR with macros to create ERC20 balances, do you think you could give it a try and implement these tables using the new macro? We can then validate if both approaches return the same result but I've validated for Polygon and it did.

I know this is an annoying request specially after all the work you put into this PR already, but it would go a long way to have a standardisable approach for these things.

**Comment by jeff-dude** [comment]
thank you for the patience, now that the spellbook migration is complete, as we attempt to rebuild transfers & balances spells on the dunesql engine 🙏 

we will close this PR now, as the work on this set of sector spells can be tracked in the following locations:
#4521 
#4523 
#4633 
#4698

**Pull request closed without merging**
