### PR TITLE
Add apeswap_*_base_trades

### PR DESCRIPTION
**Pull request by Hosuke**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by Hosuke** [comment]
Not sure about this [error](https://github.com/duneanalytics/spellbook/actions/runs/6968851563/job/18966168132#step:11:26)

**Comment by Hosuke** [comment]
Seems `apeswap_polygon.ApePair_evt_Swap` decoded source is missing records before 2022-11-26:

Trades happened at 2022-11-22:
https://polygonscan.com/tx/0x2f15cd0b477cc45c55924b7aa461a516e2b2f369a3806b55042e3c0e5b0877da

where the earliest trades recorded in dex.trades is at 2022-11-26 :
https://dune.com/queries/3249923

**Comment by Hosuke** [comment]
> > Seems `apeswap_polygon.ApePair_evt_Swap` decoded source is missing records before 2022-11-26:
> > Trades happened at 2022-11-22: https://polygonscan.com/tx/0x2f15cd0b477cc45c55924b7aa461a516e2b2f369a3806b55042e3c0e5b0877da
> > where the earliest trades recorded in dex.trades is at 2022-11-26 : https://dune.com/queries/3249923
> > (Maybe we need to rerun this decoded source)
> 
> not sure if anything changed, but i see rows back to october 2021 in your linked query? i think we can proceed, if that's how the data is in `dex.trades` too
> 
> i'd say continue on and get CI passing as expected

I submitted the contract address for decoding, and see if the new decoded source can help with passing the tests.

**Comment by Hosuke** [comment]
Now the missing trades records have been included:
[Sample apeswap_polygon.base_trades](https://dune.com/queries/3265164)

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
> Now the missing trades records have been included: [Sample apeswap_polygon.base_trades](https://dune.com/queries/3265164)

legend! thank you

**Pull request merged**
