### PR TITLE
odos dupes - wip 

### PR DESCRIPTION
**Pull request by henrystats**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by Hosuke** [comment]
`odos.trades` dupes detail:
https://dune.com/queries/2100535?d=1&category=abstraction&namespace=odos

It may be a batch swap.

Snowtrace log:
https://snowtrace.io/tx/0x9bc19737e7f4e4336ed7729939c4370c3d17177f5f7d537e0b546900e5c4770e#eventlog

Possible fix: we may use swap events for dex.trades (25, 29, 33, 37, 41) instead of the last event index.

**Comment by henrystats** [comment]
Thank you very much ser @Hosuke, taking a look now ser!

**Comment by Hosuke** [comment]
> bump @Hosuke, @jeff-dude

In my opinion, we can either change/fix the source, or add token_address as part of unique_key for aggregator_trades.
I think there are some difference between dex.trades and dex_aggregator.trades, and we may upgrade our design/implementation along the way when necessary.

**Comment by henrystats** [comment]
hmm sorry I don't quite understand ser @Hosuke, the reason why we're having duplicates is because there are multiple tokens being bought/sold. 

And we're currently selecting Amounts[1] hence it's duplicated, we can use `POSEXPLODE` to have a **swap_index** that we include in the unique key (not sure if this one is a better alternative though), but another issue is the token_sold columns.

How we do we handle multiple token_sold columns? it isn't that user A is swapping 10$ ETH, 10$ AVAX for 10$ USDC & 10$ AVAX. 

User A is swapping 10$ ETH + 10$ BTC for 6$USDC, 7$ AVAX, etc.....

**Comment by jeff-dude** [comment]
> bump ser @jeff-dude

sorry -- will follow up soon! i know this one has been excluded in prod for awhile, would be nice to finalize. in the meantime, can you share a query (on the source data, compiled in dbt with filters) that gives examples of the issues outstanding?

**Comment by jeff-dude** [comment]
sorry ser, i don't have time to dig into this issue. i'd advise to create a GH issue for the bug here and work with folks who understand the protocol to move forward. for now, it's still excluded in production and data will be stale.

**Pull request closed without merging**
