### PR TITLE
[EASY] add WLD token

### PR DESCRIPTION
**Pull request by pandajackson42**

### CODE REVIEW

**Comment by jeff-dude** [comment]
hi @pandajackson42 -- we've reconfigured the token files to be compatible on both dunesql and spark. there should be two separate files. please see this PR as reference on how to add to both: https://github.com/duneanalytics/spellbook/pull/3821/files

**Comment by pandajackson42** [comment]
> hi @pandajackson42 -- we've reconfigured the token files to be compatible on both dunesql and spark. there should be two separate files. please see this PR as reference on how to add to both: https://github.com/duneanalytics/spellbook/pull/3821/files

thanks for noticing! added

**Comment by pandajackson42** [comment]
Checked that it's because it has already been added on both Ethereum https://github.com/duneanalytics/spellbook/pull/3813 and Optimism https://github.com/duneanalytics/spellbook/pull/3841/commits/0575ca89533709f9f56eefffe3a6fd5206a9c958 

This PR can be closed

**Comment by jeff-dude** [comment]
thank you! we do have a user adding in an automated fashion weekly, so you likely will get yours added without the need to do on your own :)

**Pull request closed without merging**
