### PR TITLE
fix(bonkbot): only include unique fee payment tx's to prevent dupes

### PR DESCRIPTION
**Pull request by whalehunting**
Fix regarding #6176 - thanks for pinging me @jeff-dude !

From now on no duplicates should be included in the spellbook

### CODE REVIEW

**Comment by jeff-dude** [comment]
hey @0xRobin -- as discussed, can you help support this open PR for solana bot trades? we had to exclude this one on dupes. this PR is intended to fix that. i'll be out rest of week, so would be nice if you could help as needed 🙏

**Comment by jeff-dude** [comment]
we're hitting that odd error here that has been occurring across PRs. @aalan3 is actively talking to our platform team to find out why

**Comment by whalehunting** [comment]
could we just merge it into production and check if the duplication error still exists? if so, we could revert it by adding the `prod_exclude` tag to the schema config again

@0xRobin @aalan3  thx for helping out btw, really appreciate it!

**Comment by whalehunting** [comment]
nice, it worked! seed is expected to fail bc we only included data from the last few days. if you're fine with it i would revert the `project_start_date` to the original value and then we can get this merged @0xRobin @jeff-dude

**Comment by 0xRobin** [comment]
yes go for it @whalehunting

**Comment by whalehunting** [comment]
@0xRobin done. it's ready to get deployed!

**Pull request merged**
