### PR TITLE
Add zkSync to `tokens`

### PR DESCRIPTION
**Pull request by lgingerich**

### CODE REVIEW

**Comment by lgingerich** [comment]
Commit 75f9b67 adds a dependency on https://github.com/duneanalytics/spellbook/pull/4548 being merged first

**Comment by jeff-dude** [comment]
hi @lgingerich welcome to spellbook!

while waiting to be unblocked by the above linked PR, you will also need to sign the spellbook open-source license agreement by commenting the below on this PR:
`I have read the CLA Document and I hereby sign the CLA`

**Comment by lgingerich** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lgingerich** [comment]
You can move this PR to `blocked` until https://github.com/duneanalytics/spellbook/pull/4529 is merged

**Comment by lgingerich** [comment]
The previously blocking PR has been merged. This should be good to move forward now

**Review by jeff-dude — APPROVED** [review]
thank you!

**Pull request merged**
