### PR TITLE
Updates to static tables 

### PR DESCRIPTION
**Pull request by catherine-2**
Brief comments on the purpose of your changes:

Hi! This pull request is all static tables - some updates and some new ones created.

- Added new rows to existing tables for new collections 
- Added a few other collection specific tables 

Tested and should be a quick merge hopefully but let me know if anything looks off! Thank you!

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by catherine-2** [comment]
@soispoke  checks passed and ready for review! Couldn't figure out how to add the label so figured I'd tag but not urgent whenever you have a chance. Thank you!

**Comment by jeff-dude** [comment]
hi @catherine-2 👋 

i cleaned up the code a bit -- hope it makes sense.

in the config blocks:
1. partition is not necessary on views, but rather for underlying tables (in which there are none here)
2. unique key is not necessary unless performing update statements (similarly not applicable here)
3. default materialization is view based on dbt_project file, not needed in config

inspired by the unique key idea, instead i added tests to the schema file on the unique columns.

**Review by jeff-dude — APPROVED** [review]

**Comment by catherine-2** [comment]
Thank you so much @jeff-dude ! I always learn a lot from your edits on my PRs :) super helpful - I will make sure to follow this format in the future!

**Comment by jeff-dude** [comment]
> Thank you so much @jeff-dude ! I always learn a lot from your edits on my PRs :) super helpful - I will make sure to follow this format in the future!

great to hear!

for your awareness, in the future (not sure when yet) we will be looking to change how we manage larger static files, such as these. tbd on that, no changes at this point 👍

**Pull request merged**
