### PR TITLE
Remove pepepepe1 coin from prices

### PR DESCRIPTION
**Pull request by dsalv**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by jeff-dude** [comment]
what was the issue here?

**Comment by dsalv** [comment]
This token id was removed by coinpaprika. The latest prices is from `2023-08-31 22:39`

**Comment by jeff-dude** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/duneanalytics/spellbook/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

@dsalv you have to sign this via PR comment in order to get it merged

**Comment by dsalv** [comment]
recheck

**Review by jeff-dude — CHANGES_REQUESTED** [review]

**Pull request merged**
