### PR TITLE
Uniswap V2 Trades (Arbitrum, Polygon, Optimism, Base, BNB & Avalanche) - Ready for review

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!

Thank you for taking the time to submit code in Spellbook. A few things to consider:
- If you are a first-time contributor, please sign the CLA by copy & pasting **_exactly_** what the bot mentions in PR comment
- Refer to [docs](#spellbook-contribution-docs) section below to answer questions
- Dune team will review submitted PRs as soon as possible

## Spellbook sub-projects

To prepare for Spellbook to scale in size, Dune team has started to pilot sub-projects:
- For a quick overview, see [the GH discussion on the topic](https://github.com/duneanalytics/spellbook/discussions/5238)
    - Please ask questions and continue the conversation there
- The first spell lineage to move: `tokens.erc20` and all upstream spells which help build it
    - **_Note_**: Please navigate to [tokens](https://github.com/duneanalytics/spellbook/tree/main/tokens) root directory to find tokens objects

## Spellbook contribution docs

The [docs](https://github.com/duneanalytics/spellbook/tree/main/docs) directory has been implemented to answer as many questions as possible. Please take the time to reference each `.md` file within this directory to understand how to efficiently contribute & why the repo is designed as it is 🪄

Example questions to be answered:
- What does each property in the [model config block](https://github.com/duneanalytics/spellbook/blob/main/docs/models/model_config_block.md) mean?
- What is the [CI test](https://github.com/duneanalytics/spellbook/blob/main/docs/ci_test/ci_test_overview.md) attached to PRs and how can I best utilize it?
- What are the Spellbook [best practices](https://github.com/duneanalytics/spellbook/blob/main/docs/general/best_practices.md)?

Please navigate through the [docs](https://github.com/duneanalytics/spellbook/tree/main/docs) directory to find as much info as you can.

**Note**: happy to take PRs to improve the docs, let us know 🤝

### CODE REVIEW

**Comment by henrystats** [comment]
submitted the contracts for decoding, waiting for them to get approved then I'll refresh and add seeds.

**Comment by henrystats** [comment]
@Hosuke Uniswap newly announced support of V2 on these new chains and I've submitted this pr to get them added to dex trades.

The current test fail is only on the v3 models, I think this is because I edited the seed file and added v2 data.

I put a blank push in the v3 models to see if triggering it would help but it doesn't seem like that changed anything.

Could you please help take a look? the v2 models I added are working fine along with the tests/seeds.

**Comment by henrystats** [comment]
@Hosuke the filter wasn't added for some of the V3 models and I guess it didn't cause an issue since they all had only one versions.

I've updated now and the tests are passing, this is now ready for review!

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @henrystats 

Though we encourage 1PR <-> 1chain for now.

[Sample uniswap_v2_arbitrum_base_trades]()
[Sample uniswap_v2_avalanche_c_base_trades]()
[Sample uniswap_v2_base_base_trades]()
[Sample uniswap_v2_bnb_base_trades]()
[Sample uniswap_v2_optimism_base_trades]()
[Sample uniswap_v2_polygon_base_trades]()

**Pull request merged**
