### PR TITLE
Fix blockchains property for Balancer spells

### PR DESCRIPTION
**Pull request by vegarsti**
The `blockchains` property is currently being set as `["{{blockchain}}"]` instead of the concrete blockchain for these `Balancer` spells:

- balancer_v2_arbitrum.liquidity
- balancer_v2_avalanche_c.liquidity
- balancer_v2_base.liquidity
- balancer_v2_ethereum.liquidity
- balancer_v2_gnosis.liquidity
- balancer_v2_optimism.liquidity
- balancer_v2_polygon.liquidity

This was a regression from #4960.

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
nice find!

were you able to test this? when we run `dbt compile` to build a model into sql code, typically this post-hook doesn't output (especially in dev, it's set to only run in prod)

**Comment by vegarsti** [comment]
I've verified the output of this to be correct (`dbt compile` and looking at the `manifest.json`)

**Comment by jeff-dude** [comment]
> Okay, now it's properly fixed. I've verified the output of this to be correct (`dbt compile` and looking at the `manifest.json`).
> 
> The clue was that we're inside a macro, and we already have access to the `blockchain` variable, so we don't need to escape it with curlies, we just need to use it as a variable. That way the variable is inserted correctly before the macro is expanded.
> 
> To verify, check out this branch and do this (find the area around the Optimism spell and then the final lines with the macro)
> 
> ```
> dbt compile && jq . target/manifest.json > manifest.json && rg --context 65 '"model.spellbook.balancer_v2_optimism_liquidity": \{' manifest.json | tail -n 5
> ```
> 
> outputs
> 
> ```
>           {
>             "sql": "{{ expose_spells('[\"optimism\"]',\n                        \"project\",\n                        \"balancer_v2\",\n                        '[\"stefenon\", \"viniabussafi\"]') }}",
>             "transaction": true,
>             "index": null
>           }
> ```

thank you for the extra effort here -- this is actually v helpful for all of spellbook!

fyi @aalan3 @couralex6 @Hosuke @0xRobin @hildobby @tomfutago @grkhr @MSilb7 -- if we ever use blockchain variable in the post-hook (or any really), this is a viable approach

**Comment by jeff-dude** [comment]
> > Okay, now it's properly fixed. I've verified the output of this to be correct (`dbt compile` and looking at the `manifest.json`).
> > The clue was that we're inside a macro, and we already have access to the `blockchain` variable, so we don't need to escape it with curlies, we just need to use it as a variable. That way the variable is inserted correctly before the macro is expanded.
> > To verify, check out this branch and do this (find the area around the Optimism spell and then the final lines with the macro)
> > ```
> > dbt compile && jq . target/manifest.json > manifest.json && rg --context 65 '"model.spellbook.balancer_v2_optimism_liquidity": \{' manifest.json | tail -n 5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > outputs
> > ```
> >           {
> >             "sql": "{{ expose_spells('[\"optimism\"]',\n                        \"project\",\n                        \"balancer_v2\",\n                        '[\"stefenon\", \"viniabussafi\"]') }}",
> >             "transaction": true,
> >             "index": null
> >           }
> > ```
> 
> thank you for the extra effort here -- this is actually v helpful for all of spellbook!
> 
> fyi @aalan3 @couralex6 @Hosuke @0xRobin @hildobby @tomfutago @grkhr @MSilb7 -- if we ever use blockchain variable in the post-hook (or any variable), this is a viable approach

**Pull request merged**
