### PR TITLE
Add `impossible_finance`

### PR DESCRIPTION
**Pull request by 0xKARTOD**
Link to workshop repo:
https://github.com/0xKARTOD/spellbook/tree/workshop

Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

### Transactions checks:
* [x] `impossible_finance_vesting` represents the transactions that users have sent to vesting contract

### Join logic:
* [x] if joining to base table (i.e. bsc transactions or bep20 transfers), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used `bnb_transactions` table for tracking txs that go to vesting contract  `tr.to = lower('0x6610f572057018843bD64ADCf7c47787EB7ba8B2')`
* [x] I also filtered out transactions that send only IDIA token to vesting contract `b.contract_address = lower('0x0b15Ddf19D47E6a86A56148fb4aFFFc6929BcB89')`

### CODE REVIEW

**Comment by augustog** [comment]
Hey Roman! Thanks for sharing this :) 

The PR as is looks good to merge, but begs the question: @0xKARTOD can this not be solved by sending the contract for decoding?

I see a large chunk of the logic is just decoding traces, and we'd prefer to keep that kind of logic (for performance & separation of concerns) in our decoding pipelines, and only add it to spellbook if the contract cannot be decoded for some reason.

**Comment by augustog** [comment]
Hello @0xKARTOD, I [decoded the contract you are using here](https://dune.com/queries?d=1&category=decoded_project&blockchain=bnb&namespace=impossible_finance&contract=vIDIA&blockchains=bnb). Could you check if the data from those tables can be used to cover your need here?

**Comment by jeff-dude** [comment]
closing due to inactivity -- please do reopen if/when ready

**Comment by jeff-dude** [comment]
i pushed some commits to standardize, but with this being a view, it needs to be dunesql compatible. i attempted to run dbt compile on latest commit, paste into dune and run, but it fails in a variety of ways. please do update query to be compatible on dunesql, then push here.

**Comment by jeff-dude** [comment]
i pushed some commits to standardize, but with this being a view, it needs to be dunesql compatible. i attempted to run dbt compile on latest commit, paste into dune and run, but it fails in a variety of ways. please do update query to be compatible on dunesql, then push here.

**Comment by jeff-dude** [comment]
running through old PRs, closing due to inactivity

**Pull request closed without merging**
