### PR TITLE
Update superrare trade query for use decoded table

### PR DESCRIPTION
**Pull request by phyyou**
Convert raw ethereum logs table query in superrare base trades SQL to decoding table.

while querying the ethereum.contracts table, I founded that the contract for "SuperRare: Auction House" is not available, and the contract ABI is not available also in Etherscan.

So I searched the superrare labs' GitHub repository, searched for deployed bytecode, and found that the ABIs for those contracts actually exist, and I just submitted them.

Here they are: https://github.com/superrare/pixura-contracts/blob/66b39164255d29d07e00b4ad8df206c379bf35e7/contracts/build/SuperRareAuctionHouse.json

_Contract submission:_
Screen Shot 2023-08-04 at 11 31 34 PM

### CODE REVIEW

**Comment by jeff-dude** [comment]
@phyyou thank you for the PR. we just had to raise this bug #3953 due to duplicates on this spell. i assume this change in the PR isn't related? if so, we would need to fix the bug prior to re-enabling and approving this PR.

**Comment by phyyou** [comment]
> @phyyou thank you for the PR. we just had to raise this bug #3953 due to duplicates on this spell. i assume this change in the PR isn't related? if so, we would need to fix the bug prior to re-enabling and approving this PR.

The bug was probably caused by me submitting the SuperRareMacrketAuction contract.
actually, this PR fixes duplication bug that you mentioned #3953.
this PR remove below code block for new decoded table.
```sql
union
-- Superrare Marketplace (not decoded)
    select block_time
            , block_number
            , bytearray_substring(topic1, 13, 20) AS contract_address
            , bytearray_to_uint256(bytearray_substring(data, 33, 32)) AS nft_token_id
            , bytearray_substring(topic3, 13, 20) AS seller
            , bytearray_substring(topic2, 13, 20) AS buyer
            , bytearray_to_uint256(bytearray_substring(data, 1, 32)) as price_raw
            , tx_hash
            , {{var("ETH_ERC20_ADDRESS")}}
            , index
    from {{ source('ethereum','logs') }}
    where contract_address =  0x65b49f7aee40347f5a90b714be4ef086f3fe5e2c
        and topic0 in (0x2a9d06eec42acd217a17785dbec90b8b4f01a93ecd8c127edd36bfccf239f8b6
                        ,0x5764dbcef91eb6f946584f4ea671217c686fa7e858ce4f9f42d08422b86556a9)
```

**Comment by jeff-dude** [comment]
> > @phyyou thank you for the PR. we just had to raise this bug #3953 due to duplicates on this spell. i assume this change in the PR isn't related? if so, we would need to fix the bug prior to re-enabling and approving this PR.
> 
> The bug was probably caused by me submitting the SuperRareMacrketAuction contract. actually, this PR fixes duplication bug that you mentioned #3953. this PR replace below code blocks to new decoded table
> 
> ```sql
> union
> -- Superrare Marketplace (not decoded)
>     select block_time
>             , block_number
>             , bytearray_substring(topic1, 13, 20) AS contract_address
>             , bytearray_to_uint256(bytearray_substring(data, 33, 32)) AS nft_token_id
>             , bytearray_substring(topic3, 13, 20) AS seller
>             , bytearray_substring(topic2, 13, 20) AS buyer
>             , bytearray_to_uint256(bytearray_substring(data, 1, 32)) as price_raw
>             , tx_hash
>             , {{var("ETH_ERC20_ADDRESS")}}
>             , index
>     from {{ source('ethereum','logs') }}
>     where contract_address =  0x65b49f7aee40347f5a90b714be4ef086f3fe5e2c
>         and topic0 in (0x2a9d06eec42acd217a17785dbec90b8b4f01a93ecd8c127edd36bfccf239f8b6
>                         ,0x5764dbcef91eb6f946584f4ea671217c686fa7e858ce4f9f42d08422b86556a9)
> ```

nice find! thanks for digging for the ABIs and getting decoded tables.

i went ahead and removed the `prod_exclude` flag so that we can see this run. with that tag, the gh action CI test didn't actually run anything, since we exclude those models.

**Review by jeff-dude — APPROVED** [review]
thanks again!

fyi @0xRobin for review upon return

**Comment by 0xRobin** [comment]
thanks for taking this on @phyyou!! :+1:

**Pull request merged**
