### PR TITLE
Adding Maverick v2 Ethereum deployment to Dex Trades

### PR DESCRIPTION
**Pull request by darvinrio**
### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by Hosuke** [comment]
This PR may have some similar contents with #6406.

**Comment by darvinrio** [comment]
> This PR may have some similar contents with #6406.

whoops yeah. 
i was waiting for initial checks, since it mentioned separate branches for separate chains 😁  

you can close this if #6406 passes.

**Comment by Hosuke** [comment]
> > This PR may have some similar contents with #6406.
> 
> whoops yeah. i was waiting for initial checks, since it mentioned separate branches for separate chains 😁
> 
> you can close this if #6406 passes.

Let's wait for the #6406 merged first.

**Comment by Hosuke** [comment]
Hi @darvinrio, once we update this PR with the latest main branch, we can see if there is anything still missing in the current spellbook.

**Comment by darvinrio** [comment]
> Hi @darvinrio, once we update this PR with the latest main branch, we can see if there is anything still need to add into main branch in this PR.

hey @Hosuke 
I checked this out, there is nothing else to add, hence closing this PR

**Pull request closed without merging**
