### PR TITLE
Make nft.fees, nft.events and nft.mints Trino compatible

### PR DESCRIPTION
**Pull request by belen-pruvost**

### CODE REVIEW

**Comment by belen-pruvost** [comment]
I'm still building these models locally. As expected, it takes forever.

A side note: if we merge this in one piece, we may want to treat the magiceden_solana incremental update separately as per today's learning 😄 (cc @jeff-dude @soispoke @dot2dotseurat)

**Comment by belen-pruvost** [comment]
I've built all these models locally, and I'm able to query them under my schema on both databricks and trino.

**Comment by belen-pruvost** [comment]
- `amount_raw` has always been casted to decimal on the trino compatibility transformation, because so has `number_of_items`
- `platform_fee_amount_raw` and `royalty_fee_amount_raw` have always been casted to double as part of this process, to follow what we have on other fee fields without rounding them

To choose the precision (and hence the type) I searched each field from the base table to the upper level view that I try to fix, and also search on the repo for ` as <field_name>` to see if there were other explicit castings, in order to keep them consistent

**Comment by 0xRobin** [comment]
Ok, @augustog we should probably change the raw fee values to decimal to be in line with amount_raw? (but not in this PR)

**Comment by jeff-dude** [comment]
> Ok, @augustog we should probably change the raw fee values to decimal to be in line with amount_raw? (but not in this PR)

this is a good point. it may make sense to document each of the nft sector objects (`nft.trades`, `nft.events`, etc) in terms of intended schema and their respective data points. that'll make it clear for us all to see. is that something @0xRobin  is comfortable with doing and @augustog supporting?

**Review by jeff-dude — APPROVED** [review]
this PR will have prod working hard, i'd recommend we merge early morning EST (or you guys can european time, but would suggest doing it with plenty of time to monitor/support).

**Comment by jeff-dude** [comment]
> this PR will have prod working hard, i'd recommend we merge early morning EST (or you guys can european time, but would suggest doing it with plenty of time to monitor/support).

we should also merge #2289 at the same time, as it's another nft events base child model

**Pull request merged**
