### PR TITLE
[READY TO REVIEW][MINOR] Fix price native token of avax and polygon

### PR DESCRIPTION
**Pull request by nhd98z**
```
select * from kyberswap_aggregator.trades where block_time > TIMESTAMP '2023-08-24 00:00' and maker = 0x2f2dd99235cb728fc79af575f1325eaa270f0c99 order by amount_usd desc;
```

Native token in polygon and avalanche currently count in eth price, should be matic price and avax price.

### CODE REVIEW

**Comment by nhd98z** [comment]
@Hosuke just a minor, please check soon. Thanks so much.

**Comment by nhd98z** [comment]
@Hosuke I got the error which I never see before `Table 'hive.test_data.dex_aggregator_seed' does not exist`. Did you guys update something?

**Comment by Hosuke** [comment]
> @Hosuke I got the error which I never see before `Table 'hive.test_data.dex_aggregator_seed' does not exist`. Did you guys update something?

This may be solved by refreshing the seed

**Review by jeff-dude — APPROVED** [review]
good catch!

**Pull request merged**
