### PR TITLE
seperate addresses and transactions

### PR DESCRIPTION
**Pull request by andrewhong5297**
Brief comments on the purpose of your changes:

@hildobby and I were discussing how to organize labels with transactions better and decided to separate `addresses` and `transactions` as their own label groups.

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by hildobby** [comment]
I would probably move the `labels.addresses` and `labels.transactions` tables into the root `labels` folder instead of within their subfolder @andrewhong5297, otherwise LGTM!

**Comment by andrewhong5297** [comment]
> I would probably move the `labels.addresses` and `labels.transactions` tables into the root `labels` folder instead of within their subfolder @andrewhong5297, otherwise LGTM!

ah interesting - yeah that actually makes a lot of sense given our other folder structures, moved lol!

**Comment by andrewhong5297** [comment]
> the dunesql check run step in the ci run flagged an issue:
> 
> ```
> 
> line 1:15: Failed analyzing stored view 'delta_prod.test_schema.git_7e1f905b_cow_protocol_tx_hash_labels_treasury_management_ethereum': line 17:19: Value expression and result of subquery must be of the same type: row(varbinary) vs row(address varchar) at line 1, position 15
> 
> ```
> 
> can you double check to see if this error message is valid? you can reproduce by trying to query the table with the dunesql engine directly since its been migrated over

This is not the right place to raise this, try creating a new issue for it.

**Comment by andrewhong5297** [comment]
Fyi @Hosuke I fixed the lens poster freq issue and added more tests in this file

**Comment by Hosuke** [comment]
> Fyi @Hosuke I fixed the lens poster freq issue and added more tests in this file

Noted, I will tag the PR affected here.

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
