### PR TITLE
Add creator_address to contracts_contract_creator_address_list.sql

### PR DESCRIPTION
**Pull request by Hirangi5**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by Hirangi5** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Hirangi5** [comment]
recheck

**Comment by jeff-dude** [comment]
based on logs, this is failing the unique test
https://github.com/duneanalytics/spellbook/actions/runs/7897557459/job/21553344493?pr=5338#step:12:21

please remove duplicates and rerun CI tests

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
thank you for PR, quick fix & welcome to spellbook!

**Pull request merged**
