### PR TITLE
pipenv lock

### PR DESCRIPTION
**Pull request by 0xRobin**
generate new lockfile after the update to dbt 1.8

steps used:
```
pipenv clean
pipenv install
pipenv lock
```

advised steps to update your local env (after this is merged)
```
pipenv clean
pipenv sync
```
```
dbt clean
dbt deps
```

### CODE REVIEW

**Comment by 0xBoxer** [comment]
will all our wizards have to do this as well?

**Review by 0xBoxer — APPROVED** [review]
approving in case you need that for merge

**Comment by 0xRobin** [comment]
> will all our wizards have to do this as well?

not needed but definitely advised, though you should be able to compile the project with older dbt versions just fine. 
We should probably do a small service announcement in a Gtihub discussion tomorrow.

**Review by jeff-dude — APPROVED** [review]
works for me, feel free to merge / post in discussions when you are ready

**Comment by 0xBoxer** [comment]
Due to a dbt version change, you need to merge main into your branch before the Github action runner runs successfully again.

**Pull request merged**
