### PR TITLE
upstream solana gas fees spells: move to solana subproject

### PR DESCRIPTION
**Pull request by jeff-dude**

### CODE REVIEW

**Comment by 0xBoxer** [comment]
ready whenever you are

**Review by 0xBoxer — APPROVED** [review]

**Comment by jeff-dude** [comment]
> ready whenever you are

if we do this in multiple steps, i will need to update your leftover spells in hourly to use source rather than ref here. then when we move those too, we will have to revert back to refs

**Comment by 0xBoxer** [comment]
aren't those all prod excluded?

I can change my refs to sources or move my project to solana folder in my branch

**Comment by 0xBoxer** [comment]
we can also do it all at once, however you prefer

**Comment by jeff-dude** [comment]
okay, let's move full lineage here. then you current working branch will need to adapt that we have moved them to solana.

**Comment by 0xBoxer** [comment]
yep I'll merge main after this is done and move to solana in my branch

**Comment by jeff-dude** [comment]
both projects are compiling = this is good for me. i will turn off modified on each and let it rip. we are slightly blocked on hourly job from another model failing, so i will need to resolve that first

**Comment by jeff-dude** [comment]
> yep I'll merge main after this is done and move to solana in my branch

if you don't want to wait, you could also merge this feature branch into yours to expedite the main branch merge and get a headstart. then main should be clean.

**Pull request merged**
