### PR TITLE
add seaport on base

### PR DESCRIPTION
**Pull request by BroderickBonelli**
### Adding Seaport on Base

Outline of changes below:
- add opensea models for Seaport on Base
- add source table needed for Base model
- add to nft.trades

@jeff-dude could I please get a review on this asap? Apologies for the extra PR, this was included in #5673 but not carried over to #5672. Thanks so much!

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
thanks for quick follow up.
fyi @0xRobin for opensea / seaport cleanup effort 🙏

**Comment by jeff-dude** [comment]
canceling CI. no need to merge in main, i'll handle this in a bit.

**Review by 0xRobin — APPROVED** [review]
:heavy_check_mark: looks indeed good to merge @jeff-dude

cc: @MSilb7

**Comment by jeff-dude** [comment]
prod is busy with a large batch of solana spells, which could take a bit. i'll get this in after.

**Comment by BroderickBonelli** [comment]
thanks both!

**Pull request merged**
