### PR TITLE
Added odos dex to dex.trades

### PR DESCRIPTION
**Pull request by ARDev097**
Added trade data of odos dex aggregator on optimism.

### CODE REVIEW

**Comment by ARDev097** [comment]
Hello @Hosuke,

In this PR, while running the checks, the operation gets canceled automatically. Please check it and let me know if anything is required from my end to resolve this.

**Comment by Hosuke** [comment]
> Hello @Hosuke,
> 
> In this PR, while running the checks, the operation gets canceled automatically. Please check it and let me know if anything is required from my end to resolve this.

It may be a CI service issue, it will be recovered soon.
Thank you for your patience.

**Comment by Hosuke** [comment]
Seems a duped PR with #5170

**Comment by Hosuke** [comment]
Hi @ARDev097,
which PR do you think we should continue reviewing on odos.trades?
#5163 or #5170 , as they both contain implementations of odos.trades.

**Comment by ARDev097** [comment]
Hello @Hosuke,
We can go with PR #5170 .

**Pull request closed without merging**
