### PR TITLE
feat: add Baseswap spellbook

### PR DESCRIPTION
**Pull request by whalehunting**
Still WIP for now, will change status away from `Draft` when it's done!

This PR adds a spellbook for the Baseswap DEX on Base + integrates it into the `dex.trades` spellbook.

### CODE REVIEW

**Comment by whalehunting** [comment]
recheck

**Comment by whalehunting** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jeff-dude** [comment]
@whalehunting thank you for initiating a contribution to spellbook 🪄 

do you need any assistance here, or just waiting to find time to finalize?

**Comment by whalehunting** [comment]
hey @jeff-dude i did not find time yet to continue working on it, so feel free to assist :) otherwise i would continue on it when i find some time!

**Comment by jeff-dude** [comment]
> hey @jeff-dude i did not find time yet to continue working on it, so feel free to assist :) otherwise i would continue on it when i find some time! I do have some WIP files on my local branch, should i push them?

take your time, no rush! just wanted to confirm. you can save the commits until you are ready

**Comment by jeff-dude** [comment]
closing due to inactivity, feel free to reopen as needed 🤝

**Pull request closed without merging**
