### PR TITLE
Add airswap to dex trades

### PR DESCRIPTION
**Pull request by Hosuke**
Brief comments on the purpose of your changes:
Add airswap to dex trades

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test （Currently I manually test the compiled sql）
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)
* [x] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by soispoke — CHANGES_REQUESTED** [review]
Thanks a lot @Hosuke for your really high quality submission, there are two things left:
- add your `dex_ethereum_airswap_trades` model to the meta table `dex.trades`
- add the airswap project in the `dbt_project.yml` file

**Comment by Hosuke** [comment]
> Thanks a lot @Hosuke for your really high quality submission, there are two things left:
> 
> * add your `dex_ethereum_airswap_trades` model to the meta table `dex.trades`
> * add the airswap project in the `dbt_project.yml` file

Hi sir, one more question to make sure I understand the comment properly
For adding the dex_ethereum_airswap_trades to the meta table `dex.trades`,
does it means, adding an union operation in /models/dex/dex_trades.sql.
Something looks like

```
SELECT *
FROM
    (
        SELECT
                ...
        FROM {{ ref('uniswap_trades') }}
        
        UNION
        
        SELECT
                ...
        FROM {{ ref('curvefi_ethereum_trades') }}

        UNION

        SELECT
                ...
        FROM {{ ref('dex_ethereum_airswap_trades') }}
)
```

**Comment by soispoke** [comment]
@Hosuke yes exactly !

**Comment by soispoke** [comment]
great, everything lgtm now, thanks @Hosuke !

**Review by soispoke — APPROVED** [review]

**Comment by jeff-dude** [comment]
@Hosuke another step we're trying to take in adding to dex trades is manually adding tx's to our ```dex_trades_seed``` file, as seen here on recent uniswap v3 PR:
https://github.com/duneanalytics/spellbook/pull/1663/files#diff-09c1b2e11432d6907b7f05a0e73f46488de55e9f905df8d54602cb7173fdba5f

for that dex, i went to their app and found the analytics page, grab 5 tx's and the link to etherscan, then fill out the info in the seed file.

once that is filled, you can add a test to the dex schema file, like so for uniswap:
https://github.com/duneanalytics/spellbook/blob/main/models/uniswap/ethereum/uniswap_ethereum_schema.yml#L67

this calls a generic test that is parameterized based on the schema file. you shouldn't have to touch the test. the end goal is to ensure the query is truly returning the token_bought value into the correct field. the test should return no results.

let me know if this makes sense & you're willing to try adding

**Comment by Hosuke** [comment]
> @Hosuke another step we're trying to take in adding to dex trades is manually adding tx's to our `dex_trades_seed` file, as seen here on recent uniswap v3 PR: https://github.com/duneanalytics/spellbook/pull/1663/files#diff-09c1b2e11432d6907b7f05a0e73f46488de55e9f905df8d54602cb7173fdba5f
> 
> for that dex, i went to their app and found the analytics page, grab 5 tx's and the link to etherscan, then fill out the info in the seed file.
> 
> once that is filled, you can add a test to the dex schema file, like so for uniswap: https://github.com/duneanalytics/spellbook/blob/main/models/uniswap/ethereum/uniswap_ethereum_schema.yml#L67
> 
> this calls a generic test that is parameterized based on the schema file. you shouldn't have to touch the test. the end goal is to ensure the query is truly returning the token_bought value into the correct field. the test should return no results.
> 
> let me know if this makes sense & you're willing to try adding

Thanks a lot, I will follow the steps and learn adding tests.

**Pull request merged**
