### PR TITLE
[CoW Protocol] Add schema for raw_app_data

### PR DESCRIPTION
**Pull request by bh2smith**
This content is planned to be streamed into community sources. I added it to the `cow_protocol_ethereum_schema`, and not sure if anything else needs to be defined. Furthermore, we had to rename trade.app_data to trades.app_hash to be in alignment with the actual "app_data" --> which will be in the `content` column of this new table.

I was hoping to specify types and nullability here like this:

```sql
cow_protocol.raw_app_data (
    first_seen_block  long   NOT NULL,
    hash              string UNIQUE & NOT NULL,  -- bytea (bytes32 - similar to txHash)
    content           json   NULLABLE,
);
``` 
but I am not sure how.

cc @dsalv - as we have been in communication about this.

### CODE REVIEW

**Comment by jeff-dude** [comment]
i'll let the other reviewers look closely, but community data being ingested outside of spellbook should likely be defined as a source in the source file, rather than schema file (which would assume a model being built to match it)

**Comment by bh2smith** [comment]
Yea thanks @jeff-dude - I will look around the project and try to find strings matching the names of the other community sources to adapt from.

Also, for testing purposes, I have generated our "genesis seed data file"

Here is a snippet, can attach a ZIP file with the fill content

```
{"app_hash": "0xd68a5c78d920efc8e8c4785baadb0d9c64d21ea88c22592631d6135fdba6fa94", "first_seen_block": 13901767, "content": {"version": "0.1.0", "appCode": "CowSwap", "metadata": {"referrer": {"address": "0xe47569e0eF600Bb7626E3E309aedCfA7A3D7F30A", "version": "0.1.0"}}}}
{"app_hash": "0x2757c919984771aaf288c738f6507886b9e218baeb199bbe6639c707742868ee", "first_seen_block": 13793465, "content": {"version": "0.1.0", "appCode": "CowSwap", "metadata": {"referrer": {"address": "0x282bb01Bda10456F022Af337A6E00195A41C2782", "version": "0.1.0"}}}}
{"app_hash": "0xc80a7dcd584a25427ae0cddc53558076c156331a29e666a45cd6cef9867239cd", "first_seen_block": 15323000, "content": {"appCode": "CowSwap", "environment": "production", "metadata": {"referrer": {"address": "0xAB850Ba6dB882ae21F09cDE30C5C1B13A6007979", "version": "0.1.0"}, "quote": {"slippageBips": "50", "version": "0.2.0"}}, "version": "0.4.0"}}
{"app_hash": "0xd3ea00a1a2148a66a6a7371fefb264eb136a66aa176870c0cf3f1f758c96a9ad", "first_seen_block": 14582881, "content": {"version": "0.1.0", "appCode": "CowSwap", "metadata": {"referrer": {"address": "0x9717682d7156088f97F65283fDD75f738E3A65ed", "version": "0.1.0"}}}}
{"app_hash": "0xbc9b6f6a7b51bfca4eab7ff60c4278591d5f06f464ef7269e61226750a17354e", "first_seen_block": 13902449, "content": {"version": "0.1.0", "appCode": "CowSwap", "metadata": {"referrer": {"address": "0x18Ef69a9da3B7983AD353Ebf7C95De76Fb5df22C", "version": "0.1.0"}}}}
{"app_hash": "0xc583fdabfcdd4cabca6913d6e8584a01b91330c34c6c850ce8517d160bb1b9f1", "first_seen_block": 13614571, "content": {"appCode": "CowSwap", "metadata": {"referrer": {"address": "0x87CfDc4BFAe569088bC1bCc0DD3C19f53Da54193", "version": "0.1.0"}}, "version": "0.1.0"}}
{"app_hash": "0xe76f9ab1c916a73e32bae92e6b5e660bbdaa918192151fb6b876da2cf00d2713", "first_seen_block": 13784118, "content": {"version": "0.1.0", "appCode": "CowSwap", "metadata": {"referrer": {"address": "0xB534DD17fdbC1459f4788fB9Dc9170D83B0cCF65", "version": "0.1.0"}}}}
{"app_hash": "0x6f48b19b09b75adc83e56c92e2e9bfba53d6719c4d5b7aa6394affb0de772614", "first_seen_block": 14799691, "content": {"version": "0.1.0", "appCode": "CowSwap", "metadata": {"referrer": {"address": "0x30730b7A86B210f9B260d33FC90979644EBFCb89", "version": "0.1.0"}}}}
{"app_hash": "0x22906658b5f23259c450831b85d4e5940014febc3f7482cde05dffa60e1750e3", "first_seen_block": 15906747, "content": {"appCode": "CoW Swap", "environment": "production", "metadata": {"referrer": {"address": "0xecbA201484cC39C7cAFdDCC6726C7fcc149CCFba", "version": "0.1.0"}, "quote": {"slippageBips": "50", "version": "0.2.0"}}, "version": "0.4.0"}}
```

**Comment by bh2smith** [comment]
> Yea thanks @jeff-dude - I will look around the project and try to find strings matching the names of the other community sources to adapt from. 

Update - I can not find anything within this project pertaining to the schemas of the existing community sources.

**Comment by dsalv** [comment]
> This content is planned to be streamed into community sources. I added it to the `cow_protocol_ethereum_schema`, and not sure if anything else needs to be defined. Furthermore, we had to rename trade.app_data to trades.app_hash to be in alignment with the actual "app_data" --> which will be in the `content` column of this new table.
> 
> I was hoping to specify types and nullability here like this:
> 
> ```sql
> cow_protocol.raw_app_data (
>     first_seen_block  long   NOT NULL,
>     hash              string UNIQUE & NOT NULL,  -- bytea (bytes32 - similar to txHash)
>     content           json   NULLABLE,
> );
> ```
> 
> but I am not sure how.
> 
> cc @dsalv - as we have been in communication about this.

Thanks for opening this PR @bh2smith. It looks like we will keep this PR on hold. Looks like this change needs an additional feature in our system. Sorry for the inconvenience 

I will create the table the old way. But we can keep this PR, and reopen it once additional features are implemented

**Comment by jeff-dude** [comment]
closing this for now, as i think i saw other initiatives for community data integration outside of spellbook

**Pull request closed without merging**
