### PR TITLE
Full rewrite of LooksRare abstraction

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:

When an aggregator is used, it often takes the place of buyer or seller in event data, this PR should fix this issue.

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by hildobby** [comment]
⚠️ MANUAL TIMEOUT CHANGE TO BE REMOVED BEFORE MERGING ⚠️

**Comment by hildobby** [comment]
Working on a full rewrite that should be a lot more efficient for LooksRare and fixes a lot of bugs, please don't touch this PR for now

**Comment by hildobby** [comment]
Just rewrote the entire LooksRare abstraction and it should:
- be more optimised
- fix wrong fees (was hardcoded to 2%, now changes based on the "strategy" as LR calls it in their contracts)
- Detect private sales
- get royalties from call data as it was before but a join condition had it missing some, that's fixed
- Remove duplicates

**Comment by hildobby** [comment]
Here is a new one, it's failing on a single trade with a token that is technically both an ERC721 and an ERC1155, gonna edit `nft_ethereum.transfers` in a separate PR to default to ERC721 when that's the case I guess
https://twitter.com/hildobby_/status/1595506161649913863?s=20&t=k4UHoqTPGklrCDCkocDCpQ

**Comment by soispoke** [comment]
@hildobby thanks, everything lgtm!

**Review by soispoke — APPROVED** [review]

**Pull request merged**
