### PR TITLE
Bright Moments collection list updates

### PR DESCRIPTION
**Pull request by catherine-2**
### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [X] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** Adding all of the new collections to the Bright Moments metadata table since I last updated it.

---

Thank you for your contribution!

### CODE REVIEW

**Comment by catherine-2** [comment]
Hi! This should hopefully be an easy review - just adding updated static metadata.

It's been awhile since I made an PR and I'm not sure how to fix the CLA failure in order to sign the new agreement? Thank you!

**Comment by catherine-2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by catherine-2** [comment]
Recheck

**Comment by catherine-2** [comment]
Recheck

**Comment by catherine-2** [comment]
This is ready for review and merge! Thank you!

**Review by jeff-dude — APPROVED** [review]
welcome back 🫡

**Comment by catherine-2** [comment]
> welcome back 🫡

Thank you!! Excited to be back ❤️

**Comment by catherine-2** [comment]
Made two tiny fixes as I was triple checking the PR. Ready to merge again. Thank you!

**Pull request merged**
