### PR TITLE
Table reservoir.tokens use windowing function instead of self join

### PR DESCRIPTION
**Pull request by helanto**
An attempt to change the view definition of table `reservoir.tokens` to use windowing functions instead of self join

### CODE REVIEW

**Comment by helanto** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by helanto** [comment]
recheck

**Review by hawkaa — APPROVED** [review]

**Comment by hawkaa** [comment]
Are there anyone in Reservoir that should be tagged in this PR? @dsalv ?

**Comment by dsalv** [comment]
> Are there anyone in Reservoir that should be tagged in this PR? @dsalv ?

We can share this PR in telegram

**Review by dsalv — APPROVED** [review]
Amazing!

**Comment by jeff-dude** [comment]
i'm going to test a quick change

**Review by jeff-dude — APPROVED** [review]
all good 🙏

**Pull request merged**
