### PR TITLE
Add DirectRouter to Paraswap.trade

### PR DESCRIPTION
**Pull request by BennyFeng**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by BennyFeng** [comment]
> 10:37:58  Database Error in model paraswap_ethereum_airdrop_claims (models/paraswap/ethereum/paraswap_ethereum_airdrop_claims.sql)
10:37:58    TrinoUserError(type=USER_ERROR, name=SCHEMA_NOT_FOUND, message="line 13:10: Schema 'dex' does not exist", query_id=20230719_103659_09332_6tppc)
10:37:58    compiled Code at target/run/spellbook/models/paraswap/ethereum/paraswap_ethereum_airdrop_claims.sql

@jeff-dude I'm not sure what happened about it, but the `{{ ref('dex_prices') }}` couldn't be found in `paraswap_ethereum_airdrop_claims.sql`. Could you please take a look if you get a moment.

**Comment by BennyFeng** [comment]
> 12:10:35  Database Error in model paraswap_v4_ethereum_trades (models/paraswap/ethereum/paraswap_v4_ethereum_trades.sql)
12:10:35    TrinoQueryError(type=INSUFFICIENT_RESOURCES, name=EXCEEDED_GLOBAL_MEMORY_LIMIT, message="Query exceeded distributed user memory limit of 574.46GB", query_id=20230719_120928_11589_6tppc)

@jeff-dude @0xRobin Also got a new error.

**Comment by jeff-dude** [comment]
> > 10:37:58  Database Error in model paraswap_ethereum_airdrop_claims (models/paraswap/ethereum/paraswap_ethereum_airdrop_claims.sql)
> > 10:37:58    TrinoUserError(type=USER_ERROR, name=SCHEMA_NOT_FOUND, message="line 13:10: Schema 'dex' does not exist", query_id=20230719_103659_09332_6tppc)
> > 10:37:58    compiled Code at target/run/spellbook/models/paraswap/ethereum/paraswap_ethereum_airdrop_claims.sql
> 
> @jeff-dude I'm not sure what happened about it, but the `{{ ref('dex_prices') }}` couldn't be found in `paraswap_ethereum_airdrop_claims.sql`. Could you please take a look if you get a moment.

`dex` schema isn't fully migrated yet, so if your spell relies on it, then the migration will have to wait until ready

**Comment by jeff-dude** [comment]
> > 12:10:35  Database Error in model paraswap_v4_ethereum_trades (models/paraswap/ethereum/paraswap_v4_ethereum_trades.sql)
> > 12:10:35    TrinoQueryError(type=INSUFFICIENT_RESOURCES, name=EXCEEDED_GLOBAL_MEMORY_LIMIT, message="Query exceeded distributed user memory limit of 574.46GB", query_id=20230719_120928_11589_6tppc)
> 
> @jeff-dude @0xRobin Also got a new error. Could you please give some suggestions for this? Much appreciate!

interesting, it must be reading a lot of data. can you double check the query to ensure it's not writing joins incorrectly and blowing up the row counts? maybe compile the query, paste on dune app, wrap in CTE and get some counts of full history run to see counts?

if that all looks good, we may need to engage our dunesql team to look at the joins and see where memory error comes from

**Comment by jeff-dude** [comment]
hi @BennyFeng -- i've pushed some commits to try and get this PR finalized. do you want to review and take it from here?

i re-enabled the seed tests. it looks like they failed on first try here. we'll have to start by debugging those. if you haven't done that before, you can do:
- run `dbt compile`
- grab the output test query from `target/models/paraswap/.../schema/` directory (not exact but general path for each blockchain / spell)
- change the `from` and `join` tables to CI logs output, i.e. `test_schema.git_dunesql_0e616306_dex_aggregator_seed` and `test_schema.git_dunesql_0e616306_paraswap_v4_ethereum_trades`
  - please note, we have automated process to drop CI tables built every 24 hours, so these specific ones i note here may be deleted at the time you see. simply re-run CI to build new test tables to put into query


here is the ethereum v4 test query from those steps, notice it returns 15 results due to test failures for model missing token bought addresses and also tx_hash values missing in the model compared to what seed has:
```
with
  matched_records as (
    select
      seed.block_date as seed_block_date,
      model_sample.block_date as model_block_date,
      seed.blockchain as seed_blockchain,
      model_sample.blockchain as model_blockchain,
      seed.project as seed_project,
      model_sample.project as model_project,
      seed.version as seed_version,
      model_sample.version as model_version,
      seed.tx_hash as seed_tx_hash,
      model_sample.tx_hash as model_tx_hash,
      seed.evt_index as seed_evt_index,
      model_sample.evt_index as model_evt_index,
      seed.trace_address as seed_trace_address,
      model_sample.trace_address as model_trace_address,
      seed.token_bought_address as seed_token_bought_address,
      model_sample.token_bought_address as model_token_bought_address,
      seed.token_sold_address as seed_token_sold_address,
      model_sample.token_sold_address as model_token_sold_address
    from
      test_schema.git_dunesql_0e616306_dex_aggregator_seed seed
      left join (
        select
          model.block_date,
          model.blockchain,
          model.project,
          model.version,
          model.tx_hash,
          model.evt_index,
          model.trace_address,
          model.token_bought_address,
          model.token_sold_address
        from
          test_schema.git_dunesql_0e616306_dex_aggregator_seed seed
          inner join test_schema.git_dunesql_0e616306_paraswap_v4_ethereum_trades model ON 1 = 1
          AND seed.block_date = model.block_date
          AND seed.blockchain = model.blockchain
          AND seed.project = model.project
          AND seed.version = model.version
          AND seed.tx_hash = model.tx_hash
          AND seed.evt_index = model.evt_index
          AND COALESCE(
            CAST(
              split(seed.trace_address, ',') as array < bigint >
            ),
            ARRAY[]
          ) = model.trace_address
      ) model_sample ON 1 = 1
      AND seed.block_date = model_sample.block_date
      AND seed.blockchain = model_sample.blockchain
      AND seed.project = model_sample.project
      AND seed.version = model_sample.version
      AND seed.tx_hash = model_sample.tx_hash
      AND seed.evt_index = model_sample.evt_index
      AND COALESCE(
        CAST(
          split(seed.trace_address, ',') as array < bigint >
        ),
        ARRAY[]
      ) = model_sample.trace_address
    WHERE
      1 = 1
      AND seed.blockchain = 'ethereum'
      AND seed.project = 'paraswap'
      AND seed.version = '4'
  ),
  -- check if the matching columns return singular results
  matching_count_test as (
    select
      'matched records count' as test_description,
      -- these are cast to varchar to unify column types, note this is only for displaying them in the test results
      cast(count(model_block_date) as varchar) as result_model,
      cast(1 as varchar) as expected_seed,
      (count(model_block_date) = 1) as equality_check,
      seed_block_date as block_date,
      seed_blockchain as blockchain,
      seed_project as project,
      seed_version as version,
      seed_tx_hash as tx_hash,
      seed_evt_index as evt_index,
      seed_trace_address as trace_address
    from
      matched_records
    GROUP BY
      seed_block_date,
      seed_blockchain,
      seed_project,
      seed_version,
      seed_tx_hash,
      seed_evt_index,
      seed_trace_address
  ),
  equality_tests as (
    select
      'equality test: token_bought_address' as test_description,
      -- these are cast to varchar to unify column types, note this is only for displaying them in the test results
      cast(model_token_bought_address as varchar) as result_model,
      cast(seed_token_bought_address as varchar) as expected_seed,
      (
        model_token_bought_address = seed_token_bought_address
      ) as equality_check,
      seed_block_date as block_date,
      seed_blockchain as blockchain,
      seed_project as project,
      seed_version as version,
      seed_tx_hash as tx_hash,
      seed_evt_index as evt_index,
      seed_trace_address as trace_address
    from
      matched_records
    UNION ALL
    select
      'equality test: token_sold_address' as test_description,
      -- these are cast to varchar to unify column types, note this is only for displaying them in the test results
      cast(model_token_sold_address as varchar) as result_model,
      cast(seed_token_sold_address as varchar) as expected_seed,
      (
        model_token_sold_address = seed_token_sold_address
      ) as equality_check,
      seed_block_date as block_date,
      seed_blockchain as blockchain,
      seed_project as project,
      seed_version as version,
      seed_tx_hash as tx_hash,
      seed_evt_index as evt_index,
      seed_trace_address as trace_address
    from
      matched_records
  )
select
  *
from
  (
    select
      *
    from
      matching_count_test
    union all
    select
      *
    from
      equality_tests
  ) all
  -- equality check can be null so we have to check explicitly for nulls
where
  equality_check is distinct
from
  true
```

**Comment by BennyFeng** [comment]
> hi @BennyFeng -- i've pushed some commits to try and get this PR finalized. do you want to review and take it from here?
> 
> i re-enabled the seed tests. it looks like they failed on first try here. we'll have to start by debugging those. if you haven't done that before, you can do:
> - run `dbt compile`
> - grab the output test query from `target/models/paraswap/.../schema/` directory (not exact but general path for each blockchain / spell)
> - change the `from` and `join` tables to CI logs output, i.e. `test_schema.git_dunesql_0e616306_dex_aggregator_seed` and `test_schema.git_dunesql_0e616306_paraswap_v4_ethereum_trades`
>   - please note, we have automated process to drop CI tables built every 24 hours, so these specific ones i note here may be deleted at the time you see. simply re-run CI to build new test tables to put into query
> 
> 
> here is the ethereum v4 test query from those steps, notice it returns 15 results due to test failures for model missing token bought addresses and also tx_hash values missing in the model compared to what seed has:
> ```
> with
>   matched_records as (
>     select
>       seed.block_date as seed_block_date,
>       model_sample.block_date as model_block_date,
>       seed.blockchain as seed_blockchain,
>       model_sample.blockchain as model_blockchain,
>       seed.project as seed_project,
>       model_sample.project as model_project,
>       seed.version as seed_version,
>       model_sample.version as model_version,
>       seed.tx_hash as seed_tx_hash,
>       model_sample.tx_hash as model_tx_hash,
>       seed.evt_index as seed_evt_index,
>       model_sample.evt_index as model_evt_index,
>       seed.trace_address as seed_trace_address,
>       model_sample.trace_address as model_trace_address,
>       seed.token_bought_address as seed_token_bought_address,
>       model_sample.token_bought_address as model_token_bought_address,
>       seed.token_sold_address as seed_token_sold_address,
>       model_sample.token_sold_address as model_token_sold_address
>     from
>       test_schema.git_dunesql_0e616306_dex_aggregator_seed seed
>       left join (
>         select
>           model.block_date,
>           model.blockchain,
>           model.project,
>           model.version,
>           model.tx_hash,
>           model.evt_index,
>           model.trace_address,
>           model.token_bought_address,
>           model.token_sold_address
>         from
>           test_schema.git_dunesql_0e616306_dex_aggregator_seed seed
>           inner join test_schema.git_dunesql_0e616306_paraswap_v4_ethereum_trades model ON 1 = 1
>           AND seed.block_date = model.block_date
>           AND seed.blockchain = model.blockchain
>           AND seed.project = model.project
>           AND seed.version = model.version
>           AND seed.tx_hash = model.tx_hash
>           AND seed.evt_index = model.evt_index
>           AND COALESCE(
>             CAST(
>               split(seed.trace_address, ',') as array < bigint >
>             ),
>             ARRAY[]
>           ) = model.trace_address
>       ) model_sample ON 1 = 1
>       AND seed.block_date = model_sample.block_date
>       AND seed.blockchain = model_sample.blockchain
>       AND seed.project = model_sample.project
>       AND seed.version = model_sample.version
>       AND seed.tx_hash = model_sample.tx_hash
>       AND seed.evt_index = model_sample.evt_index
>       AND COALESCE(
>         CAST(
>           split(seed.trace_address, ',') as array < bigint >
>         ),
>         ARRAY[]
>       ) = model_sample.trace_address
>     WHERE
>       1 = 1
>       AND seed.blockchain = 'ethereum'
>       AND seed.project = 'paraswap'
>       AND seed.version = '4'
>   ),
>   -- check if the matching columns return singular results
>   matching_count_test as (
>     select
>       'matched records count' as test_description,
>       -- these are cast to varchar to unify column types, note this is only for displaying them in the test results
>       cast(count(model_block_date) as varchar) as result_model,
>       cast(1 as varchar) as expected_seed,
>       (count(model_block_date) = 1) as equality_check,
>       seed_block_date as block_date,
>       seed_blockchain as blockchain,
>       seed_project as project,
>       seed_version as version,
>       seed_tx_hash as tx_hash,
>       seed_evt_index as evt_index,
>       seed_trace_address as trace_address
>     from
>       matched_records
>     GROUP BY
>       seed_block_date,
>       seed_blockchain,
>       seed_project,
>       seed_version,
>       seed_tx_hash,
>       seed_evt_index,
>       seed_trace_address
>   ),
>   equality_tests as (
>     select
>       'equality test: token_bought_address' as test_description,
>       -- these are cast to varchar to unify column types, note this is only for displaying them in the test results
>       cast(model_token_bought_address as varchar) as result_model,
>       cast(seed_token_bought_address as varchar) as expected_seed,
>       (
>         model_token_bought_address = seed_token_bought_address
>       ) as equality_check,
>       seed_block_date as block_date,
>       seed_blockchain as blockchain,
>       seed_project as project,
>       seed_version as version,
>       seed_tx_hash as tx_hash,
>       seed_evt_index as evt_index,
>       seed_trace_address as trace_address
>     from
>       matched_records
>     UNION ALL
>     select
>       'equality test: token_sold_address' as test_description,
>       -- these are cast to varchar to unify column types, note this is only for displaying them in the test results
>       cast(model_token_sold_address as varchar) as result_model,
>       cast(seed_token_sold_address as varchar) as expected_seed,
>       (
>         model_token_sold_address = seed_token_sold_address
>       ) as equality_check,
>       seed_block_date as block_date,
>       seed_blockchain as blockchain,
>       seed_project as project,
>       seed_version as version,
>       seed_tx_hash as tx_hash,
>       seed_evt_index as evt_index,
>       seed_trace_address as trace_address
>     from
>       matched_records
>   )
> select
>   *
> from
>   (
>     select
>       *
>     from
>       matching_count_test
>     union all
>     select
>       *
>     from
>       equality_tests
>   ) all
>   -- equality check can be null so we have to check explicitly for nulls
> where
>   equality_check is distinct
> from
>   true
> ```

@jeff-dude This PR seems to unnecessary, because it was created for new changes and these changes that modified with SparkSQL had been merged. If you think this PR are nessesary, I can take a look when I get a moment, otherwise, maybe we should close it for now.

**Comment by jeff-dude** [comment]
@BennyFeng we need to migrate the full paraswap lineage to dunesql. this PR seems to have been repurposed to do that, which is why i picked it up to help finalize. if new changes to logic aren't needed, can we at least get this migrated?

**Comment by BennyFeng** [comment]
I see. I'll keep going from here in my morning.

**Review by jeff-dude — APPROVED** [review]
nice! thank you for helping push this through, much appreciated

**Pull request merged**
