### PR TITLE
Add updated missing tokens

### PR DESCRIPTION
**Pull request by gentrexha**
Generated with

```
docker run \                                                   
    -e SPELLBOOK_PATH=$SPELLBOOK_PATH \
    -e INFURA_KEY=$INFURA_KEY \
    -e DUNE_API_KEY=$DUNE_API_KEY \
    -v $SPELLBOOK_PATH:$SPELLBOOK_PATH \
    ghcr.io/cowprotocol/data-misc-missing-tokens:main
```

Updated based on comment [here](https://github.com/duneanalytics/spellbook/pull/3642#issuecomment-1614737942).

### CODE REVIEW

**Review by bh2smith — CHANGES_REQUESTED** [review]
Should we be updating both legacy and this table now? or is `_legacy` just a cheeky temp fix during migration?

I noticed that our trades table is pointing to legacy now as well (see here https://github.com/duneanalytics/spellbook/blob/main/models/cow_protocol/ethereum/cow_protocol_ethereum_trades.sql#L91-L93)

Can we already redirect our table to read from the migrated tokens @jeff-dude or do we have to wait till the whole spell is migrated to dunesql?

In the meantime, I think we will need to update both the _legacy and the new tables...

**Comment by jeff-dude** [comment]
> Should we be updating both legacy and this table now? or is `_legacy` just a cheeky temp fix during migration?
> 
> I noticed that our trades table is pointing to legacy now as well (see here https://github.com/duneanalytics/spellbook/blob/main/models/cow_protocol/ethereum/cow_protocol_ethereum_trades.sql#L91-L93)
> 
> Can we already redirect our table to read from the migrated tokens @jeff-dude or do we have to wait till the whole spell is migrated to dunesql?
> 
> In the meantime, I think we will need to update both the _legacy and the new tables...

we will release an updated spellbook contribution guide v shortly as we come out of the freeze. short answer: yes, add to both for now (through migration period). any downstream spells which read from them (i.e. in `ref()` usage), we will update to legacy, then next step when migrating downstream spells, such as cow trades, we will remove legacy ref call.

i believe cow trades moved to `dex_aggregator` lineage, so it's not in our scope during the freeze, so you're more than welcome to go ahead and start migrating if you'd like. otherwise, it'll come up in next set of priorities for us asap.

**Comment by bh2smith** [comment]
Awesome thanks @jeff-dude! I may try to take a stab at it soon...

**Comment by gentrexha** [comment]
Closed in favour of https://github.com/duneanalytics/spellbook/pull/3673

**Pull request closed without merging**
