### PR TITLE
Spellbook Workshop Submission

### PR DESCRIPTION
**Pull request by justabi**
Brief comments on the purpose of your changes:
- Migrated the v1 balancer ethereum balances abstraction to a v2 spellbook/dbt model

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)
* [x] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### CODE REVIEW

**Comment by justabi** [comment]
general comment
- updated the final select to be an inner join as we were getting a bunch of blank rows - in theory if the join condition fails we don't need a date and blank data? (unless there's a use case for this)

**Comment by justabi** [comment]
@dot2dotseurat - heya, is this error related to my pr or would it be fixed with the v2_engine label?

**Comment by dot2dotseurat** [comment]
> @dot2dotseurat - heya, is this error related to my pr or would it be fixed with the v2_engine label?

hey @justabi I'm looking now. We are still working out some kinks on this test. This is definitely an issue on our end not yours. I'll report back soon.

**Comment by justabi** [comment]
> > @dot2dotseurat - heya, is this error related to my pr or would it be fixed with the v2_engine label?
> 
> 
> 
> hey @justabi I'm looking now. We are still working out some kinks on this test. This is definitely an issue on our end not yours. I'll report back soon. 

Thank you!! Lmk if I can help at all ^_^

**Pull request closed without merging**
