### PR TITLE
Add curvefi to `dex.trades_beta`

### PR DESCRIPTION
**Pull request by tomfutago**
linked to #4759

### CODE REVIEW

**Comment by Hosuke** [comment]
Not sure about the CI failing reason:
https://github.com/duneanalytics/spellbook/actions/runs/7500883617/job/20426414197#step:11:29

**Comment by tomfutago** [comment]
> Not sure about the CI failing reason: https://github.com/duneanalytics/spellbook/actions/runs/7500883617/job/20426414197#step:11:29

temporary blip? seem to be fine on re-run

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @tomfutago 

[curvefi_*.base_trades checking](https://dune.com/queries/3347108)

**Review by jeff-dude — APPROVED** [review]
thank you as always 🙏 

curve is a bit different than most, with different chains querying different source tables. it's an exception we had in previous lineage. eventually, we may end up reworking all to query logs directly like ethereum does, but tbd on that.

**Pull request merged**
