### PR TITLE
Split Blur v1 into Blur v1 & Blur seaport

### PR DESCRIPTION
**Pull request by hildobby**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Review by 0xRobin — APPROVED** [review]
good split :heavy_check_mark:

**Comment by 0xRobin** [comment]
adding 'do-not-merge` until we figure out the issue that happened with the LooksRare PR

**Comment by hildobby** [comment]
Why the do not merge tag here @0xRobin ?

**Comment by 0xRobin** [comment]
@hildobby we're having some backend issues when merging new dunesql models that previously did not exist on the legacy spark side. Once we have the resolution in place this will be merged as is. :+1:

**Comment by 0xRobin** [comment]
@jeff-dude @antonio-mendes, let's get this in. :heavy_check_mark:

**Review by antonio-mendes — APPROVED** [review]
lfg!

**Pull request merged**
