### PR TITLE
SPE-142 Migrate Seaport

### PR DESCRIPTION
**Pull request by couralex6**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by couralex6** [comment]
FYI @0xRobin These are still being used a lot, so I gave them a try. I looked at the macros you wrote for inspiration, but i'm still getting some errors. Maybe you'll know how to fix them

**Comment by 0xRobin** [comment]
@couralex6 I ironed out some bugs and fixes, but still no successful CI.

**Comment by couralex6** [comment]
Looks like we're good to go! Thanks @0xRobin for the help!

**Review by 0xRobin — APPROVED** [review]
Great! :rocket:

**Pull request merged**
