### PR TITLE
Missing Tokens: Add 631 Moar

### PR DESCRIPTION
**Pull request by bh2smith**
Just the usual erc20 token update.

### CODE REVIEW

**Review by jeff-dude — COMMENTED** [review]
hmm, do you know why this edit is changing the entire file?
any chance you can take a quick look to see why and ideally push a commit that only shows the new?

**Comment by bh2smith** [comment]
Sorry I hadn't noticed that. Will check tomorrow.

**Comment by bh2smith** [comment]
Fixed it @jeff-dude

**Review by jeff-dude — APPROVED** [review]
much better, thank you 🙏

**Pull request merged**
