### PR TITLE
Update maker_ethereum_accounting_legacy.sql

### PR DESCRIPTION
**Pull request by web3lyt**
added correct classification of an RWA ilk

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by jeff-dude** [comment]
hi @web3lyt -- the license agreement you signed was on a user's forked repo of spellbook, not the dune repo. you will need to comment here on this PR to get it signed officially

**Comment by web3lyt** [comment]
> hi @web3lyt -- the license agreement you signed was on a user's forked repo of spellbook, not the dune repo. you will need to comment here on this PR to get it signed officially

Gotcha. That was the email I got haha but I'll sign again here.

I have read the CLA Document and I hereby sign the CLA

**Comment by jeff-dude** [comment]
the bot can be a bit finicky, you may need to comment just that one sentence, no other quotes or wording

**Comment by web3lyt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
