### PR TITLE
Remove redundant brackets in select ... from (database.table)

### PR DESCRIPTION
**Pull request by jkylling**
Brief comments on the purpose of your changes:

Some SQL parsers do not like parsing `select * from (database.table)`. I suspect this breaks with the ANSI SQL specification. Hence we remove the redundant brackets to make these views easier to parse.

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by jkylling** [comment]
Many of the sql files are missing newlines at the end of the file. We should consider adding some linting checks to this repo to enforce a consistent style.

**Comment by jkylling** [comment]
Link T-16775

**Comment by throwaway2847t8ter7gz** [comment]
Link T-16777

**Review by soispoke — COMMENTED** [review]
lgtm, yeah adding linting has been on our minds for a while but I think we really have to do this. In the meantime, we can try to make sure that both that there are newlines at the end of SQL files and that refs are not between parentheses for upcoming spells submissions

**Review by soispoke — APPROVED** [review]

**Comment by andre-dune** [comment]
Link T-16777

**Comment by a-monteiro** [comment]
Link T-16777

**Pull request merged**
