### PR TITLE
One other view --> table change

### PR DESCRIPTION
**Pull request by catherine-2**
Brief comments on the purpose of your changes:

Thank you for your help updating the last table! That query went from 25 minutes --> 7 seconds! 

Found one last one that could be better as a table (currently takes ~7 minutes to run). 

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by catherine-2** [comment]
@jeff-dude One last punk file to change to a table. Sorry for the separate PRs! Will make sure to combine in the future.

**Comment by jeff-dude** [comment]
i don't know the intention of the table, but this seems like maybe it's not what you want:
```
select
  *
from
  test_schema.git_67b0a446_cryptopunks_ethereum_owners_over_time
where
  unique_wallets != 0
order by
  day
```

**Comment by jeff-dude** [comment]
if it hasn't been mentioned, you can query the test tables built in the gh action

**Comment by jeff-dude** [comment]
> > if it hasn't been mentioned, you can query the test tables built in the gh action
> 
> I did not know that - super helpful thank you!
> 
> I realized with the error that I probably don't need to make a new incremental table to improve performance. I re-wrote it to use the punk transfers table we just merged and tested the gh action table and select * from owners_over_time is now accurate + running quickly.

sounds good. added a test to ensure uniqueness as well, looks good to go.

also pushed commit for minor syntax change. to prepare for upcoming architecture changes on dune, the usage of ` will not be compatible on views (since views run underlying query at runtime). more to come on these types of changes soon, but wanted to point that out as you may see this changed by internal dune teammates (along with other potential syntax changes)

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
it's not necessary, just a habit on my end

**Comment by catherine-2** [comment]
Got it thank you!

**Pull request merged**
