### PR TITLE
Add Odos v2 Ethereum Spell And Fix Base Spell

### PR DESCRIPTION
**Pull request by amalashkevich**
# Thank you for contributing to Spellbook!

Thank you for taking the time to submit code in Spellbook. A few things to consider:

- If you are a first-time contributor, please sign the CLA by copy & pasting **_exactly_** what the bot mentions in PR comment
- Refer to [docs](#spellbook-contribution-docs) section below to answer questions
- Dune team will review submitted PRs as soon as possible

## Spellbook sub-projects

To prepare for Spellbook to scale in size, Dune team has started to pilot sub-projects:

- For a quick overview, see [the GH discussion on the topic](https://github.com/duneanalytics/spellbook/discussions/5238)
  - Please ask questions and continue the conversation there
- The first spell lineage to move: `tokens.erc20` and all upstream spells which help build it
  - **_Note_**: Please navigate to [tokens](/tokens) root directory to find tokens objects

## Spellbook contribution docs

The [docs](docs) directory has been implemented to answer as many questions as possible. Please take the time to reference each `.md` file within this directory to understand how to efficiently contribute & why the repo is designed as it is 🪄

Example questions to be answered:

- What does each property in the [model config block](/docs/models/model_config_block.md) mean?
- What is the [CI test](/docs/ci_test/ci_test_overview.md) attached to PRs and how can I best utilize it?
- What are the Spellbook [best practices](/docs/general/best_practices.md)?

Please navigate through the [docs](/docs) directory to find as much info as you can.

**Note**: happy to take PRs to improve the docs, let us know 🤝

### CODE REVIEW

**Comment by amalashkevich** [comment]
This spell is similar to Optimism one, except it does not include v1 query at all.
Also, the Base spell was copied from a not quite correct spell which was used before, therefore this fix is required.

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @amalashkevich 

[Sample odos_trades](https://dune.com/queries/3503125)

**Comment by amalashkevich** [comment]
Thank you @Hosuke 
Could you share, why some fields are empty in this query result?
image

In the same time, the token info is available in the etherscan, e.g. https://etherscan.io/tx/0x8c115a95e5898f253eb1f714ffbc709086a5eb881a09d2f3a0a3cc9fc2dd6097

**Comment by amalashkevich** [comment]
@Hosuke  Another question:
Odos is an aggregator and I'd like to add a tag. Which one is a correct one?
1. 'dex_aggregator'
2. 'aggregator'
I can see both of them are used in the trade schema yml files.
Should I specify those tags in each schema file or only in the root schema in `models/odos/odos_trades_schema.yml`?

**Comment by Hosuke** [comment]
> Thank you @Hosuke Could you share, why some fields are empty in this query result? image
> 
> In the same time, the token info is available in the etherscan, e.g. https://etherscan.io/tx/0x8c115a95e5898f253eb1f714ffbc709086a5eb881a09d2f3a0a3cc9fc2dd6097

Maybe the prices data for weth is missing for that specific time, but I am not sure yet.

Also I think [`dex`, `aggregator`] may be a choice for the tag.

**Comment by amalashkevich** [comment]
> Maybe the prices data for weth is missing for that specific time, but I am not sure yet.
> Also I think [dex, aggregator] may be a choice for the tag.

Great, thanks. I just updated the tags. Is there anything else that needs to be done before the merge @Hosuke?

**Comment by amalashkevich** [comment]
> > > Maybe the prices data for weth is missing for that specific time, but I am not sure yet.
> > > Also I think [dex, aggregator] may be a choice for the tag.
> > 
> > 
> > Great, thanks. I just updated the tags. Is there anything else that needs to be done before the merge @Hosuke?
> 
> Please run `git merge main` to update this PR.

Done!

**Pull request merged**
