### PR TITLE
update feeds | add base | create ocr macro

### PR DESCRIPTION
**Pull request by AnonJon**
- Update existing feeds and operators
- Add Base to feeds
- Start new OCR chainlink macro

### CODE REVIEW

**Comment by AnonJon** [comment]
@jeff-dude good to go now

**Comment by jeff-dude** [comment]
wow! thank you for refactoring your code with this approach, it's much appreciated.

the refactor all looks good, i'm just going to hold off for a second so we can dig into the performance on some of the incremental models. it's actually something i've wanted to do for a bit, as the runtimes in prod are a bit slow too. we are likely just missing a few filters / join conditions / something along those lines in one or two macros. i'm happy to help dig into those long running ones and help here in a bit.

in case you're not following what i'm referring to, if you expand the runtime of the gh action for CI run(s) on the incremental run step, you'll see some long running models. ideally most of the incremental step runs are much shorter than hundreds of seconds.

some that i'd like to look closer at:
- ocr_reward_evt_transfer_daily
- ocr_fulfilled_transactions

**Comment by jeff-dude** [comment]
> Yeah, no rush on my side so if we can make these more efficient that would be great. Ill take a look into the ones you listed and see how they could be updated. Cheers

thanks for taking an initial look and helping decrease incremental time a bit already 🙏 

i'll be out until early next week, do you need me to merge this before i'm out or can this sit more until late next week?

**Comment by AnonJon** [comment]
Next week is fine. Ill take some more time with it before then and see if I can make them faster.

**Comment by jeff-dude** [comment]
fyi, as noted in gh discussion that i tagged you, these models have moved in the directory. if you wanted to rebase the branch and get it up to date, we can try to continue this soon.

**Comment by AnonJon** [comment]
@jeff-dude rebased everything to new layout

**Review by noelportillo — APPROVED** [review]

**Comment by jeff-dude** [comment]
thank you again for raising this. apologies we didn't get it finalized. as far as i can tell, the chainlink spells are running fine in prod and there aren't frequent changes coming through via new PRs, so this isn't as high priority.

please do keep this branch on your fork, so when (or if) changes do come through in future for chainlink spells, we can pick up this macro approach and do as efficiently as possible.

**Pull request closed without merging**
