### PR TITLE
Update airswap_ethereum_trades.sql

### PR DESCRIPTION
**Pull request by MarcoVugts**
i might be an idiot but it seems like the bought and sold are swapped in this query: example https://dune.com/queries/2003937
etherscan: https://etherscan.io/tx/0xbb34f1fc76ffe9cba4ee1ff26cdad555cae6ea535e81159bf0b1765e7c12aa83

It seems like the senderAmount was labeled as bought, but looks like this is the sold amount.

Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @MarcoVugts

**Comment by MarcoVugts** [comment]
> LGTM.✅ Thank you @MarcoVugts

Awesome thanks for the quick fix!

**Review by jeff-dude — APPROVED** [review]
good catch both!

for reference, i had previously left a comment in the main `dex.trades` spell [here](https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_trades.sql#L10) for a few protocols which didn't fit our new seed test approach at the time. glad to see you apply it properly here @Hosuke -- if you want, we can go ahead and look into other models commented there too. they may have the old seed approach too.

**Comment by jeff-dude** [comment]
> I just ran an experiment on airswap:
> 
> image
> 
> image
> 
> https://etherscan.io/tx/0x4e3c3ff376e448da4bba99e23dd533b22c24d125cfb2d24770df8b3922a83068#eventlog
> @MarcoVugts You are right.

wow, the dedication! 🙂

**Comment by jeff-dude** [comment]
> good catch both!
> 
> for reference, i had previously left a comment in the main `dex.trades` spell [here](https://github.com/duneanalytics/spellbook/blob/main/models/dex/dex_trades.sql#L10) for a few protocols which didn't fit our new seed test approach at the time. glad to see you apply it properly here @Hosuke -- if you want, we can go ahead and look into other models commented there too. they may have the old seed approach too.

not in this PR, fyi, but a separate one

**Pull request merged**
