### PR TITLE
Add Mauve - ready for review

### PR DESCRIPTION
**Pull request by ra-phael**
This PR adds new spells for Mauve ([https://www.mauve.org/](https://www.mauve.org/)).

### CODE REVIEW

**Comment by ra-phael** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ra-phael** [comment]
I added the LsETH token in `models/tokens/ethereum/tokens_ethereum_erc20.sql` but `mauve_ethereum_trades` still have empty columns for this token when it is involved in a trade...

What am I missing? @jeff-dude 

image


Sorry I'm a Dune newbie, this is like my first day in the school of Blockchain analytics and Wizardry. 😆

**Comment by jeff-dude** [comment]
> I added the LsETH token in `models/tokens/ethereum/tokens_ethereum_erc20.sql` but `mauve_ethereum_trades` still have empty columns for this token when it is involved in a trade...
> 
> What am I missing? @jeff-dude
> 
> image
> Sorry I'm a Dune newbie, this is like my first day in the school of Blockchain analytics and Wizardry. 😆

no need to apologize -- welcome to spellbook and thank you for contributing 🪄 

i think i see the issue here and it's not anything you've done wrong. in our PR CI test actions, we only run models which are directly modified in that specific PR. if a model is referenced and not in the PR, it will read from prod instead. in this instance, you modify the `tokens_ethereum_erc20` spell, but the `tokens_erc20` spell is not included, which combines all blockchains into one. then in your new dex spell, you join to `tokens_erc20`, which will then read from prod instead (i.e. no new token).

your best bet for a quick workaround is to modify the `tokens_erc20` spell to be included here. it could be a simple new line addition, remove an empty line, etc etc.

**Comment by ra-phael** [comment]
Got it, thank you for the explanation!

**Comment by jeff-dude** [comment]
> Got it, thank you for the explanation!

are you good with letting this ride then, and pushing to prod? there it will follow proper dependencies & tokens would flow through.

**Comment by ra-phael** [comment]
Yes, pushing to prod sounds good to me.

**Review by jeff-dude — APPROVED** [review]
sounds good -- let's get this queued up for merge!

thanks again for the contribution

**Pull request merged**
