### PR TITLE
Add Ringers Metadata Spell

### PR DESCRIPTION
**Pull request by catherine-2**
Brief comments on the purpose of your changes:

Hi! This is my first spell PR so using a basic query first that is all static data :)

Please let me know if I missed any files or information needed

One thing to note: I created a new subfolder under nft_ethereum called "metadata" to store metadata tables for NFT collections. I think these would be useful to have as spells (I have a number of user generated metadata tables I can upload so others can use them too). Let me know if there is a different way you'd like to organize these tables.

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by soispoke** [comment]
Hi @catherine-2 thanks for your submission !

Can you please adapt the `nft_ethereum_metadata_ringers.sql` model so it a table with static values (by following the model here for example (https://github.com/duneanalytics/spellbook/blob/main/models/tokens/ethereum/tokens_ethereum_erc20.sql)
Where yours work, we would like to have static tables structured consistently across spells

**Comment by soispoke** [comment]
@catherine-2 thanks for applying changes, would you like to expose this view on Dune.com as well ? 
If you do, there is an extra step needed, where you add metadata to the view/table you want to expose:

Here is the macro where you need to add your new model:
https://github.com/duneanalytics/spellbook/blob/main/macros/alter_table_properties.sql

After this lgtm!

**Comment by catherine-2** [comment]
Thank you @soispoke  - yeah I can add that. To make sure I understand - when you say 'expose this view on dune.com' does that mean in the online documentation, in the table list in the query editor, or both?

**Comment by catherine-2** [comment]
@soispoke  awesome let's merge now then to remove from the queue and I will make a note to expose this table alongside the others once those are added

thank you so much for your help!

**Review by soispoke — APPROVED** [review]

**Comment by soispoke** [comment]
sounds good, thanks for submitting this first spell 🔥 @catherine-2 !

**Comment by catherine-2** [comment]
@soispoke  is there a delay for the table to show up on the documentation page? I had set it up to have a folder called 'metadata' under the nft model category but am not seeing it. Want to make sure I didn't mess it up and if I did make sure I know how to fix it in the next PR!

https://spellbook-docs.dune.com/#!/model/model.spellbook.nft_ethereum_aggregators

**Comment by soispoke** [comment]
@catherine-2 yes there is, the best way to make sure everything worked is just to query your table on Dune :) 

https://dune.com/queries/1227549?d=1&category=abstraction

**Comment by catherine-2** [comment]
@soispoke  ah got it - was typing the name in wrong trying to check it :) thank you for opening the other PR to fix!

**Pull request merged**
