### PR TITLE
Labels relaunch 2023 (Final Review Period Until 2/16 EOD)

### PR DESCRIPTION
**Pull request by andrewhong5297**
This is the full labels refactor per the discussion [here](https://github.com/duneanalytics/spellbook/discussions/2634). There will be a three-day period to debug/take final comments before merging. 

Note, that for all models that have been placed in a top-level category, their `category` column has been changed, so you will need to update your queries. I left the ENS model as is as a special case, given that would break too many queries likely. 

All the `array(blockchain)` have been changed to just `blockchain` strings instead, so no more array `contains()` usage is required in queries.

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by andrewhong5297** [comment]
@jeff-dude made a merge from main and getting a weird new error

**Comment by jeff-dude** [comment]
> @jeff-dude made a merge from main and getting a weird new error

looks like latest commit got past `dbt compile` which i think is where it errored out? it'll still likely timeout here soon

**Comment by jeff-dude** [comment]
did you ever setup local dbt? can you run this locally where there isn't a timeout? curious if you went through that during dev

**Comment by andrewhong5297** [comment]
> did you ever setup local dbt? can you run this locally where there isn't a timeout? curious if you went through that during dev

Hmmm I don't think I did.

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
