### PR TITLE
migrate erc4337 to dunesql (mini upgrade with one chain) [Do not merge]

### PR DESCRIPTION
**Pull request by 0xbitfly**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by 0xbitfly** [comment]
@jeff-dude now only one polygon chain. and only one error at `dbt test initial model`. didn't find any backquoted identifiers  at my code. 

``` bash
04:45:06  Running with dbt=1.4.6
04:45:13  Found 2633 models, 2055 tests, 0 snapshots, 0 analyses, 585 macros, 0 operations, 123 seed files, 1634 sources, 0 exposures, 0 metrics
04:45:13  
04:46:17  Concurrency: 8 threads (target='dev')
04:46:17  
04:46:17  1 of 2 START test check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_  [RUN]
04:46:17  2 of 2 START test dbt_utils_unique_combination_of_columns_account_abstraction_erc4337_polygon_userops_userop_hash__tx_hash  [RUN]
04:46:[17](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:18)  1 of 2 ERROR check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_  [ERROR in 0.30s]
04:46:[18](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:19)  2 of 2 PASS dbt_utils_unique_combination_of_columns_account_abstraction_erc4337_polygon_userops_userop_hash__tx_hash  [PASS in 1.18s]
04:46:18  
04:46:18  Finished running 2 tests in 0 hours 1 minutes and 5.07 seconds (65.07s).
04:46:20  
04:46:20  Completed with 1 error and 0 warnings:
04:46:20  
04:46:20  Database Error in test check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_ (models/account_abstraction/erc4337/polygon/account_abstraction_erc4337_polygon_schema.yml)
04:46:20    TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 43:41: backquoted identifiers are not supported; use double quotes to quote identifiers", query_id=202307[19](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:20)_044617_07672_z7r53)
04:46:[20](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:21)  
04:46:20  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
Error: Process completed with exit code 1.
```

**Comment by Hosuke** [comment]
> @jeff-dude now only one polygon chain. and only one error at `dbt test initial model`. didn't find any backquoted identifiers at my code.
> 
> ```shell
> 04:45:06  Running with dbt=1.4.6
> 04:45:13  Found 2633 models, 2055 tests, 0 snapshots, 0 analyses, 585 macros, 0 operations, 123 seed files, 1634 sources, 0 exposures, 0 metrics
> 04:45:13  
> 04:46:17  Concurrency: 8 threads (target='dev')
> 04:46:17  
> 04:46:17  1 of 2 START test check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_  [RUN]
> 04:46:17  2 of 2 START test dbt_utils_unique_combination_of_columns_account_abstraction_erc4337_polygon_userops_userop_hash__tx_hash  [RUN]
> 04:46:[17](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:18)  1 of 2 ERROR check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_  [ERROR in 0.30s]
> 04:46:[18](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:19)  2 of 2 PASS dbt_utils_unique_combination_of_columns_account_abstraction_erc4337_polygon_userops_userop_hash__tx_hash  [PASS in 1.18s]
> 04:46:18  
> 04:46:18  Finished running 2 tests in 0 hours 1 minutes and 5.07 seconds (65.07s).
> 04:46:20  
> 04:46:20  Completed with 1 error and 0 warnings:
> 04:46:20  
> 04:46:20  Database Error in test check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_ (models/account_abstraction/erc4337/polygon/account_abstraction_erc4337_polygon_schema.yml)
> 04:46:20    TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 43:41: backquoted identifiers are not supported; use double quotes to quote identifiers", query_id=202307[19](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:20)_044617_07672_z7r53)
> 04:46:[20](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:21)  
> 04:46:20  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
> Error: Process completed with exit code 1.
> ```

https://github.com/duneanalytics/spellbook/pull/3769/files#r1265142974
I am not sure but maybe this can fix.

**Comment by jeff-dude** [comment]
> > @jeff-dude now only one polygon chain. and only one error at `dbt test initial model`. didn't find any backquoted identifiers at my code.
> > ```shell
> > 04:45:06  Running with dbt=1.4.6
> > 04:45:13  Found 2633 models, 2055 tests, 0 snapshots, 0 analyses, 585 macros, 0 operations, 123 seed files, 1634 sources, 0 exposures, 0 metrics
> > 04:45:13  
> > 04:46:17  Concurrency: 8 threads (target='dev')
> > 04:46:17  
> > 04:46:17  1 of 2 START test check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_  [RUN]
> > 04:46:17  2 of 2 START test dbt_utils_unique_combination_of_columns_account_abstraction_erc4337_polygon_userops_userop_hash__tx_hash  [RUN]
> > 04:46:[17](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:18)  1 of 2 ERROR check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_  [ERROR in 0.30s]
> > 04:46:[18](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:19)  2 of 2 PASS dbt_utils_unique_combination_of_columns_account_abstraction_erc4337_polygon_userops_userop_hash__tx_hash  [PASS in 1.18s]
> > 04:46:18  
> > 04:46:18  Finished running 2 tests in 0 hours 1 minutes and 5.07 seconds (65.07s).
> > 04:46:20  
> > 04:46:20  Completed with 1 error and 0 warnings:
> > 04:46:20  
> > 04:46:20  Database Error in test check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_ (models/account_abstraction/erc4337/polygon/account_abstraction_erc4337_polygon_schema.yml)
> > 04:46:20    TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 43:41: backquoted identifiers are not supported; use double quotes to quote identifiers", query_id=202307[19](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:20)_044617_07672_z7r53)
> > 04:46:[20](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:21)  
> > 04:46:20  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
> > Error: Process completed with exit code 1.
> > ```
> 
> https://github.com/duneanalytics/spellbook/pull/3769/files#r1265142974 I am not sure but maybe this can fix.

please refer to our discord thread. remove `_legacy` on any seed macro calls in schema files if the model has migrated to dunesql

**Comment by 0xbitfly** [comment]
> > > @jeff-dude now only one polygon chain. and only one error at `dbt test initial model`. didn't find any backquoted identifiers at my code.
> > > ```shell
> > > 04:45:06  Running with dbt=1.4.6
> > > 04:45:13  Found 2633 models, 2055 tests, 0 snapshots, 0 analyses, 585 macros, 0 operations, 123 seed files, 1634 sources, 0 exposures, 0 metrics
> > > 04:45:13  
> > > 04:46:17  Concurrency: 8 threads (target='dev')
> > > 04:46:17  
> > > 04:46:17  1 of 2 START test check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_  [RUN]
> > > 04:46:17  2 of 2 START test dbt_utils_unique_combination_of_columns_account_abstraction_erc4337_polygon_userops_userop_hash__tx_hash  [RUN]
> > > 04:46:[17](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:18)  1 of 2 ERROR check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_  [ERROR in 0.30s]
> > > 04:46:[18](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:19)  2 of 2 PASS dbt_utils_unique_combination_of_columns_account_abstraction_erc4337_polygon_userops_userop_hash__tx_hash  [PASS in 1.18s]
> > > 04:46:18  
> > > 04:46:18  Finished running 2 tests in 0 hours 1 minutes and 5.07 seconds (65.07s).
> > > 04:46:20  
> > > 04:46:20  Completed with 1 error and 0 warnings:
> > > 04:46:20  
> > > 04:46:20  Database Error in test check_seed_legacy_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_first_funded_by_seed_ (models/account_abstraction/erc4337/polygon/account_abstraction_erc4337_polygon_schema.yml)
> > > 04:46:20    TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 43:41: backquoted identifiers are not supported; use double quotes to quote identifiers", query_id=202307[19](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:20)_044617_07672_z7r53)
> > > 04:46:[20](https://github.com/duneanalytics/spellbook/actions/runs/5595069767/jobs/10230581360#step:13:21)  
> > > 04:46:20  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
> > > Error: Process completed with exit code 1.
> > > ```
> > 
> > 
> > https://github.com/duneanalytics/spellbook/pull/3769/files#r1265142974 I am not sure but maybe this can fix.
> 
> please refer to our discord thread. remove `_legacy` on any seed macro calls in schema files if the model has migrated to dunesql

I have tried that. it raised another error I met before. I am confused why it can not find the test data. it works in SparkSQL.
- I have change the `check_seed_legacy`  to `check_seed`.
- Also do some small edit in `account_abstraction_erc4337_userops_seed.csv`

``` bash
14:18:05  
14:18:05  Finished running 50 tests in 0 hours 0 minutes and 25.93 seconds (25.93s).
14:18:07  
14:18:07  Completed with 1 error and 0 warnings:
14:18:07  
14:18:07  Database Error in test check_seed_account_abstraction_erc4337_polygon_userops_tx_hash__bundler__userop_hash__ref_account_abstraction_erc4337_userops_seed_ (models/account_abstraction/erc4337/polygon/account_abstraction_erc4337_polygon_schema.yml)
14:18:07    TrinoUserError(type=USER_ERROR, name=SCHEMA_NOT_FOUND, message="line 18:18: Schema 'test_data' does not exist", query_id=20230719_141754_15425_6tppc)
14:18:07  
14:18:07  Done. PASS=49 WARN=0 ERROR=1 SKIP=0 TOTAL=50
Error: Process completed with exit code 1.
```

**Comment by jeff-dude** [comment]
@0xbitfly i will close this PR now, please look at #3804 for reference on how to migrate these spells and their seed tests

**Comment by jeff-dude** [comment]
> @0xbitfly i will close this PR now, please look at #3804 for reference on how to migrate these spells and their seed tests

it's currently failing for a few reasons, but we're on the right path:
- tests run for all blockchains, likely due to unique nature of this sector spell having a macro used on each blockchain and the macro is modified in the PR. all other spells other than arbitrum v05 are expected to fail in that setup, as we haven't done the modifications to others
- the seed test is failing on arbitrum v05 due to missing column in model? looks like maybe `bundler` is only used in the rollup of v05 and v06? if that is the case, you are welcome to make edits to v06 and rollup of v05/v06 spell for arbitrum only, then move seed tests back to the rollup spell in schema file, if needed
- it's okay to continue to see other blockchain tests fail, lets focus on arbitrum with this example

**Comment by jeff-dude** [comment]
feel free to start fresh on your forked repo. ensure main is up-to-date. then create new branch for arbitrum. then you should be able to pull changes from my branch into your new branch and open a new PR from there to continue the work noted above

**Pull request closed without merging**
