### PR TITLE
T-26026 - Change kyberswap trades model to be Trino compatible

### PR DESCRIPTION
**Pull request by belen-pruvost**

### CODE REVIEW

**Comment by soispoke** [comment]
Looks like you missed the `CAST` part of the statements for this one

**Comment by belen-pruvost** [comment]
> Looks like you missed the `CAST` part of the statements for this one

Oops! Should be better now.

**Comment by belen-pruvost** [comment]
Unrelated issue `Missing model (ref) dex_model` pops in the CI

**Comment by jeff-dude** [comment]
please do merge main and try the tests again. dex trades has had some test enhancements today.

**Comment by belen-pruvost** [comment]
> please do merge main and try the tests again. dex trades has had some test enhancements today.

@jeff-dude thank you! I rebased and now the check that should pass is passing. Then there is an unrelated issue on the pre commit hook `Missing model (ref) dex_model` but I believe this PR should be good to be reviewed now.

**Comment by soispoke** [comment]
@belen-pruvost can you merge main into this branch 🙏?

**Comment by belen-pruvost** [comment]
> @belen-pruvost can you merge main into this branch 🙏?

I've rebased it onto main, which is similar to merging but tidier on the commit history. TLDR it has all the changes from main as of 09:28 am :D

**Comment by soispoke** [comment]
@belen-pruvost ok, then I guess the for loop is still not taken into account by the pre commit hook, lgtm though

**Review by soispoke — APPROVED** [review]

**Pull request merged**
