### PR TITLE
[Easy] make trader frequencies spell cross chain - Ready for review 

### PR DESCRIPTION
**Pull request by henrystats**
@gentrexha this is similar to pr: https://github.com/duneanalytics/spellbook/pull/2555

This pr makes the trader diversity spell crosschain 

erm not sure why the spell Is failing in gh. The compiled query works on dune.com

### CODE REVIEW

**Comment by henrystats** [comment]
@augustog, @gentrexha originally worked on this spell and we discussed on a previous pr (similar to this one) and we opted to have these split by blockchains instead of combining all into one. 

I also think it's better splitted since many times one would want t use this for a specific blockchain and not cross-chain.

**Comment by augustog** [comment]
I think we may have sth lost in translation here...
this PR is building a a cross-chain spell on a single file (as opposed to having spell/ethereum/...sql spell/optimism/...sql), which I think, for this use case, is correct (we may want to partition by blockchain and block_date to facilitate single chain usage, but I think this way minimises duplication).

hence, I think this is ready to merge :)

**Comment by henrystats** [comment]
ah I see, awesome!

**Review by soispoke — APPROVED** [review]
lgtm!

**Pull request merged**
