### PR TITLE
Added ERN to prices.usd

### PR DESCRIPTION
**Pull request by 0xTollywood**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by 0xTollywood** [comment]
Lmk if there is something I need to change next time to pass token prices automation. Thanks!

**Comment by 0xTollywood** [comment]
https://api.coinpaprika.com/v1/tickers/ern-ethos-reserve-note

0xc5b001DC33727F8F26880B184090D3E252470D45
https://optimistic.etherscan.io/address/0xc5b001dc33727f8f26880b184090d3e252470d45

**Comment by jeff-dude** [comment]
you can look to reactivate on their site, there should be an option to add/edit a project. once ready, we can look to integrate. i'll close this PR for now.

if you reopen the PR, this spell will likely have been migrated to dunesql, so slightly different format to contribute to. follow #3700 for status of migration of `prices_tokens` across blockchains. thank you!

**Comment by 0xTollywood** [comment]
weve activated it! @jeff-dude so am i to use these tables:
ref('prices_native_tokens')
,ref('prices_arbitrum_tokens')
,ref('prices_avalanche_c_tokens')
,ref('prices_bnb_tokens')
,ref('prices_ethereum_tokens')
,ref('prices_fantom_tokens')
,ref('prices_gnosis_tokens')
,ref('prices_optimism_tokens')
,ref('prices_polygon_tokens')
,ref('prices_solana_tokens')
] %}

or as per your ideas in 3700 use tokens_erc20?

**Comment by jeff-dude** [comment]
since #3700 is on hold, you can add in the same manner you have in this PR

**Pull request closed without merging**
