### PR TITLE
enhance the PR CI test GH action

### PR DESCRIPTION
**Pull request by jeff-dude**
the goal:
- don't run CI test on `main` after merge, as we only merge if passing on feature branch -- this will also save compute resources for other PRs
- don't run CI test when syncing feature branch with main -- most commonly done via the new button on PRs to keep up-to-date with main branch prior to merge. we should have a passing CI test previously, then if another PR is merged, we're asked to updated to main again, therefore kicking off CI test again, taking up compute resources for other PRs

cc @duneanalytics/team-abstract

### CODE REVIEW

**Comment by dot2dotseurat** [comment]
I think we want the first case but not the second.

tests can fail because the branch is not up to date with main and that’s why we added the button for syncing to main.

**Comment by jeff-dude** [comment]
> I think we want the first case but not the second.
> 
> tests can fail because the branch is not up to date with main and that’s why we added the button for syncing to main.

second case can get finicky quick. for example:
- review PR1, tests pass, approve PR, no other PRs have been merged into main so the button isn't there, don't merge PR1 quite yet
- review PR2, tests pass, approve PR, no other PRs have been merged into main so the button isn't there, don't merge PR2 quite yet
- merge PR1
- revisit PR2, now the button pops up, click to sync with main from changes on PR1 (even if unrelated completely), CI tests run again after sync with main
- wait for success and then merge PR2

while i outline that, i'm still okay removing the second case to be safe. the workarounds:
- don't sync with main, bypass and merge, avoid the tests again
- just be patient and let it ride

**Comment by dot2dotseurat** [comment]
Yeah, I think bypassing is the better solution imho.

**Comment by jeff-dude** [comment]
> Yeah, I think bypassing is the better solution imho.

that's fine with me. happy to merge if you approve it 🙏

**Review by dot2dotseurat — APPROVED** [review]

**Pull request merged**
