### PR TITLE
Update trusted_tokens

### PR DESCRIPTION
**Pull request by Hosuke**
### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [x] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by Hosuke** [comment]
Major update in this PR:
add [`linea`, `scroll`, `zkevm`] trusted tokens.

**Comment by jeff-dude** [comment]
what's our plan for:
- adding mantle to prices spell lineage?
- adding mantle to manual erc20 token lineage?
- adding mantle to this trusted tokens list?

**Comment by Hosuke** [comment]
> what's our plan for:
> 
> * adding mantle to prices spell lineage?
> * adding mantle to manual erc20 token lineage?
> * adding mantle to this trusted tokens list?

Thinking...
At least I know these may be the trusted tokens:
https://mantlescan.xyz/tokens

**Comment by Hosuke** [comment]
Added mantle trusted tokens in this PR.

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
