### PR TITLE
Add DirectRouter to Paraswap in Spark

### PR DESCRIPTION
**Pull request by BennyFeng**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by springzh** [comment]
@jeff-dude @Hosuke  @0xRobin Since ParaSwap is eager to see the update asap, to make it simpler, we created this new PR that adding new data into spark sql version spellbook directly instead of mixing adding new data logic and upgrade to Dune SQL together. Hope this can make it easier to be reviewed and approved quicker. Thank you all.

**Review by Hosuke — APPROVED** [review]
LGTM.✅ for updates in legacy spells.

**Comment by jeff-dude** [comment]
> ee the update asap, to make it simpler, we created this new PR that adding new data into spark sql version spellbook directly inste

yes, i'd prefer to see changes in separate PR. thank you for considering this.

**Review by jeff-dude — APPROVED** [review]
thank you team. will look to apply asap.

~~once merged, feel free to start the migration PR(s) 🤝 ~~
can ignore this, i think it'll fall into dex lineage, which is in progress

**Pull request merged**
