### PR TITLE
Migrate v1 abstractions

### PR DESCRIPTION
**Pull request by dot2dotseurat**
Hello beloved wizards, 

Spellbook has grown a lot and we are starting to run into memory errors and bump up against maximum repo size limits on a number of applications. To alleviate this, we need to migrate the contents of the v1 abstractions folder to a new repo. 

I'm tagging those of you who have committed to this folder in the last month. I'll wait a week before I merge this in but henceforth these files will be in the dune-v1-abstractions repo. We will keep applying changes to the v1 engine until is it fully deprecated but I do hope that the deprecation schedule is not a surprise to any of you. 

I hope this migration is not too disruptive and happy holidays!

https://github.com/duneanalytics/dune-v1-abstractions

@mendesfabio @bh2smith @hivtushok @codenutt @fatayri @ripples3 @gentrexha @MSilb7 @harisang @halink0803 @abylaw

### CODE REVIEW

**Review by soispoke — APPROVED** [review]
nice!

**Review by bh2smith — APPROVED** [review]

**Comment by dot2dotseurat** [comment]
image

**Comment by dot2dotseurat** [comment]
Screen Shot 2022-12-14 at 10 46 34 AM
@bh2smith :( why ben

**Comment by dot2dotseurat** [comment]
@bh2smith I'll move your changes to the new repo.

**Comment by dot2dotseurat** [comment]
https://github.com/duneanalytics/dune-v1-abstractions/pull/1

**Comment by bh2smith** [comment]
Sorry that fix was supposed to be for v2 as well. I was just fixing it in both places while the repo was still here. Sorry!

**Comment by dot2dotseurat** [comment]
@bh2smith no worries. I'm just joking around. <3

**Pull request merged**
