### PR TITLE
Migrate `cex` sector to DuneSQL

### PR DESCRIPTION
**Pull request by hildobby**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by 0xRobin** [comment]
Awesome to see you take up migration work.
FYI we're not sure yet where this error comes from, looking into it. 
```TrinoExternalError(type=EXTERNAL, name=DELTA_LAKE_INVALID_SCHEMA, message="Unsupported type: timestamp(0)", query_id=20230713_015148_02591_nqgy2)
```

**Comment by 0xRobin** [comment]
@hildobby we've pinpointed the problem and currently only support `timestamp(3) with timezone` or `date` types in materialized models.
There are 3 possible solutions:
1. Wait until Dune team rolls out support for `timestamp(0)` (~ 1 week)
2. convert `timestamp '2022-01-10'` -> `timestamp '2022-01-10 00:00:00.000 UTC'`
3. convert `timestamp '2022-01-10'` -> `date '2022-01-10'`

I think #3 makes the most sense here for these models.

**Comment by hildobby** [comment]
> 

Alright sg, just applied 3 to all cex (non legacy) tables

**Review by jeff-dude — APPROVED** [review]
as rob mentioned, thank you for being proactive on these migrations -- much appreciated!

**Pull request merged**
