### PR TITLE
Add Candle ERC-20s and NFTs

### PR DESCRIPTION
**Pull request by samisbakedham**
Brief comments on the purpose of your changes:

Converted the list of main Candle tokens into those with the required SQL syntax.

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [x] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by samisbakedham** [comment]
@makoto @philippWassibauer @jpzk @alfetopito

**Comment by alfetopito** [comment]
> @makoto @philippWassibauer @jpzk @alfetopito

Any reason why I was tagged?
I don't have much context here

**Comment by soispoke** [comment]
Hi @samisbakedham, if I understand it well, those tokens are actually on Ethereum right ? Dune does not index the Candle blockchain afaik, so I don't think it's necessary to create new tables, you could just add tokens in the respective erc20 and nft tokens spells that already exist on ethereum: 
https://github.com/duneanalytics/spellbook/tree/main/models/tokens/ethereum

**Comment by samisbakedham** [comment]
> Hi @samisbakedham, if I understand it well, those tokens are actually on Ethereum right ? Dune does not index the Candle blockchain afaik, so I don't think it's necessary to create new tables, you could just add tokens in the respective erc20 and nft tokens spells that already exist on ethereum: https://github.com/duneanalytics/spellbook/tree/main/models/tokens/ethereum

These tokens are on Candle, how do we enable the indexing of it?

**Review by soispoke — COMMENTED** [review]
I'm afraid Dune would first have to index Candle as a blockchain first before adding any new tables/tokens. Please submit feedback and propose to index the Candle blockchain before submitting PRs like this one 🙏
https://feedback.dune.xyz/

**Comment by jeff-dude** [comment]
closing this PR until candle is evaluated and built on dune, then spells can be added on top

**Comment by samisbakedham** [comment]
> closing this PR until candle is evaluated and built on dune, then spells can be added on top

Let's do it then

**Comment by jeff-dude** [comment]
https://feedback.dune.xyz/features/p/support-for-candle-network

**Pull request closed without merging**
