### PR TITLE
Update Ethereum/Optimism/Polygon Safe Balance V2

### PR DESCRIPTION
**Pull request by safeintern**
Made changes because previous version doesn't properly capture the balances for the safe

### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by 0xRobin** [comment]
Hi, I will be working on an incrementally enabled macro to materialize balance in [this PR](https://github.com/duneanalytics/spellbook/pull/6608) today. 
The goal is that it will be directly applicable for Safe as well and should resolve the incremental problems you were seeing.

**Comment by safeintern** [comment]
> Hi @safeintern, I will be working on an incrementally enabled macro to materialize balance in [this PR](https://github.com/duneanalytics/spellbook/pull/6608) today. The goal is that it will be directly applicable for Safe as well and should resolve the incremental problems you were seeing.

thanks! curious if my approach now works but if your solution is more efficient, great!

**Comment by safeintern** [comment]
@0xRobin is there any update on this?

**Comment by 0xRobin** [comment]
Yes, we've got the new macro to materialize balances merged, I'll test that out today in this PR

**Comment by 0xRobin** [comment]
Performance is worrisome here, I will revert my commits and we can seek to merge your changes. 
I'll have to experiment more but don't want to block your progress as well.

**Review by 0xRobin — APPROVED** [review]

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
