### PR TITLE
Adds Clipper Coves to dex.trades on Optimism

### PR DESCRIPTION
**Pull request by aothman**
Brief comments on the purpose of your changes:
Clipper Coves recently launched on Optimism, allowing users to trade arbitrary tokens.

This PR, based on Clipper Coves Polygon, adds Coves support to dex.trades on Optimism.

### CODE REVIEW

**Comment by jeff-dude** [comment]
@aothman i can begin working on this, but in the meantime, can you update the PR to reflect our new repo structure? note that this directory now lives within our 'deprecated_v1' root directory

**Review by jeff-dude — CHANGES_REQUESTED** [review]
history is filled, automation enabled. just waiting for repo update to reflect here.

**Comment by aothman** [comment]
@jeff-dude I believe I've done this now but please let me know if it doesn't fit your expectations. It looks like the whole repo changed right after this PR was created!

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
> @jeff-dude I believe I've done this now but please let me know if it doesn't fit your expectations. It looks like the whole repo changed right after this PR was created!

yep, we changed the repo to optimize for spellbook and new spells on v2 engine. would love to help get you on board, seems like clipper is a great fit to roll into the new dex trades there, as it's cross-chain

**Pull request merged**
