### PR TITLE
Spellbook Workshop Submission

### PR DESCRIPTION
**Pull request by mtitus6**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [X] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [X] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [X] if adding a new model, I added a test
* [X] the filename is unique and ends with .sql
* [X] each sql file is a select statement and has only one view, table or function defined  
* [X] column names are `lowercase_snake_cased`
* [X] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [X] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [X] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by dot2dotseurat** [comment]
Thank you for participating in our Spellbook workshop competition! It was a close race and although your submission didn't win, there will be future opportunities to participate in Spellbook hackathons and bounties (launching soon). we hope you learned something new and had some fun.

**Comment by mtitus6** [comment]
Thanks Meghan.. It was a great learning experience anyways.  From a general learning standpoint, was there anything in my PR that you would have structured differently?  I plan on doing another project, so just trying to get ahead of any best practices I might have missed.

**Comment by dot2dotseurat** [comment]
> Thanks Meghan.. It was a great learning experience anyways. From a general learning standpoint, was there anything in my PR that you would have structured differently? I plan on doing another project, so just trying to get ahead of any best practices I might have missed.

Of course! This was a strong submission. These are just suggestions to make it better. Nothing you did was wrong and we would love to keep working with you. And I think you should definitely go after some bounties (Boxer will release more info on those soon). 

-  More informative tests. 
The non_null test on pool from the workshop was illustrative of the ability to add tests but isn't the most meaningful in terms of data quality. Something that I think could have been useful would be a uniqueness test on multiple columns. So ensuring there is only one cumulative amount recorded for each token/pool pair per day. Or a test to confirm if there are negative values in the cumulative amount. You could have also manually copied some values from the V1 abstractions and wrote a custom test to see if the values in V2 matched V1.  

- Minor formatting changes. models/balancer/ethereum/balancer_ethereum_sources.yml has some extra white space at the bottom. tbh not that big of a deal but a nice thing to watch out for. 

- Post hooks instead of alter_table_properties. I didn't include this in the judging since we just implemented this but we can define the block explorer information in a posthook now like it's done in this spell. https://github.com/duneanalytics/spellbook/blob/e4ca8ffa6fd976850152702725ec760229af60fd/models/nomad/ethereum/nomad_ethereum_view_bridge_transactions.sql#L5

**Comment by mtitus6** [comment]
Thanks for the kind feedback and I appreciate the advice.

I saw the bounties posted but was clearly too slow😥.  Next time

I hate to bother with more questions but I had no luck in the Discord.

What is the best way to check for what others are actively working on and
to broadcast that I am actively working on a new spell?

I ask because I created uni v3 trades, got all the way to the pull request,
and realized the code was already added.  No biggie, was a great practice
for me but made me realize I have a lot to learn about contributing to an
open source project.

For example, I would love to work on the Polygon and Arbitrum Uniswap
trades tables.  How do suggest I start that from a communication
perspective?

**Comment by dot2dotseurat** [comment]
@mtitus6 I think there will be a fair amount of Polygon work coming up soon. We are still working out the details of that. 

You raise a good point on how to coordinate work. We don't have a great system for that now. Generally, people have worked on what interests them most and we haven't had a huge problem with overlapping work (to my knowledge). 

For now, I think discord is still probably the best bet for communicating that you're about to start working on something. I saw today 1chioku and Springzhang coordinating on some sybil network stuff.  

I'll chat with our community team to see if they have any better ideas.

**Pull request closed without merging**
