### PR TITLE
Update dex readme with architecture overview

### PR DESCRIPTION
**Pull request by Hosuke**
New [README preview](https://github.com/duneanalytics/spellbook/blob/c028982059f6743d3eafceb8182a46e2bf770fce/models/_sector/dex/readme.md)

### CODE REVIEW

**Comment by jeff-dude** [comment]
testing something here
dex_trades_architecture_overview

**Comment by couralex6** [comment]
Testing something too

test

**Comment by couralex6** [comment]
test

**Comment by jeff-dude** [comment]
okay, got it to work now. including directly in readme vs storing file in repo separately.
- open gh issue
- upload image to desc
- copy/paste link there and use in readme
- remove file from repo
- discard dummy issue

**Review by jeff-dude — APPROVED** [review]
thanks for getting this built out -- looks great!

**Pull request merged**
