### PR TITLE
Add Zora Network to the UserOps table

### PR DESCRIPTION
**Pull request by intensodefi**
### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [x] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** Add userops to zora blockchain

---
I will add seed once the data is indexed

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @intensodefi 

[Sample account_abstraction_erc4337_zora_account_deployed](https://dune.com/queries/3903725)
[Sample account_abstraction_erc4337_zora_userops](https://dune.com/queries/3903716)

**Comment by Hosuke** [comment]
By the way these two views currently do not have any result.
@intensodefi do you think this is normal/expected?

**Comment by intensodefi** [comment]
@Hosuke I have just submitted the contracts for decoding a few hours ago. Therefore, I think data is currently being indexed right now. That's reason why we still haven't got any results so far

**Comment by intensodefi** [comment]
@Hosuke I got result for userops table now. AccountDeployed table shall be ready soon.
**test_schema.git_dunesql_b42c6f1_account_abstraction_erc4337_zora_userops**

**Comment by intensodefi** [comment]
@Hosuke The PR is ready for your review now. I got results for both views
**test_schema.git_dunesql_8e3080f_account_abstraction_erc4337_zora_userops**
**test_schema.git_dunesql_8e3080f_account_abstraction_erc4337_zora_account_deployed**

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
