### PR TITLE
[Ready For Review] init Balancer CoWSwap AMM spells

### PR DESCRIPTION
**Pull request by viniabussafi**
### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---
This PR covers the new Balancer CoWSwap AMM pools. They are built on top of Balancer V1 and the GPV2Settlement contract. Therefore, these spells are heavily inspired on balancer_ethereum_balances, balancer_v1_ethereum_liquidity, labels_balancer_v1_pools and cow_protocol_ethereum_trades, making the adaptation to accomodate the novelties.
The trades spell should be integrated into dex.trades on a new PR, if you don't mind, as I would like some more data just to make sure everything is alright.
New chains will probably be integrated in the future as well (at least arbitrum and gnosis), so I took the liberty of already creating the future cross-chain tables

- **Spell name(s):** *balancer_cowswap_amm_{{chain}}_trades*
- **Description:** All trades on the GPV2Settlement contract on pools deployed by BCoWAMM pools
- **Who are the new spell(s) for?** general community
---
- **Spell name(s):** *balancer_cowswap_amm_{{chain}}_balances*
- **Description:** Daily balances per pool and token
- **Who are the new spell(s) for?** general community
---
- **Spell name(s):** *balancer_cowswap_amm_{{chain}}_liquidity*
- **Description:** Daily tvl per pool and token
- **Who are the new spell(s) for?** general community
---
- **Spell name(s):** labels_balancer_cowswap_amm_pools_{{chain}}
- **Description:** Labels for all pools deployed by the BCoWAMM pool factory
- **Who are the new spell(s) for?** general community

### CODE REVIEW

**Comment by jeff-dude** [comment]
while we end goal is to feed into `dex.trades` (based on description), the models aren't quite written in the design necessary in current state. i think that's fine, since you mentioned wanting to monitor these tables first anyway. with that in mind, these should live in the `daily_spellbook` subproject for now. when we're ready to refactor and put into dex, we can take those steps at that time

**Comment by viniabussafi** [comment]
> also wondering if it makes sense to use just balancer in the directory path, rather than the longer name? this is a project owned by balancer?

Also agree that naming is quite atrocious at the moment, but can't think of anything better. This project is co-owned by Balancer and CoWSwap: [CoW CIP](https://snapshot.org/#/cow.eth/proposal/0x5a7435a287fda55133fa5973b4979465687c341def703564986f2771780352b0), [Balancer BIP](https://forum.balancer.fi/t/bip-628-balancer-cow-protocol-strategic-partnership-launching-cowamm-pools/5813)

**Comment by viniabussafi** [comment]
moved everything into daily_spellbook, @jeff-dude! Will follow-up on future PR to include new chains and tweak the spells

**Comment by jeff-dude** [comment]
okay, i think we should be final (pending CI).
- merged in main to reflect latest subproject structure
- updated source files. you can continue to use project directories for sources that read decoded tables. the subproject output sources should only be other spells which are referenced across projects
- moved files back into new daily spellbook directory
- minor formatting
- removed post hooks for now, we can look to add in future if needed

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
