### PR TITLE
add zkswap_finance_v3 to trades

### PR DESCRIPTION
**Pull request by ZkSwapFinance**
## Thank you for contributing to Spellbook 🪄
Please open the PR in **draft** and mark as ready when you want to request a review. 

### Description:
Add zkSwapFinance exchange v3 to trades. 
More info at: https://docs.zkswap.finance/contracts-and-audits/smart-contracts/zkswap-exchange
[...]

---
quick links for more information:
- [README.md](https://github.com/duneanalytics/spellbook/blob/main/README.md)
- [spellbook docs](https://github.com/duneanalytics/spellbook/tree/main/docs)
- [CONTRIBUTING.md](https://github.com/duneanalytics/spellbook/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ZkSwapFinance** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZkSwapFinance** [comment]
@0xRobin @jeff-dude

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @ZkSwapFinance 

[Sample zkswap_finance_v3_zksync_base_trades]()

**Review by jeff-dude — APPROVED** [review]
thank you for the patience, i will be looking to do merges tomorrow

**Pull request merged**
