### PR TITLE
add chains to swaap_v2 dex

### PR DESCRIPTION
**Pull request by borelien**
**Description:** adding chains to swaap_v2 dex in dex.trades

### CODE REVIEW

**Comment by borelien** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Hosuke** [comment]
Hi @borelien , please run `git merge main` to update this PR.

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @borelien

**Comment by borelien** [comment]
thks @Hosuke !
I just rebased main

**Comment by borelien** [comment]
just rebased again

**Comment by borelien** [comment]
anything to do on my end to have the PR merge?

**Comment by Hosuke** [comment]
> anything to do on my end to have the PR merged?

Nothing. We just need to wait for the next batch mergning.

Or you can regularly run `git merge main` to update this branch.

**Pull request merged**
