### PR TITLE
add oneinch to dex aggregator

### PR DESCRIPTION
**Pull request by jeff-dude**
there is still an outstanding issue for oneinch #3030 

we don't have a solution quite yet, but this issue also persists in the original code from v1 engine. we can move forward knowing that the bug needs resolved and short-term fixes may be necessary to filter out tx's which blow up `amount_usd`

~~edit: looking to add test for `amount_usd`, but will require thought on how to run in prod~~
will follow up with new PR to add tests

### CODE REVIEW

**Review by augustog — APPROVED** [review]
Lgtm!

**Comment by bh2smith** [comment]
I think that putting left commas on the erc20 token list did not belong here and should be reverted. If we want to go left commas its fine, but not without warning and in a totally irrelevant PR!

**Comment by jeff-dude** [comment]
> I think that putting left commas on the erc20 token list did not belong here and should be reverted. If we want to go left commas its fine, but not without warning and in a totally irrelevant PR!

you're correct, that was oversight on my part. we'll work together to get this back in a solid state.

**Comment by jeff-dude** [comment]
fyi @gentrexha -- i do believe you wanted a heads up once this data was available

**Comment by gentrexha** [comment]
> fyi @gentrexha -- i do believe you wanted a heads up once this data was available

Yes, I did. Thanks!

**Pull request merged**
