### PR TITLE
[Easy] [ERC20] Add 117 missing tokens

### PR DESCRIPTION
**Pull request by gentrexha**
Usual missing tokens update. Some of these have emojis in them. Not really sure how to handle those.

```
python -m src.missing_tokens
Execute on Network Network.MAINNET
Fetching V2 missing tokens for Network.MAINNET from https://dune.com/queries/1403073?Blockchain=ethereum
2023-05-05 10:03:47,954 INFO dune_client.client waiting for query execution 01GZNF0HCGZX9WKKFWSNE3VN9H to complete: ExecutionState.EXECUTING
Found 0 missing tokens on V1 and 117 on V2. Fetching token details...

V1 results:



V2 results:

('0x0212625d381ca301880533d8dad01f1988ba763f', 'MOON', 18),
('0x02d3d5882490991970c35c9c6e3a64e03ffd4dfc', 'WSPEPE', 18),
('0x0414d8c87b271266a5864329fb4932bbe19c0c49', 'WSB', 18),
('0x049e9f5369358786a1ce6483d668d062cfe547ec', 'CHECKS', 18),
('0x0ab59317164c2bb619d5beeb1ebcb628e1aa06c8', 'ELSAPO', 9),
('0x0c9098c40a40ef89fc47528aec3038e4abf7f5e2', 'TOADZ', 18),
('0x1032abe2902a23ddcbab085c20e0e69c33ceb8fa', 'SNAKE', 18),
('0x11fac889bc1e9e1f043fc575bf817d336a258641', 'MAX', 18),
('0x122303734c898e9d233affc234271f04e42e77ad', 'Cat', 18),
('0x137469b55d1f15651ba46a89d0588e97dd0b6562', 'BADGERWBTC-f', 18),
('0x15534f223bd53b3a2f573453e53f2cd6bce7fb42', 'DN', 18),
('0x169495fd23b4cec644c45fbd8f953407c9de4e76', 'DN', 18),
('0x1811b049f045b86f5bc0f36644ed17ca98c3c803', 'PANDA', 18),
('0x184da821bd956cafc598dcb4fa9b8e040c45ada1', 'TRBNR', 9),
('0x1926f950f7d81e5f609d2abf257a573262d748a5', 'BTK', 18),
('0x1b0d5f7a6f08fcd65efa036bc13a9e438167c24e', '8-Bit Elon', 9),
('0x1ed799d4ac91459adb73c638dfdbec67a35fbd24', 'TRBNR', 18),
('0x1ef840cfaaf7225f37388fcd1669ae7e17072ef4', 'APE', 9),
('0x2368fd5f713de6a81acc662ae4334afba5055758', 'BRRR', 18),
('0x2454f2b6661276a7f33b3f594d6b34014aa436d0', 'SNEAKY', 18),
('0x25722cd432d02895d9be45f5deb60fc479c8781e', 'SPONGE', 18),
('0x2981c7d25f44f95bd22286ff071db5f28b98a53d', '🚫🧢', 18),
('0x31271a9df797c330f743deb08e6e80799b162566', 'BOI', 18),
('0x333c9e4f61de80b028e5eda5ad77aeffd9ad20cf', 'MIDA', 6),
('0x335f4e66b9b61cee5ceade4e727fcec20156b2f0', 'ELMO', 18),
('0x3398b3d448beab3a12c21cfc5e6e630e512ca341', 'Chud', 18),
('0x39b448ed2dce5659fa6635bd9a9c380393e583a3', 'JUGGS', 18),
('0x39dfd50c197f9288d21a308758dbd080d2ae8128', 'biz', 18),
('0x3bef42ac9fe692680dfa402515ef738c65acc657', 'PEPEBULL', 18),
('0x3ced168d89962b3419c62d2032cda262b250066a', 'V', 18),
('0x3d2b66bc4f9d6388bd2d97b95b565be1686aefb3', 'LAMBO', 18),
('0x3e32ab1f70d8caf3306baf4398738c35697d9b8f', 'POPO', 8),
('0x3e50a628f4aee9a9a88a8d2b965a4a76ffa79b50', 'WONKA', 18),
('0x3f7d1c62a8456893c0f55c13e3b5993d2f68287a', 'FROKI', 18),
('0x41e1ef16ff3dea3b9c10e99077bc91ef607e0e4e', 'FOMC', 18),
('0x426df698386ea0fd51658bd5ea9089309dcb7c6d', 'Candy', 9),
('0x43baa9019d44bfa1c4395cf869ccfff7c09f4b28', 'BASED', 9),
('0x465808f64774cc340f6d5515c10d7ffee4a4dff0', 'PIVOT', 18),
('0x48011585b026b451ab2902ff611f4ae82d1b1bc1', 'WEN', 9),
('0x4bf2069f825540cb08e3e5bf22381412dd944e65', 'SEXYPEPE', 18),
('0x51404d261ecb1d8a0afb700dce28a049895a2383', 'BUTT', 18),
('0x54debe126da16a8fcaa67285d6830c3a7c6752fd', 'Steve', 9),
('0x551d0501cd5df92663c3d12c3201c9d70ba79998', 'YOBASE', 18),
('0x55d22e8df391d2d449d0111ca07cfc1de37746da', 'WSD', 18),
('0x57d5f53cab3882edf7d2dd6f2e0d7b3300cccc98', 'STD', 18),
('0x57d8dc5ef3762395ab1e842473354cec9ab14f5b', 'MIDA', 6),
('0x58f121917a75db7bfddad151000030ad4e7f5933', 'BC', 9),
('0x5b65a0ff66f40ad0404f7749edfbce830da8ae37', 'YODA', 18),
('0x5ccda66ea68e787459ad781dfbbbb5f1fd4171fb', 'INSHALLAH', 18),
('0x5f59edfb93498abf59afeb6a0d73260c115a2162', 'RICH', 8),
('0x6381ab15ffbafa0fc1b733cc8b009ffae27dd9e7', 'Billy', 18),
('0x64145ea43df747f78edc7369a01871fbddc6e3dc', 'GREEN', 9),
('0x64551fa4093c2d6c298cf1792740f884084a8f69', 'SPGBB', 18),
('0x64a2f3f9a84ff8a60e128f9003c215712b1bf66d', '$PAPI', 18),
('0x65381dd16168623dcb9bf08dc99f9bd28af2ed5f', 'GOPHER', 18),
('0x66be46376e90ea83a1dd05eb0aae1805c778504d', '$TPEPE', 18),
('0x6802ef8b502bfac0f6effddb01bca2f299ed7875', 'HRMBE', 18),
('0x69b14e8d3cebfdd8196bfe530954a0c226e5008e', 'SpacePi', 9),
('0x7131df0d8ca995cafecad61e181e6f32df48b580', 'MOV', 8),
('0x750a575284fad07fbf2fcc45eb26d1111afee165', 'FORCE', 18),
('0x76fcf0e8c7ff37a47a799fa2cd4c13cde0d981c9', '50OHM-50DAI', 18),
('0x77571a64342667f7818520ef004b2b91f47a266b', 'SNM', 18),
('0x7945b0a6674b175695e5d1d08ae1e6f13744abb0', 'BaoUSD', 18),
('0x8025d6c18807c4ff46f316c1942462b907119c7e', 'PEPEGA', 8),
('0x84c056acdcfedc1ab79a32993aa3125eecef5d9a', 'PECHU', 18),
('0x8522ebc1ff41687cecaab09b1302da1f42b6f6a3', 'WOKEPEPE', 18),
('0x86eab36585eddb7a949a0b4771ba733d942a8aa7', 'REDDIT', 9),
('0x881d637877c304b91e9244939cb7d8627f0d1303', 'YUMMY', 9),
('0x898da829be1757095860a442a33c2e07aef6b9da', 'PEEP', 18),
('0x8a944bb731e302fdb3571350513f149f15fcbe34', 'RIZZ', 18),
('0x8df566cb30994babc1bf4702b811a7afae47e043', 'WHAT', 18),
('0x8f4a616463e14442a6c26ea0c7f64db4ba9c4b9f', 'THEX', 18),
('0x929b61908df08e8637ba1fe03a505dab78ed8902', 'MPEPE', 18),
('0x92d01d01fb6704eda1d2bdbae41d7db9d07ceec6', 'POGE', 9),
('0x95be23d48155162cf82afd99a68a2b6af7692b1b', 'TETE', 9),
('0x9b0c67713790ae6cc68fad9ee59eb14456649249', 'GLIZZY', 18),
('0x9f1fe7af2909d7eb3e891d33a7f5ac5237425f37', 'ATH', 9),
('0xa15865d9de09cb96aaa3a9081b3dfc8481f07d33', 'POPE', 18),
('0xa1974e043bb6d31e87cd64dc02acad153f5d53cf', 'PIGLET', 9),
('0xac156acebfe694aa2796c0c52bcf622302153f71', 'BLAPE', 9),
('0xaee9ba9ce49fe810417a36408e34d9962b653e78', 'SNIBBU', 9),
('0xb08686f3bf55a1ea172542d161a63350baf9e219', 'IKUN', 18),
('0xb2c3cceae436b9101f3a7b878aa04933fba69eb0', '$MONGA', 18),
('0xb4e3a50ea625c71042499e9c8a4e069530147aab', 'GM', 18),
('0xb69753c06bb5c366be51e73bfc0cc2e3dc07e371', 'POOH', 18),
('0xb6a5b010ebf40031269962a2520eb54174045ceb', '$ZOOMER', 9),
('0xb92ebb3973fc8942664dac8788770e533b3ecf66', 'OB1', 18),
('0xbae9992488ae7f7c1edb34ed74c213b28d928991', 'WYD', 18),
('0xbc0f2372008005471874e426e86ccfae7b4de79d', 'bb-i-USDC', 18),
('0xc08e7911ee27169967ed8ec252fee73048cc0dff', 'PepeCash', 18),
('0xc99156c34260ae579c9eaf63f0e88fd47af064b9', 'BEAST', 18),
('0xcb3d566da04094f6e5bd7419cf3627df80c5b99a', 'FGT', 18),
('0xcf1e086a145dd7b5b771b1e6acbbc1d2b58d7e80', 'GENW', 18),
('0xcf5c5f572ed550b9669f6de9e3bb87bf7faa918b', '🐸', 18),
('0xd057f20762c0c003d7291247b9d5b5939fe508c7', '$RIZZ', 18),
('0xdb2c75dd52f379baf279d3e603d2d4df0d5c9c1a', '💎🙌', 18),
('0xdba274b4d04097b90a72b62467d828cefd708037', 'bb-i-DAI', 18),
('0xdd53e7944fbe2f0eb5c024caab96bbd5a818166c', 'YODA', 18),
('0xdd78b3e430361560a70b9cbb7d98d961f0428b61', 'Pat', 18),
('0xdd84ca5066c9a334a6f1d87dbef6e8b3dc432330', 'PIPI', 18),
('0xe0a458bf4acf353cb45e211281a334bb1d837885', '4CHAN', 9),
('0xe1ec350ea16d1ddaff57f31387b2d9708eb7ce28', 'PC', 9),
('0xe22f94e75b411257fa5dca7804f00e712db5350e', 'BULLS', 18),
('0xe30773d49293978cc1baa873afa735c715d15a81', 'GULAG', 18),
('0xe30f50e598e71f091f0e95a37f51d1558fd25a0b', 'WSC', 18),
('0xe46091dce9c67691bcf22768bbee0bc9e20d4beb', 'WSBC', 9),
('0xe5cf28aac55c70ba4d815dfc65b002221a76aa47', 'PEPITO', 18),
('0xe68fb107710c59154ea15d5e0221d37bcda5c1fc', 'SHINARIUM', 18),
('0xecbee2fae67709f718426ddc3bf770b26b95ed20', 'CLIPS', 18),
('0xed328e9c1179a30ddc1e7595e036aed8760c22af', 'MCADE', 18),
('0xf1182229b71e79e504b1d2bf076c15a277311e05', 'LBR', 18),
('0xf12ccd17759367cf139776710b47b00c43d1ac2b', 'Emoji', 9),
('0xf7168c8abb0ff80116413a8d95396bbdc318a3ff', 'KEKE', 7),
('0xf951e335afb289353dc249e82926178eac7ded78', 'swETH', 18),
('0xfb272d3acfcbf3e0f92bd01ffbcde92575c371f9', 'JPOW', 9),
('0xfca99bf40253563f619b5fbaed621021b2987a09', 'zjz', 18),
('0xfe60fba03048effb4acf3f0088ec2f53d779d3bb', '3d3d', 18),

```

### CODE REVIEW

**Review by Hosuke — APPROVED** [review]

**Comment by bh2smith** [comment]
> how important is the metadata on most of these?

Its pretty important to know the token decimals (symbol doesn't matter) but having decimals is the only way to do accounting with prices.usd.

**Comment by jeff-dude** [comment]
> > how important is the metadata on most of these?
> 
> Its pretty important to know the token decimals (symbol doesn't matter) but having decimals is the only way to do accounting with prices.usd.

what % of those trades with a missing token have the other side available? and if available, what % is it a reliable token such as eth/usdc/etc?

we're working on restructuring the design of underlying spells in dex trades & with that establishing a more consistent approach to `amount_usd` by looking for the more reliable tokens in a trade first, especially with all the coinpaprika data quality issues

**Comment by bh2smith** [comment]
So, knowing the % of trade involving one known  token and one non-known token is only enough information to estimate the USD value of a trade, but not enough to do proper "slippage accounting" that is what is the value of incoming token and outgoing token (for this we need to know the token units of both sides). 

The reason I would like to add a few more (note the query shows "popularity" as in number of occurrences in trades) is so that we don't have to add 100 every 3 days...

**Comment by jeff-dude** [comment]
> So, knowing the % of trade involving one known token and one non-known token is only enough information to estimate the USD value of a trade, but not enough to do proper "solver slippage" accounting; that is what is the net token imbalance at the end of a single transaction (incoming and outgoing token ledger) - for this we need to know the token units of all tokens.
> 
> The reason I would like to add a few more (note the query shows "popularity" as in number of occurrences in trades) is so that we don't have to add 100 every 3 days...
> 
> If I bump the "popularity" up to 100 (i.e. token has appeared in at least 100 trades since StartTime) there are only 7000. Does that seem reasonable?

much better for the short term. this is good info though, thanks for sharing. i'll use this to bring to the team to raise awareness for reworking the tokens process.

**Comment by jeff-dude** [comment]
let me know if you'd like to proceed with this PR or wait for your updated script output. i think we can reason with 7k more since we're over 20k already.

**Comment by bh2smith** [comment]
You can go ahead and merge this one, I will prepare a bigger one after this lands (so I don't wind up with duplicates). Also not sure if I am going to get rate limited making so many eth RPC calls. Might have to run my script with a sleep delay over the weekend...

**Review by jeff-dude — APPROVED** [review]
fyi on the emojis:
image
no symbol, but decimals are available. based on convo here, i imagine that's acceptable

**Pull request merged**
