### PR TITLE
Migrating aztec v1 spells to v2 (Ready for review)

### PR DESCRIPTION
**Pull request by henrystats**
Brief comments on the purpose of your changes:

Migrating some of [Aztec abstractions](https://github.com/duneanalytics/spellbook/tree/main/deprecated-dune-v1-abstractions/ethereum/aztec_v2) (v1) to spells (v2). 

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by henrystats** [comment]
So the reasons why the tests are failing is because of a duplicates which is to be expected since rollup bridge transfers is a table that contains the flow of tokens of aztec connect bridge DeFi transactions. 

See readme of v1 for more details - <https://github.com/duneanalytics/spellbook/tree/main/deprecated-dune-v1-abstractions/ethereum/aztec_v2>

**Comment by augustog** [comment]
gm @henrystats, thanks for yet another addition to spellbook!

I had a look at the test results and they seem to spotting some duplicates. Could you try running the compiled sql on dune.com to check what the cause may be?

I'm happy to help if you need any pointers :)

**Comment by henrystats** [comment]
Thank you very much ser @augustog, I'm going to be working towards identifying the problem today.

I'm using the same query from v1 so not sure where the dupes could be from at the moment but I'll be working on it in the next few hours. Thank you very much for your help ser, I'll ping you if I need your help, I appreciate.

**Comment by henrystats** [comment]
Hola ser @augustog, I need help here ser pls. I've been troubleshooting this and can't seem to figure out what could be wrong. the v1 version still works correctly and it's the same code I'm using here except a change which is in the labels. 

This is the test schema from the gh action that has dupes - https://dune.com/queries/1545428

This is the compiled query on dune that doesn't have dupes - https://dune.com/queries/1559977 

This is the compiled query on dune but I made an update where I included the additional labels I added to the labels.aztec table - https://dune.com/queries/1558659 - this also has no dupes. 

So it looks like the label is breaking this, but I've no idea why or how and can't seem to figure it out.

**Comment by henrystats** [comment]
pr resubmitted her e- https://github.com/duneanalytics/spellbook/pull/1941

**Pull request closed without merging**
