### PR TITLE
Add fantom balances (erc[20, 1155, 721]), FTM to balances spell - Help Needed

### PR DESCRIPTION
**Pull request by henrystats**
Hola 👋 - I'd love to add FTM (ERC20, ERC1155 & ERC721) balances to the balances spell. 

I've mirrored the set up for erc20 balances for ethereum. I do want to note that the transfers_ethereum.erc20 table is currently not incremental and instead materialised, was there a reason for this or shall I adjust my spell so it's incremental incase that will increase it's performance. 

I'd also love to work on an FTM balances spell but want to get this reviewed first as I guess I'd have to make a lot of changes. 

Edit: The test run in quite a short time (15mins or so) so I've added balances for FTM as well

### CODE REVIEW

**Comment by henrystats** [comment]
erm the gh actions was running fine not sure what happened haha. I didn't make any changes to the seeds mentioned. 

The tests have originally passed and the balances are showing properly except for some tokens which I assume are rebase tokens not listed in the fantom.rebase erc20 tokens list, will submit a push to update.

Tested the balances_erc20_latest with this query using the schema file - <https://dune.com/queries/1795043>

**Comment by henrystats** [comment]
The FTM balance returned is incorrect so trying to fix.

**Comment by henrystats** [comment]
not sure what's wrong as the balances are returning inaccurate values for a lot of the wallets but it's also correct for some (the code looks correct).

https://dune.com/queries/1798466?d=1

**Comment by 0xRobin** [comment]
I've taken a quick look but didn't get any wiser.
We should try to find a wallet address with a low number of transactions that still has wrong balance info.
Then we can try and pinpoint which transfers are not getting represented.

**Comment by henrystats** [comment]
ty ser, I'll take a look today!

**Comment by henrystats** [comment]
@0xRobin I've taken a look and seem to have found the error. 

The `from` of this particular transaction that is causing the balance to reflect incorrectly is returning **0** in the fantom.traces table. 

https://dune.com/queries/1886784?d=1

**Comment by henrystats** [comment]
Thank you very much sir!

**Comment by 0xRobin** [comment]
@henrystats small update, issue has been tracked down but we're still working on resolving it.

**Comment by henrystats** [comment]
Thank you ser @0xRobin!

**Comment by 0xRobin** [comment]
@henrystats another small update, issue should be fixed upstream.
We expect around ~2 weeks until we have the correct data in Dune.

**Comment by 0xRobin** [comment]
update: still waiting on the upstream fix from our data provider.

**Comment by jeff-dude** [comment]
closing due to inactivity, can be reopened as needed in future

**Pull request closed without merging**
