### PR TITLE
Critical bug fix for `balancer_v2.trades` spells

### PR DESCRIPTION
**Pull request by thetroyharris**
# Critical bug fix for Balancer Trades entries in `dex.trades` by fixing: 
- `balancer_v2_arbitrum.trades`
- `balancer_v2_ethereum.trades`
- `balancer_v2_gnosis.trades`
- `balancer_v2_optimism.trades`
- `balancer_v2_polygon.trades`

# SPELLBOOK FREEZE

From June 22 to June 29, we will be freezing some Spellbook contributions for the migration to DuneSQL. We will not accept contributions to the lineage of the following models:

* dex.trades
* nft.trades
* labels
* token.erc20
* tokens.nft

Run the following command to see the list of affected files:

```
dbt ls --resource-type model --output path --select +dex_trades +labels +nft_trades +tokens_nft +tokens_erc20
```

Don't hesitate to reach out on Discord if you have any questions.

Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by thetroyharris** [comment]
@jeff-dude 

This is the fix for the issue you informed me about. Thanks again for that.

Seems to be auto-canceling `dbt slim ci (in beta) / dbt-test (spark) (pull_request)` not sure why.

**Comment by couralex6** [comment]
Hey @thetroyharris, I had to cancel your workflow, we're fixing a bug that's forcing a full refresh on the entire project (not just the models affected by the PR.

I'll start it up when we fix it

**Comment by couralex6** [comment]
Just restarted the job @thetroyharris

**Comment by thetroyharris** [comment]
> Hey @thetroyharris, I had to cancel your workflow, we're fixing a bug that's forcing a full refresh on the entire project (not just the models affected by the PR.
> 
> I'll start it up when we fix it

Gotcha, thanks for letting me know Alex!

**Comment by thetroyharris** [comment]
Fixed across all files. Good to go on my end.

**Review by mendesfabio — APPROVED** [review]

**Comment by thetroyharris** [comment]
@jeff-dude 

PR has passed the ci. Can we look to merge soon?

**Comment by thetroyharris** [comment]
@jeff-dude

GM sir, hope you had a nice 4th :)
The PR has passed the ci. Can we look to merge soon?

**Comment by jeff-dude** [comment]
> @jeff-dude
> 
> GM sir, hope you had a nice 4th :) The PR has passed the ci. Can we look to merge soon?

yes, let's ensure the CI test runs now (i just merged main again). previously, due to another PR merge, it tried to run far too many models and timed out. ideally now we will just see the modified ones here.

thanks again for the patience -- more to come tonight on how to start contributing on dunesql!

**Comment by thetroyharris** [comment]
> > @jeff-dude
> > GM sir, hope you had a nice 4th :) The PR has passed the ci. Can we look to merge soon?
> 
> yes, let's ensure the CI test runs now (i just merged main again). previously, due to another PR merge, it tried to run far too many models and timed out. ideally now we will just see the modified ones here.
> 
> thanks again for the patience -- more to come tonight on how to start contributing on dunesql!

Interesting -- when it passed the CI earlier today it only ran the modified models. Later on I updated the branch and then it failed due to timing out after trying to run a lot of models.

Hopefully, it passes this time. Excited to learn more about contributing in DuneSQL.

**Comment by jeff-dude** [comment]
for your awareness, the reason it ran so many is because another PR had an edit which hit all 1k+ models. i merged that PR right about the same time you merged main into your branch here.

when i merge another PR to `main`, [this](https://github.com/duneanalytics/spellbook/actions/workflows/commit_manifest.yml) gh action runs to commit a dbt manifest file to our data lake that shows current state of spellbook on `main`. this gh action sometimes takes a long time to complete -- looks like ~40 minutes the most recent merge as you can see at the link there. if any open PR pushes a commit while that action is in progress, the PR will think it needs to run all the models contained in that other PR recently merged too, since it hasn't fully completed yet.

when in doubt, or see more models running than expected, check that actions page for that workflow. if in progress, you have your answer. if recently completed, it could still have overlapped. a new commit when you're certain it's done will ideally then only run your models.

**Comment by thetroyharris** [comment]
> for your awareness, the reason it ran so many is because another PR had an edit which hit all 1k+ models. i merged that PR right about the same time you merged main into your branch here.
> 
> when i merge another PR to `main`, [this](https://github.com/duneanalytics/spellbook/actions/workflows/commit_manifest.yml) gh action runs to commit a dbt manifest file to our data lake that shows current state of spellbook on `main`. this gh action sometimes takes a long time to complete -- looks like ~40 minutes the most recent merge as you can see at the link there. if any open PR pushes a commit while that action is in progress, the PR will think it needs to run all the models contained in that other PR recently merged too, since it hasn't fully completed yet.
> 
> when in doubt, or see more models running than expected, check that actions page for that workflow. if in progress, you have your answer. if recently completed, it could still have overlapped. a new commit when you're certain it's done will ideally then only run your models.

Thanks for sharing that insight with me! I will make sure to keep an eye on that page in the future to try and avoid such occurrences.

**Comment by jeff-dude** [comment]
thanks again for the patience!

**Pull request merged**
