### PR TITLE
bnb chain contract mapping

### PR DESCRIPTION
**Pull request by davidcheongyl**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
thank you @davidcheongyl -- please do look at my commit to PR here for reference to finalize this model

**Comment by davidcheongyl** [comment]
thanks @jeff-dude for review and merge. did you add this chunk of metadata code for me into contracts_bnb_contract_mapping.sql? i dont recall adding these btw. 1st time spellbooker here

{{
  config(
        alias='contract_mapping',
        post_hook='{{ expose_spells(\'["bnb"]\',
                                    "sector",
                                    "contracts",
                                    \'["davidcheongyl"]\') }}'
        )
}}

**Comment by jeff-dude** [comment]
> thanks @jeff-dude for review and merge. did you add this chunk of metadata code for me into contracts_bnb_contract_mapping.sql? i dont recall adding these btw. 1st time spellbooker here
> 
> {{ config( alias='contract_mapping', post_hook='{{ expose_spells('["bnb"]', "sector", "contracts", '["davidcheongyl"]') }}' ) }}

yes, i did. the config block allows us to do a variety of things. in this case:
- alias gives us db object name (view or table)
- post hook tells our db to display this spell on the dune ui explorer, with those fields being metadata to tell it where/how to display
- by default, this spell is a view, based on config in dbt_project.yml file (which i also added) -- that file helps us control schema names and default materialization

**Comment by jeff-dude** [comment]
thanks for contributing to spellbook and enjoy your gitpoap!

**Pull request merged**
