### PR TITLE
automate fungible token metadata for solana

### PR DESCRIPTION
**Pull request by andrewhong5297**
Solana tokens all have an init when deployed and then get metadata attached at some point later. We may run into some edge cases where the model runs after the init for deploying but before the metadata attachment - should be pretty rare though.

### CODE REVIEW

**Comment by jeff-dude** [comment]
nice, it's cool to see that the metadata can be dynamic based on some source tables

this won't have an impact, but to avoid confusion, maybe you should now remove the `static` tag in the config block at the top? since this is a view, it'll still get created when merged into main, then always stay up-to-date at query runtime of course, but it could be misleading to see static there now

**Comment by andrewhong5297** [comment]
ah yeah, removed!

**Review by jeff-dude — APPROVED** [review]
sounds good!

@couralex6 can you include this in your recent merge(s)? it's just a view, so shouldn't be an issue on prod

**Comment by andrewhong5297** [comment]
oh wait I meant to make this a table

**Comment by andrewhong5297** [comment]
hold on

**Comment by andrewhong5297** [comment]
lmk if that changes anything

**Comment by andrewhong5297** [comment]
nvm keeping it a view, it only takes 10 seconds to run no reason to materialize it

**Comment by andrewhong5297** [comment]
Ah okay got it

**Comment by andrewhong5297** [comment]
only takes 1 second lol, we're good to go

**Pull request merged**
