### PR TITLE
[quick] Revert changes on punk_transfers

### PR DESCRIPTION
**Pull request by catherine-2**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by catherine-2** [comment]
@jeff-dude  Sorry quick revert back to old code (+ improved the incremental join like we did on some other files earlier today). Triple confirmed the output from this schema table in Dune matches what is on Etherscan. Should be good to merge. Thank you!

**Review by jeff-dude — APPROVED** [review]

**Comment by catherine-2** [comment]
@jeff-dude  I'm still seeing incorrect data on cryptopunks_ethereum.punk_transfers after this merge. 

I just re-ran the code in this file that we merged in Dune directly and the tx hash below shows up but it isn't showing up in punk_transfers directly (it should).

0x8ef8ffacae8501542954f51188ee623967b9437a04b0d40f6f13ed13af964323

Do you know what could be causing that / anything I need to do to get the new code to run instead of the old version that still seems to be live?

**Comment by catherine-2** [comment]
https://dune.com/queries/1758543 using this to test if helpful!

**Comment by catherine-2** [comment]
@jeff-dude actually it could be because of a delay? Are there any known issues with incremental models rebuilding at the moment?

**Comment by jeff-dude** [comment]
we're resolving a prod issue on nft sector spells, but cryptopunks ran yesterday as expected. is it a model which flipped from view to table? i wonder if old view persisted?

**Comment by catherine-2** [comment]
Got it - we didn't change anything in this PR related to view vs. table so I don't think that should be the issue. punk_transfers is an incremental model / table.

I'm using these queries to debug this issue: https://dune.com/queries/1758543 
- The top query uses punk_transfers directly
- The bottom query uses the code copied from punk_transfers (including the >= 1 week incremental filters)

These two tx hashes are missing from punk_transfers. The tx hashes happened over 3 hours ago so would expect them to be showing up in punk_transfers which is why I was wondering if it was a delay on the table re-running vs. an issue with the code in the file?

0xfe2b6fd54993710fa30925f3b15f662a853459b38556582af0d59efa8f20629a
0x8ef8ffacae8501542954f51188ee623967b9437a04b0d40f6f13ed13af964323

**Comment by jeff-dude** [comment]
if the tx's are within the last few hours, please give us time to fix prod issues. due to failure on magiceden model, all others are delayed

**Comment by catherine-2** [comment]
Sounds good thank you! Was driving myself crazy trying to figure out what was wrong with my PR 🙂

Is there a place for us to check prod status so I can see when to re-check / for future issues so I don't have to bother you unnecessarily?

**Comment by jeff-dude** [comment]
at this time, we don't have a public view of prod job monitoring. we can explore that when implementing a new orchestration tool in the near future.

**Comment by dot2dotseurat** [comment]
> These two tx hashes are missing from punk_transfers. The tx hashes happened over 3 hours ago so would expect them to be showing up in punk_transfers which is why I was wondering if it was a delay on the table re-running vs. an issue with the code in the file?

@catherine-2 we'll be migrating to a new orchestration tool in the new year. I expect the migration itself to take some time but it will give us a lot more flexibility to build a public view of jobs in production. I'll make sure we discuss where to prioritize that in our project planning.

**Comment by catherine-2** [comment]
> @catherine-2 we'll be migrating to a new orchestration tool in the new year. I expect the migration itself to take some time but it will give us a lot more flexibility to build a public view of jobs in production. I'll make sure we discuss where to prioritize that in our project planning.

That sounds awesome - thank you!

**Pull request merged**
