### PR TITLE
Add missing Eigenlayer collateral assets to ERC20 token list

### PR DESCRIPTION
**Pull request by bernatfp**
## Add tokens to ERC20 spell

- **Description:** Adding missing Eigenlayer assets (SWELL and slisBNB) to the ERC20 Ethereum tokens list

### CODE REVIEW

**Comment by bernatfp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bernatfp** [comment]
recheck

**Review by jeff-dude — APPROVED** [review]
well well well, looks who's back 🙏 

unfortunate our automated metadata source didn't pick these up. we can add here.

**Comment by bernatfp** [comment]
thx for picking it up right away! I have merged main and checks have passed. Let me know if you need anything else from me, otherwise see you soon in BKK 😏

**Pull request merged**
