### PR TITLE
Add spartacus_exchange to `dex.trades_beta`

### PR DESCRIPTION
**Pull request by tomfutago**
linked to #4759

### CODE REVIEW

**Comment by tomfutago** [comment]
Just a quick one to Open the year at the Source ;)

Happy New Year @dune-eng  team! 🥳🚀

**Comment by Hosuke** [comment]
> Just a quick one to Open the year at the Source ;)
> 
> Happy New Year @dune-eng team! 🥳🚀

Happy New Year @tomfutago !

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @tomfutago 

[Sample spartacus_exchange_fantom_base_trades](https://dune.com/queries/3321464)

**Review by jeff-dude — COMMENTED** [review]
thank you as always (& happy new year)!

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
