### PR TITLE
porting Element to Blast

### PR DESCRIPTION
**Pull request by hildobby**
blocked, waiting for 0x4196b39157659BF0De9ebF6E505648B7889a39cE decoding to be approved on blast

### CODE REVIEW

**Comment by jeff-dude** [comment]
trying while i'm here. if not, we can do later.

**Comment by jeff-dude** [comment]
closing due to inactivity. feel free to reopen and describe what needs to happen next, if necessary. thank you.

**Comment by hildobby** [comment]
Resubmitted 0x4196b39157659BF0De9ebF6E505648B7889a39cE for decoding, hopefully it all works well now

**Comment by jeff-dude** [comment]
apologies for the double close here, but i'll take it's not high priority if sitting since august 2nd. of course, feel free to reopen when it does become priority

**Pull request closed without merging**
