### PR TITLE
Quix Seaport Trades and Base Pairs

### PR DESCRIPTION
**Pull request by chuxinh**
- Mostly based on https://github.com/duneanalytics/spellbook/pull/1908
- Updating my names from `chuxinh` to `chuxin` in some files

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by chuxinh** [comment]
Also i'm trying to use this macro for unioning all events but unable to push the changes due to missing model ref.
However if I do dbt compile it works as it's supposed to.

```
{{
  config(
        alias='trades',
        post_hook='{{ expose_spells(\'["optimism"]\',
                                    "project",
                                    "quix",
                                    \'["chuxin"]\') }}')
}}

{% set quix_events = [
'quix_v1_optimism_events'
,'quix_v2_optimism_events'
,'quix_v3_optimism_events'
,'quix_v4_optimism_events'
,'quix_v5_optimism_events'
,'quix_seaport_optimism_trades'
] %}

select *
from (
    {% for model in quix_events %}
    select
        blockchain,
        project,
        version,
        block_time,
        token_id,
        collection,
        amount_usd,
        token_standard,
        trade_type,
        number_of_items,
        trade_category,
        evt_type,
        seller,
        buyer,
        amount_original,
        amount_raw,
        currency_symbol,
        currency_contract,
        nft_contract_address,
        project_contract_address,
        aggregator_name,
        aggregator_address,
        tx_hash,
        block_number,
        tx_from,
        tx_to
    from {{ ref(model) }}
    where evt_type = 'Trade'
    {% if not loop.last %}
    union all
    {% endif %}
    {% endfor %}
)

```
image

That's for another file called `quix_optimism_trades`

**Comment by Hosuke** [comment]
> Also i'm trying to use this macro for unioning all events but unable to push the changes due to missing model ref. However if I do dbt compile it works as it's supposed to.
> 
> ```
> {{
>   config(
>         alias='trades',
>         post_hook='{{ expose_spells(\'["optimism"]\',
>                                     "project",
>                                     "quix",
>                                     \'["chuxin"]\') }}')
> }}
> 
> {% set quix_events = [
> 'quix_v1_optimism_events'
> ,'quix_v2_optimism_events'
> ,'quix_v3_optimism_events'
> ,'quix_v4_optimism_events'
> ,'quix_v5_optimism_events'
> ,'quix_seaport_optimism_trades'
> ] %}
> 
> select *
> from (
>     {% for model in quix_events %}
>     select
>         blockchain,
>         project,
>         version,
>         block_time,
>         token_id,
>         collection,
>         amount_usd,
>         token_standard,
>         trade_type,
>         number_of_items,
>         trade_category,
>         evt_type,
>         seller,
>         buyer,
>         amount_original,
>         amount_raw,
>         currency_symbol,
>         currency_contract,
>         nft_contract_address,
>         project_contract_address,
>         aggregator_name,
>         aggregator_address,
>         tx_hash,
>         block_number,
>         tx_from,
>         tx_to
>     from {{ ref(model) }}
>     where evt_type = 'Trade'
>     {% if not loop.last %}
>     union all
>     {% endif %}
>     {% endfor %}
> )
> ```
> 
> image
> 
> That's for another file called `quix_optimism_trades`

You can temporarily disable _compulsory_ pre-commit-hook checks for this commit.

**Comment by chuxinh** [comment]
> > Also i'm trying to use this macro for unioning all events but unable to push the changes due to missing model ref. However if I do dbt compile it works as it's supposed to.
> > ```
> > {{
> >   config(
> >         alias='trades',
> >         post_hook='{{ expose_spells(\'["optimism"]\',
> >                                     "project",
> >                                     "quix",
> >                                     \'["chuxin"]\') }}')
> > }}
> > 
> > {% set quix_events = [
> > 'quix_v1_optimism_events'
> > ,'quix_v2_optimism_events'
> > ,'quix_v3_optimism_events'
> > ,'quix_v4_optimism_events'
> > ,'quix_v5_optimism_events'
> > ,'quix_seaport_optimism_trades'
> > ] %}
> > 
> > select *
> > from (
> >     {% for model in quix_events %}
> >     select
> >         blockchain,
> >         project,
> >         version,
> >         block_time,
> >         token_id,
> >         collection,
> >         amount_usd,
> >         token_standard,
> >         trade_type,
> >         number_of_items,
> >         trade_category,
> >         evt_type,
> >         seller,
> >         buyer,
> >         amount_original,
> >         amount_raw,
> >         currency_symbol,
> >         currency_contract,
> >         nft_contract_address,
> >         project_contract_address,
> >         aggregator_name,
> >         aggregator_address,
> >         tx_hash,
> >         block_number,
> >         tx_from,
> >         tx_to
> >     from {{ ref(model) }}
> >     where evt_type = 'Trade'
> >     {% if not loop.last %}
> >     union all
> >     {% endif %}
> >     {% endfor %}
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> > That's for another file called `quix_optimism_trades`
> 
> You can temporarily disable _compulsory_ pre-commit-hook checks for this commit.

Thanks, modified query a bit so it worked

**Comment by MSilb7** [comment]
Commenting so I can get notified for updates. This would be awesome to get in to make OP NFT analysis possible on v2!

**Comment by 0xRobin** [comment]
Looks good to be merged after merge freeze window! :ok_hand: 
Not sure why Quix decided to deploy their own seaport contract instead of using the provided one.

**Review by 0xRobin — APPROVED** [review]

**Pull request merged**
