### PR TITLE
[CoW Protocol] Add Laertes Solver

### PR DESCRIPTION
**Pull request by bh2smith**
Updating CoW Protocol Solver List.

### CODE REVIEW

**Review by soispoke — APPROVED** [review]
lgtm ✔

**Comment by bh2smith** [comment]
@jeff-dude this doesn't appear to have been applied.

**Comment by jeff-dude** [comment]
@soispoke did this get applied to v1 engine?

**Comment by fleupold** [comment]
Hey, can we apply this change please?

**Comment by jeff-dude** [comment]
updated 👍

**Pull request merged**
