### PR TITLE
Fix tigris pnl schema - ready for review - easy 

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
@couralex6 this still isn't working on dune... It doesn't show in the schema and it's returning this error:

`Error: Line 1:15: a column of tigris.trades_pnl of type integer has no name at line 1, position 15 [Execution ID: 01HBQYEKDBTWA4HF9M7H26WWWC].`

**Comment by henrystats** [comment]
@jeff-dude hola ser, could you pls help me here... I'm not sure what's wrong but I'm unable to query tigris.trades_pnl on dune.com but the test schema works correctly. 

I was thinking it was the unique keys and it failing in the incremental run but the column keys are correct.

**Comment by jeff-dude** [comment]
> @jeff-dude hola ser, could you pls help me here... I'm not sure what's wrong but I'm unable to query tigris.trades_pnl on dune.com but the test schema works correctly.
> 
> I was thinking it was the unique keys and it failing in the incremental run but the column keys are correct.

according to the model in this PR, you have the schema incorrect. this works:
```
select *
from tigris_arbitrum.trades_pnl
limit 10
```

**Comment by henrystats** [comment]
oouu :( thank you ser, can't believe how I've missed that

**Comment by henrystats** [comment]
now fixed and ready for review ser @jeff-dude

**Review by jeff-dude — APPROVED** [review]
sounds good 👍

**Pull request merged**
