### PR TITLE
Add Trades Models to OP Bots

### PR DESCRIPTION
**Pull request by MSilb7**
Testing integrating dex/nft/perp trades back in to bot logic so we can segment trading bots.

### CODE REVIEW

**Comment by jeff-dude** [comment]
do we want to keep this in draft until final for all three?

there's some risk in merging the migration beta, in terms of ensuring we update this spell once we remove that one and finalize dex trades original spell

**Comment by MSilb7** [comment]
> do we want to keep this in draft until final for all three?
> 
> there's some risk in merging the migration beta, in terms of ensuring we update this spell once we remove that one and finalize dex trades original spell

Yeah, is there an eta on dex/nft spell migrations? DEX is more relevant here, since NFT trading bots are more rare (and NFT is commented out right now).

If DEX trades is a week or so, then I'm good waiting. If it's months, then that gets tricky.

**Comment by jeff-dude** [comment]
> Cool, so I can mod this to use dex.trades and we'll wait for it to be ready

dex is ready!

**Comment by jeff-dude** [comment]
do you want to finalize this now? i believe all is migrated

**Comment by jeff-dude** [comment]
closing due to inactivity, feel free to reopen as needed 🤝

**Pull request closed without merging**
