### PR TITLE
Revert "Looksrare seaport-routed base trades (#3734)"

### PR DESCRIPTION
**Pull request by jeff-dude**
This reverts commit fe6e6c5d86d981bbfcf42481b86b4a2f8fcd01c5.

fyi @0xRobin @hildobby 
i need to revert this for the time being, as it created unintended side effects on the legacy spark orchestration in prod. running dbt compile (which dbt cloud does by default on our run command) is failing.
```
databricks.sql.exc.ServerOperationError: [SCHEMA_NOT_FOUND] The schema `looksrare_seaport` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a catalog, verify the current_schema() output, or qualify the name with the correct catalog.
To tolerate the error on drop use DROP SCHEMA IF EXISTS.
```

it may have to do with some of our dune override macros that are part of the overall compile process?

seems like it doesn't know to filter out the metastore used for trino side, and tries to list the schema on spark?

i'm thinking our gh actions pass compile successfully because we pass in flags for `tag:legacy`, while we can't do that in dbt cloud?

### CODE REVIEW

**Comment by jeff-dude** [comment]
fwiw, all was good on the dunesql side

**Comment by 0xRobin** [comment]
hmm, that's unfortunate. I've re-opened a PR with the LooksRare additions so we can run some checks if needed. 
Was this the first time where a new model was added to dunesql?

**Comment by jeff-dude** [comment]
> hmm, that's unfortunate. I've re-opened a PR with the LooksRare additions so we can run some checks if needed. Was this the first time where a new model was added to dunesql?

following up via height task, but for hildobby awareness, this is still open issue we're working on. this may be first model added to only dunesql and schema didn't exist on spark, which caused unexpected errors.

**Comment by hildobby** [comment]
Hey any updates here @jeff-dude @0xRobin? I don't see the model in spellbook, were you guys able to fix the issue?

**Comment by jeff-dude** [comment]
> Hey any updates here @jeff-dude @0xRobin? I don't see the model in spellbook, were you guys able to fix the issue?

this looks like it was what started our issue with missing legacy files, therefore failing spark. you can reopen that commit in a new PR, then add the dummy model for legacy, and we should be good

**Comment by hildobby** [comment]
> > Hey any updates here @jeff-dude @0xRobin? I don't see the model in spellbook, were you guys able to fix the issue?
> 
> this looks like it was what started our issue with missing legacy files, therefore failing spark. you can reopen that commit in a new PR, then add the dummy model for legacy, and we should be good

Alright sg, reopened the PR for it (including the dummy spark file) here: https://github.com/duneanalytics/spellbook/pull/4204

**Pull request merged**
