### PR TITLE
Rework `dex.pools` to allow for pools with more/less than 2 tokens

### PR DESCRIPTION
**Pull request by hildobby**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by hildobby** [comment]
Have you seen this error before @jeff-dude ? Not sure what it's caused by or how to fix it
Screenshot 2024-01-03 at 01 26 42

**Comment by jeff-dude** [comment]
> Have you seen this error before @jeff-dude ? Not sure what it's caused by or how to fix it Screenshot 2024-01-03 at 01 26 42

i have not seen that error before. the changes here are relatively simple, so i'd imagine it's either `array_agg()` or `ROW()` function you're using that is failing? maybe `token0` or `token1` is null in some instances, and the function(s) don't like those nulls?

**Comment by hildobby** [comment]
> > Have you seen this error before @jeff-dude ? Not sure what it's caused by or how to fix it Screenshot 2024-01-03 at 01 26 42
> 
> i have not seen that error before. the changes here are relatively simple, so i'd imagine it's either `array_agg()` or `ROW()` function you're using that is failing? maybe `token0` or `token1` is null in some instances, and the function(s) don't like those nulls?

What I'm confused about is that those spells work fine in dune.com, here is an example: https://dune.com/queries/3341998

So I'm not sure what to do here @jeff-dude

**Comment by jeff-dude** [comment]
> What I'm confused about is that those spells work fine in dune.com, here is an example: https://dune.com/queries/3341998
> 
> So I'm not sure what to do here @jeff-dude

this has been passed on to the engine team to help look

**Comment by belen-pruvost** [comment]
Hey @hildobby 👋 I took the liberty of pushing a new commit that should fix the issues you were seeing on the previous CI runs. Delta requires that all the inner values inside structs are named when creating a table (and the error is not reproducible with just a `SELECT` statement). So the fix here is to explicitly name the columns in the row that we use for aggregation.

There is a new error popping up now on the CI - but it's unrelated: `uniswap_optimism_pools` needs a token column ;)

**Comment by hildobby** [comment]
> Hey @hildobby 👋 I took the liberty of pushing a new commit that should fix the issues you were seeing on the previous CI runs. Delta requires that all the inner values inside structs are named when creating a table (and the error is not reproducible with just a `SELECT` statement). So the fix here is to explicitly name the columns in the row that we use for aggregation.
> 
> There is a new error popping up now on the CI - but it's unrelated: `uniswap_optimism_pools` needs a tokens column ;)

Great thank you!!

**Comment by henrystats** [comment]
Hola ser @hildobby 👋 - I'm working on a bounty for the dex pools category and one of the tasks is to move dex.pools to the _sector category and also create some macros that can be reused (uniswap v2 & uniswap v3) and then add for existing dexes.

I wanted to ask if I could use the code that you currently have written to set up the macro that would allow for pools with more/less than 2 tokens!

**Comment by hildobby** [comment]
> Hola ser @hildobby 👋 - I'm working on a bounty for the dex pools category and one of the tasks is to move dex.pools to the _sector category and also create some macros that can be reused (uniswap v2 & uniswap v3) and then add for existing dexes.
> 
> I wanted to ask if I could use the code that you currently have written to set up the macro that would allow for pools with more/less than 2 tokens!

yeah ofc go ahead! the idea here was to allow for pools of different token amounts to also live in the same spell (ie some curve pools, ambient's singleton contract, and uni v4's upcoming singleton). By the time this was merged, I had moved on to other projects hoping to resume this one later, so please go ahead :)

**Comment by henrystats** [comment]
Thank you very much ser @hildobby

**Comment by jeff-dude** [comment]
closing this in favor of new PR from @henrystats -- please reference this PR # in the new one for transparency

**Pull request closed without merging**
