### PR TITLE
Update kyber aggregator router on V1

### PR DESCRIPTION
**Pull request by halink0803**
Brief comments on the purpose of your changes:
Update for KyberAggregator data

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by augustog** [comment]
Hello @halink0803, thanks for the submission! 

Before we take it in, @dot2dotseurat / @jeff-dude can y'all think of a reason why tests didn't trigger on this one?

**Comment by dot2dotseurat** [comment]
It's on v1, Tests only run for v2

**Comment by halink0803** [comment]
It seems the USD value from the trades if fixed to 0. Let me check and update the PR. Who should I mention when I finished @dot2dotseurat?

**Comment by halink0803** [comment]
I updated the PR, please check.

**Comment by jeff-dude** [comment]
hi @halink0803 thank you for the PR. based on this announcement:
https://discord.com/channels/757637422384283659/757639462137102377/1037467921095606343
we are deprecating new decoded tables/abstractions on v1 engine.

it appears the new optimism abstraction here doesn't have all tables decoded on the v1 engine. we will ignore this one as it requires a few steps to build. our goal is to continue this work on v2 engine.

as for the three edited abstractions (eth, bsc, polygon), those are currently rerunning history with the changes applied.

**Comment by jeff-dude** [comment]
closing here, finalize in #1884

**Comment by halink0803** [comment]
@jeff-dude i just checked again and it is lack of usd amount for most case 😞 My bad, should I update the code again or continue with v2?

**Pull request closed without merging**
