### PR TITLE
update source freshness on all warning/error models

### PR DESCRIPTION
**Pull request by jeff-dude**
using prod as starting point, fix any source freshness issues in full dbt project

### CODE REVIEW

**Comment by jeff-dude** [comment]
@dot2dotseurat @soispoke plz take a look, this is a step towards getting our daily views/seeds/tests job to run in prod successfully

**Comment by jeff-dude** [comment]
agreed. each decoded table can vary wildly in terms of freshness. sometimes it's simply a "pool added" to a dex & that can go months without a new pool. it requires users to really dig deep into each one, then at that point, is it worth it?

i'll push this through for now, but a larger conversation should be had. this doesn't feel like the best approach.

**Comment by jeff-dude** [comment]
also should add source freshness dbt command to our slim ci job, will help PRs catch them up front

**Comment by soispoke** [comment]
👍 thanks for looking into this @jeff-dude

**Pull request merged**
