### PR TITLE
Add unit test framework

### PR DESCRIPTION
**Pull request by masquot**
Split out unit test framework from #1523 (additional info available there) and add sample OpenSea test transaction

### CODE REVIEW

**Comment by soispoke** [comment]
@masquot  This test is failing when I'm running ran on local dev environement:

Capture d’écran 2022-09-08 à 11 25 44

**Comment by masquot** [comment]
Hey @soispoke, that was expected. Sorry If this wasn't clear 😅

The goal here is to put the test tx and setup around it in place first, so we can develop a solution and ensure the new code handles this transaction correctly. Opened this branch so we can start developing following TDD principles.

Generally, this PR was also meant to serve as an example for all contributors (such as @agaperste who reported the specific tx included in seed file here) to demonstrate  how we can add txs that we look up on etherscan as tests in here in a seed csv file.

**Comment by soispoke** [comment]
@masquot Ok, I thought it was the case but wasn't sure 👍  Well, looks like the test is failing as expected then :)

**Comment by jeff-dude** [comment]
@masquot i'm going through each open PR. i've been a bit confused on next steps here. please share what steps to take next and who should help do so 👍

**Comment by masquot** [comment]
Thank you @jeff-dude. Sorry I forgot about this one. I'll take it from here.

**Pull request closed without merging**
