### PR TITLE
WIP [oneinch] add static contract addresses

### PR DESCRIPTION
**Pull request by grkhr**
**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by augustog** [comment]
hey @jeff-dude, trying to confirm the approach here. If I understand correctly (@grkhr correct me if I'm wrong) they are trying to add this static file and use it from DSQL, which means we should use strings here and explicit cast them to varbinary on the overrides, no?

**Comment by jeff-dude** [comment]
> hey @jeff-dude, trying to confirm the approach here. If I understand correctly (@grkhr correct me if I'm wrong) they are trying to add this static file and use it from DSQL, which means we should use strings here and explicit cast them to varbinary on the overrides, no?

yes, for the time being, the approach is to write spells compatible in spark sql (added bonus if compatible on both). once merged, if we want any field to be varbinary specifically, we'll handle that in a separate private repo. more to come on this process to leverage dunesql types, where it's not hidden behind private repo

**Comment by jeff-dude** [comment]
i've pushed a commit to standardize, hopefully assumptions made are fine -- otherwise, feel free to overwrite
- added column alias to get past failure
- removed usage of `metadata` in schema/table naming, keep clean
- added a few tests (unique address, accepted values for blockchain)

**Comment by jeff-dude** [comment]
> i've pushed a commit to standardize, hopefully assumptions made are fine -- otherwise, feel free to overwrite
> 
> * added column alias to get past failure
> * removed usage of `metadata` in schema/table naming, keep clean
> * added a few tests (unique address, accepted values for blockchain)

looks like combo of blockchain/address still isn't unique -- is this intended? if so, we can remove. otherwise, could clean up the file

**Comment by grkhr** [comment]
Removed duplicates. It wasn't intended, I just didn't notice, my bad here. @augustog @jeff-dude 

Everything is great in my opinion. Thanks for the cleanup. 

Can be merged.

**Review by jeff-dude — APPROVED** [review]
thank you!

**Pull request merged**
