### PR TITLE
Static EVM Stablecoins

### PR DESCRIPTION
**Pull request by Synthquest**
### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [ x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *tokens.tokens_erc20_stablecoins*
- **Description:** contract, description, and decimal definitions for L1 & L2 evm stablecoins
- **Who are the new spell(s) for?** general community + internal work
- **How will the new spell(s) be used downstream?** 
General - quick views of stablecoins on l2's. 

Internal -  filter for token transfers

- **Implementation details:** static
- **Test instructions:** unique contract address + blockchain
- **Related issue(s):** N/A

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by jeff-dude** [comment]
@Synthquest it looks like we already have some initial start on stablecoin spells, an example [here](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/tokens/models/tokens/ethereum/tokens_ethereum_erc20_stablecoins.sql) for ethereum. if you go back a directory, other chains also exist. can we combine the efforts here with those existing ones, to have one approach on stablecoins? then we can have a crosschain spell on top of all chain specific ones, similar to `tokens_erc20`?

**Comment by Synthquest** [comment]
> @Synthquest it looks like we already have some initial start on stablecoin spells, an example [here](https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/tokens/models/tokens/ethereum/tokens_ethereum_erc20_stablecoins.sql) for ethereum. if you go back a directory, other chains also exist. can we combine the efforts here with those existing ones, to have one approach on stablecoins? then we can have a crosschain spell on top of all chain specific ones, similar to `tokens_erc20`?

Sure, do you want to update the schema of these or keep the schema the same? I ask only because certain chains do not follow the same schema.

Optimism for instance:
https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/tokens/models/tokens/optimism/tokens_optimism_erc20_stablecoins.sql

I'm also seeing a separate `labels.stablecoins` table on dune

**Comment by Synthquest** [comment]
@jeff-dude 
I ran through adding in new chain tables, appending any stables from the existing tables, and normalizing to a standardized schema for all chains. Please let me know if we should change any naming conventions / column formats

**Comment by jeff-dude** [comment]
this is looking good to me. plz do explicitly add `schema` property in each model though, rather than rely on value in dbt project file.

**Comment by Synthquest** [comment]
Schema properties added

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
