### PR TITLE
Please update safe_polygon_safes

### PR DESCRIPTION
**Pull request by bearishbuilder**
Hi @jeff-dude, this spell for Polygon is only updated up till 10th March 2023. Can you please fix this?

Thanks!

Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by Hosuke** [comment]
The incremental view should be updated, unless there is no updates in the source table.

**Comment by bearishbuilder** [comment]
@Hosuke thanks for getting back to me. Have we merged the update? The last time is still 10th March 2023, but [block explorer](https://polygonscan.com/address/0xa6b71e26c5e0845f74c812102ca7114b6a896ab2) shows latest time for Polygon's Safe created as today

**Comment by Hosuke** [comment]
> @Hosuke thanks for getting back to me. Have we merged the update? The last time is still 10th March 2023, but [block explorer](https://polygonscan.com/address/0xa6b71e26c5e0845f74c812102ca7114b6a896ab2) shows latest time for Polygon's Safe created as today

We may need to check the source table and check if there is new contract update for this spell on chain.

**Comment by bearishbuilder** [comment]
@Hosuke I checked the source tables. All of these tables have records beyond 10th March 2023 inside there except `gnosis_safe_polygon.ProxyFactory_v1_1_1_call_createProxyWithCallback` which has 0 records.

Can you please do a refresh of the incremental views?

Thanks.

**Comment by Hosuke** [comment]
It seems the incremental view logic works well:
https://dune.com/queries/2327531?d=1

Please can you please check on spark v2? You can attach any query you think looks like having problems.

**Comment by bearishbuilder** [comment]
This [query](https://dune.com/queries/2329905) that relies on incremental view logic shows last creation_time to be 10th March 2023.

**Comment by Hosuke** [comment]
Hi @bearishbuilder 
Please use this table first:
https://dune.com/queries/2330746?d=1

I am trying to figure out the problem.

**Comment by jeff-dude** [comment]
hi @bearishbuilder -- thanks for following up. due to info in #2779, that spell was turned off in prod due to failing duplicates. the issue was resolved at the source, therefore we can re-enable the spell again. follow along the comments in that PR for context

**Pull request closed without merging**
