### PR TITLE
Rubicon V2 updates

### PR DESCRIPTION
**Pull request by denverbaumgartner**
Brief comments on the purpose of your changes:
updated underlying rubicon_optimism_trades and rubicon_optimism_offers tables for v2 of the protocol. included events were `emitOffer` and `emitTake`

updated queries for both: 
- [rubicon_optimism_offers](https://dune.com/queries/2520173)
- [rubicon_optimism_trades](https://dune.com/queries/2521177?category=decoded_project&namespace=rubicon&blockchains=optimism&contract=RubiconMarket)

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by denverbaumgartner** [comment]
hey @Hosuke hope you are well! have not changed anything related to the tests (that in the past have not had any problem picking up the seed data) and am running into the following: 

`Runtime Error in test rubicon_optimism_offers_test (tests/rubicon/optimism/rubicon_optimism_offers_test.sql)
[TABLE_OR_VIEW_NOT_FOUND] The table or view `test_data`.`dex_offers_seed` cannot be found. Verify the spelling and correctness of the schema and catalog.`

was wondering if you may know the source of this problem or a possible solution? thanks for the help as always 🙏

[data](https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/offers/dex_offers_seed.csv)
[test](https://github.com/duneanalytics/spellbook/blob/main/tests/rubicon/optimism/rubicon_optimism_offers_test.sql)

**Comment by Hosuke** [comment]
> hey @Hosuke hope you are well! have not changed anything related to the tests (that in the past have not had any problem picking up the seed data) and am running into the following:
> 
> `Runtime Error in test rubicon_optimism_offers_test (tests/rubicon/optimism/rubicon_optimism_offers_test.sql) [TABLE_OR_VIEW_NOT_FOUND] The table or view `test_data`.`dex_offers_seed` cannot be found. Verify the spelling and correctness of the schema and catalog.`
> 
> was wondering if you may know the source of this problem or a possible solution? thanks for the help as always 🙏
> 
> [data](https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/offers/dex_offers_seed.csv) [test](https://github.com/duneanalytics/spellbook/blob/main/tests/rubicon/optimism/rubicon_optimism_offers_test.sql)

Hi @denverbaumgartner,
please fix the `block_number` field in this file:
https://github.com/duneanalytics/spellbook/blob/main/seeds/dex/offers/dex_offers_seed.csv

This may solve the problem.

**Comment by denverbaumgartner** [comment]
> data

got it! just corrected any values that were written as scientific notation, hopefully that corrects the problem 🙌

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @denverbaumgartner 

[Sample rubicon optimism offers](https://dune.com/queries/2600595)
[Sample rubicon optimism trades](https://dune.com/queries/2600642)

**Comment by denverbaumgartner** [comment]
@Hosuke just wanted to see if there was anything i can do to help finalize / review this PR? currently our dashboards drive off of `dex.trades` and `dex.offers`, so they are currently not populating with live data as of this protocol upgrade. thanks again for all the help

**Comment by Hosuke** [comment]
> @Hosuke and/or @jeff-dude, just wanted to see if there was anything i can do to help finalize / review this PR? currently our dashboards drive off of `dex.trades` and `dex.offers`, so they are currently not populating with live data as of this protocol upgrade. thanks as always for all the help

This PR is in the merging queue, please wait for a while. Thank you.

**Comment by denverbaumgartner** [comment]
> 

sounds good, ty @Hosuke - know y'all are managing a very active repo and appreciate y'alls efforts 🙏

**Review by jeff-dude — APPROVED** [review]
thank you @denverbaumgartner -- we'll get this included in next merge 🙏

**Pull request merged**
