### PR TITLE
Add Quix Trades to `nft.trades`

### PR DESCRIPTION
**Pull request by chuxinh**
Brief comments on the purpose of your changes:
- Cast `amount_raw` values to decimal(38, 0) to be consistent with that in `nft.trades` (let me know if it's better to do that in individual tables instead and if that'd affect incremental build since data type change
- add `quix_optimism_trades` to `nft.trades`. There is no `unique_trade_id` in those event tables. I remember I was told to use `unique_key` in config instead. Let me know whichever works

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by chuxinh** [comment]
Also curious what's the reason for breaking out platform fee and creator fee from `nft.trades`? 
i realised that the quix trades one also does not have those despite fees exist in separate event tables

**Comment by 0xRobin** [comment]
Had a quix look: 

1. To expose the fee data, we should make a `quix_optimism_fees` model and include it in the main `nft.fees` model.
2. We definitely want to get rid of the `unique_trade_id` field in the future, for now though it's still in place. :(
This means we should add it to all the different event abstractions (a simple concat of all the unique_key fields will do the trick)
3. as a rule of thumb we want to cast the fields in the materialized tables, not in the views on top. This means doing the cast in the base event tables. There are other fields we'd like to see cast (like `number_of_items`, I'm hoping @belen-pruvost can provide a list.)

**Comment by belen-pruvost** [comment]
Thanks for summoning me @0xRobin 😁 yes, both `number_of_items` and `amount_raw` should be explicitly casted to decimal(38,0) on `quix_v1_optimism_events`, `quix_v2_optimism_events`, `quix_v3_optimism_events`, `quix_v4_optimism_events`, `quix_v5_optimism_events` and `quix_seaport_optimism_trades`.

`number_of_items` already has the right type on `quix_optimism_trades` but for readibility we'd rather cast it explicitly on the underlying models.

**Comment by chuxinh** [comment]
Thanks! Have already addressed the comments above. 
Note that I created an extra cte as final in v1 - v5 so it seemed as if there were lots of changes. It's just for convenience that i can select * and a the `unique_trade_id` :p

**Review by 0xRobin — APPROVED** [review]
@chuxinh I pushed some final tweaks to get everything integrated. 
This looks good now, thanks for the contribution!

**Review by jeff-dude — APPROVED** [review]
thank you @chuxinh & @0xRobin 🤝

**Pull request merged**
