### PR TITLE
Spellbook Workshop Submission

### PR DESCRIPTION
**Pull request by LeviScoffie**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [x] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by LeviScoffie** [comment]
Still not yet done polishing the spell. I will be done before deadline date. Hopefully will have resolved all the conflicts

**Comment by LeviScoffie** [comment]
@dot2dotseurat  i'm finding it hard to dbt compile since it keeps on throwing an error yet all my yml files are correct

**Comment by dot2dotseurat** [comment]
> @dot2dotseurat i'm finding it hard to dbt compile since it keeps on throwing an error yet all my yml files are correct

Can you sync with main? Alter ta

**Comment by dot2dotseurat** [comment]
@LeviScoffie I think you need to merge main into your branch. can you try this? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Pull request closed without merging**
