### PR TITLE
CI upgrade: list modified downstream

### PR DESCRIPTION
**Pull request by 0xRobin**
CI upgrade: 
This adds a step that prints the list of modified downstream models (adds about ~8sec in CI)

### CODE REVIEW

**Comment by 0xRobin** [comment]
example run with modified: https://github.com/duneanalytics/spellbook/actions/runs/11481249786/job/31951477756?pr=6997
example with no modified: https://github.com/duneanalytics/spellbook/actions/runs/11481249806/job/31951477823?pr=6997

**Review by Hosuke — APPROVED** [review]
Great upgrade!

**Review by jeff-dude — APPROVED** [review]
love it!

looks like it kicks off all CI jobs, due to modification to `dbt_run.yml`, but shouldn't trigger anything in prod if merged?

**Comment by 0xRobin** [comment]
> looks like it kicks off all CI jobs, due to modification to `dbt_run.yml`, but shouldn't trigger anything in prod if merged?

That's correct!

**Comment by 0xBoxer** [comment]
Due to a dbt version change, you need to merge main into your branch before the Github action runner runs successfully again.

**Pull request merged**
