### PR TITLE
Add Base to Contracts Mapping

### PR DESCRIPTION
**Pull request by MSilb7**
~Comes after https://github.com/duneanalytics/spellbook/pull/4222~ **DONE**
~& after https://github.com/duneanalytics/spellbook/pull/4240~ **DONE**

Adds Base to multi-chain creator mapping & adds handling for OP Stack Chain Predeploys

### CODE REVIEW

**Comment by MSilb7** [comment]
Seems like there's timeout issues, but the initial build runs in < 5 mins on dune.com: https://dune.com/queries/2994348

**Comment by MSilb7** [comment]
Still not sure why this is causing so many runtime issues. It completes in 10 mins here: https://dune.com/queries/2994348

**Comment by jeff-dude** [comment]
> Wondering if there's any insight/ideas as to why this spell initial build times out (or things to try to modify)?
> 
> Running both self-destruct and contract mapping on dune.com (free tier) takes ~ 7 mins: https://dune.com/queries/2994348
> 
> cc @jeff-dude

replicating the query by using a CTE for the spell dependency on the app may not help us understand the query planning and performance it seems. can you push a commit to up the timeout on CI to a higher number of minutes? you can find in the gh workflows directory. let's see what happens when it runs on a higher timeout period, even though it's odd when ethereum ran in the set time just fine

**Comment by MSilb7** [comment]
doubled the timeout

**Pull request closed without merging**
