### PR TITLE
[Easy] [Labels] Implement dex trader label

### PR DESCRIPTION
**Pull request by gentrexha**
Adding a dex trader label for addresses that have completed a trade on a dex.

Tagging @bh2smith for internal review

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
~~* [ ] if adding a new model, I added a test~~
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
~~* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)~~
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### CODE REVIEW

**Comment by gentrexha** [comment]
> Looks good to me, just wondering if we also consider aggregator traders as dex traders or will have a separate label for that.

We were thinking of having a separate label for that.

**Comment by soispoke** [comment]
@gentrexha  thanks a lot for contributing to labels it's awesome! Would you consider having models similar to what was done for NFT traders (Top 1,5,10% DEX traders based on either volume or transactions), and then a model for dex "users" 
=> https://github.com/duneanalytics/spellbook/tree/main/models/labels/nft 

It would make it more granular/consistent with the existing NFT trades labels

**Comment by gentrexha** [comment]
> @gentrexha thanks a lot for contributing to labels it's awesome! Would you consider having models similar to what was done for NFT traders (Top 1,5,10% DEX traders based on either volume or transactions), and then a model for dex "users" => https://github.com/duneanalytics/spellbook/tree/main/models/labels/nft
> 
> It would make it more granular/consistent with the existing NFT trades labels

That's a great idea. I think it's a great idea to add labels dynamically like that. 

Here are some discussion points regarding that:

1. One issue I have with that is that you don't see the actual value of the top 1% (e.g.: that the top 1 %'s average trade value is $50k). Is it possible to add the actual value to the label text?
2. Would you include all these new labels into this newly dex "users" models folder?

**Comment by soispoke** [comment]
That's my personal opinion, but
1. I'd rather see `Top 1% DEX trader`, and the number of DEXs he traded on + his average trade value (two labels categories you already added) than the average traded value for all TOP 1% DEX traders?
2. In the example, DEX "users" is actually a single model, just explicitly printing the names of DEXs a particular address has traded on: https://github.com/duneanalytics/spellbook/blob/main/models/labels/nft/labels_nft_users_platforms.sql

**Comment by gentrexha** [comment]
1. Would those all be separate labels? If so, it makes sense to me to have one for the top 1% percentiles and one with the average trade value. The only remaining issue I have is that if you want to categorize users, it's hard to observe how much average trade value they need to belong in each category, i.e., If I'm visualizing volume by average trade value percentiles for a project, where does the 1% average trade value user start becoming 1%?
2. I see. That makes more sense. If I were to add this new umbrella folder for this, should it be named dex or dex_aggregator labels? I would want to include both.

**Comment by gentrexha** [comment]
Starting analyzing some of these labels, I think having a label printing the names of DEXs a particular address has traded on is also helpful.

Also, open to having this PR put everything into one folder, similar to NFTs.

**Comment by soispoke** [comment]
@gentrexha Hi, what's your current opinion about this PR? Do you want to proceed with this?

**Comment by gentrexha** [comment]
> @gentrexha Hi, what's your current opinion about this PR? Do you want to proceed with this?

Yeah, I think that makes sense.

**Pull request merged**
