### PR TITLE
Add Pyth spellbook - evm price feeds

### PR DESCRIPTION
**Pull request by Synthquest**
### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** 
pyth.evms_price_feed_ids
pyth.evms_price_feed_logs_all
pyth.evms_transactions_all
- **Description:** 
pyth.evms_price_feed_ids - all price feed labels
pyth.evms_price_feed_logs_all - Pyth price feed log data transforms and estimated end user labels
pyth.evms_transactions_all - Pyth contract trace interactions and estimated end user labels
pyth.price_feed_contracts - Pyth price feed contracts
- **Who are the new spell(s) for?** Pyth team and end users of pyth price feed oracles
- **How will the new spell(s) be used downstream?** Overall evm pyth oracle usage as well as individual project usage of pyth price feeds
- **Implementation details:** trace and log data were transformed to view oracle events and contract interactions. Dune labels and manual labels were added to "from" contracts in trace interactions for pyth.evms_transactions_all
and labels were added to the transaction "to" contract for pyth.price_feed_logs_all. Both give an estimate label of which project is using pyth price feeds for that transaction.

- **Test instructions:** 
- **Related issue(s):** 

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Review by Synthquest — COMMENTED** [review]
recheck

**Comment by jeff-dude** [comment]
hi @Synthquest -- welcome to spellbook and thank you for the PR!

this is off to a great start. a few things:
- as for the CLA, you need to comment that one sentence only, nothing else in comment. it's a bit picky
- i highly recommend you leverage dbt macros for these models, since all EVM chains follow similar (or exact) code. that way, it's stored in one spot for maintenance and each chain model is clean. we have tons of examples out there in the repo to do this, let me know if you can't find any

**Comment by Synthquest** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Synthquest** [comment]
> hi @Synthquest -- welcome to spellbook and thank you for the PR!
> 
> this is off to a great start. a few things:
> 
>     * as for the CLA, you need to comment that one sentence only, nothing else in comment. it's a bit picky
> 
>     * i highly recommend you leverage dbt macros for these models, since all EVM chains follow similar (or exact) code. that way, it's stored in one spot for maintenance and each chain model is clean. we have tons of examples out there in the repo to do this, let me know if you can't find any

Is this necessary for this submission? Wish I realized this, I had a find/replace script running locally for all the files :/

A few questions about using the macro:
It looks like it points to the sources folder rather than the model schema. Is a schema still necessary?
I have static label files within the spell model. Would this need a combination of models to reference static files & macros? 
Also, will the queries still get compiled in the target folder or somewhere else after running dbt compile? I don't see projects that solely use macros appearing in the target folder.

**Comment by Synthquest** [comment]
recheck

**Comment by Synthquest** [comment]
@jeff-dude I think I've pushed these tests to their breaking point 0.o. Sorry to bug you with this but I've ran unique checks locally for a each of the queries and they seem to pass. I hope this one can go through... It seems to have timed out.

As a side note, is there a way to run the checks locally or materialize the views between fails? It felt abusive to come back after an hour+ run and have to fix for failed test. I see the value in using a macro here but I'm not confident I could have correctly given the use of nested queries. I think it still would have needed a combination of models + macros and I didn't see a clear example that ported well to the work here.

**Review by Synthquest — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by SeblyAnalytics** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SeblyAnalytics** [comment]
recheck

**Comment by SeblyAnalytics** [comment]
recheck

**Comment by SeblyAnalytics** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SeblyAnalytics** [comment]
recheck

**Comment by Synthquest** [comment]
recheck

**Comment by SeblyAnalytics** [comment]
recheck

**Comment by jeff-dude** [comment]
@Synthquest thanks again for initiating the PR and building with us.

i think our best course of action here is to keep this branch as point of reference, but to start a new branch and start simple.
- one chain (to start, add more after)
- leverage dbt macros, since it appears code repeats across chains
- make spells incremental, since you read from large raw base tables per chain (this puts a lot of strain on our infra to do full refresh every run)

these are my initial thoughts on first glance, more to come when we take the next steps. can you close this PR, start a new branch with one chain, then take these steps? this may also help start fresh on the CLA assistant that seems to be tricky here.

once you initiate that new PR, we can ask @Hosuke to help you on anything in the above steps that may be uncertain to you on how to implement

**Comment by jeff-dude** [comment]
as agreed with user, closing this PR and focusing on new PRs

**Pull request closed without merging**
