### PR TITLE
Stablecoin Balances - ethereum 

### PR DESCRIPTION
**Pull request by Synthquest**
### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by Synthquest** [comment]
@jeff-dude 
Do you want to try with an open limit or cut it back to a certain date? 
The PR only includes ethereum and some fixes to static tables

**Comment by jeff-dude** [comment]
> @jeff-dude Do you want to try with an open limit or cut it back to a certain date? The PR only includes ethereum and some fixes to static tables

let's start with an abbreviated date range, so you can adjust the start date to see how it performs on CI runs.
also pulling in @0xRobin to assist on balances PRs now that he is back 🙏

**Comment by Synthquest** [comment]
@jeff-dude 
The model successfully ran for >2024-01-01: https://github.com/duneanalytics/spellbook/actions/runs/11222351772/job/31194622640?pr=6886

The outputs looked good. I pushed it back to 2023 & re-ran it. If this is as far as we can pull it back that's fine for our needs for now. I'd imagine the amount of addresses tracked starts to explode from 2020-2023

@0xRobin amazing work on this macro! it was very easy to adopt for this 🙏

**Comment by Synthquest** [comment]
@jeff-dude pinging
cc: @0xRobin

**Comment by 0xRobin** [comment]
hey @Synthquest, code looks good.
I am still a bit concerned with the performance of the macro, but that's on us to take a closer look to see if we can optimize it further.
Do you need to have all these stablecoins, or would a smaller subset be sufficient?

**Comment by jeff-dude** [comment]
we should do either:
- smaller subset of stablecoins
- restricted history

**Comment by Synthquest** [comment]
> hey @Synthquest, code looks good. I am still a bit concerned with the performance of the macro, but that's on us to take a closer look to see if we can optimize it further. Do you need to have all these stablecoins, or would a smaller subset be sufficient?

I filtered down to ~top 30 all time and top 10 for 2024 by transfer volume. I've also included the time filter for 2023 ->

I'm thinking we'll just need to rely on historical filtering judging by the amount of new stables being released this year alone. This list is likely going to grow/change with new tokens

**Comment by Synthquest** [comment]
@0xRobin 

This should be good to go
It tracks the stable balance for filtered tokens & limits the run to balance history after 2023.

**Review by jeff-dude — APPROVED** [review]
i think i'm good with the sacrifices here of subset of tokens & restricted history.

we'll let @0xRobin give a final look too, so we're all on the same page

**Comment by Synthquest** [comment]
Squeezing in one last question about future chains with this approach- 
Should we take them one at a time or bulk add all the one from the previous PR? 

In the previous PR they all seemed to materialize without issue.

**Review by 0xRobin — APPROVED** [review]
Ok let's get this in with the current limits! :ok_hand: 

For future PRs, if they successfully run in CI it is fine to bulk add them. 
If not, better to go by chain

**Pull request merged**
