### PR TITLE
Identify more NFT aggregator trades

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:

Added a table with all of the hashes identifying direct trades routed from an aggregator, see here:
- For Reservoir: https://twitter.com/ptrwtts/status/1572377213693210627
- For Gem: https://twitter.com/vasa_develop/status/1572331744032067584
- For Blur: https://twitter.com/PacmanBlur/status/1583578608676663296
- I was also told by the Rarible team that they use "9616c6c64617461" as their hash identifier (@dot2dotseurat can also confirm)

I'm sure we will see more going forward and given that the list is starting to become quite extensive, creating a new table for it made most sense to me.

This table is then used to identify direct aggregator trades from Gem, Blur, Reservoir and Rarible for OpenSea/Seaport, LooksRare & X2Y2.

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by hildobby** [comment]
Tests fail after ~1h, pretty sure it's a runtime error not an actual error here 🤔

**Comment by dot2dotseurat** [comment]
@hildobby yes, it's failing on cancelation at runtime. it looks like it was trying to run more models that it was supposed to. I'm retrying to see if that is resolved and it it keeps failing I can extend the timeout time on this workflow file.

**Comment by dot2dotseurat** [comment]
@hildobby it looks like it's running on the right models now but there's a regular sql error. I'm sorry it took so long. to uncover the error, waiting for the job to timeout when it picks up too many modified models it not a good debug cycle :(

**Comment by hildobby** [comment]
This should be ready for merging (don't want to put the tag myself though). Tests timeout was extended and passed and I then put the timeout back to 1h.

**Comment by jeff-dude** [comment]
i merged in main to get this to run tests again and remove the code not necessary. looks like it's failing on compile due to issue in schema file?

**Pull request closed without merging**
