### PR TITLE
Migrate `airdrop_optimism.addresses_1`

### PR DESCRIPTION
**Pull request by hildobby**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by Hosuke** [comment]
Do you think the addresses now are covered in `dune.oplabspbc.dataset_op_airdrop1_addresses_detailed_list`?

**Comment by hildobby** [comment]
> Do you think the addresses now are covered in `dune.oplabspbc.dataset_op_airdrop1_addresses_detailed_list`?

@MSilb7, all good on the airdrop list front? It might be worth having a spell that's a view of all the uploaded tables joined together? If you're down lmk the table names and I try to figure out how to tackle this. @jeff-dude, dune uploaded tables can be used in spellbook, right?

**Comment by jeff-dude** [comment]
> > Do you think the addresses now are covered in `dune.oplabspbc.dataset_op_airdrop1_addresses_detailed_list`?
> 
> @MSilb7, all good on the airdrop list front? It might be worth having a spell that's a view of all the uploaded tables joined together? If you're down lmk the table names and I try to figure out how to tackle this. @jeff-dude, dune uploaded tables can be used in spellbook, right?

yeah, still finalizing the details on what is/isn't allowed (especially since free tier users can't use the upload feature on the app), but for now, we approved the approach for OP airdrops. the static spell in this PR is too large to include in spellbook, we are actively going away from that pattern if files get too large.

**Comment by jeff-dude** [comment]
closing due to comment above, airdrop is now a dune upload and a source in spellbook

**Pull request closed without merging**
