### PR TITLE
restore reverted paraswap methods

### PR DESCRIPTION
**Pull request by alexshchur**
- [x] Bug fix

- **Description:** fixes the bug with broken `amount_usd` logic 
- **Steps to reproduce:** [described in this PR](https://github.com/duneanalytics/spellbook/pull/6504)

### CODE REVIEW

**Comment by jeff-dude** [comment]
@alexshchur if you don't mind, to be safe, can you force minor changes (line breaks, comments, etc.) to force downstream spells to run, up to `dex_aggregator.trades`? that way, CI will run those tables and run the tests on `amount_usd` for us

**Comment by jeff-dude** [comment]
> @alexshchur if you don't mind, to be safe, can you force minor changes (line breaks, comments, etc.) to force downstream spells to run, up to `dex_aggregator.trades`? that way, CI will run those tables and run the tests on `amount_usd` for us

we can revert those changes after CI runs and succeeds for us 🙏

**Comment by alexshchur** [comment]
> @alexshchur if you don't mind, to be safe, can you force minor changes (line breaks, comments, etc.) to force downstream spells to run, up to `dex_aggregator.trades`? that way, CI will run those tables and run the tests on `amount_usd` for us

not sure if I did it right, but tests seem OK. I don't see anything related to USD checks in the CI output though, @jeff-dude . Did the corresponding checks run?

**Comment by alexshchur** [comment]
now I'm seeing USD range test in the CI log. Awesome! Thank you @jeff-dude 
should I revert that tmp commit now? 
Or maybe force-pushing a version just before that commit would be preferable?

**Comment by jeff-dude** [comment]
> now I'm seeing USD range test in the CI log. Awesome! Thank you @jeff-dude should I revert that tmp commit now? Or maybe force-pushing a version just before that commit would be preferable?

nice! looking good to me.

either one works 🙏

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
