### PR TITLE
Add contract mapping for L1 NFT bridged to Optimism

### PR DESCRIPTION
**Pull request by chuxinh**
Add `tokens_optimism_nft_bridged_mapping` to `tokens_nft` for L1 NFTs bridged to L2 and the corresponding addresses.  Let me know if it's worth exposing this one as well since it will provide an easy L2 -> L1 contract map. Alternative is to have an extra column in `tokens_nft`.

Will be helpful for building OP `nft.trades`

*For Dune Engine V2*
I've checked that:
General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory): https://dune.com/queries/1498012?d=1
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### CODE REVIEW

**Comment by augustog** [comment]
Hello @chuxinh ! Thanks for the contribution! :) 
The tests seem to be failing because main is ahead of this branch. Would you mind doing a merge commit so tests can run?

**Comment by chuxinh** [comment]
Thanks @augustog! 
I git pull from the main and merge this branch into my local main but seeing an issue here preventing me to push 
image

The only `gas_model` ref i can find is here: 
image

**Comment by soispoke** [comment]
Hey @chuxinh, you can ignore this error, the test is not "smart" enough to understand loops over gas models but everything lgtm

**Comment by soispoke** [comment]
lgtm, thanks @chuxinh !

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
