### PR TITLE
Add ethereum stakers

### PR DESCRIPTION
**Pull request by nerolation**
I looked at those deposit addresses with the most validators to ensure to not capture single-validator stakers.
All the added entities should have a significant amout of validators.

Most are .eth addresses, some are entities such as Frax Finance or Stader Liquid Staking.

### CODE REVIEW

**Comment by jeff-dude** [comment]
tagging @hildobby as there is another open PR editing this spell -- do you want to help take a look?

**Comment by jeff-dude** [comment]
also, in order to proceed, you will need to sign the spellbook license agreement. to do, comment on this PR the below:
`I have read the CLA Document and I hereby sign the CLA`

**Comment by hildobby** [comment]
> tagging @hildobby as there is another open PR editing this spell -- do you want to help take a look?

I'm reworking this sector quite a bit in https://github.com/duneanalytics/spellbook/pull/4556, I'll make a PR that adds entities (including those in this PR & add @nerolation to the table contributor list) once that PR is merged, thanks for all those @nerolation!

**Comment by jeff-dude** [comment]
with the above comment, i will close this PR then. please do tag @nerolation when you add this extra metadata, so they are aware 👍

**Pull request closed without merging**
