### PR TITLE
Add drop market trades to Foundation

### PR DESCRIPTION
**Pull request by fuJiin**
This adds fixed price mints and dutch auction mints from Foundation's Drop Market [contract](https://etherscan.io/address/0x53f451165ba6fdbe39a134673d13948261b2334a).

### CODE REVIEW

**Comment by fuJiin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fuJiin** [comment]
@0xRobin let me know if you need anything from me to help push this through

**Review by 0xRobin — APPROVED** [review]
:heavy_check_mark: looks good

**Review by jeff-dude — APPROVED** [review]
works for me, thanks for the collab on this

**Pull request merged**
