### PR TITLE
Fix some spellbook attributions

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:

I noticed that some spellbook contributor entries were inaccurate so I propose this fix:
- `OxRob` -> `0xRob` (fix username typo)
- `sui414` -> `danning.sui` (switch from Twitter username to Dune username)
- `rantumBIts` -> `rantum` (switch from Twitter username to Dune username)
- `Henrystats 0xRob` -> `Henrystats`, `0xRob` (comma helps it recognise it's 2 ppl and not just 1 account)
- `rantum,bakabhai993` -> `rantum`, `bakabhai993` (space helps it recognise it's 2 ppl and not just 1 account)

@0xRobin @henrystats @sui414 @RantumBits @bakabhai993 

There are more usernames in contributors that aren't dune profiles including: `victorstefenon` , `theachenyj`, `thb0301`, `guyhow`, `davidcheongyl`, `jackiep00`, `tian7` & `ripple3` . But idk what dune usernames these people have 🤷‍♂️

Also, it's probably worth making it very explicit in docs that it should be the dune username in the contributors section, what do you think @andrewhong5297?

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by augustog — APPROVED** [review]
Test is failing due to a known error (working to fix!), I checked the files and none of them affect logic so we should be good to go here.

**Review by jeff-dude — APPROVED** [review]
big time, good looking out 🐐

**Comment by jeff-dude** [comment]
@Stefenon fyi on this PR description (your name is called out), if you put a username for your contributions, feel free to update to dune username to get the proper recognition

**Comment by RantumBits** [comment]
dune handle > Twitter handle

**Pull request merged**
