### PR TITLE
Ethereum staking deposits

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:

Moving my Ethereum staking dashboard (https://dune.com/hildobby/ETH2-Deposits) to v2 and making the tables public for all to use and contribute to.

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by 0xRobin** [comment]
@hildobby pretty sure the line 13 is the problem here.
 ```
 Syntax error near line 14
    ------------------------------
    11 |     description: Ethereum staking identified depositor entities
    12 |     columns:
    13 |       - address
    14 |         name: address
    15 |         description: "Address of indentified depositor entity"
    16 |         tests:
    17 |           - unique
```

Either replace `address` by `&address` which adds a marker (not sure what the official name for this is) and allows you to reuse it in other models as `*address`, or you could just drop that line and start with `- name:`

(example: https://docs.getdbt.com/reference/resource-properties/columns)

**Comment by hildobby** [comment]
> @hildobby pretty sure line 13 is the problem here.
> 
> ```
> Syntax error near line 14
>    ------------------------------
>    11 |     description: Ethereum staking identified depositor entities
>    12 |     columns:
>    13 |       - address
>    14 |         name: address
>    15 |         description: "Address of indentified depositor entity"
>    16 |         tests:
>    17 |           - unique
> ```
> 
> Either replace `address` by `&address` which adds a marker (not sure what the official name for this is) and allows you to reuse it in other models as `*address`, or you could just drop that line and start with `- name:`
> 
> (example: https://docs.getdbt.com/reference/resource-properties/columns)

Ahh makes sense, thought I still had to define them under a name even if not to be used again, thanks @0xRobin!

**Comment by jeff-dude** [comment]
i pushed some commits to reorg the structure & fix some missing jinja/add more filtering/etc.
i'll be curious to see how this runs
please do take a look through the changes and let me know what you think

**Comment by hildobby** [comment]
Awesome ty! I tested it out and it looks good to me :)
https://dune.com/queries/1925023

**Comment by hildobby** [comment]
Awesome ty! I tested it out and it looks good to me @jeff-dude :)
https://dune.com/queries/1925023

**Comment by jeff-dude** [comment]
assuming you saw the error on failed test for unique key assignment?

**Review by jeff-dude — APPROVED** [review]
sounds good ser 🤝

**Pull request merged**
