### PR TITLE
 Polygon Data Team NFT trades - Ready for review

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
Hola ser @jeff-dude, not sure if you are able to access this dework [link](https://app.dework.xyz/polygon/nfttrades-32774?taskId=a2423a84-9429-403b-a626-d7a198f715cb) but it's a task to add a different methodology for nft.trades specifically for polygon.

The methodology in this pr is a duplication of what the polygon data team described in the dework task link I shared and they want to build a dashboard on the spell.

I didn't add a post hook in the schema as the spell doesn't have to exposed on dune.

Would it be possible for this to be added to spellbook?

**Comment by jeff-dude** [comment]
> Hola ser @jeff-dude, not sure if you are able to access this dework [link](https://app.dework.xyz/polygon/nfttrades-32774?taskId=a2423a84-9429-403b-a626-d7a198f715cb) but it's a task to add a different methodology for nft.trades specifically for polygon.
> 
> The methodology in this pr is a duplication of what the polygon data team described in the dework task link I shared and they want to build a dashboard on the spell.
> 
> I didn't add a post hook in the schema as the spell doesn't have to exposed on dune.
> 
> Would it be possible for this to be added to spellbook?

this feels like a good use case for materialized view within the app? since it's specific to the team.

also, please look to use `tokens_<blockchain>.transfers` for transfers tables

**Comment by henrystats** [comment]
@jeff-dude the query times out on dune.com :( 

I'll update to use tokens_<blockchain>.transfers for transfers tables now!

**Comment by henrystats** [comment]
@jeff-dude I've updated the transfers table... The query doesn't run on dune so can't make it materialised as it times out :( 

would it be possible to add this to spellbook?

**Comment by henrystats** [comment]
bump @jeff-dude 👀

**Comment by jeff-dude** [comment]
> @jeff-dude I've updated the transfers table... The query doesn't run on dune so can't make it materialised as it times out :(
> 
> would it be possible to add this to spellbook?

i don't have access to the link for the request. i'm still a bit hesitant in this code current state to add to spellbook. if this is experimental, and intended only for one team, i think it should happen in mat views. if there are performance issues on the app, there can be workarounds:
- start with a subset of the historical data, build small and test out from there
- build multiple mat views that span different timeframes, union together

just a few ideas. i'm not sure the end goal here with this spell and how it can be built out in the future to help the entire community. it's heavy processing add for an experimental adhoc spell

**Pull request closed without merging**
