### PR TITLE
erc4337 account_deployed polygon chain

### PR DESCRIPTION
**Pull request by 0xbitfly**
# introduction
this is another event log for erc4337. it's for smart wallet creation. it's different from `userop`

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by 0xbitfly** [comment]
@jeff-dude do you have any time review this PR today?  I plan to finish all the erc4337 related spellbook this week.

- AccountCreated spellbook
  - [x] polygon: this PR
  - [ ] ethereum: next PR
  - [ ] optimism: next PR
  - [ ] arbitrum: next PR
  - [ ] avalanche_c: next PR
  - [ ] gnosis: next PR
- UserOps spellbook(alreadly merged)
  - [x] polygon
  - [x] ethereum
  - [x] optimism
  - [x] arbitrum
  - [x] avalanche_c
  - [x] gnosis

**Review by jeff-dude — APPROVED** [review]
nice & clean -- thank you!

**Comment by jeff-dude** [comment]
@0xbitfly you need to sign the new license agreement in order for this to be merged. plz see above comment from the bot and copy/paste the message as a comment

**Comment by 0xbitfly** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xbitfly** [comment]
> @0xbitfly you need to sign the new license agreement in order for this to be merged. plz see above comment from the bot and copy/paste the message as a comment

Done!

**Pull request merged**
