### PR TITLE
added boost deployed data

### PR DESCRIPTION
**Pull request by raho1**
Creating spell for Boost Protocol data

### CODE REVIEW

**Comment by raho1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by raho1** [comment]
recheck

**Comment by raho1** [comment]
recheck

**Comment by jeff-dude** [comment]
hi @raho1 -- the license agreement bot gets tripped up when commits look like this:
image

any way you can revert the commit from full name user? or change the owner? if not, maybe start a fresh branch and close this / reopen on fresh branch where commits are only on @raho1 username

**Pull request closed without merging**
