### PR TITLE
[Easy] Add 708 missing erc20 tokens

### PR DESCRIPTION
**Pull request by bh2smith**
Generated with the script:

```sh
docker run \
    -e SPELLBOOK_PATH=$SPELLBOOK_PATH \
    -e INFURA_KEY=$INFURA_KEY \
    -e DUNE_API_KEY=$DUNE_API_KEY \
    -v $SPELLBOOK_PATH:$SPELLBOOK_PATH \
    ghcr.io/cowprotocol/data-misc-missing-tokens:main
```

### CODE REVIEW

**Comment by jeff-dude** [comment]
seems you introduced duplicates?

**Comment by bh2smith** [comment]
Oops ... Maybe this isn't based on main....

**Comment by jeff-dude** [comment]
> Oops ... Maybe this isn't based on main....

still the same dupes, maybe the script is misreading the missing?

**Comment by bh2smith** [comment]
This is weird.... will have to check later.

**Comment by bh2smith** [comment]
Our query disagrees...

https://dune.com/queries/2444707

Do we have an example of a duplicate... the failing test doesn't seem to reveal this.

**Comment by bh2smith** [comment]
Ok so I found 292 duplicates:

<details><summary>List Here</summary>

```
0x1848e4766543e5fe33810038df35424db0774eb0
0x9600ea58a8601e718e9bb63d19416d9935c553cb
0x1e9cbaaca99ee55ed44428ef100d844358e51d6b
0x617417f4916db12f5f3e6b0cfaf551cb2f5facee
0xc7f4fbc261f466c9c0554233f5e14d9158f51048
0x4c547c10fc0d378c97d894e8e7042c44d4ac6b03
0x79ae58264da958b1ab54360fa5b73a9958bfe8a4
0x13cfb6e0a9d9b9432150cf2f47e3bd5dc186c514
0x40338e61be9bcd360d6655bd267d9fcfef687c32
0x84748c1c0c30e1c4b7862d259a8d229229e39345
0x616dc2536ea9c5cf44001bc6356e67fbefe0a029
0x4d7b30b075ed663b9dcd87ecd9e66e86f1fc9abf
0xe8e385a06ad6b9e26f35b502411a6eff711bc2ec
0x0a8785516e616b188b7a030e1ad4541de79e29b9
0x13f56a42a00eb1a43bd69778d4d1dc880153fdcf
0xc0c172dd361c665d864ed316ab321cec6b91f6c0
0xfeedf8d2a8238adc9595db4c80778c6871cc1854
0xa4ab8072c5cb03fc0fcee277573e1d7f50f4ec0d
0x16c1dd49c25adb023fdc18fca76c2aea54160558
0xd223e60031796733db95925ba3ac75ca1df3ddf9
0x1a97807548ccd5b4671c1576ea70a673859c3a04
0xfe364abcf6b14c1d591f7c9eb13ab52366a0cf78
0x07ab97808c9503bb0a00a63cb80511a80fd7268a
0x0d90138e116b58aec1c80b9e90775a7194943856
0x581dafeba7bf8fa69e4387eff5eae9eb6401657c
0xfa4460d83397dc15eb04019c67d5948b257b507b
0xbedebc001ce635ea76c9c8c94a383e2c1220f49f
0x5fbd6d0f3c7c1b076377ccece6a3015892dff96c
0xd337ba765105a77e294a2add7883ae44e5a9664a
0x80b8b1c28e1c64f421f642928c2b74e6784433f8
0xc798783c7ceb9efe21e6213bac441ae28696ae9d
0x58d877839faa4628ce16465c64db9c50634ad700
0x81872fa3c3a34192425d7facdff0e9d8a0157207
0x7e0051bda2251b4376b0d4ca9b5ed6f921b60cb5
0x99f5acc8ec2da2bc0771c32814eff52b712de1e5
0x8bf820345895f3a92206114048c9bf011fe2a83e
0xe48f40c570a0c56d83d56467e6b0c840b0644ba2
0x68a495bda9474e8cebdbefeae6cfee69624dce6d
0xd50478febf49d289284b6530f89acaf220256ef5
0x51df3fd77ee452fff9a04533302c5bd06087ccf3
0x5532628753bbb19d42851d95ed8be6ff70fcf2fb
0xa147361dfcfbb265a5ac115bf2d125bdbe5de39c
0x9be0fe64c9e52c0aead33017d07aaabefc8836c7
0x0e6fa9c050c8a707e7f56a2b3695665e4f9eac9b
0x77b09f8efc211251a961eb3ca384534837e1a5be
0xa3f4feb58869e4bf1b4a680d7180115157d6a22a
0xc018b0dfd9b98676fd9ecab7e9dd0f332292cd5e
0xf3115b544c287380d34a19280dcfd029eeada9c8
0x04d132e5f2147390b9f7676ad4b5a9202e145cbd
0x50a84eb70b68bb07ff685c353f516773e9e3a2b7
0xd5dee004ac366dda5e5475ef98d46adaca8701e7
0x5f4cc3b0a2a3d310ef4e8ebcbeabd97a369585c1
0x5d59c0752dadb7a92917deda1b8569a6987c3b54
0xd4a112f31f93f4d0740a664d3c16ea7ba65c6258
0x80a47189daf835e9c9df83592718bf656205ebce
0xd57cdba5e2828ee1411530a38326e56347da8771
0xc825ed9c8dc1b5d21c80f7f9dfe25bc73a6240ad
0x5c40e75663a589151ea19aee70f797df0d5975ed
0x7f2bef1baad2903542346c919029020e266d8c75
0xcc54b3ae56ef26158f0b8933cc7e19c5d95d0e98
0xd82bc9f7691f26c17fba5ace2863ad85f14c4765
0x6bed6d168fb3429542f009df46c8e8f307deb2a8
0xc3212208ee2071501d861dcbcc5a22bd7291b09a
0x3162d6415741a92ccea91b13b870a5291ce74f65
0xc1a6ace27d823fffec66c09cd9308637784914e6
0x15673a67750dfae6f81ccfc34a2ff6b3badf8837
0xa007599855adb8b937089d5c8934a01093d3cafe
0x67cfa4b79bd5dc24774a1277a9b06c726c13d71f
0x41c2ad4add42a83eb74701cc8b132501a991a933
0xb45c4e945e83f08f6a51017822c9defc6ded9093
0x1e3f899a191a44665dc213f0c01891d56c970392
0x50b275a15e4f5004aa96f972a30e6a9c718b203f
0xd37ff58006413cad3b105af098ba483e1a8a870c
0xa408808f0960f811cd6c4cbf4af6d61f18ad8703
0xf93adb8a9b357d4be154cd12d04703f8c4c75b09
0x517f20f70cc385109e0b72a109226e563e079dab
0xbb16c24ef85639219eb8b35b1879bb0e21321940
0x7f86bf177dd4f3494b841a37e810a34dd56c829b
0x851fa59c45eb9e36366f67dd363d08012b04fc17
0x8a78b5943f1a0e3f01e8c25b03c2790231422257
0x8636add2ff5ce1e3433b4967ee7e690489ec1603
0x7e7f692a260bd70278624dc840cef47364bb512d
0xb875f3f096155ea558962337c205175c5a15ce2e
0x69b29f7f8f6732d992c65b82ae49ac060529aa6e
0x8297ca8ea92641189be80a1b8a7486aec284a557
0x521b8074f3c6cb038dbac73d34bdd761401ce553
0x669c01caf0edcad7c2b8dc771474ad937a7ca4af
0xe15ec736585342122d94ee6d190ec9aeb0913694
0x4a385f4dcba8274f23165866b300aa97108491cb
0x8c44b722ede8d6cc9f7b2372cbe10a935e5092b1
0xf6afc05fccea5a53f22a3e39ffee861e016bd9a0
0x553f52dfa1ec7cafd7209dcd7c9c455b75112db3
0x6842811df0fcfaa4c3b8ba6567dfafb9d4f3c23d
0x7de2931dbf998999189d09156caa209c08d36ad9
0x22699dede2cf5b15748b6d6dcdb158bee32fa7fa
0x3ef6bdee7ad23dfb206907590b6f411ded50f2df
0x0f7257b1d426b990d5d067d7765e0fda3744f6ff
0xfb067bb7f66ba03dda09bc652fca7922a592bf14
0x3345b3e069256fcb8cab59876cc7f2ff6f06214c
0x748509433ef209c4d11ada51347d5724a5da0ca5
0x26a1626d0f4cc7250ac7dd1f1a1e868008f5cad9
0x9f4e7d5600cf01a83fc0d27903c464982fb42af8
0x093162de984c7b4e6743a5a551816c05e09e25b3
0xb1dc1897284f1c7e4e643d333e1d24686ac018c0
0x9b5e827caf1e7c106a285f4eb1f62445033b6dd4
0x5fba129da70ee69dfc6688b0704d9ccb43f4eb82
0x7c07c8d83431d9e9080b435c0c71450b987d594e
0x6caea02cbd2ef17000d390d8478199db62f0080f
0xc0c894e0e85cdf5b915afc279ec5510a41bb285d
0x37e8e6e45bf9bcc4f02f2949c6a7e41f84b7f3da
0xaf65705438adc83c0191e23ae4350d0d50c356c4
0xd270d49e0474ac272d758447e3ae0165725d508e
0xeaee577410beb3d4992915daf96a6cbe92fe8366
0x7b43218c1c09f00576d609cc22783c47b286189b
0x478a0b41c682806864a58fe8430ce1afdcaab786
0x25d6d0feb66dbacdedf3d74fedc01b923c0092e0
0x559458f6ece2944533b4495b90d2c7b593fe5b90
0xfb243bc5e98286e8560f17c3f6b48203afe43139
0xe5d10e024403ec7b507094e1762527f419742d2f
0xd4152f6fc741c6ae16906a7d00ec1cd7afe3833d
0xa3d070051e8ef3d52a0711d91f8886011dee2908
0x8fab6fa901877eb6ffcc69f2917aed5d78e0a275
0xcb36470ea3bfd5f743edcb9667cd88ee45121926
0xde67d97b8770dc98c746a3fc0093c538666eb493
0xbb1e6a3208e106fd4f2e436ec864d2038bc19c69
0x30f59885a0965415a88d270cf11152e0ea8e2db9
0x55f1e22e75086aaf2da85a6765752e7c849a9066
0x0cd6f267b2086bea681e922e19d40512511be538
0x497b5a114df1fb373ff4e3194fdd46478fe02290
0xa48c5cd4c83fa42a4a401560a5a29fdf010fd600
0x407af4979e863775a106ae6f43d8fb80697da2fa
0xe4d3920c274f107176a022a831c354332e0e9180
0xee080fd34c339825eebb7cb31352c84661b22e76
0xa130e3a33a4d84b04c3918c4e5762223ae252f80
0x1164158013b4596b3e0c26d5ca05ef19577171c5
0x0a80ccc5bbd06be093d51bbbaf268e2a1fe0b420
0x35ee3845aaf439406d4736b53287c841ed6bc99e
0x50e5d59b54fd8331fdfc59974a02e421f78b3a58
0x961eac17469f5ae471678c1e8d88f6c82ed4349e
0x4b005ce15988b1ca03b5de5e14d036568abea453
0xf07ebf00aa847bbb0057b92cb469747e2c7c8a4f
0xc368a3a0e9db251de9a853931ce44d0a1194be7b
0x923283dc2cfee206f0c855876df18024ad722c8f
0x330e73dd089946013f48e13d68dc49217b991e88
0x0e232485f7cae375f90ce11c91db0d6ecd9cb9d4
0x345e885a1318283c4f805f0250214b63b87d2605
0x21f424ff9672c5d3ccfc2885aefa1897dc1a722e
0x24094425778f26064cea5952c197c069be22b001
0xeb075bad09f1f82a6bb11e2922856bf68b78e8be
0xde7eeaa7afce822641afa98759820fe678039eb4
0xa35b1b31ce002fbf2058d22f30f95d405200a15b
0xab84f9a1ad03ce87447eb75f31a3e803d16fcc92
0xaedf386b755465871ff874e3e37af5976e247064
0xdf448d65c83d32d839f985165a05000fde9040ca
0x95e54566c0a2e3c205c54a7fea64ca84d81c8c96
0x8adeeb3e23ed8fda0687401d8b9dcde48dca42a0
0xd37650aceeac8d89ef030d21bd4018ec92ed5d91
0x9a4d16453e964f157ed15ea3b10da5e3a89ed613
0x964ba9cc88899b8bfbd3836891c7e96b499d821d
0xc92109d8fcba917438555b8c7cc2445e169eaf02
0x2fcea621fba92c268fe16f17ca6bf37e70c7fa1a
0xe3785d29ddc233153518e0f59317b2a79c8107bd
0x69bceb0b47cc6d4447e8ec398f640175958cef07
0x4071fe86ca1eb1a6a273579d62a1fd6cff551f95
0x2463178ec05b26b97037a70a8951289bb64bf142
0xb2cfc9a054562bcfd854dad55a99e8bc8085a480
0xb1efa5f766abed7fcc455f53b4fae1d0560a413a
0xe7f5457b292d9068ff4df35272dabbb1767f1f11
0x9c616f1d606efb4b294bdf00e55252ea0a1a0921
0xfe278e61560482c04cb786347f8ebd84ac2ed13b
0xe8d06e2a1d55d0c2bc803e52a90e9da0f1fc1f47
0x69a68d4d83d5ea53dc9fa35ca0a49e7dadbb3c3e
0x948c93e1417d354b991cf1098dd94210f9dba506
0x52d10b3a09c82640a027c61bff5e9eb558008095
0x6036250b1db579ad5f333a130ea5a4ec28b5789e
0xca48e61f149920e3a23cbffc9b5541e410c02381
0xaa36d465defc469c7f520994b1f9be4786bf35bf
0xeca87795fb9eb6a0b8698cbac2fd9f1df78510c4
0x1405ec07d4c618fc8a1629758b39516e2b64bf3d
0x93082832a419846f833abd45d8e07ba0701029f6
0x61bd7728089053b1f814d61072b81bd6e3ba32ae
0x6e9da4d9ba8b9fd07efaafe8bdd00c8c2d20c446
0x3e777240cc618957ed0ad94ab05e57505b01f0b4
0x91d9a6f7647c9379647b6276b758f8adf12c4340
0x9459ea2dac369336816ba44641c951c0d714fa07
0xcd39d2b22ff6fac1f4cba56dff886e54f5357bc2
0x069cf7c4d2e0936c92f854e9c8f6993387af45c5
0xba444bb7d5671872e7466810a4071549cdb5defb
0x4ce68164a25f786a53dd1f401e11a8f353045a71
0x1c73c71e2a9c9a83848d0980179eb237a9fd2153
0x3feb4fea5132695542f8ede5076ac43296d17c6d
0xbde273ed13266e26d30a810edd8641dd07dc1208
0x04195dc5d6369cbddd3133d20f678156dd06ed52
0x52392e8ceceb1ff0fc23e9989fb98eae590151a4
0x0c94c1848f92c31ce03b8f8d5eb845b6d5485797
0x949bb77e38059914895debf4b2384a7a09c6b32e
0xd2c869382c7ac9f87ff73548d029d67c0f9dee31
0xe1df28a9ba2f46014c947c300952b7ca20031e3f
0xf234248cc8df4cd24e05e1b2f50c4fc8ff0c3310
0x152aa255dea1cb8161deec24e3037be377586e39
0xba37b0f8ce86b32a2e588c03a93c6c2dc029d803
0x85eae426d61b2b18f901ae87ad3f45d79ed9fd39
0x1093192168a4e3344af3bc01cc19bae02a3fa3d1
0x0a5a60e575dee5c7bce341af4ee9b50e173355fc
0xe9fea4479fc04f797190350687775573496d27a7
0x240d6faf8c3b1a7394e371792a3bf9d28dd65515
0x0e89367ce28209fe791c5b0dbb9880ea23f546e2
0x24d0bcbd7693bd225df019c261c831938a6b9b70
0xf03992df822556ea83b9023620d2b0b6660b05b5
0x65c01b3ceadf887161a3a6572eb78c48cd53e061
0x0bdd34120cfe6fa2a2c99e0e876c8d732498b1d0
0x9e962815efeaa9fbb0ca98f1c8feb55828da4557
0xe7c5eff99cf7550e1995c7b7c33c7ae1d9a48cfa
0x524a7802a3a46a676979eb19b8a1aeb39b42c9ef
0xac37ead00e1eb4fddbc784b12286b360ff96f2e8
0x9aef15adc06082e107411b775d418faa4575dc9e
0x0eb64d242eaaf5dc2238ba84d34dea40dfbc0f72
0xb177e63619deb8227cc0796d0620f62643602267
0x74fa792e17904e70b0eea734769ad87264f00928
0xbef2f75d5d7ab52a047e87b0c26d4028aff2bd66
0xd606d9ac395755be8b14951d124616371fe4737c
0x4e50fb56770945cc154edca34daf17e148ef907d
0x6293bbe52c3682057163172850002f18f993da6a
0xbe82bbd9c47e05f1fac183b106a768717588be73
0x0b0f960d1eb4d857ce221303342f77c5e94acabc
0xc1e83dd3cfdbb4a33d78b01bc79f6d06c38df931
0x9cb575e4fb5b6b1f649e79594edab80949eea119
0x76bda39e2b3f35c3fd6a6ec57c87b2657b500a0b
0xcdf6d021dc97f4eb26d69013725447082ac9568f
0xd28c23e00c8e04132bfcd74543c43870b16ffa26
0x2437a553f2355c46106bb278c64c3fa0d844b1c9
0xb6f996af983d677949ea3246750aa19ff07a2243
0x21177b3724c5c83e1bf7c3944fec427e6916937e
0x8946321bc493ae18aca042dad3a9c87718f4dd67
0x3607d80ba2b33539cec60fb1cc3aa4a336258bf0
0xb8f5ede5892b093011a36bd3acaebdeeccfef86c
0x9f85cc1fc60451e032e191ecff141d557c7fa969
0x2c5f76142ec17bbcef2b513d1a66458eaf9c2171
0x72bab498fa50a33a03362d0024bb27efbc50a7b7
0x2d783c1f7e76518475a67c72642885d900e6d8fa
0x226597281b5706ffb963f1890b5a2794f86e5228
0xd2bdaaf2b9cc6981fd273dcb7c04023bfbe0a7fe
0xa2036f15f47d6c85d9a9338390496032b9823ce5
0x9877a389947ee0c076bb9935581e9a70b0700c22
0x6e4c77fa440fbb40b3e935204d9080c3a92ff94b
0xa917f7087e5709ed8bc8a93d557ba4e9a16ecf9d
0x19dac950c6ac36c0e1ed2744821c20759ed96979
0x678b34fab2e2d927fbc95602b2589476e0ca0fe0
0x57e01d1ada5c4aa4d6d00bd1ad4a774880fd60b4
0x0000000001d11ff1aaee65e923f5657e45b260e1
0xd11008d2936eab0021000281863cf7240b9c338e
0x88f28a9812896e92c552b2f3b7bc464e2f834242
0xf2be205e75368b68f76d02ecf4c2834951b345e4
0xd71b6ced37527c015d7d8e2717d78d70834d64f9
0xe44a6e7dea9a0835846e6dcbdded0fe620ff5fc9
0x359243395d30f3c966eec8ed5c535cc82ff9d745
0x999998e49a19cd9ccf3fcc0ae61051a09be7d182
0xfdad8ce706961c0b897ca20398f17d7801a14e20
0x227a880e3048b9fee3c01bd0b081c2d16013c968
0xc19c1ff5ccd550f0489e1027892e4c7ceed9f189
0xbb703412d47b681646f5b241a937b8136d9a2bc8
0x711b3ee03a211dfe144c79645c7da808bea6a914
0x54a1f841b5d8699ba2f3c02fdc754575614ca3dc
0x4ce5df9033ead87976255a8695592bca3e8cb5cb
0x6d73fd63cbfac5cb3a0f914b126a0d69e671840f
0x6144364b64cc4a37025fe92284e37d7968216a6b
0x75209a127fdf7cc9fba1976caaeef54e6da0bf54
0xe9be1172e2a12deada42fd397ff8d4d9ed227a30
0xc4e4f65e4ec6caeb0d7ca9962bde1edf8c402cb3
0x035158f32f05abd6f519dd6f2d2771d290118a1b
0xd8585025375965343178dde010271bd46ec880e2
0x0a7fafa2c531f137570b94bc86fe39f75f2f8240
0xbaea5e07080f00d54965a6121d6fb69a6c648c1f
0x9d6db170fad62e991bb02d4ad22a3ce56c54ea95
0xe8c26519e6fa96f5b6104c9e50fe8c2911ed462f
0x6bf3c7602fd73d17a52ca1fd7438d844586c8609
0xf69a7b4307e89676b9ade53cd8c9bd27cc19e73d
0x1eb6181d3d0b4bc77df7e7f70a4a93d69063e3a9
0xf523467cc5d9f3f78c388bc429d68f9b79ca6ede
0xd822aa7a904deb860a44e0bb455ca11a9cfe1ed6
0x703293d32aea894cca91d6c282db9efffe47c308
0x63a2ef2c7d20f8226d1c8c4b71e6832bdca47d48
```
</details>

**Comment by bh2smith** [comment]
So --- I believe you guys have some problem with your table not reflecting what is in the static file:

Here is a query showing that none of the 282 "duplicated" tokens above are in the tokens table.

https://dune.com/queries/2756023

Perhaps the last token update was merged, but did not make it into the actual table... and thus, my missing tokens query is returning incorrect results. 

Just let me know when this is sorted out on your end and I will rerun the token data fetching script.

**Comment by jeff-dude** [comment]
interesting. i'm running a full refresh on dunesql engine for the `tokens_erc20` lineage in prod. then maybe you could rerun your script to see what it adds?

**Comment by bh2smith** [comment]
It appears to be fixed now. I will rerun the thing.

**Comment by bh2smith** [comment]
Done. added 456

**Comment by jeff-dude** [comment]
> Done. added 456 tokens and passing.

much better. will queue it up and look to merge after some prod maintenance.

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
> This is getting pretty OLD and dated. I just updated and now its 708 tokens. Can we get this merged today?
> 
> cc @jeff-dude

i'll queue up a batch now ser, thanks for the patience 🙏

**Pull request merged**
