### PR TITLE
add opensea_usernames to labels.nft (seed file)

### PR DESCRIPTION
**Pull request by JohnSweeney85**
Brief comments on the purpose of your changes:

add opensea_usernames to labels.nft (seed file)
fix csv error from last commit

### CODE REVIEW

**Comment by jeff-dude** [comment]
hi @JohnSweeney85 thanks for looking to add some labels!

we have some concerns with adding such a large static file (1m+ rows), as it causes issues with dbt. is there any alternative to dynamically retrieve these values?

**Comment by jeff-dude** [comment]
> @jeff-dude It's off-chain data from the OpenSea API that I exported from a local Postgres DB...I can it get very easily in any form. It failed with all the data in an SQL file as well. What do you recommend?

@nileslawrence @dsalv do you guys think this is a good use case for community data uploads?

**Comment by jeff-dude** [comment]
or maybe we look at [this announcement](https://discord.com/channels/757637422384283659/757639462137102377/1112856286204268614) for a process to upload?

**Comment by dsalv** [comment]
> @jeff-dude It's off-chain data from the OpenSea API that I exported from a local Postgres DB...I can it get very easily in any form. It failed with all the data in an SQL file as well. What do you recommend?

What's your dune username? I can whitelist you tomorrow

**Comment by jeff-dude** [comment]
> > @jeff-dude It's off-chain data from the OpenSea API that I exported from a local Postgres DB...I can it get very easily in any form. It failed with all the data in an SQL file as well. What do you recommend?
> 
> What's your dune username? I can whitelist you tomorrow

ensuring @JohnSweeney85 saw this, as it's intended to help proceed

**Comment by jeff-dude** [comment]
closing this until post-freeze, as tracked [here](https://github.com/duneanalytics/spellbook/discussions/3558)

**Pull request closed without merging**
