### PR TITLE
[easy] make trader-age label crosschain - Ready for review

### PR DESCRIPTION
**Pull request by henrystats**
@andrewhong5297 I've been unable to follow the labels relaunch :( 

I missed checking the pr and I had earlier submitted a pr that was merged to make some of the dex labels crosschain. The current one only has for ethereum. 

previously merged crosschain pr - https://github.com/duneanalytics/spellbook/pull/2555

I'll resubmit the pr's.

Thank you soo much ser for the relaunch, this new look is amazing!

### CODE REVIEW

**Comment by andrewhong5297** [comment]
ah yes! maybe we can just call it 'cross-EVM' in the aggregation.

**Comment by andrewhong5297** [comment]
there should be a row for trader-age by blockchain now

**Comment by henrystats** [comment]
hmm sorry I don't quite understand ser @andrewhong5297 but I wanted to mention that the trader age is grouped by blockchain so it should be different across multiple chains and will create multiple rows for an address that trades on multiple chains.

**Comment by andrewhong5297** [comment]
> hmm sorry I don't quite understand ser @andrewhong5297 but I wanted to mention that the trader age is grouped by blockchain so it should be different across multiple chains and will create multiple rows for an address that trades on multiple chains.

ahh yeah - I see what you mean. I was thinking of the nft usage labels. I must have removed your changes when I made the merge, sorry!

**Comment by andrewhong5297** [comment]
looks good to me then! I'll let Jeff take a look too.

**Comment by henrystats** [comment]
okaiee, thank you very much ser 🥳

**Review by Hosuke — APPROVED** [review]
LGTM.✅

This PR adds trader-age labels cross chains. Each chain counts users' age independently.

Thank you @henrystats 

[Sample trader-age label crosschain](https://dune.com/queries/2032493?d=1)

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
