### PR TITLE
Stablecoin balances evms

### PR DESCRIPTION
**Pull request by Synthquest**
### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** stablecoins_{chain}.balances
- **Description:** materialized table of daily balances of stablecoins
- **Who are the new spell(s) for?** Internal team
- **How will the new spell(s) be used downstream?** Using solely the daily_balances table hits runtime errors & recreating the logic for daily views of stablecoin balances among wallets hits query complexity/runtime errors.

This query is for anyone interested in network views of stablecoin balances
- **Implementation details:**The stablecoins are defined in the tokens_{network}.erc20_stablecoins tables

- **Test instructions:** unique address/balance/day
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by Synthquest** [comment]
@jeff-dude 
I'm having trouble finding the macro or model that creates the `balances_raw` table

https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/tokens/macros/balances/balances_daily_agg.sql

https://github.com/duneanalytics/spellbook/blob/main/dbt_macros/shared/balances_incremental_subset_daily.sql

Specifically on optimism - I just want to make sure it accounts for legacy transfers

**Comment by Synthquest** [comment]
Otherwise these should be good to go. 

Note for myself: To add more chain in the future we have to create the base daily balances table for the network first

**Comment by jeff-dude** [comment]
> @jeff-dude I'm having trouble finding the macro or model that creates the `balances_raw` table
> 
> https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/tokens/macros/balances/balances_daily_agg.sql
> 
> https://github.com/duneanalytics/spellbook/blob/main/dbt_macros/shared/balances_incremental_subset_daily.sql
> 
> Specifically on optimism - I just want to make sure it accounts for legacy transfers

raw balances is done outside of spellbook due to compute requirements (v heavy). they are based on transfers spells though, which can be found here:
https://github.com/duneanalytics/spellbook/tree/main/dbt_subprojects/tokens/models/transfers_and_balances/optimism

`base_transfers` for raw data
`transfers` for enriched with metadata

you can help us validate the optimism transfers there 🙏

**Comment by Synthquest** [comment]
> > @jeff-dude I'm having trouble finding the macro or model that creates the `balances_raw` table
> > https://github.com/duneanalytics/spellbook/blob/main/dbt_subprojects/tokens/macros/balances/balances_daily_agg.sql
> > https://github.com/duneanalytics/spellbook/blob/main/dbt_macros/shared/balances_incremental_subset_daily.sql
> > Specifically on optimism - I just want to make sure it accounts for legacy transfers
> 
> raw balances is done outside of spellbook due to compute requirements (v heavy). they are based on transfers spells though, which can be found here: https://github.com/duneanalytics/spellbook/tree/main/dbt_subprojects/tokens/models/transfers_and_balances/optimism
> 
> `base_transfers` for raw data `transfers` for enriched with metadata
> 
> you can help us validate the optimism transfers there 🙏


thanks for this!
It looks like it's missing the legacy chain transfers. I'm not sure how I can contribute here with it being off the spellbook but two approaches i can think of is 
1) to initialize the current query with a "snapshot" of the address/token/balances taken at the last block of the legacy version
2) include the legacy tables in the model
```
select  
      'optimism' as blockchain
    , log.block_time
    , log.block_date
    , coalesce(bytearray_to_uint256(bytearray_substring(log.data,1,32)),0) as value
    , bytearray_substring(topic1,1+12,20) as "from"
    , bytearray_substring(topic2,1+12,20) as "to"
    , log.contract_address
    , log.tx_hash
    from optimism_legacy_ovm1.logs log
```

**Comment by jeff-dude** [comment]
> I'm not sure how I can contribute here with it being off the spellbook but two approaches i can think of is
> 
> 1. to initialize the current query with a "snapshot" of the address/token/balances taken at the last block of the legacy version
> 2. include the legacy tables in the model

i think best you can do is look to modify the transfers pipeline for optimism, then balances will pick it up. with this being only legacy, i would have to check with the team on how we'd handle the history for balances, may require a new backfill

**Comment by Synthquest** [comment]
> > I'm not sure how I can contribute here with it being off the spellbook but two approaches i can think of is
> > 
> > 1. to initialize the current query with a "snapshot" of the address/token/balances taken at the last block of the legacy version
> > 2. include the legacy tables in the model
> 
> i think best you can do is look to modify the transfers pipeline for optimism, then balances will pick it up. with this being only legacy, i would have to check with the team on how we'd handle the history for balances, may require a new backfill

@jeff-dude I removed OP for now. I'll look to handle that it in a separate PR

**Comment by jeff-dude** [comment]
> @jeff-dude Pinging
> 
> [#6826 (comment)](https://github.com/duneanalytics/spellbook/pull/6826#issuecomment-2381671086)

okay, revisiting OP after works for me.

do you think this PR is in merge-ready state?
i notice we had a short timeframe run a few commits ago, but haven't seen it run again since. i guess the commits are mostly just metadata fixes?

**Comment by Synthquest** [comment]
> > @jeff-dude Pinging
> > [#6826 (comment)](https://github.com/duneanalytics/spellbook/pull/6826#issuecomment-2381671086)
> 
> okay, revisiting OP after works for me.
> 
> do you think this PR is in merge-ready state? i notice we had a short timeframe run a few commits ago, but haven't seen it run again since. i guess the commits are mostly just metadata fixes?

Yea the changes since then are just to the tokens_erc20_stablecoin tables. I ran through similar checks on the balance tables and picked up some issues with them.
These balance tables should be good to go though🤞

**Review by jeff-dude — APPROVED** [review]
okay, let's give this a try.

with this macro gaining more traction (seeing it used in multiple spots), i will catch up with @0xRobin next week on a full plan for these spells

**Pull request merged**
