### PR TITLE
[Contracts] Materialize Chain-Level Tables

### PR DESCRIPTION
**Pull request by jeff-dude**
follow-up to reverting #5023 due to failures in prod
fyi @MSilb7 

prod failure:
```
19:05:21    Database Error in model contracts_zora_contract_mapping (models/_sector/contracts/zora/contracts_zora_contract_mapping.sql)
  TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="This connector does not support renaming views", query_id=20231222_190438_89686_rzduy)
  compiled Code at target/run/spellbook/models/_sector/contracts/zora/contracts_zora_contract_mapping.sql
```

not sure why this happened quite yet and don't have time to debug further today.

### CODE REVIEW

**Comment by MSilb7** [comment]
> follow-up to reverting #5023 due to failures in prod fyi @MSilb7
> 
> prod failure:
> 
> ```
> 19:05:21    Database Error in model contracts_zora_contract_mapping (models/_sector/contracts/zora/contracts_zora_contract_mapping.sql)
>   TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="This connector does not support renaming views", query_id=20231222_190438_89686_rzduy)
>   compiled Code at target/run/spellbook/models/_sector/contracts/zora/contracts_zora_contract_mapping.sql
> ```
> 
> not sure why this happened quite yet and don't have time to debug further today.

Not sure what's causing this either, is it due to changing something from a view to materialized? And is it only happening with Zora, or everything? @jeff-dude

**Comment by jeff-dude** [comment]
> Not sure what's causing this either, is it due to changing something from a view to materialized? And is it only happening with Zora, or everything? @jeff-dude

we ran into this issue again today, so i dug into it a bit more. context in #5100 
we'll need to add that extra property for the short term

**Comment by MSilb7** [comment]
Sounds good! I was about to add the new Celo model too, but I see you got it already 👍

**Comment by MSilb7** [comment]
We should also add `, ref('contracts_celo_contract_mapping')` to the cross-chain view `contracts_contract_mapping.sql`
@jeff-dude

**Comment by jeff-dude** [comment]
> We should also add `, ref('contracts_celo_contract_mapping')` to the cross-chain view `contracts_contract_mapping.sql` @jeff-dude

done ✅

**Pull request merged**
