### PR TITLE
Arbitrum ERC721/1155 transfers

### PR DESCRIPTION
**Pull request by tomfutago**

### CODE REVIEW

**Comment by tomfutago** [comment]
@antonio-mendes do you think it'd be a good idea to convert all erc721/1155 transfers spells into macros?

**Comment by antonio-mendes** [comment]
@tomfutago yeah I think that's a good idea and the final goal, but it's ok if we do chains like this right now, validate we are happy with the final results in terms of data quality and table design and then do a macro.

But by all means, if you feel like you'd like to dig into that feel free to go ahead and experiment!

**Comment by tomfutago** [comment]
@antonio-mendes what a timing! just wanted to add a comment that I decided to have a go at creating macros anyway - and it's actually ready for review (including converting already merged erc 721/1155 transfers for Celo) - PR [#4365](https://github.com/duneanalytics/spellbook/pull/4365). 

All my evm specific PRs (this one for Arbitrum and all the rest) are re-using exactly the same code, so I think it'll be much cleaner to check and merge #4365 first (and totally in line with your point of having macros as a final goal, easier to maintain and add future evm chains) - and then I'll update all my erc721/155 transfer PRs to use macros. What do you think?

**Comment by tomfutago** [comment]
@antonio-mendes @jeff-dude just to check what's the update on erc721/1155 transfers testing?

**Comment by jeff-dude** [comment]
> @antonio-mendes @jeff-dude just to check what's the update on erc721/1155 transfers testing?

hi @tomfutago!

we're tracking transfers and balances [here](https://github.com/duneanalytics/spellbook/issues/4521) and @aalan3 is helping take the lead while antonio is out for a bit. first step is a macro for erc20 transfers, then balances, then we can focus back on erc721/1155 to follow a similar pattern

**Comment by tomfutago** [comment]
Thanks @jeff-dude makes sense (and no rush, I'm away atm too). Btw, as mentioned in one of my previous comments - I also have opened PR #4365 to go with macros for all erc721/1155 transfers and also updated #4306 to use macros for erc721/1155 balances.

**Comment by jeff-dude** [comment]
> Thanks @jeff-dude makes sense (and no rush, I'm away atm too). Btw, as mentioned in one of my previous comments - I also have opened PR #4365 to go with macros for all erc721/1155 transfers and also updated #4306 to use macros for erc721/1155 balances.

yep, the team will be sure to leverage all the open PRs in this use case while finalizing 🙏 thank you for the work up-front to get us started
cc @aalan3

**Comment by jeff-dude** [comment]
thank you for the patience, now that the spellbook migration is complete, as we attempt to rebuild transfers & balances spells on the dunesql engine 🙏 

we will close this PR now, as the work on this set of sector spells can be tracked in the following locations:
#4521 
#4523 
#4633 
#4698

**Pull request closed without merging**
