### PR TITLE
Fix Linea and Zksync for Rollup Economics mapping

### PR DESCRIPTION
**Pull request by lorenz234**
### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [x] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by lorenz234** [comment]
Hi @jeff-dude,

Just updated some of the mapping to new addresses, though now getting:

TrinoQueryError(type=INSUFFICIENT_RESOURCES, name=CLUSTER_OUT_OF_MEMORY, message="Query killed because the cluster is out of memory. Please try again in a few minutes.", query_id=20240614_074019_00004_fii5e)

is it my query or something on dunes end?

Thanks

**Comment by jeff-dude** [comment]
i see @0xRobin self-assigned this -- i'm wondering if CI failing is a sign we should split this spell up like we normally do per blockchain, then union together after each chain spell is built?

**Comment by 0xRobin** [comment]
yes @jeff-dude I agree, these queries could use some optimizations. 
Currently the `ethereum.transactions` and `prices.usd` table is joined in for every chain subquery, which is not optimal. 
I think we can reduce the queries to:
1. for each chain, get the `block_number` and `tx_hash` of all the relevant txs (this is different for each chain, some use events, some use a filter on transactions..)
2. union these all together
3. join the result with transactions and prices to extract the relevant fee information.

We could do (1) in chain specific models and then (2) and (3) in the final model, both should then be materialized I think.
thoughts on this design @lorenz234 @Jam516?

**Comment by lorenz234** [comment]
> 1. for each chain, get the `block_number` and `tx_hash` of all the relevant txs (this is different for each chain, some use events, some use a filter on transactions..)

I totally agree, this spell is slowly growing into being unsustainable. I would even say we should fully switch to filter on transaction level rather than events. While events might not change as frequently we could then just create one consistent mapping, a long table of from_address, entity and function method. This would help to more quickly add new methods into the spell. 

e.g.
`
FROM (
    values
      (0xAddress, 'zkSync Era', 0xMethod)
      , (...) 
    AS x(address, entity, method)`

**Comment by Jam516** [comment]
Yeah, I agree with those changes @0xRobin @lorenz234 . Makes sense at this point.

**Comment by jeff-dude** [comment]
refactor is happening in #6426 -- plz contribute there if interested in the design / output.

**Pull request closed without merging**
