### PR TITLE
Feature/vrf metrics

### PR DESCRIPTION
**Pull request by AnonJon**
Adding Chainlink VRF metrics
- gas_daily
- requests_daily
- reverted/fulfilled tx's
- VRF v1/v2 randomness fulfilled logs
- VRF v1 randomness requested logs

### CODE REVIEW

**Comment by jeff-dude** [comment]
thank you for adding more spell here, will look asap, ideally tomorrow

**Comment by AnonJon** [comment]
Didnt see the last part of the message but just updated to main.

**Comment by jeff-dude** [comment]
@Hosuke do you mind giving this a review while i'm out?

each spell should be the same across blockchains, then there are existing spells on main in these directories that could be used as reference if needed.

thank you!

**Comment by Hosuke** [comment]
Hi @AnonJon, you can run `git merge main` to update this branch.

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @AnonJon

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
