### PR TITLE
handle unique decimal logic for curve in `dex.trades_beta`

### PR DESCRIPTION
**Pull request by jeff-dude**
in reference to #5214 

fyi @Hosuke @tomfutago 

spoke a bit with andrew, who built curve on ethereum. preference is to keep logic as close as-is. the back story is that curve contracts on ethereum got all messy when decoded, so the tables are all over the place, hence the base table usage.
ultimately, approach in #5195 won't work, as we shouldn't default to use `3CRV` token necessarily.

i'm not attached to this approach either, but here is an attempt at getting curve logic implemented. this approach avoids new columns, but requires a new macro and modifying final `dex.trades_beta` to union both macros.

### CODE REVIEW

**Comment by jeff-dude** [comment]
i haven't fully tested this yet, just wanted to get it out there.

**Comment by tomfutago** [comment]
> i'm not attached to this approach either, but here is an attempt at getting curve logic implemented. this approach avoids new columns, but requires a new macro and modifying final `dex.trades_beta` to union both macros.

I like it. So branching off with project specific logic on the final stage in the lineage without messing up existing intermediate models. Nice!

I guess something similar could be adopted for balancer too, so that `amount_usd` gets calculated as per legacy and included in `dex.trades` rather than exposed view. And there's also 1inch in this ballpark perhaps too..

**Review by Hosuke — APPROVED** [review]
Since the decimal mismatch happened in certain `type`/`version`:
https://dune.com/queries/3389004

I think this fix can handle the edge cases well.

**Comment by jeff-dude** [comment]
wrote a quick test query to see differences between new lineage vs. old
```
with
  new as (
    select
      blockchain,
      project,
      block_month,
      sum(token_bought_amount) as total_bought,
      sum(token_sold_amount) as total_sold,
      sum(amount_usd) as total_usd
    from
      test_schema.git_dunesql_22a881e_dex_trades_beta
    where
      blockchain in ('ethereum', 'optimism')
      and project = 'curve'
    group by
      blockchain,
      project,
      block_month
  ),
  old as (
    select
      blockchain,
      project,
      block_month,
      sum(token_bought_amount) as total_bought,
      sum(token_sold_amount) as total_sold,
      sum(amount_usd) as total_usd
    from
      dex.trades
    where
      blockchain in ('ethereum', 'optimism')
      and project = 'curve'
    group by
      blockchain,
      project,
      block_month
  )
select
  new.blockchain,
  new.project,
  new.block_month,
  new.total_bought - old.total_bought as bought,
  new.total_sold - old.total_sold as sold,
  new.total_usd - old.total_usd as usd
from
  new
  join old on new.blockchain = old.blockchain
  and new.project = old.project
  and new.block_month = old.block_month
order by
  new.blockchain,
  new.block_month desc
```

ethereum is pretty spot on. optimism has some differences. think we're good to merge for now, but we can revisit this query in final testing stages

**Pull request merged**
