### PR TITLE
Arbitrum RWA user balances

### PR DESCRIPTION
**Pull request by darvinrio**
### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** rwa_arbitrum.*
- **Description:** Track RWA asset balances of User
- **Who are the new spell(s) for?** PYOR team and community
- **How will the new spell(s) be used downstream?** Build holder analysis metrics
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

**Comment by darvinrio** [comment]
@0xRobin 
the tables are built based on the recommendations from issue https://github.com/duneanalytics/spellbook/issues/5666 
do you have any suggestions about schema or macros? 

context: 
we are analyzing rwa protocol growth in arbitrum.

**Comment by 0xRobin** [comment]
hey @darvinrio, from a quick look at this PR it doesn't look like you would need to build this out in spellbook to build queries for RWA balances on Arbitrum.

Can you try leveraging the existing `tokens_arbitrum.balances_daily` model?
If this isn't suited for what you're trying to do, please expand a bit on you're use case and we will try to find the best way to support.

**Comment by darvinrio** [comment]
hey @0xRobin. 
we want to do analytics on top of the holders table. 
we are looking at metrics like: 
* Weekly Active Holders
* Holder Retentions Corhorts
* Decentralization indexes

We want to do this for a list of 36 assets and ~10 governance tokens. (we expect the list to grow). 
We want it refreshed daily. We will be using APIs to feed this into our front end. 
We were unable to materialize this on the Dune's Largest Tier. 
That is why we went this route. Moreover, we saw the open request to build an incremental version. 

My understanding is that the underlying source table has made the `balanceOf()` call every time there is a transfer. (Not sure where I read this, it was in some discussion)
Hence we went with a simple incremental model.

**Comment by darvinrio** [comment]
we couldn't find the `daily_agg_base` on the frontend. 
image

all of those we found were views, which is why we chose to explore the spellbook route. 

to be honest, we would love to utilize the spellbook, as we will be 
1. getting analytics streamlined for ourselves
2. empowering the community with a dataset and macro that could be useful. 

me and my team have prior experience in building dbt models internally.

**Comment by darvinrio** [comment]
bumping this @0xRobin @jeff-dude

**Comment by darvinrio** [comment]
we are currently planning on using a materialized view, till we can get the dune table up and running. 
can we however, move this up the priority ?

**Comment by darvinrio** [comment]
got it @0xRobin .

you can also share me your specs, and i can get it changed accordingly.

**Comment by 0xRobin** [comment]
ok I'm happy with the changes in the macro @darvinrio, I made some naming changes as well to the models to be consistent with the rest of spellbook. 

Can you give my changes a review from your side?

**Review by 0xRobin — APPROVED** [review]

**Comment by darvinrio** [comment]
@0xRobin this looks good to me. 
thanks for the patch on the incremental. 
🫡

**Pull request merged**
