### PR TITLE
Added models for QuickSwap v3

### PR DESCRIPTION
**Pull request by sameepsi**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by 0xBoxer** [comment]
I don't understand why the pre-commit hook fails here.

I suspect it's due to the test defined here: https://github.com/duneanalytics/spellbook/blob/da1f372d405c8e5c81b3b5e58ea273aac8e9e0ef/tests/dex/dex_trades_assert_freshness.sql 

I can't figure out why it would fail now though, I just changed the number of hours until the test fails.

I had to increase the number as the test was failing, but everything is working fine, the dex just didn't have a tx in 80 hours.

**Comment by Hosuke** [comment]
> I don't understand why the pre-commit hook fails here.
> 
> I suspect it's due to the test defined here: https://github.com/duneanalytics/spellbook/blob/da1f372d405c8e5c81b3b5e58ea273aac8e9e0ef/tests/dex/dex_trades_assert_freshness.sql
> 
> I can't figure out why it would fail now though, I just changed the number of hours until the test fails.
> 
> I had to increase the number as the test was failing, but everything is working fine, the dex just didn't have a tx in 80 hours.

I recovered the `dex_trades_assert_freshness.sql`, and the freshness test failed is due to airswap inactivity.
https://dune.com/queries/2019835?d=1

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @sameepsi 

- Metadata & naming conventions ✅
- Config blocks match uniqueness tests in schema files ✅
- Tests and seeds added for the new models ✅
- Incremental filters added when joining large tables ✅
- Contract addresses are lowercase ✅
- Inner join to large tables(polygon.transactions) as possible ✅
- `CAST()` used in the base models

[Sample quickswap v3 polygon trades](https://dune.com/queries/2019844?d=1)

**Review by 0xBoxer — APPROVED** [review]

**Review by jeff-dude — APPROVED** [review]
thank you @sameepsi & others for the support

**Pull request merged**
