### PR TITLE
Chainlink performance improvements

### PR DESCRIPTION
**Pull request by aalan3**
Adds more incremental predicates on some models where it was missed.

### CODE REVIEW

**Comment by aalan3** [comment]
Ok I figured out why this is slow, it's basically doing a full scan on logs via `ocr_reward_evt_transfer` -> `chainlink_ethereum_ocr_reward_transmission_logs`. Not sure if it's worth fixing atm but should be considered when refactoring these models

**Comment by jeff-dude** [comment]
> Ok I figured out why this is slow, it's basically doing a full scan on logs via `ocr_reward_evt_transfer` -> `chainlink_ethereum_ocr_reward_transmission_logs`. Not sure if it's worth fixing atm but should be considered when refactoring these models

fyi @AnonJon for when we continue refactoring chainlink spells code

**Review by jeff-dude — APPROVED** [review]
queueing up for later merge

**Comment by AnonJon** [comment]
@jeff-dude Thanks. Going to start rebasing the current PR I have out with the changes that are in/going in and ill take a look at the extra refactoring.

**Pull request merged**
