### PR TITLE
Add carbon defi to dex trades (post migration)

### PR DESCRIPTION
**Pull request by tiagofilipenunes**
Simple PR just to add carbondefi to dex_trades.sql after the Dune SQL migration is complete.

Relevant: #3861

### CODE REVIEW

**Comment by jeff-dude** [comment]
looks like you need to ensure `carbon_defi_ethereum_trades` has `block_month` column, since the sector level spell pulls it through. this is a new column in all projects and used mainly as the partition column in model config blocks.

**Comment by jeff-dude** [comment]
you can look to edit in this same PR

**Comment by tiagofilipenunes** [comment]
Thanks @jeff-dude , just added the block_month and for the tables to be partitioned by block_month instead of block_date.

**Review by jeff-dude — APPROVED** [review]
thank you!

**Pull request merged**
