### PR TITLE
RW-5: cleanup block_date in base trades models

### PR DESCRIPTION
**Pull request by 0xRobin**
Clean up partitioning and `block_date` columns in the lower levels of nft.trades (beta).

To recap:
- no partitioning and `block_date` in platform specific models
- partitioning on `block_month` in `nft_ethereum_trades_beta` and `nft_events`

### CODE REVIEW

**Comment by 0xRobin** [comment]
CI tests blocked by: https://github.com/duneanalytics/spellbook/pull/4419

**Comment by 0xRobin** [comment]
follow up:
https://github.com/duneanalytics/spellbook/pull/4427

**Comment by jeff-dude** [comment]
we can revisit a rerun here once gh actions seem to clear up -- we've had queue delays and longer runtimes today

**Review by aalan3 — APPROVED** [review]

**Comment by jeff-dude** [comment]
> will batch together with #4427

guess i forgot this one, my bad! will look to do in next batch

**Pull request merged**
