### PR TITLE
chore: add new chainswap deployer to spellbook

### PR DESCRIPTION
**Pull request by whalehunting**
Adds `0x686c0072dF3Df7A13ef666a3b661803a48558A90` as an additional deployer to ChainSwap's spellbook

### CODE REVIEW

**Review by merlox — APPROVED** [review]

**Comment by 0xRobin** [comment]
@whalehunting, the CI is failing on a uniqueness error.
Can you investigate this?

The last PR for these models did run and test successfully in the CI https://github.com/duneanalytics/spellbook/actions/runs/10792660335/job/29932804281

**Comment by whalehunting** [comment]
> @whalehunting, the CI is failing on a uniqueness error. Can you investigate this?
> 
> The last PR for these models did run and test successfully in the CI https://github.com/duneanalytics/spellbook/actions/runs/10792660335/job/29932804281

Seems to happen because the new router handles fees different (sending both eth + erc20s to the fee address). will think of a solution and implement it once i find the time. thanks for the ping!

**Comment by jeff-dude** [comment]
this PR and #7075 appear to be doing the same thing, but a different deployer address assigned?

can we coordinate the changes and get into one PR?

with that in mind, i'm closing #7075 with hope of pulling in changes here

**Review by merlox — APPROVED** [review]

**Comment by jeff-dude** [comment]
> @jeff-dude applied changes from #7075 in this one, can ignore the other PR

noted, will ignore other one and wait for your word here 🙏

**Comment by whalehunting** [comment]
@jeff-dude @0xRobin tests are passing, ready for final review 🫡
this team has been waiting for a long time for this (my bad), would appreciate if we can merge it fast

**Pull request merged**
