### PR TITLE
creating institutions

### PR DESCRIPTION
**Pull request by andrewhong5297**
Brief comments on the purpose of your changes: moving CEX and Funds into Institutional Category 

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by andrewhong5297** [comment]
this is currently failing because I've moved two labels into a new label category so labels.all will only work on full rerun.

**Comment by andrewhong5297** [comment]
@henrystats noticing `dao_framework` has duplicates - is there a reason that a dao address can be linked to two tools? Can I add a distinct to the model?

**Comment by andrewhong5297** [comment]
@henrystats just checking if you have time to fix this! if not I'll just exclude the model from labels.dao and labels.all for now and we can revisit later

**Comment by henrystats** [comment]
Hola ser @andrewhong5297, I've been away for a while now. I'm hoping to get back to working today/tomorrow.

So if today/tomorrow can work then I'd be happy to look into fixing this, else I can revisit later as I plan to make an update to the dao spell later this week.

**Comment by andrewhong5297** [comment]
> Hola ser @andrewhong5297, I've been away for a while now. I'm hoping to get back to working today/tomorrow.
> 
> 
> 
> So if today/tomorrow can work then I'd be happy to look into fixing this, else I can revisit later as I plan to make an update to the dao spell later this week. 

I'm going to force uniqueness on this model and then merge for now, you can visit this again when you have time

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
