### PR TITLE
remove uniqueness test on hash for optimism transactions

### PR DESCRIPTION
**Pull request by soispoke**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by chuxinh** [comment]
Thanks for this! 
I think it'd be better instead of dropping unique_ids unique test, we should instead update the unique id to `tx_hash` and `block number` instead. That also means the table needs a rebuild if necessary?

**Review by soispoke — COMMENTED** [review]
@chuxin we wouldn't need to rebuild the table, we could change the test to something similar to the commit I last pushed. However, the trace_address doesn't seem to be a column in the transactions table ? (so we can't use it as a unique id)

**Comment by chuxinh** [comment]
> @chuxin we wouldn't need to rebuild the table, we could change the test to something similar to the commit I last pushed. However, the trace_address doesn't seem to be a column in the transactions table ? (so we can't use it as a unique id)

ohhh i got confused here. thought you were referring to `transfer_optimism_eth`. yea that looks good to me!

**Comment by chuxinh** [comment]
is this going to re-enable of incremental build for `transfers_optimism.eth` after merge?
it's been paused since Aug 27

**Comment by soispoke** [comment]
@chuxinh ok great, will merge today then 👍

And unfortunately I think the pause on optimism is due to other factors not related to this particular issue

**Comment by chuxinh** [comment]
just wonder is there's any error or issue that's blocking the incremental build of `transfers_optimism.eth`?

**Comment by soispoke** [comment]
Opened a PR here #1522 to improve the incremental filters, let's also wait for @aalan3 or @jeff-dude's inputs to make sure there aren't any other issues with that table

**Comment by jeff-dude** [comment]
updated the unique test to remove ```tx_hash``` which doesn't exist on base table, results pass

**Comment by jeff-dude** [comment]
> @chuxinh Opened a PR here #1522 to improve the incremental filters, let's also wait for @aalan3 or @jeff-dude's inputs to make sure there aren't any other issues with that table

this PR looks good (and it's merged already), plus dbt shows that this model has been refreshing today 👍

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
