### PR TITLE
Add/Migrate Some OP DEXs (Beets, Rubicon, Kyber, Synthetix, Zipswap)

### PR DESCRIPTION
**Pull request by MSilb7**
Brief comments on the purpose of your changes:

- Migrate Beethoven, Rubicon, Synthetix (spot swaps), Kyber
- For Kyber - forked/modified the existing spell for kyber on avax
- Rubicon slightly modified per suggestions by Rubicon team
- Also added seeds for Curve meta pools, per discussion here: https://github.com/duneanalytics/spellbook/pull/2345 (and added pool_type to the OP-Specific table for easier testing.

One of the checks is failing for a missing `dex_model`, but can't figure out where that is.

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by MSilb7** [comment]
Still not sure why the dex model loops are failing, but otherwise should be good to go.

**Comment by Hosuke** [comment]
> Still not sure why the dex model loops are failing, but otherwise should be good to go.

I tried to fix this issue in the last commit. Hopefully it works now.

**Comment by MSilb7** [comment]
> Fix ref definition

ah wow, yeah that's a good catch. i'll see if I can fix the remaining flags

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @MSilb7 

[Sample Beets OP trades](https://dune.com/queries/1970295?d=1)
[Sample Rubicon OP trades](https://dune.com/queries/1970301)
[Sample Kyber OP trades](https://dune.com/queries/1970303)
[Sample Synthetix OP trades](https://dune.com/queries/1970309)
[Sample Zipswap OP trades](https://dune.com/queries/1970313)

**Comment by soispoke** [comment]
Looks good, tests do pass after a rerun

**Pull request merged**
