### PR TITLE
[Easy] [ERC20] Add missing tokens

### PR DESCRIPTION
**Pull request by gentrexha**
Usual missing tokens update. Updating both legacy and the new spell.

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
Looks great!

**Review by jkylling — APPROVED** [review]

**Review by jeff-dude — APPROVED** [review]
awesome -- thanks for adapting to the new setup quickly!

**Comment by bh2smith** [comment]
wenmerg!?

**Comment by jeff-dude** [comment]
> wenmerg!?

now merge

**Pull request merged**
