### PR TITLE
add wallet_address to unique_id

### PR DESCRIPTION
**Pull request by soispoke**
Brief comments on the purpose of your changes:

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if adding a new model, I edited the alter table macro to display new database object (table or view) in UI explorer
* [ ] if adding a new materialized table, I edited the optimize table macro

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]

**Review by soispoke — COMMENTED** [review]
thanks @jeff-dude !

**Comment by 0xRobin** [comment]
@soispoke @jeff-dude I don't think this is the correct solution to the problem here as this will again introduce multiple reported owners for 1 ID in case of duplicate mints in the same hour/day.
Does the no-duplicate-owners test still pass under this build?
See my comments here: https://github.com/duneanalytics/spellbook/pull/1525#issuecomment-1241290341

In essence the breaking smart contracts (with double mints) are violating ERC721 standards and I believe we should correct their mistake as early as possible in the data flow instead of propagating it.

**Comment by soispoke** [comment]
@0xRobin Yes, tests are passing. This fix was pushed because otherwise the incremental tables (agg_hour and day) couldn't be updated without throwing an error because the unique_id wasn't actually unique.

**Comment by 0xRobin** [comment]
> @0xRobin Yes, tests are passing. This fix was pushed because otherwise the incremental tables (agg_hour and day) couldn't be updated without throwing an error because the unique_id wasn't actually unique.

Ok so keys can be duplicates over different incremental runs but aren't automatically deduplicated within 1 query run. Gotcha!
In that case we should deduplicate in the query.

**Comment by 0xRobin** [comment]
as you can see here:
https://dune.com/queries/1253709?d=1

this results in 2 entries and we have **no guarantees** which one makes it into the `balances.erc721_day` view

**Comment by 0xBoxer** [comment]
I think this particular contract had this issue when 2 token_id's were minted in the same block, we could sort based on evt_index and keep the higher one

**Pull request merged**
