### PR TITLE
Feat/balancer vebal votes abstraction

### PR DESCRIPTION
**Pull request by Stefenon**
Brief comments on the purpose of your changes:

Migrate `balancer_vebal_votes` abstraction from Dune V1.

cc: @markusbkoch @mendesfabio @hedgehog-jacek 

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by Stefenon** [comment]
I tried turning this query into incremental, but I don't think it works. Do you have any thoughts on that?

**Comment by Hosuke** [comment]
> I tried turning this query into incremental, but I don't think it works. Do you have any thoughts on that?

I tried to make the spell into incremental in the last commit:
- not incremental: https://dune.com/queries/1888672
- incremental: https://dune.com/queries/1888779

Entries will be updated based on unique_keys defined in the config block.
Please have a review.

**Comment by Stefenon** [comment]
> > I tried turning this query into incremental, but I don't think it works. Do you have any thoughts on that?
> 
> I tried to make the spell into incremental in the last commit:
> 
> * not incremental: https://dune.com/queries/1888672
> * incremental: https://dune.com/queries/1888779
> 
> Entries will be updated based on unique_keys defined in the config block. Please have a review.

Hey @Hosuke, I believe this incremental spell doesn't output the expected results, because the query relies on previous data from the table to create its new rows. This happens because even if providers did not vote in a specific round, they should still be present on it if they voted previously.

Therefore, when we build the spell as incremental, there will be information missing from providers that only voted in rounds previous to the ones from the incremental filter.

Perhaps if this spell is built as a materialized table, it wouldn't be heavy to query. Since voting rounds happen on a weekly basis, not having the most updated version of the spell every time we query it should not be a problem.

**Comment by Hosuke** [comment]
> Hey @Hosuke, I believe this incremental spell doesn't output the expected results, because the query relies on previous data from the table to create its new rows. This happens because even if providers did not vote in a specific round, they should still be present on it if they voted previously.
> 
> Therefore, when we build the spell as incremental, there will be information missing from providers that only voted in rounds previous to the ones from the incremental filter.

The incremental view, will update incrementally, so it preserve the old/original records, and append/update new records to the view.
Incremental view records = not incremental records(first time refresh) + incremental records update daily

**Comment by Stefenon** [comment]
> > Hey @Hosuke, I believe this incremental spell doesn't output the expected results, because the query relies on previous data from the table to create its new rows. This happens because even if providers did not vote in a specific round, they should still be present on it if they voted previously.
> > Therefore, when we build the spell as incremental, there will be information missing from providers that only voted in rounds previous to the ones from the incremental filter.
> 
> The incremental view, will update incrementally, so it preserve the old/original records, and append/update new records to the view. Incremental view records = not incremental records(first time refresh) + incremental records update daily

I believe the problem is in the query from row 86 to 126. We rely on the data from previous rounds to produce the data from the next ones, which is why I believe an incremental strategy wouldn't work except if we can query the spell inside itself to get the data from previous rounds.

**Comment by Hosuke** [comment]
> I believe the problem is in the query from row 86 to 126. We rely on the data from previous rounds to produce the data from the next ones, which is why I believe an incremental strategy wouldn't work except if we can query the spell inside itself to get the data from previous rounds.

Noted.

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @Stefenon 

Due to https://github.com/duneanalytics/spellbook/pull/2447#issuecomment-1400155301 this PR is currently not modified to incremental view. The full-refresh time is within 2 minutes, based on [dbt slim ci](https://github.com/duneanalytics/spellbook/actions/runs/4030407963/jobs/6929046025#step:9:13).

[Sample votes](https://dune.com/queries/1936727).

**Pull request closed without merging**
