### PR TITLE
feat(dex.trades): add knightswap

### PR DESCRIPTION
**Pull request by developerfred**
Brief comments on the purpose of your changes:

**[WIP]** 

**For Dune Engine V2**

```
- add KnightSwap (Binance) on Dune Engine V2
```

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [x] `coin_id` represents the ID of the coin on coinpaprika.com
* [x] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [x] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [x] where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [x] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Review by jeff-dude — CHANGES_REQUESTED** [review]
@developerfred apologies for the delay, working back through post-holidays.

i'm not sure if this model ever ran through successfully, but i've pushed a few updates and the test for matching the seed entries is failing.

please see [here](https://dune.com/queries/1855667?d=1), with test compiled -- note tables used only persist ~24 hours from this comment, may need to rerun the gh action and rebuild new tables, then paste names from gh action logs into query to reproduce

**Comment by developerfred** [comment]
> @developerfred apologies for the delay, working back through post-holidays.
> 
> i'm not sure if this model ever ran through successfully, but i've pushed a few updates and the test for matching the seed entries is failing.
> 
> please see here, with test compiled -- note tables used only persist ~24 hours from this comment, may need to rerun the gh action and rebuild new tables, then paste names from gh action logs into query to reproduce

thank you very much, I will check here

**Comment by jeff-dude** [comment]
> > @developerfred apologies for the delay, working back through post-holidays.
> > i'm not sure if this model ever ran through successfully, but i've pushed a few updates and the test for matching the seed entries is failing.
> > please see here, with test compiled -- note tables used only persist ~24 hours from this comment, may need to rerun the gh action and rebuild new tables, then paste names from gh action logs into query to reproduce
> 
> thank you very much, I will check here

sounds good, let me know when passing and ready for final review/merge.

**Comment by jeff-dude** [comment]
closing due to inactivity

**Pull request closed without merging**
