### PR TITLE
Update tokens_optimism_erc20_curated.sql fix token decimals

### PR DESCRIPTION
**Pull request by 0xroll**
fix usd+ token decimals

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Review by jeff-dude — APPROVED** [review]
thank you!

**Comment by jeff-dude** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/duneanalytics/spellbook/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

@0xroll you will need to do this, prior to merging

**Comment by jeff-dude** [comment]
@0xroll can you sign the license agreement, in order to merge this? otherwise, i will need to close and make the change myself.

**Comment by 0xroll** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xroll** [comment]
will take note on future PRs . so sorry on the delay!

**Pull request merged**
