### PR TITLE
zeroex settler - revise model [base]

### PR DESCRIPTION
**Pull request by RantumBits**
### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [x] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- fix maker token values
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]
#6658 
---

### CODE REVIEW

**Comment by RantumBits** [comment]
[draft] - marked 'ready for review' by mistake. timed out on first test run

**Comment by jeff-dude** [comment]
hmm def concerning that this one chain is running so long, while the other PR with multiple chains ran in 20 minutes. was this an issue on initial build? is there a bug in the query?

**Comment by RantumBits** [comment]
this is now ready @jeff-dude

**Review by jeff-dude — APPROVED** [review]
run time looks much better, thank you!

**Pull request merged**
