### PR TITLE
timeswap: adds arbitrum pools

### PR DESCRIPTION
**Pull request by waverune**
Four pools added
ARB/USDC - - 2
glpUSDC/USDC
APT/USDC

### CODE REVIEW

**Comment by Hosuke** [comment]
Hi @waverune, 
Thank you for your contribution. 
However, at this time, we are only accepting submissions in Dune SQL format. 
If possible, could you please translate this spell into Dune SQL?

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @waverune

**Comment by jeff-dude** [comment]
@Hosuke we need to ensure the original changes of this PR get pushed to the `_legacy.sql` file, then we can migrate the non-legacy file

can you do the following:
- revert your commits
- move changes from non-legacy file(s) to legacy file(s), ensure spark compatibility
- once spark looks good on legacy files, then re-commit changes to non-legacy file(s), ensure latest changes are picked up

moving forward, @waverune, please ensure any spark changes are on the `_legacy.sql` version models and then we can duplicate changes to dunesql models (without `_legacy.sql` suffix)

**Comment by jeff-dude** [comment]
> I have revert my changes.

thank you.

@waverune can you move your changes to the same file, but with `_legacy.sql` in file name? that file refers to the spark engine. the file you are editing is sitting idle until you are ready to help migrate it to dunesql (refer to readme on how).

**Comment by waverune** [comment]
> > I have revert my changes.
> 
> thank you.
> 
> @waverune can you move your changes to the same file, but with `_legacy.sql` in file name? that file refers to the spark engine. the file you are editing is sitting idle until you are ready to help migrate it to dunesql (refer to readme on how).

Have moved the changes to _legacy.sql 
Thx @Hosuke @jeff-dude :))

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
