### PR TITLE
optimism bridges

### PR DESCRIPTION
**Pull request by RantumBits**
optimism bridges

### CODE REVIEW

**Comment by MSilb7** [comment]
I see optimism and I click 👀

Depending on the purpose, it could also be worth adding `..0007` which is where L2 messages are sent:
- https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000007
& The relayer [0x36BDE71C97B33Cc4729cf772aE268934f7AB70B2](0x36bde71c97b33cc4729cf772ae268934f7ab70b2)

**Comment by RantumBits** [comment]
> I see optimism and I click 👀
> 
> Depending on the purpose, it could also be worth adding `..0007` which is where L2 messages are sent:
> 
> * https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000007
>   & The relayer [0x36BDE71C97B33Cc4729cf772aE268934f7AB70B2](0x36bde71c97b33cc4729cf772ae268934f7ab70b2)

ty ser, always appreciated 🫡

**Review by jeff-dude — CHANGES_REQUESTED** [review]
plz apply same requested changes from #4827

**Comment by RantumBits** [comment]
merged with #4810

**Pull request closed without merging**
