### PR TITLE
Add OP Address Archetype Labels

### PR DESCRIPTION
**Pull request by kaiblade**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by kaiblade** [comment]
@Hosuke , Hello, I'm having an issue getting the checks successful for this PR. This is due to the dbt test failing as a result of duplicates in the `labels_eth_stakers` model, a model I didn't work on . I would be grateful if you could look into this issue. Thanks!

**Comment by jeff-dude** [comment]
> @Hosuke , Hello, I'm having an issue getting the checks successful for this PR. This is due to the dbt test failing as a result of duplicates in the `labels_eth_stakers` model, a model I didn't work on . I would be grateful if you could look into this issue. Thanks!

gm @kaiblade 

while you aren't directly modifying `labels.addresses`, all spells in labels directly roll into this spell. then the spell has a test for unique combo of columns [here](https://github.com/duneanalytics/spellbook/blob/main/models/labels/labels_addresses_schema.yml#L5). check [here](https://github.com/duneanalytics/spellbook/blob/main/models/labels/labels_addresses.sql) to see which spell you're loading new data into, then you'll see how it ends up in final labels spell.

this means one of your new spells either:
- has duplicates in itself on those columns
- or adds rows which already exist in another spell that roll into `labels.addresses`

i would test out the first scenario above, to see if one of your new spells has duplicates. that'll be the easier check.

**Comment by kaiblade** [comment]
> > @Hosuke , Hello, I'm having an issue getting the checks successful for this PR. This is due to the dbt test failing as a result of duplicates in the `labels_eth_stakers` model, a model I didn't work on . I would be grateful if you could look into this issue. Thanks!
> 
> gm @kaiblade
> 
> while you aren't directly modifying `labels.addresses`, all spells in labels directly roll into this spell. then the spell has a test for unique combo of columns [here](https://github.com/duneanalytics/spellbook/blob/main/models/labels/labels_addresses_schema.yml#L5). check [here](https://github.com/duneanalytics/spellbook/blob/main/models/labels/labels_addresses.sql) to see which spell you're loading new data into, then you'll see how it ends up in final labels spell.
> 
> this means one of your new spells either:
> 
> * has duplicates in itself on those columns
> * or adds rows which already exist in another spell that roll into `labels.addresses`
> 
> i would test out the first scenario above, to see if one of your new spells has duplicates. that'll be the easier check.

@jeff-dude Thanks for the reply. But If you run the query generated by dbt test to see the duplicates, it duplicates shown are not from any of the models I added. Here the dbt test generated query: ```select * from hive.test_schema.git_dunesql_719b98be_dbt_utils_unique_combination_of_columns_labels_addresses_address__name__category__model_name__blockchain```. 
Can you kindly run it and see?

**Comment by jeff-dude** [comment]
> > > @Hosuke , Hello, I'm having an issue getting the checks successful for this PR. This is due to the dbt test failing as a result of duplicates in the `labels_eth_stakers` model, a model I didn't work on . I would be grateful if you could look into this issue. Thanks!
> > 
> > 
> > gm @kaiblade
> > while you aren't directly modifying `labels.addresses`, all spells in labels directly roll into this spell. then the spell has a test for unique combo of columns [here](https://github.com/duneanalytics/spellbook/blob/main/models/labels/labels_addresses_schema.yml#L5). check [here](https://github.com/duneanalytics/spellbook/blob/main/models/labels/labels_addresses.sql) to see which spell you're loading new data into, then you'll see how it ends up in final labels spell.
> > this means one of your new spells either:
> > 
> > * has duplicates in itself on those columns
> > * or adds rows which already exist in another spell that roll into `labels.addresses`
> > 
> > i would test out the first scenario above, to see if one of your new spells has duplicates. that'll be the easier check.
> 
> @jeff-dude Thanks for the reply. But If you run the query generated by dbt test to see the duplicates, the duplicates shown are not from any of the models I added. Here is the dbt test generated query: `select * from hive.test_schema.git_dunesql_719b98be_dbt_utils_unique_combination_of_columns_labels_addresses_address__name__category__model_name__blockchain`. Can you kindly run it and see?

i went ahead and fixed for ya. linked PR in comments here.

**Comment by kaiblade** [comment]
Thank you veey much!

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
