### PR TITLE
Arbitrum ETH & ERC20 balances

### PR DESCRIPTION
**Pull request by henrystats**
# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by henrystats** [comment]
@antonio-mendes we're missing eth deposits though the bridge here I believe, maybe we'd need to use a similar approach as how I added the base one? same with avalanche_c... can look into both later this afternoon!

**Comment by antonio-mendes** [comment]
Yep @henrystats was gonna ping you about that as I do see negative ETH balances for wallets. Random eg.:
Screenshot 2023-09-15 at 14 53 18

**Review by antonio-mendes — CHANGES_REQUESTED** [review]
Pushed changes but we need to figure out how to get the ETH balances to be accurate. Let me know if I can help you with this.

Also @henrystats if you think it makes sense for some of these chaisn feel free to split ETH and ERC20 into different PRs

**Comment by henrystats** [comment]
Thank you very much ser, also yeah I think for Arbitrum, Avalanche, Fantom & Base I'll seperate the prs for the erc20 tokens since those can be reviewed / merged then continue working on the mainnet tokens . 

I can do that right away!

**Comment by jeff-dude** [comment]
thank you for the patience, now that the spellbook migration is complete, as we attempt to rebuild transfers & balances spells on the dunesql engine 🙏 

we will close this PR now, as the work on this set of sector spells can be tracked in the following locations:
#4521 
#4523 
#4633 
#4698

**Pull request closed without merging**
