### PR TITLE
zeroex - fix bnb sushi direct [FOR REVIEW]

### PR DESCRIPTION
**Pull request by RantumBits**
add bnb sushi direct

### CODE REVIEW

**Comment by RantumBits** [comment]
Trying to add a new swap type to bnb here. Can you help with this test error @Hosuke ?

**Comment by Hosuke** [comment]
> Trying to add a new swap type to bnb here. Can you help with this test error @Hosuke ?

Maybe something related with config blocks, but I am not sure yet

**Comment by Hosuke** [comment]
Wow 2 years ago...
image

**Comment by RantumBits** [comment]
> Wow 2 years ago... image

lol...that's a long time

**Comment by RantumBits** [comment]
> > Trying to add a new swap type to bnb here. Can you help with this test error @Hosuke ?
> 
> Maybe something related with config blocks, but I am not sure yet

This is the when testing:

18:23:33    TrinoExternalError(type=EXTERNAL, name=HIVE_CURSOR_ERROR, message="Failed to read Parquet file: s3a://arrakis-prod-datasets-118330671040/hive_metastore/bsc/traces_0007/block_date=2021-02-27/part-00072-835a3ba5-ef82-4706-8d00-d0b3da3c96ff.c000.snappy.parquet", query_id=20231025_181622_06616_g5t7e)

**Comment by Hosuke** [comment]
The problem mentioned above seems to be solved.
Currently only `dbt test initial models` failed:
https://github.com/duneanalytics/spellbook/actions/runs/6656967528/job/18090692174?pr=4680#step:12:31

**Comment by RantumBits** [comment]
> The problem mentioned above seems to be solved. Currently only `dbt test initial models` failed: https://github.com/duneanalytics/spellbook/actions/runs/6656967528/job/18090692174?pr=4680#step:12:31

Thanks. This is set & ready for review

**Review by Hosuke — APPROVED** [review]
LGTM.✅
Thank you @RantumBits

**Review by jeff-dude — APPROVED** [review]

**Pull request merged**
