### PR TITLE
change dodo aggregator project name to DODO X

### PR DESCRIPTION
**Pull request by owen05**
Only Change the brand name of "DODO Aggregator" to "DODO X"

# Thank you for contributing to Spellbook!
Please refer to the top of the `readme` in the root of Spellbook to learn how to contribute to Spellbook on DuneSQL.

### CODE REVIEW

**Comment by owen05** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by owen05** [comment]
recheck

**Comment by owen05** [comment]
recheck

**Comment by Hosuke** [comment]
Hi @owen05, we may need to migrate these spells into dune sql spells.
Here is a dex migration PR you can use as a reference:
https://github.com/duneanalytics/spellbook/pull/3989/files

**Comment by owen05** [comment]
> Hi @owen05, we may need to migrate these spells into dune sql spells. Here is a dex migration PR you can use as a reference: https://github.com/duneanalytics/spellbook/pull/3989/files

Got it👌，Thanks!

**Pull request closed without merging**
