### PR TITLE
Add spell for bep20 transfers on BNB

### PR DESCRIPTION
**Pull request by tschubotz**
Brief comments on the purpose of your changes:

- This PR adds a spell for ERC20 token transfers on BSC.
- This PR is similar to #2949 
- It is inspired/copied from #2883 which in turn followed [transfers_ethereum_erc20.sql](https://github.com/duneanalytics/spellbook/blob/main/models/transfers/ethereum/erc20/transfers_ethereum_erc20.sql)
- **no** incremental logic used since the 2 links above don't use it either.

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:

doesn't apply.

### Join logic:
* [x] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:

not used. see beginning of PR decription.

### CODE REVIEW

**Comment by tschubotz** [comment]
> hi @tschubotz -- thank you for the PR (and others like it). can you do me a favor? as of now, we applied an automated dunesql compatibility test in our CI test attached to PRs, but it's not finalized yet in terms of outputting logs to comments and such. in the short term, since this builds a view and will run on dunesql within the dune app, can you compile this model and copy/paste into dune, ensure it works? if not, potentially push changes to make it run successfully?
> 
> thanks ahead of time for the flexibility while we work behind-the-scenes to automate these checks

@jeff-dude 

Sure, no worries. I went ahead and made it compatible with Dune SQL. It now runs on both Dune SQL and Spark SQL:

- Dune SQL: https://dune.com/queries/2247825
- Spark SQL: https://dune.com/queries/2247856

Is this what you had in mind? Please let me know what you think. If all good, I'll replicate this to the other PRs related to ERC20 token transfers.

**Review by jeff-dude — APPROVED** [review]
that's exactly what i was looking for, incredible 🙌  thank you! feel free to apply elsewhere, then i'll be happy to merge

**Comment by jeff-dude** [comment]
> @jeff-dude I'm unable to access this new spell on Dune SQL:
> 
> ```
> select *
> from transfers_bnb.bep20
> limit 10
> ```
> 
> Fails with `Error: Line 2:6: Failed analyzing stored view 'delta_prod.transfers_bnb.bep20': line 51:1: column 3 in UNION query has incompatible types: varbinary, varchar(4) at line 2, position 6.`
> 
> (Query on Dune: https://dune.com/queries/2272461)
> 
> Same error for
> 
> * `transfers_optimism.erc20`
> * `transfers_avalanche_c.erc20`
> * `transfers_fantom.erc20`
> 
> All works fine for
> 
> * `transfers_arbitrum.erc20`
> * `transfers_polygon.erc20`

i think those two exceptions make sense -- polygon was materialized as a table, arbitrum reads from two less source tables. with that in mind, it makes me think the datatype mismatch is coming from the 3rd/4th tables introduced in other spells. we have two options:
1 - continue digging in to see why the datatypes would mismatch
2 - revisit each blockchain version and materialize as incremental table, which ultimately is likely the best move, as these views may actually end up taking awhile to return results (side note: @Hosuke mentioned he may look into materializing these already, but if not, maybe you can help?). also, another note here: on the polygon spell, since it was materialized as a table, the usage of `"from"` in the select actually caused a hardcoded string value `from` in the column, since it runs on the spark engine. we will need to fix that.

**Comment by tschubotz** [comment]
> 2 - revisit each blockchain version and materialize as incremental table, which ultimately is likely the best move, as these views may actually end up taking awhile to return results (side note: @Hosuke mentioned he may look into materializing these already, but if not, maybe you can help?). also, another note here: on the polygon spell, since it was materialized as a table, the usage of `"from"` in the select actually caused a hardcoded string value `from` in the column, since it runs on the spark engine. we will need to fix that.

Alright, here's what I understand you are suggesting:
- Change each of the ERC20 transfer spells to materialize as incremental tables, similar to what @Hosuke did here: https://github.com/duneanalytics/spellbook/pull/2950/files
- Change `"from"` back to just `from` since materialized views run on the spark engine which caused a hardcoded string to appear instead of the actual column.

Also, once we are at it:
- Get rid of unique_transfer_id. Introduce a new field `transfer_type` which can be one of 4 values in `[send, receive, deposit, withdraw]` and together with `evt_tx_hash`, `evt_index`, `wallet_address` to form the `unique_key`. I don't fully understand the implications, but @Hosuke suggested and implemented it here https://github.com/duneanalytics/spellbook/pull/2950#issuecomment-1471808040

I went ahead and made these changes for ftm here: https://github.com/duneanalytics/spellbook/pull/3060

Let me know what you think. If all good, happy to replicate to the other networks as well.

**Comment by Hosuke** [comment]
@tschubotz Committed in the new PR. Majorly add an uniqueness test in the schema.yml to test the unique_key.

**Comment by jeff-dude** [comment]
> > 2 - revisit each blockchain version and materialize as incremental table, which ultimately is likely the best move, as these views may actually end up taking awhile to return results (side note: @Hosuke mentioned he may look into materializing these already, but if not, maybe you can help?). also, another note here: on the polygon spell, since it was materialized as a table, the usage of `"from"` in the select actually caused a hardcoded string value `from` in the column, since it runs on the spark engine. we will need to fix that.
> 
> Alright, here's what I understand you are suggesting:
> 
> * Change each of the ERC20 transfer spells to materialize as incremental tables, similar to what @Hosuke did here: https://github.com/duneanalytics/spellbook/pull/2950/files
> * Change `"from"` back to just `from` since materialized views run on the spark engine which caused a hardcoded string to appear instead of the actual column.
> 
> Also, once we are at it:
> 
> * Get rid of unique_transfer_id. Introduce a new field `transfer_type` which can be one of 4 values in `[send, receive, deposit, withdraw]` and together with `evt_tx_hash`, `evt_index`, `wallet_address` to form the `unique_key`. I don't fully understand the implications, but @Hosuke suggested and implemented it here [Add spell for erc20 transfers on Polygon #2950 (comment)](https://github.com/duneanalytics/spellbook/pull/2950#issuecomment-1471808040)
> 
> I went ahead and made these changes for ftm here: #3060
> 
> Let me know what you think. If all good, happy to replicate to the other networks as well.

yes to everything here 🤝 thanks for summarizing the understanding. i'm advocating for usage of an array of keys for unique key, rather than generated surrogate key `unique_transfer_id`, so thanks for pushing that forward @Hosuke along with the unique test in the schema file. let's continue convo on #3060

**Pull request merged**
