### PR TITLE
Fix wash filter

### PR DESCRIPTION
**Pull request by hildobby**
Brief comments on the purpose of your changes:

Added case columns to group by and also added an anti left join for incremental runs to make sure trades arent abstracted twice.

*For Dune Engine V2*
I've checked that:
General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributors)

Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by hildobby** [comment]
I just pushed and was trying to look into the test that errors in dune but it doesn't work 🤔 

Screenshot 2022-11-03 at 21 07 49

**Comment by jeff-dude** [comment]
> I just pushed and was trying to look into the test that errors in dune but it doesn't work 🤔
> 
> Screenshot 2022-11-03 at 21 12 21

yeah, if the step where it actually creates that table fails, it won't exist. if you haven't already, i'd recommend compiling locally and running on dune -- does that work?

**Comment by hildobby** [comment]
> yeah, if the step where it actually creates that table fails, it won't exist. if you haven't already, i'd recommend compiling locally and running on dune -- does that work?

Ah you're right, found the issue and fixed it that way! I also ran some tests on dune.com and ran the abstraction on the past 1 month of data yields no duplicates, see here: https://dune.com/queries/1522465 . So I am pretty sure duplicates come from rerunning the table on incremental runs. I added a recursive check, this should now make the abstraction work as intended:

```
{% if is_incremental() %}
LEFT ANTI JOIN {{this}} nft_wtf ON nftt.unique_trade_id = nft_wtf.trade_unique_id
{% endif %}
```

**Review by jeff-dude — APPROVED** [review]
i think this is good, i'll merge it & we can monitor

**Pull request merged**
