### PR TITLE
Add gmx margin trades to perpetual trades table - Ready for review 

### PR DESCRIPTION
**Pull request by henrystats**
Brief comments on the purpose of your changes:

**For Dune Engine V2**

I've checked that:

### General checks:
* [ ] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [ ] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [ ] if adding a new model, I added a test
* [ ] the filename is unique and ends with .sql
* [ ] each sql file is a select statement and has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`
* [ ] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [ ] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] `coin_id` represents the ID of the coin on coinpaprika.com
* [ ] all the coins are active on coinpaprika.com (please remove inactive ones)

### Join logic:
* [ ] if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible

### Incremental logic:
* [ ] I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables
  * [ ] where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')
* [ ] if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')

### CODE REVIEW

**Comment by henrystats** [comment]
I'm not sure what's wrong with the model here that's causing it to not run. The underlying tables that I'm combining (avalanche_c & Arbitrum gmx perpetual works and runs) so not sure why it's failing.

**Comment by henrystats** [comment]
I'm still not sure what's wrong with the model here that's causing it to not run. The underlying tables that I'm combining (avalanche_c & Arbitrum gmx perpetual works and runs) so not sure why it's failing.

**Comment by Hosuke** [comment]
> I'm still not sure what's wrong with the model here that's causing it to not run. The underlying tables that I'm combining (avalanche_c & Arbitrum gmx perpetual works and runs) so not sure why it's failing.

Hi @henrystats,  I have tried to fix the issue, please check if I missed anything.

**Comment by henrystats** [comment]
Thank you soo soo much ser. I'm trying to find where the error was but still can't find it yet.

I'll add seed files shortly.

**Comment by henrystats** [comment]
Added seed files for gmx in the perpetual_trades_seeed. 

I also created a test similar to check_dex_seed for perpetual trades. I have two other pr's open that add files to the perpetual trades table. I'll update those once this gets merged so I don't have to re edit the tests.

**Review by Hosuke — APPROVED** [review]
This PR adds gmx perpetual trades on arbitrum and avalanche_c chains.

I have reviewed the PR and here is the summary:
- Metadata & naming conventions look good ✅
- Config blocks match uniqueness tests in schema files ✅
- Tests and seeds added for the new models ✅
- Incremental filters added when joining large tables ✅
- Inner join to large tables(*.transactions) as possible ✅

The deleted source files are merged into new source files.

**Comment by henrystats** [comment]
Thank you soo much ser @Hosuke

**Review by jeff-dude — APPROVED** [review]
good stuff 🤝

**Pull request merged**
