### PR TITLE
add WETH and USDB for blast to get token pricing

### PR DESCRIPTION
**Pull request by kennyran**
### Contribution type
Please check the type of contribution this pull request is for:

- [x] New spell(s)
- [ ] Adding to existing spell lineage
- [ ] Bug fix

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *spellbook/models/prices/blast/prices_blast_tokens.sql*
- **Description:** Added blast prices sql and yml files for getting blast token prices for duneanalytics
- **Who are the new spell(s) for?** general community and Aori 
- **How will the new spell(s) be used downstream?** Will be used to price tokens for blast analytics 
- **Implementation details:** USDB and WETH implemented via sql and yml with 'blast-blast' being added to the token checker 
- **Test instructions:** 
- **Related issue(s):**

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

### CODE REVIEW

**Comment by kennyran** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by henrystats** [comment]
👀

**Comment by kennyran** [comment]
> 👀

Spider_Man_meme

i was confused what the eyes were for lol, I didn't see you also had a PR for this. Will close mine now lmao

**Comment by kennyran** [comment]
PR for same exact tokens is already open by @henrystats first, was unaware, disregard mine 🙏

**Pull request closed without merging**
